-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc7`='$N versus the ferocious clefthoof, Brokentoe!' WHERE `word_id` = 7594; -- db_script_string - content : entry=2000000003
UPDATE `trans_words` SET `content_loc7`='%s reads from the book of the dead.' WHERE `word_id` = 268248; -- db_script_string - content : entry=2000000488
UPDATE `trans_words` SET `content_loc7`='%s scurries away, attempting to flee from Twinkle.' WHERE `word_id` = 7620; -- db_script_string - content : entry=2000000391
UPDATE `trans_words` SET `content_loc7`='...And then the tauren said, "13 INCHES!"' WHERE `word_id` = 7080; -- db_script_string - content : entry=2000005032
UPDATE `trans_words` SET `content_loc7`='Ah, this must be him now... no?' WHERE `word_id` = 7070; -- db_script_string - content : entry=2000005018
UPDATE `trans_words` SET `content_loc7`='Ahh, much appreciated, Corbett. We\'ll get these on the racks immediately.' WHERE `word_id` = 7019; -- db_script_string - content : entry=2000000148
UPDATE `trans_words` SET `content_loc7`='All right, I shall find people to help him.' WHERE `word_id` = 6944; -- db_script_string - content : entry=2000000011
UPDATE `trans_words` SET `content_loc7`='All right, let\'s go.' WHERE `word_id` = 7586; -- db_script_string - content : entry=2000000012
UPDATE `trans_words` SET `content_loc7`='An Avatar of Terokk! To arms!' WHERE `word_id` = 7599; -- db_script_string - content : entry=2000000025
UPDATE `trans_words` SET `content_loc7`='Anaya\'s soft voice trails away into the mists. "Know that I love you always..."' WHERE `word_id` = 7428; -- db_script_string - content : entry=2000005344
UPDATE `trans_words` SET `content_loc7`='And even more!' WHERE `word_id` = 7598; -- db_script_string - content : entry=2000000024
UPDATE `trans_words` SET `content_loc7`='And that\'s how Lother killed thirty six orcs with his bare hands!' WHERE `word_id` = 7099; -- db_script_string - content : entry=2000005115
UPDATE `trans_words` SET `content_loc7`='And who do we have here?  No doubt th... crzzzk ...ade this communication possible?  I give you greetings fro... psshzzzk... Azure Watch.' WHERE `word_id` = 268219; -- db_script_string - content : entry=2000005549
UPDATE `trans_words` SET `content_loc7`='Ask me how you can get a free drink at the Blue Recluse!' WHERE `word_id` = 7149; -- db_script_string - content : entry=2000005191
UPDATE `trans_words` SET `content_loc7`='At least we would not be around to have to clean it up.' WHERE `word_id` = 7523; -- db_script_string - content : entry=2000005149
UPDATE `trans_words` SET `content_loc7`='Be patient $N. The torch is almost complete.' WHERE `word_id` = 6948; -- db_script_string - content : entry=2000000019
UPDATE `trans_words` SET `content_loc7`='begins a spell of summoning...' WHERE `word_id` = 7591; -- db_script_string - content : entry=2000000043
UPDATE `trans_words` SET `content_loc7`='Bijou lost! SQUAWK! *cough' WHERE `word_id` = 7062; -- db_script_string - content : entry=2000005002
UPDATE `trans_words` SET `content_loc7`='But isn\'t that what caused the initial problems with Adept Syleria\'s magical formula?' WHERE `word_id` = 7121; -- db_script_string - content : entry=2000005155
UPDATE `trans_words` SET `content_loc7`='But wouldn`t that mean crossing the streams? Isn`t that really bad?' WHERE `word_id` = 7526; -- db_script_string - content : entry=2000005160
UPDATE `trans_words` SET `content_loc7`='BY THE LIGHT OF ELUNE! Eredar! Cursed demons, what have you to me? I have not come alone, we will fight you as we have in the past! I...' WHERE `word_id` = 7636; -- db_script_string - content : entry=2000000660
UPDATE `trans_words` SET `content_loc7`='Children if you would please follow me, we will now be going to see the keep where King Anduin Wrynn himself sits on this throne.' WHERE `word_id` = 7113; -- db_script_string - content : entry=2000005136
UPDATE `trans_words` SET `content_loc7`='Deja vu. For a moment I thought I was back home... before the plague...' WHERE `word_id` = 7093; -- db_script_string - content : entry=2000005108
UPDATE `trans_words` SET `content_loc7`='Derived from cutting edge Shattered Hand Offensive military technology, it blasts away stubborn stains with ease!' WHERE `word_id` = 7532; -- db_script_string - content : entry=2000005207
UPDATE `trans_words` SET `content_loc7`='Fear not! All fortunes can be discerned for those who know the way.' WHERE `word_id` = 7535; -- db_script_string - content : entry=2000005213
UPDATE `trans_words` SET `content_loc7`='Fizzles used to be a great wizard. But got turned into a rabbit when one of his spells went bad.' WHERE `word_id` = 7144; -- db_script_string - content : entry=2000005184
UPDATE `trans_words` SET `content_loc7`='Follow me, good $C. I\'ll have your barding done faster than I could down a Dwarven stout. Mmmm... stout.' WHERE `word_id` = 6975; -- db_script_string - content : entry=2000000063
UPDATE `trans_words` SET `content_loc7`='Follow, $N. I will soon begin the summoning...' WHERE `word_id` = 6954; -- db_script_string - content : entry=2000000029
UPDATE `trans_words` SET `content_loc7`='Fresh bread for sale' WHERE `word_id` = 7515; -- db_script_string - content : entry=2000005099
UPDATE `trans_words` SET `content_loc7`='Get it while its hot' WHERE `word_id` = 7516; -- db_script_string - content : entry=2000005100
UPDATE `trans_words` SET `content_loc7`='Gird yourself $N, for the demon in this orb is a fel beast.' WHERE `word_id` = 6956; -- db_script_string - content : entry=2000000032
UPDATE `trans_words` SET `content_loc7`='Glad to see you\'re doing so well, Harlan. And I hope to see you again soon' WHERE `word_id` = 7563; -- db_script_string - content : entry=2000000149
UPDATE `trans_words` SET `content_loc7`='Glowing Soulgem bursts open!' WHERE `word_id` = 6967; -- db_script_string - content : entry=2000000078
UPDATE `trans_words` SET `content_loc7`='Go, my servant. Send word of Stonetalon to Apothecary Zamah.' WHERE `word_id` = 7051; -- db_script_string - content : entry=2000000093
UPDATE `trans_words` SET `content_loc7`='Good day. Elling! Hullo Elaine! Let me have a wheel of blue cheese, eh?' WHERE `word_id` = 7024; -- db_script_string - content : entry=2000000153
UPDATE `trans_words` SET `content_loc7`='Hear ye, denizens of Tanaris! Let it be known $N is an exalted member of the Mithril Order. A blacksmith of honor, dedication, and infinite patience. Three cheers for $N!' WHERE `word_id` = 6979; -- db_script_string - content : entry=2000000076
UPDATE `trans_words` SET `content_loc7`='Hello Grimclaw' WHERE `word_id` = 6938; -- db_script_string - content : entry=2000000050
UPDATE `trans_words` SET `content_loc7`='Here\'s a beacon, $N. Keep it to yourself, if you\'re gonna find mutilated things that we need.' WHERE `word_id` = 7059; -- db_script_string - content : entry=2000000318
UPDATE `trans_words` SET `content_loc7`='Hey there, Belm! Give me a mug of Thunder Ale, and one for my good friend $N.' WHERE `word_id` = 6971; -- db_script_string - content : entry=2000000056
UPDATE `trans_words` SET `content_loc7`='Hey, you there. Want some candy?' WHERE `word_id` = 7492; -- db_script_string - content : entry=2000005052
UPDATE `trans_words` SET `content_loc7`='Hi Corbett! Here, you go! I trust business is faring well at your clothier shop...?' WHERE `word_id` = 7026; -- db_script_string - content : entry=2000000155
UPDATE `trans_words` SET `content_loc7`='Hullo, Trias clan! A ball of your smoked mozzarella, if you please!' WHERE `word_id` = 7023; -- db_script_string - content : entry=2000000152
UPDATE `trans_words` SET `content_loc7`='I can make it the rest of the way. $N. THANKS!' WHERE `word_id` = 732; -- db_script_string - content : entry=2000000018
UPDATE `trans_words` SET `content_loc7`='I FEEL DEATH ALONGSIDE' WHERE `word_id` = 7546; -- db_script_string - content : entry=2000005231
UPDATE `trans_words` SET `content_loc7`='I need to consult Noram and Horatio.' WHERE `word_id` = 6950; -- db_script_string - content : entry=2000000021
UPDATE `trans_words` SET `content_loc7`='I swear, people have actualy seen them. Pandaren really do exist!!' WHERE `word_id` = 7096; -- db_script_string - content : entry=2000005112
UPDATE `trans_words` SET `content_loc7`='I think, I\'ll be able to get to Brackenwall. The cargo they carried to the top of the towers. Be careful!' WHERE `word_id` = 8726; -- db_script_string - content : entry=2000000486
UPDATE `trans_words` SET `content_loc7`='I WICKED OGR' WHERE `word_id` = 7545; -- db_script_string - content : entry=2000005230
UPDATE `trans_words` SET `content_loc7`='I WILL DESTROY ALL' WHERE `word_id` = 7483; -- db_script_string - content : entry=2000005043
UPDATE `trans_words` SET `content_loc7`='I will do my best to take care of the children, Grandmother.' WHERE `word_id` = 7481; -- db_script_string - content : entry=2000005041
UPDATE `trans_words` SET `content_loc7`='It is time to force your final challenge young warriors! Prepare for your hardest fight yet.' WHERE `word_id` = 7559; -- db_script_string - content : entry=2000005075
UPDATE `trans_words` SET `content_loc7`='It\'s all here... how the raven\'s followers captured and subdued the sprints of rivals, trapping them forever within stone statues! The tablet even mentions the raven god\'s name -- Anzu. I\'d thought it was lost to history!' WHERE `word_id` = 7581; -- db_script_string - content : entry=2000000072
UPDATE `trans_words` SET `content_loc7`='Jeffrey Kaplan! Tom Chilton! Rob Pardo!' WHERE `word_id` = 268222; -- db_script_string - content : entry=2000000490
UPDATE `trans_words` SET `content_loc7`='Just sit right back and you\'ll hear a ta... *hic* a tai... *hic* a taiii *hic* Damnit!' WHERE `word_id` = 7156; -- db_script_string - content : entry=2000005233
UPDATE `trans_words` SET `content_loc7`='Justin Thavirat! Roman Kenney! Our entire awesome art and animation team!' WHERE `word_id` = 268223; -- db_script_string - content : entry=2000000491
UPDATE `trans_words` SET `content_loc7`='Keep moving!' WHERE `word_id` = 7608; -- db_script_string - content : entry=2000000033
UPDATE `trans_words` SET `content_loc7`='Kevin Jordan and Jonathan LeCraft!' WHERE `word_id` = 268224; -- db_script_string - content : entry=2000000492
UPDATE `trans_words` SET `content_loc7`='Look out! More are coming!' WHERE `word_id` = 7597; -- db_script_string - content : entry=2000000023
UPDATE `trans_words` SET `content_loc7`='Look! Minions of Terokk are approaching!' WHERE `word_id` = 7596; -- db_script_string - content : entry=2000000022
UPDATE `trans_words` SET `content_loc7`='New posting up! Adventurers and heroes, gather round the bulletin board!' WHERE `word_id` = 7482; -- db_script_string - content : entry=2000005042
UPDATE `trans_words` SET `content_loc7`='NOBODY WILL GET THROUGH ME' WHERE `word_id` = 7548; -- db_script_string - content : entry=2000005235
UPDATE `trans_words` SET `content_loc7`='Not a challenge at all it seems. Let us see how hou handle your second test. Lysta, bring forth the minions of the Lich King.' WHERE `word_id` = 7561; -- db_script_string - content : entry=2000005073
UPDATE `trans_words` SET `content_loc7`='Now get out of my way, it\'s time to send the Burning Legion back to the nether!' WHERE `word_id` = 7504; -- db_script_string - content : entry=2000005413
UPDATE `trans_words` SET `content_loc7`='Of Course Im talking to myself. Only way to get a decent conversation in this city.' WHERE `word_id` = 7519; -- db_script_string - content : entry=2000005105
UPDATE `trans_words` SET `content_loc7`='Oh no! They a here!' WHERE `word_id` = 7587; -- db_script_string - content : entry=2000000013
UPDATE `trans_words` SET `content_loc7`='Oh sweet, delicious, spotted eggs - you will be mine...' WHERE `word_id` = 7573; -- db_script_string - content : entry=2000005093
UPDATE `trans_words` SET `content_loc7`='Oh, hello Grimclaw.' WHERE `word_id` = 7588; -- db_script_string - content : entry=2000000014
UPDATE `trans_words` SET `content_loc7`='Ok, $N. Now i can go the the Auberdine alone. Go to Terenthis. He waits for you. Thanks for the help.' WHERE `word_id` = 7589; -- db_script_string - content : entry=2000000015
UPDATE `trans_words` SET `content_loc7`='Ok, good luck friend. Thanks for the help.' WHERE `word_id` = 7590; -- db_script_string - content : entry=2000000016
UPDATE `trans_words` SET `content_loc7`='Ok, let\'s get started!' WHERE `word_id` = 7422; -- db_script_string - content : entry=2000000096
UPDATE `trans_words` SET `content_loc7`='Only if we did not follow the proper initialization procedures.' WHERE `word_id` = 7524; -- db_script_string - content : entry=2000005150
UPDATE `trans_words` SET `content_loc7`='Our oldest clutch of dragons are still far from maturity, but with patience and study, we are confident the dragons will soon be ready.' WHERE `word_id` = 7078; -- db_script_string - content : entry=2000005029
UPDATE `trans_words` SET `content_loc7`='Perry Gatner! What an act! The cantina is open all night long, so please, stay and enjoy yourselves!' WHERE `word_id` = 7550; -- db_script_string - content : entry=2000005301
UPDATE `trans_words` SET `content_loc7`='Please! I must feed on something soon... A mana crystal... a shard... anything! The pain is unbearable!' WHERE `word_id` = 7476; -- db_script_string - content : entry=2000005036
UPDATE `trans_words` SET `content_loc7`='Prizes! Get your prizes right here! Get over here and turn in your Darkmoon Faire Prize Tickets for valuable prizes!' WHERE `word_id` = 7471; -- db_script_string - content : entry=2000005025
UPDATE `trans_words` SET `content_loc7`='Right. We just busted our tails to haul all of this stuff up here, and you want us to work more?' WHERE `word_id` = 7494; -- db_script_string - content : entry=2000005056
UPDATE `trans_words` SET `content_loc7`='Sarath fades into the mist...' WHERE `word_id` = 7427; -- db_script_string - content : entry=2000000080
UPDATE `trans_words` SET `content_loc7`='Seems like a hundred times a day I walk all the way to get more water. No respect for their elders I tell ya.' WHERE `word_id` = 5747; -- db_script_string - content : entry=2000005107
UPDATE `trans_words` SET `content_loc7`='Shane Dabiri, Lee, Alex T., Rob F., J. A. B., A. Mayberry!' WHERE `word_id` = 268221; -- db_script_string - content : entry=2000000489
UPDATE `trans_words` SET `content_loc7`='Sniff... That\'s the spirit soldier... I only wish we had more soldiers like you in this army. Now go out there and give \'em hell!' WHERE `word_id` = 7503; -- db_script_string - content : entry=2000005414
UPDATE `trans_words` SET `content_loc7`='Spirits of Water, I give you praise, and I beg of you a favour. You have heard $N\'s pleas, and I trust his inent is noble. Please, will you aid us?' WHERE `word_id` = 7572; -- db_script_string - content : entry=2000000057
UPDATE `trans_words` SET `content_loc7`='Sure Paige. Just be gentle.' WHERE `word_id` = 7141; -- db_script_string - content : entry=2000005181
UPDATE `trans_words` SET `content_loc7`='Tell us! Where does you leader hide?' WHERE `word_id` = 7478; -- db_script_string - content : entry=2000005038
UPDATE `trans_words` SET `content_loc7`='Thank you again, $N. This rare earth will be very helpful in my experiments.' WHERE `word_id` = 6965; -- db_script_string - content : entry=2000000049
UPDATE `trans_words` SET `content_loc7`='Thank you great spirit. Thank you!' WHERE `word_id` = 6973; -- db_script_string - content : entry=2000000058
UPDATE `trans_words` SET `content_loc7`='Thank you. I thought I was going to die.' WHERE `word_id` = 7625; -- db_script_string - content : entry=2000005545
UPDATE `trans_words` SET `content_loc7`='That\'s interesting...' WHERE `word_id` = 6949; -- db_script_string - content : entry=2000000020
UPDATE `trans_words` SET `content_loc7`='The boss wants all hands on high alert. The rusty anchor sinks tonight.' WHERE `word_id` = 7225; -- db_script_string - content : entry=2000005408
UPDATE `trans_words` SET `content_loc7`='The Darkmoon Faire is the greatest event in all of Outland' WHERE `word_id` = 7540; -- db_script_string - content : entry=2000005221
UPDATE `trans_words` SET `content_loc7`='The Portal will shift slightly. At this point if you cast a binding cantrip you will solidify it in place.' WHERE `word_id` = 7528; -- db_script_string - content : entry=2000005173
UPDATE `trans_words` SET `content_loc7`='There\'s something else here, too. After a discription of a bloody battle and the downfall of the raven, there\'s a prophecy. Anzu will haunt the dreams of his enemies, twisting them to affect a return to this world...' WHERE `word_id` = 7582; -- db_script_string - content : entry=2000000073
UPDATE `trans_words` SET `content_loc7`='They all go to the Spire but none never come back... just like Bijou.' WHERE `word_id` = 5673; -- db_script_string - content : entry=2000005006
UPDATE `trans_words` SET `content_loc7`='This data will be quite usefull for Project Blue Book. Er, I mean this will be great for my new look. See if you can gather any more data.' WHERE `word_id` = 7541; -- db_script_string - content : entry=2000005222
UPDATE `trans_words` SET `content_loc7`='This is a shiney rock. I\'ll put it in my bucket. Ok, I just need a few more...' WHERE `word_id` = 7292; -- db_script_string - content : entry=2000005325
UPDATE `trans_words` SET `content_loc7`='This is great news! Your efforts have indeed saved us, $N!' WHERE `word_id` = 8633; -- db_script_string - content : entry=2000005551
UPDATE `trans_words` SET `content_loc7`='This is the last time that I buy second-hand equipment from ethereal' WHERE `word_id` = 7466; -- db_script_string - content : entry=2000005067
UPDATE `trans_words` SET `content_loc7`='This makes sense!' WHERE `word_id` = 6955; -- db_script_string - content : entry=2000000030
UPDATE `trans_words` SET `content_loc7`='Tickets! Redeem your Darkmoon Faire Prize Tickets here! Wondrous and exotic prizes are waiting for you!' WHERE `word_id` = 7534; -- db_script_string - content : entry=2000005212
UPDATE `trans_words` SET `content_loc7`='Turning to face Tuluun, the Draenei Artificer sneers contemptuously.' WHERE `word_id` = 7642; -- db_script_string - content : entry=2000000662
UPDATE `trans_words` SET `content_loc7`='US ALREADY ALL ANYMORE AND ANYMORE' WHERE `word_id` = 7484; -- db_script_string - content : entry=2000005044
UPDATE `trans_words` SET `content_loc7`='Volcor need help ?' WHERE `word_id` = 6943; -- db_script_string - content : entry=2000000010
UPDATE `trans_words` SET `content_loc7`='Volcor was gone?' WHERE `word_id` = 6940; -- db_script_string - content : entry=2000000052
UPDATE `trans_words` SET `content_loc7`='Welcome one and all to the Darkmoon Faire, the greatest event in all the worlds! We have it all... delicious food, strong drinks, exotic artifacts, fortunes read, amazing prizes and excitement without end! Don\'t forget to turn in your Darkmoon Faire Prize Tickets to Gelvas Grimegate! All it takes is five or more and you\'re on your way to the most wondrous prizes in all of Outland. Everybody is a winner' WHERE `word_id` = 7475; -- db_script_string - content : entry=2000005034
UPDATE `trans_words` SET `content_loc7`='Well hand it overand let\'s see what you got!' WHERE `word_id` = 7490; -- db_script_string - content : entry=2000005050
UPDATE `trans_words` SET `content_loc7`='Well, I am off than. Take care, Harlan!' WHERE `word_id` = 7021; -- db_script_string - content : entry=2000000150
UPDATE `trans_words` SET `content_loc7`='Well, ok. I am now sending people . We need find and help him.' WHERE `word_id` = 6942; -- db_script_string - content : entry=2000000054
UPDATE `trans_words` SET `content_loc7`='Well, that should do it. Come now, back to the shop to finish our business!' WHERE `word_id` = 6976; -- db_script_string - content : entry=2000000064
UPDATE `trans_words` SET `content_loc7`='What happens?' WHERE `word_id` = 6939; -- db_script_string - content : entry=2000000009
UPDATE `trans_words` SET `content_loc7`='Where do you think you are going soldier? Those are fatal wounds you\'ve got there. Now, get back in tent and let the nurse treat you!' WHERE `word_id` = 7505; -- db_script_string - content : entry=2000005412
UPDATE `trans_words` SET `content_loc7`='Who? The Tauren Chieftains! What? A live performance. Where? The World\'s End Tavern! When? The top of the hour! BE THERE!' WHERE `word_id` = 7439; -- db_script_string - content : entry=2000005305
UPDATE `trans_words` SET `content_loc7`='Worm goes on the hook, hook goes in the water, Fish is in the water, our fish.' WHERE `word_id` = 7104; -- db_script_string - content : entry=2000005122
UPDATE `trans_words` SET `content_loc7`='Wouldn\'t you like to bring those days back? I have some friends who know just the way to do that.' WHERE `word_id` = 7469; -- db_script_string - content : entry=2000005022
UPDATE `trans_words` SET `content_loc7`='Wow, all this for a love potion. Hope he is worth it.' WHERE `word_id` = 7527; -- db_script_string - content : entry=2000005171
UPDATE `trans_words` SET `content_loc7`='Yer wearin down, princess, I can sense it!' WHERE `word_id` = 7530; -- db_script_string - content : entry=2000005203
UPDATE `trans_words` SET `content_loc7`='Yes you may, $N. But do not stray too far from home.' WHERE `word_id` = 7506; -- db_script_string - content : entry=2000005321
UPDATE `trans_words` SET `content_loc7`='You know where he is?' WHERE `word_id` = 6941; -- db_script_string - content : entry=2000000053
UPDATE `trans_words` SET `content_loc7`='You know why Orcs eyes glow red? It\'s because they drink blood!' WHERE `word_id` = 7097; -- db_script_string - content : entry=2000005113
UPDATE `trans_words` SET `content_loc7`='YOU PRAY SERVANTS MY' WHERE `word_id` = 7539; -- db_script_string - content : entry=2000005220
UPDATE `trans_words` SET `content_loc7`='You want to go do the bounty off of this wanted poster after this shift is over?' WHERE `word_id` = 7487; -- db_script_string - content : entry=2000005047
UPDATE `trans_words` SET `content_loc7`='Your body is mine! Our fates are forever intertwined!' WHERE `word_id` = 7595; -- db_script_string - content : entry=2000000031

SET NAMES 'latin1';
