-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc7`='[PH] Learn Dimensional Ripper.' WHERE `word_id`=128975; -- locales_gossip_menu_option - option_text : menu_id=20003-id=0
UPDATE `trans_words` SET `content_loc7`='[PH] Learn Ultrasafe Transporter.' WHERE `word_id`=128976; -- locales_gossip_menu_option - option_text : menu_id=20004-id=0
UPDATE `trans_words` SET `content_loc7`='[ph]Learn recipe...' WHERE `word_id`=128221; -- locales_gossip_menu_option - option_text : menu_id=6443-id=0
UPDATE `trans_words` SET `content_loc7`='<Nod>' WHERE `word_id`=128168; -- locales_gossip_menu_option - option_text : menu_id=5702-id=0
UPDATE `trans_words` SET `content_loc7`='<Take the letter>' WHERE `word_id`=128038; -- locales_gossip_menu_option - option_text : menu_id=141-id=4
UPDATE `trans_words` SET `content_loc7`='Arena' WHERE `word_id`=114452; -- locales_gossip_menu_option - option_text : menu_id=10043-id=0
UPDATE `trans_words` SET `content_loc7`='Can you send me to Theramore? I have an urgent message to Lady Jaina from King Wrynn.' WHERE `word_id`=128748; -- locales_gossip_menu_option - option_text : menu_id=8846-id=0
UPDATE `trans_words` SET `content_loc7`='Can you tell me about this shard?' WHERE `word_id`=127827; -- locales_gossip_menu_option - option_text : menu_id=21-id=1
UPDATE `trans_words` SET `content_loc7`='Do you know where I can find Half Pendant of Aquatic Agility?' WHERE `word_id`=127921; -- locales_gossip_menu_option - option_text : menu_id=4041-id=1
UPDATE `trans_words` SET `content_loc7`='Do you know where I can find Half Pendant of Aquatic Endurance?' WHERE `word_id`=128016; -- locales_gossip_menu_option - option_text : menu_id=4042-id=1
UPDATE `trans_words` SET `content_loc7`='Emblem Gear' WHERE `word_id`=128942; -- locales_gossip_menu_option - option_text : menu_id=10173-id=2
UPDATE `trans_words` SET `content_loc7`='Garrosh is beyond redemption, Greatmother. I fear that in helping the Maghar, I have convinced Garrosh that he is unfit to lead.' WHERE `word_id`=269448; -- locales_gossip_menu_option - option_text : menu_id=7768-id=1
UPDATE `trans_words` SET `content_loc7`='Greatmother, I never had the honor. Durotan died long before my time, but his heroics are known to all on my world. The orcs of Azeroth reside in a place known as Durotar, named after your son. And... (You take a moment to breathe and think through what you are about to tell the Greatmother.)' WHERE `word_id`=129032; -- locales_gossip_menu_option - option_text : menu_id=7978-id=0
UPDATE `trans_words` SET `content_loc7`='Guide me back to the Alliance landing camp.' WHERE `word_id`=5466; -- locales_gossip_menu_option - option_text : menu_id=10128-id=5
UPDATE `trans_words` SET `content_loc7`='Guide me back to the Horde landing camp.' WHERE `word_id`=5465; -- locales_gossip_menu_option - option_text : menu_id=10129-id=5
UPDATE `trans_words` SET `content_loc7`='Guide me to the Broken Ring Graveyard.' WHERE `word_id`=128935; -- locales_gossip_menu_option - option_text : menu_id=10128-id=2
UPDATE `trans_words` SET `content_loc7`='Gul\'dan' WHERE `word_id`=84267; -- locales_gossip_menu_option - option_text : menu_id=4764-id=0
UPDATE `trans_words` SET `content_loc7`='Hmm, I listen. Also that you offer?' WHERE `word_id`=128551; -- locales_gossip_menu_option - option_text : menu_id=4781-id=1
UPDATE `trans_words` SET `content_loc7`='I have pald your price, Gloom\'rel. Now teach me your secrets!' WHERE `word_id`=128541; -- locales_gossip_menu_option - option_text : menu_id=1945-id=1
UPDATE `trans_words` SET `content_loc7`='I need to find Dajik, do you have his worn chalk?' WHERE `word_id`=128851; -- locales_gossip_menu_option - option_text : menu_id=9741-id=3
UPDATE `trans_words` SET `content_loc7`='I wish to to visit the Rise of the Defiler.' WHERE `word_id`=128540; -- locales_gossip_menu_option - option_text : menu_id=1541-id=0
UPDATE `trans_words` SET `content_loc7`='I wish to train my pet.' WHERE `word_id`=128552; -- locales_gossip_menu_option - option_text : menu_id=4783-id=3
UPDATE `trans_words` SET `content_loc7`='I wish to unlearn my pet\'s skills.' WHERE `word_id`=127826; -- locales_gossip_menu_option - option_text : menu_id=0-id=15
UPDATE `trans_words` SET `content_loc7`='I would speak against my brother joining the order, rushing a permanent breech in our relationship. He would be a danger to himself and those around him, and that is too great a risk hoping he would improve over time.' WHERE `word_id`=128210; -- locales_gossip_menu_option - option_text : menu_id=6209-id=0
UPDATE `trans_words` SET `content_loc7`='I\'m ready to fly! Take me to the dragon!' WHERE `word_id`=128676; -- locales_gossip_menu_option - option_text : menu_id=8229-id=0
UPDATE `trans_words` SET `content_loc7`='I\'ve been meaning to ask out about that monkey.' WHERE `word_id`=127949; -- locales_gossip_menu_option - option_text : menu_id=6555-id=0
UPDATE `trans_words` SET `content_loc7`='Im fine, thank you. You asked for me?' WHERE `word_id`=269450; -- locales_gossip_menu_option - option_text : menu_id=8436-id=0
UPDATE `trans_words` SET `content_loc7`='Is there anything you would have of me?' WHERE `word_id`=128367; -- locales_gossip_menu_option - option_text : menu_id=20007-id=1
UPDATE `trans_words` SET `content_loc7`='Lady Jaina, this may sound like an odd request... but I have a young ward who is quite shy. You are a hero to him, and he asked me to get your autograph.' WHERE `word_id`=127878; -- locales_gossip_menu_option - option_text : menu_id=2465-id=0
UPDATE `trans_words` SET `content_loc7`='Let me browse your goods' WHERE `word_id`=128103; -- locales_gossip_menu_option - option_text : menu_id=3130-id=0
UPDATE `trans_words` SET `content_loc7`='My answer - Alexstrasza.' WHERE `word_id`=127930; -- locales_gossip_menu_option - option_text : menu_id=4763-id=3
UPDATE `trans_words` SET `content_loc7`='My answer - Malygos.' WHERE `word_id`=127929; -- locales_gossip_menu_option - option_text : menu_id=4763-id=4
UPDATE `trans_words` SET `content_loc7`='My answer - Neltharion.' WHERE `word_id`=127932; -- locales_gossip_menu_option - option_text : menu_id=4763-id=1
UPDATE `trans_words` SET `content_loc7`='My answer - Nozdormu.' WHERE `word_id`=127931; -- locales_gossip_menu_option - option_text : menu_id=4763-id=2
UPDATE `trans_words` SET `content_loc7`='My answer - Ysera.' WHERE `word_id`=127933; -- locales_gossip_menu_option - option_text : menu_id=4763-id=0
UPDATE `trans_words` SET `content_loc7`='Ner\'zhul' WHERE `word_id`=128151; -- locales_gossip_menu_option - option_text : menu_id=4764-id=2
UPDATE `trans_words` SET `content_loc7`='Oh, its not my fault, I can assure you.' WHERE `word_id`=269449; -- locales_gossip_menu_option - option_text : menu_id=8435-id=0
UPDATE `trans_words` SET `content_loc7`='Paladin' WHERE `word_id`=99882; -- locales_gossip_menu_option - option_text : menu_id=10768-id=1
UPDATE `trans_words` SET `content_loc7`='Perhaps I can be of some assistance. I will make a deal with you, Satyr. I shall recover this unforged breastplate and slay the beast. In exchange for this task, you will teach me how to create the breastplate.' WHERE `word_id`=128373; -- locales_gossip_menu_option - option_text : menu_id=20019-id=0
UPDATE `trans_words` SET `content_loc7`='Read on, if you dare...' WHERE `word_id`=128279; -- locales_gossip_menu_option - option_text : menu_id=7984-id=0
UPDATE `trans_words` SET `content_loc7`='Send me to Shatter Point.' WHERE `word_id`=128671; -- locales_gossip_menu_option - option_text : menu_id=8100-id=0
UPDATE `trans_words` SET `content_loc7`='Teleport me to the Molten Core, Lothos.' WHERE `word_id`=128554; -- locales_gossip_menu_option - option_text : menu_id=5750-id=0
UPDATE `trans_words` SET `content_loc7`='Than I can help?' WHERE `word_id`=128526; -- locales_gossip_menu_option - option_text : menu_id=21-id=0
UPDATE `trans_words` SET `content_loc7`='Tharnariun, the trap is lost. Do you have another?' WHERE `word_id`=128455; -- locales_gossip_menu_option - option_text : menu_id=10482-id=0
UPDATE `trans_words` SET `content_loc7`='This Dimensional Imploder sounds dangerous! How can I make one?' WHERE `word_id`=128186; -- locales_gossip_menu_option - option_text : menu_id=6092-id=0
UPDATE `trans_words` SET `content_loc7`='Train me' WHERE `word_id`=128133; -- locales_gossip_menu_option - option_text : menu_id=3643-id=0
UPDATE `trans_words` SET `content_loc7`='Um, no... no, I don	 want that at all.' WHERE `word_id`=269451; -- locales_gossip_menu_option - option_text : menu_id=8437-id=0
UPDATE `trans_words` SET `content_loc7`='What does the Dalson\'s Tears Cauldron need?' WHERE `word_id`=128546; -- locales_gossip_menu_option - option_text : menu_id=3223-id=3
UPDATE `trans_words` SET `content_loc7`='What does the Felstone Field Cauldron need?' WHERE `word_id`=128545; -- locales_gossip_menu_option - option_text : menu_id=3223-id=2
UPDATE `trans_words` SET `content_loc7`='What does the Gahrron\'s Withering Cauldron need?' WHERE `word_id`=128548; -- locales_gossip_menu_option - option_text : menu_id=3223-id=5
UPDATE `trans_words` SET `content_loc7`='What does the Writhing Haunt Cauldron need?' WHERE `word_id`=128547; -- locales_gossip_menu_option - option_text : menu_id=3223-id=4
UPDATE `trans_words` SET `content_loc7`='What Guardian? I don	 understand any of this.' WHERE `word_id`=128488; -- locales_gossip_menu_option - option_text : menu_id=86-id=0
UPDATE `trans_words` SET `content_loc7`='What if I don\'t like drinking... Is there another way I can help out?' WHERE `word_id`=128309; -- locales_gossip_menu_option - option_text : menu_id=9006-id=0
UPDATE `trans_words` SET `content_loc7`='Yarp.' WHERE `word_id`=128313; -- locales_gossip_menu_option - option_text : menu_id=9023-id=0
UPDATE `trans_words` SET `content_loc7`='Yes elder. Tell me more of the book.' WHERE `word_id`=128719; -- locales_gossip_menu_option - option_text : menu_id=8617-id=0
UPDATE `trans_words` SET `content_loc7`='Yes... yes, it\'s me.' WHERE `word_id`=128718; -- locales_gossip_menu_option - option_text : menu_id=8616-id=0
UPDATE `trans_words` SET `content_loc7`='You gave the crew disguises?' WHERE `word_id`=128740; -- locales_gossip_menu_option - option_text : menu_id=8775-id=0

SET NAMES 'latin1';
