-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc5`='Aldor Gem Vendor' WHERE `word_id` = 127324; -- locales_points_of_interest - icon_name : entry=361
UPDATE `trans_words` SET `content_loc5`='Ammen Ford, Fisherwoman' WHERE `word_id` = 127295; -- locales_points_of_interest - icon_name : entry=232
UPDATE `trans_words` SET `content_loc5`='Arena Battlemaster Exodar' WHERE `word_id` = 127376; -- locales_points_of_interest - icon_name : entry=442
UPDATE `trans_words` SET `content_loc5`='Azure Watch, Alchemist' WHERE `word_id` = 127290; -- locales_points_of_interest - icon_name : entry=227
UPDATE `trans_words` SET `content_loc5`='Azure Watch, Engineering Trainer' WHERE `word_id` = 127293; -- locales_points_of_interest - icon_name : entry=230
UPDATE `trans_words` SET `content_loc5`='Azure Watch, First Aid Trainer' WHERE `word_id` = 127294; -- locales_points_of_interest - icon_name : entry=231
UPDATE `trans_words` SET `content_loc5`='Azure Watch, Herbalist' WHERE `word_id` = 127296; -- locales_points_of_interest - icon_name : entry=233
UPDATE `trans_words` SET `content_loc5`='Azure Watch, Hunter Trainer' WHERE `word_id` = 127284; -- locales_points_of_interest - icon_name : entry=221
UPDATE `trans_words` SET `content_loc5`='Azure Watch, Innkeeper' WHERE `word_id` = 127282; -- locales_points_of_interest - icon_name : entry=219
UPDATE `trans_words` SET `content_loc5`='Azure Watch, Mage Trainer' WHERE `word_id` = 127285; -- locales_points_of_interest - icon_name : entry=222
UPDATE `trans_words` SET `content_loc5`='Azure Watch, Mining Trainer' WHERE `word_id` = 127298; -- locales_points_of_interest - icon_name : entry=235
UPDATE `trans_words` SET `content_loc5`='Azure Watch, Paladin Trainer' WHERE `word_id` = 127286; -- locales_points_of_interest - icon_name : entry=223
UPDATE `trans_words` SET `content_loc5`='Azure Watch, Priest Trainer' WHERE `word_id` = 127287; -- locales_points_of_interest - icon_name : entry=224
UPDATE `trans_words` SET `content_loc5`='Azure Watch, Shaman Trainer' WHERE `word_id` = 127288; -- locales_points_of_interest - icon_name : entry=225
UPDATE `trans_words` SET `content_loc5`='Azure Watch, Stable Master' WHERE `word_id` = 127283; -- locales_points_of_interest - icon_name : entry=220
UPDATE `trans_words` SET `content_loc5`='Azure Watch, Warrior Trainer' WHERE `word_id` = 127289; -- locales_points_of_interest - icon_name : entry=226
UPDATE `trans_words` SET `content_loc5`='Battlemasters Darnassus' WHERE `word_id` = 127193; -- locales_points_of_interest - icon_name : entry=97
UPDATE `trans_words` SET `content_loc5`='Battlemasters Ironforge' WHERE `word_id` = 127183; -- locales_points_of_interest - icon_name : entry=59
UPDATE `trans_words` SET `content_loc5`='Battlemasters Orgrimmar' WHERE `word_id` = 127212; -- locales_points_of_interest - icon_name : entry=187
UPDATE `trans_words` SET `content_loc5`='Battlemasters Stormwind' WHERE `word_id` = 127172; -- locales_points_of_interest - icon_name : entry=29
UPDATE `trans_words` SET `content_loc5`='Battlemasters Thunder Bluff' WHERE `word_id` = 127240; -- locales_points_of_interest - icon_name : entry=317
UPDATE `trans_words` SET `content_loc5`='Battlemasters Undercity' WHERE `word_id` = 127234; -- locales_points_of_interest - icon_name : entry=280
UPDATE `trans_words` SET `content_loc5`='Bixi and Buliwyf' WHERE `word_id` = 127182; -- locales_points_of_interest - icon_name : entry=58
UPDATE `trans_words` SET `content_loc5`='Bloodhoof Village Inn' WHERE `word_id` = 127245; -- locales_points_of_interest - icon_name : entry=338
UPDATE `trans_words` SET `content_loc5`='Darnassus Alchemy Trainer' WHERE `word_id` = 127198; -- locales_points_of_interest - icon_name : entry=102
UPDATE `trans_words` SET `content_loc5`='Darnassus Bank' WHERE `word_id` = 127188; -- locales_points_of_interest - icon_name : entry=90
UPDATE `trans_words` SET `content_loc5`='Darnassus Cooking Trainer' WHERE `word_id` = 127199; -- locales_points_of_interest - icon_name : entry=103
UPDATE `trans_words` SET `content_loc5`='Darnassus Druid Trainer' WHERE `word_id` = 127194; -- locales_points_of_interest - icon_name : entry=98
UPDATE `trans_words` SET `content_loc5`='Darnassus Enchanting Trainer' WHERE `word_id` = 127200; -- locales_points_of_interest - icon_name : entry=104
UPDATE `trans_words` SET `content_loc5`='Darnassus First Aid Trainer' WHERE `word_id` = 127201; -- locales_points_of_interest - icon_name : entry=105
UPDATE `trans_words` SET `content_loc5`='Darnassus Fishing Trainer' WHERE `word_id` = 127202; -- locales_points_of_interest - icon_name : entry=106
UPDATE `trans_words` SET `content_loc5`='Darnassus Guild Master' WHERE `word_id` = 127190; -- locales_points_of_interest - icon_name : entry=92
UPDATE `trans_words` SET `content_loc5`='Darnassus Herbalism Trainer' WHERE `word_id` = 127249; -- locales_points_of_interest - icon_name : entry=440
UPDATE `trans_words` SET `content_loc5`='Darnassus Hippogryph Master' WHERE `word_id` = 127189; -- locales_points_of_interest - icon_name : entry=91
UPDATE `trans_words` SET `content_loc5`='Darnassus Hunter Trainer' WHERE `word_id` = 127195; -- locales_points_of_interest - icon_name : entry=99
UPDATE `trans_words` SET `content_loc5`='Darnassus Inn' WHERE `word_id` = 127191; -- locales_points_of_interest - icon_name : entry=93
UPDATE `trans_words` SET `content_loc5`='Darnassus Leatherworking Trainer' WHERE `word_id` = 127203; -- locales_points_of_interest - icon_name : entry=108
UPDATE `trans_words` SET `content_loc5`='Darnassus Mage Trainer' WHERE `word_id` = 127373; -- locales_points_of_interest - icon_name : entry=438
UPDATE `trans_words` SET `content_loc5`='Darnassus Mailbox' WHERE `word_id` = 127192; -- locales_points_of_interest - icon_name : entry=94
UPDATE `trans_words` SET `content_loc5`='Darnassus Paladin Trainer' WHERE `word_id` = 127374; -- locales_points_of_interest - icon_name : entry=439
UPDATE `trans_words` SET `content_loc5`='Darnassus Rogue Trainer' WHERE `word_id` = 127196; -- locales_points_of_interest - icon_name : entry=100
UPDATE `trans_words` SET `content_loc5`='Darnassus Skinning Trainer' WHERE `word_id` = 127204; -- locales_points_of_interest - icon_name : entry=109
UPDATE `trans_words` SET `content_loc5`='Darnassus Tailor' WHERE `word_id` = 127205; -- locales_points_of_interest - icon_name : entry=110
UPDATE `trans_words` SET `content_loc5`='Dolanaar Inn' WHERE `word_id` = 127206; -- locales_points_of_interest - icon_name : entry=111
UPDATE `trans_words` SET `content_loc5`='Eversong Woods, Leatherworker' WHERE `word_id` = 127371; -- locales_points_of_interest - icon_name : entry=416
UPDATE `trans_words` SET `content_loc5`='Eversong Woods, Skinner' WHERE `word_id` = 127372; -- locales_points_of_interest - icon_name : entry=417
UPDATE `trans_words` SET `content_loc5`='Exodar, Alchemist Trainers' WHERE `word_id` = 127269; -- locales_points_of_interest - icon_name : entry=205
UPDATE `trans_words` SET `content_loc5`='Exodar, Auctioneer' WHERE `word_id` = 127254; -- locales_points_of_interest - icon_name : entry=190
UPDATE `trans_words` SET `content_loc5`='Exodar, bank' WHERE `word_id` = 127255; -- locales_points_of_interest - icon_name : entry=191
UPDATE `trans_words` SET `content_loc5`='Exodar, Battlemasters' WHERE `word_id` = 127375; -- locales_points_of_interest - icon_name : entry=441
UPDATE `trans_words` SET `content_loc5`='Exodar, Blacksmithing Trainers' WHERE `word_id` = 127270; -- locales_points_of_interest - icon_name : entry=206
UPDATE `trans_words` SET `content_loc5`='Exodar, Cook' WHERE `word_id` = 127281; -- locales_points_of_interest - icon_name : entry=218
UPDATE `trans_words` SET `content_loc5`='Exodar, Druid Trainer' WHERE `word_id` = 127262; -- locales_points_of_interest - icon_name : entry=198
UPDATE `trans_words` SET `content_loc5`='Exodar, Enchanters' WHERE `word_id` = 127271; -- locales_points_of_interest - icon_name : entry=207
UPDATE `trans_words` SET `content_loc5`='Exodar, Engineering' WHERE `word_id` = 127272; -- locales_points_of_interest - icon_name : entry=208
UPDATE `trans_words` SET `content_loc5`='Exodar, First Aid Trainer' WHERE `word_id` = 127273; -- locales_points_of_interest - icon_name : entry=209
UPDATE `trans_words` SET `content_loc5`='Exodar, Fishing Trainer' WHERE `word_id` = 127274; -- locales_points_of_interest - icon_name : entry=210
UPDATE `trans_words` SET `content_loc5`='Exodar, Guild Master' WHERE `word_id` = 127257; -- locales_points_of_interest - icon_name : entry=193
UPDATE `trans_words` SET `content_loc5`='Exodar, Herbalist Trainer' WHERE `word_id` = 127275; -- locales_points_of_interest - icon_name : entry=211
UPDATE `trans_words` SET `content_loc5`='Exodar, Hippogryph Master' WHERE `word_id` = 127256; -- locales_points_of_interest - icon_name : entry=192
UPDATE `trans_words` SET `content_loc5`='Exodar, Hunter Trainers' WHERE `word_id` = 127263; -- locales_points_of_interest - icon_name : entry=199
UPDATE `trans_words` SET `content_loc5`='Exodar, Inn' WHERE `word_id` = 127258; -- locales_points_of_interest - icon_name : entry=194
UPDATE `trans_words` SET `content_loc5`='Exodar, Jewelcrafters' WHERE `word_id` = 127276; -- locales_points_of_interest - icon_name : entry=213
UPDATE `trans_words` SET `content_loc5`='Exodar, Leatherworking' WHERE `word_id` = 127277; -- locales_points_of_interest - icon_name : entry=214
UPDATE `trans_words` SET `content_loc5`='Exodar, Mage Trainers' WHERE `word_id` = 127264; -- locales_points_of_interest - icon_name : entry=200
UPDATE `trans_words` SET `content_loc5`='Exodar, Mailbox' WHERE `word_id` = 127259; -- locales_points_of_interest - icon_name : entry=195
UPDATE `trans_words` SET `content_loc5`='Exodar, Mining Trainers' WHERE `word_id` = 127278; -- locales_points_of_interest - icon_name : entry=215
UPDATE `trans_words` SET `content_loc5`='Exodar, Paladin Trainers' WHERE `word_id` = 127265; -- locales_points_of_interest - icon_name : entry=201
UPDATE `trans_words` SET `content_loc5`='Exodar, Priest Trainers' WHERE `word_id` = 127266; -- locales_points_of_interest - icon_name : entry=202
UPDATE `trans_words` SET `content_loc5`='Exodar, Shaman Trainer' WHERE `word_id` = 127267; -- locales_points_of_interest - icon_name : entry=203
UPDATE `trans_words` SET `content_loc5`='Exodar, Skinning Trainer' WHERE `word_id` = 127279; -- locales_points_of_interest - icon_name : entry=216
UPDATE `trans_words` SET `content_loc5`='Exodar, Stable Master' WHERE `word_id` = 127260; -- locales_points_of_interest - icon_name : entry=196
UPDATE `trans_words` SET `content_loc5`='Exodar, Tailors' WHERE `word_id` = 127280; -- locales_points_of_interest - icon_name : entry=217
UPDATE `trans_words` SET `content_loc5`='Exodar, Warrior Trainers' WHERE `word_id` = 127268; -- locales_points_of_interest - icon_name : entry=204
UPDATE `trans_words` SET `content_loc5`='Exodar, Weapon Master' WHERE `word_id` = 127261; -- locales_points_of_interest - icon_name : entry=197
UPDATE `trans_words` SET `content_loc5`='Falconwing Square, Cook' WHERE `word_id` = 127366; -- locales_points_of_interest - icon_name : entry=411
UPDATE `trans_words` SET `content_loc5`='Falconwing Square, First Aid Trainer' WHERE `word_id` = 127368; -- locales_points_of_interest - icon_name : entry=413
UPDATE `trans_words` SET `content_loc5`='Falconwing Square, Hunter Trainer' WHERE `word_id` = 127358; -- locales_points_of_interest - icon_name : entry=403
UPDATE `trans_words` SET `content_loc5`='Falconwing Square, Innkeeper' WHERE `word_id` = 127356; -- locales_points_of_interest - icon_name : entry=401
UPDATE `trans_words` SET `content_loc5`='Falconwing Square, Jewelcrafter' WHERE `word_id` = 127370; -- locales_points_of_interest - icon_name : entry=415
UPDATE `trans_words` SET `content_loc5`='Falconwing Square, Mage Trainer' WHERE `word_id` = 127359; -- locales_points_of_interest - icon_name : entry=404
UPDATE `trans_words` SET `content_loc5`='Falconwing Square, Priest Trainer' WHERE `word_id` = 127361; -- locales_points_of_interest - icon_name : entry=406
UPDATE `trans_words` SET `content_loc5`='Falconwing Square, Rogue Trainer' WHERE `word_id` = 127362; -- locales_points_of_interest - icon_name : entry=407
UPDATE `trans_words` SET `content_loc5`='Falconwing Square, Stable Master' WHERE `word_id` = 127357; -- locales_points_of_interest - icon_name : entry=402
UPDATE `trans_words` SET `content_loc5`='Falconwing Square, Warlock Trainer' WHERE `word_id` = 127363; -- locales_points_of_interest - icon_name : entry=408
UPDATE `trans_words` SET `content_loc5`='Farstrider Retreat, Blacksmith' WHERE `word_id` = 127365; -- locales_points_of_interest - icon_name : entry=410
UPDATE `trans_words` SET `content_loc5`='Hunter Lodge' WHERE `word_id` = 127173; -- locales_points_of_interest - icon_name : entry=33
UPDATE `trans_words` SET `content_loc5`='Ironforge Gryphon Master' WHERE `word_id` = 127179; -- locales_points_of_interest - icon_name : entry=53
UPDATE `trans_words` SET `content_loc5`='Ironforge Mailbox' WHERE `word_id` = 127181; -- locales_points_of_interest - icon_name : entry=56
UPDATE `trans_words` SET `content_loc5`='Ironforge Rogue Trainer' WHERE `word_id` = 127184; -- locales_points_of_interest - icon_name : entry=63
UPDATE `trans_words` SET `content_loc5`='Ironforge Shaman Trainer' WHERE `word_id` = 127251; -- locales_points_of_interest - icon_name : entry=65
UPDATE `trans_words` SET `content_loc5`='Ironforge Warlock Trainer' WHERE `word_id` = 127185; -- locales_points_of_interest - icon_name : entry=64
UPDATE `trans_words` SET `content_loc5`='Odesyus\' Landing, Blacksmith' WHERE `word_id` = 127291; -- locales_points_of_interest - icon_name : entry=228
UPDATE `trans_words` SET `content_loc5`='Odesyus\' Landing, Cook' WHERE `word_id` = 127292; -- locales_points_of_interest - icon_name : entry=229
UPDATE `trans_words` SET `content_loc5`='Odesyus\' Landing, Tailor' WHERE `word_id` = 127300; -- locales_points_of_interest - icon_name : entry=237
UPDATE `trans_words` SET `content_loc5`='Orgrimmar Eastern Zeppelin Tower' WHERE `word_id` = 127252; -- locales_points_of_interest - icon_name : entry=182
UPDATE `trans_words` SET `content_loc5`='Orgrimmar Hunter\'s Hall' WHERE `word_id` = 127248; -- locales_points_of_interest - icon_name : entry=420
UPDATE `trans_words` SET `content_loc5`='Orgrimmar Inn' WHERE `word_id` = 127208; -- locales_points_of_interest - icon_name : entry=179
UPDATE `trans_words` SET `content_loc5`='Orgrimmar Mailbox' WHERE `word_id` = 127209; -- locales_points_of_interest - icon_name : entry=180
UPDATE `trans_words` SET `content_loc5`='Razor Hill Inn' WHERE `word_id` = 127213; -- locales_points_of_interest - icon_name : entry=253
UPDATE `trans_words` SET `content_loc5`='Saltheril\'s Haven, Alchemist' WHERE `word_id` = 127364; -- locales_points_of_interest - icon_name : entry=409
UPDATE `trans_words` SET `content_loc5`='Saltheril\'s Haven, Enchanter' WHERE `word_id` = 127367; -- locales_points_of_interest - icon_name : entry=412
UPDATE `trans_words` SET `content_loc5`='Saltheril\'s Haven, Herbalist' WHERE `word_id` = 127369; -- locales_points_of_interest - icon_name : entry=414
UPDATE `trans_words` SET `content_loc5`='Saltheril\'s Haven, Tailor' WHERE `word_id` = 127247; -- locales_points_of_interest - icon_name : entry=418
UPDATE `trans_words` SET `content_loc5`='Sayoc & Hanashi' WHERE `word_id` = 127211; -- locales_points_of_interest - icon_name : entry=184
UPDATE `trans_words` SET `content_loc5`='Scryer Gem Vendor' WHERE `word_id` = 127325; -- locales_points_of_interest - icon_name : entry=362
UPDATE `trans_words` SET `content_loc5`='Shattrath Alchemist' WHERE `word_id` = 127305; -- locales_points_of_interest - icon_name : entry=342
UPDATE `trans_words` SET `content_loc5`='Shattrath Alchemy Lab' WHERE `word_id` = 127314; -- locales_points_of_interest - icon_name : entry=351
UPDATE `trans_words` SET `content_loc5`='Shattrath Arena Battlemasters' WHERE `word_id` = 127323; -- locales_points_of_interest - icon_name : entry=360
UPDATE `trans_words` SET `content_loc5`='Shattrath Armor/Weapon Crafter' WHERE `word_id` = 127306; -- locales_points_of_interest - icon_name : entry=343
UPDATE `trans_words` SET `content_loc5`='Shattrath Bank Aldor' WHERE `word_id` = 127315; -- locales_points_of_interest - icon_name : entry=352
UPDATE `trans_words` SET `content_loc5`='Shattrath Bank Scryer' WHERE `word_id` = 127316; -- locales_points_of_interest - icon_name : entry=353
UPDATE `trans_words` SET `content_loc5`='Shattrath Battlemasters Alliance' WHERE `word_id` = 127321; -- locales_points_of_interest - icon_name : entry=358
UPDATE `trans_words` SET `content_loc5`='Shattrath Battlemasters Horde' WHERE `word_id` = 127322; -- locales_points_of_interest - icon_name : entry=359
UPDATE `trans_words` SET `content_loc5`='Shattrath Cantina' WHERE `word_id` = 127303; -- locales_points_of_interest - icon_name : entry=340
UPDATE `trans_words` SET `content_loc5`='Shattrath Cook' WHERE `word_id` = 127307; -- locales_points_of_interest - icon_name : entry=344
UPDATE `trans_words` SET `content_loc5`='Shattrath Enchanters' WHERE `word_id` = 127308; -- locales_points_of_interest - icon_name : entry=345
UPDATE `trans_words` SET `content_loc5`='Shattrath First Aid' WHERE `word_id` = 127309; -- locales_points_of_interest - icon_name : entry=346
UPDATE `trans_words` SET `content_loc5`='Shattrath Inn Aldor' WHERE `word_id` = 127317; -- locales_points_of_interest - icon_name : entry=354
UPDATE `trans_words` SET `content_loc5`='Shattrath Inn Scryer' WHERE `word_id` = 127318; -- locales_points_of_interest - icon_name : entry=355
UPDATE `trans_words` SET `content_loc5`='Shattrath Jewelcrafter' WHERE `word_id` = 127310; -- locales_points_of_interest - icon_name : entry=347
UPDATE `trans_words` SET `content_loc5`='Shattrath Leatherworker' WHERE `word_id` = 127311; -- locales_points_of_interest - icon_name : entry=348
UPDATE `trans_words` SET `content_loc5`='Shattrath Mana Loom' WHERE `word_id` = 127313; -- locales_points_of_interest - icon_name : entry=350
UPDATE `trans_words` SET `content_loc5`='Shattrath Skinner' WHERE `word_id` = 127312; -- locales_points_of_interest - icon_name : entry=349
UPDATE `trans_words` SET `content_loc5`='Shattrath Stable Aldor' WHERE `word_id` = 127319; -- locales_points_of_interest - icon_name : entry=356
UPDATE `trans_words` SET `content_loc5`='Shattrath Stable Scryer' WHERE `word_id` = 127320; -- locales_points_of_interest - icon_name : entry=357
UPDATE `trans_words` SET `content_loc5`='Shattrath Taxi' WHERE `word_id` = 127304; -- locales_points_of_interest - icon_name : entry=341
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, Alchemy' WHERE `word_id` = 127342; -- locales_points_of_interest - icon_name : entry=386
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, Auction House' WHERE `word_id` = 127326; -- locales_points_of_interest - icon_name : entry=367
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, Bank' WHERE `word_id` = 127327; -- locales_points_of_interest - icon_name : entry=369
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, Battlemasters' WHERE `word_id` = 127334; -- locales_points_of_interest - icon_name : entry=378
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, Blacksmithing' WHERE `word_id` = 127343; -- locales_points_of_interest - icon_name : entry=387
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, Cooking' WHERE `word_id` = 127344; -- locales_points_of_interest - icon_name : entry=388
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, Druid Trainer' WHERE `word_id` = 127335; -- locales_points_of_interest - icon_name : entry=379
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, Enchanting' WHERE `word_id` = 127345; -- locales_points_of_interest - icon_name : entry=389
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, Engineering' WHERE `word_id` = 127346; -- locales_points_of_interest - icon_name : entry=390
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, First Aid' WHERE `word_id` = 127347; -- locales_points_of_interest - icon_name : entry=391
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, Fishing' WHERE `word_id` = 127348; -- locales_points_of_interest - icon_name : entry=392
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, Flight Master' WHERE `word_id` = 127328; -- locales_points_of_interest - icon_name : entry=371
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, Guild House' WHERE `word_id` = 127329; -- locales_points_of_interest - icon_name : entry=372
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, Herbalism' WHERE `word_id` = 127349; -- locales_points_of_interest - icon_name : entry=393
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, Hunter Trainer' WHERE `word_id` = 127336; -- locales_points_of_interest - icon_name : entry=380
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, Inn' WHERE `word_id` = 127330; -- locales_points_of_interest - icon_name : entry=373
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, Jewelcrafting' WHERE `word_id` = 127350; -- locales_points_of_interest - icon_name : entry=395
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, Leatherworking' WHERE `word_id` = 127351; -- locales_points_of_interest - icon_name : entry=396
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, Mage Trainer' WHERE `word_id` = 127337; -- locales_points_of_interest - icon_name : entry=381
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, Mailbox' WHERE `word_id` = 127331; -- locales_points_of_interest - icon_name : entry=375
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, Mana Loom' WHERE `word_id` = 127355; -- locales_points_of_interest - icon_name : entry=400
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, Mining' WHERE `word_id` = 127352; -- locales_points_of_interest - icon_name : entry=397
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, Paladin Trainer' WHERE `word_id` = 127338; -- locales_points_of_interest - icon_name : entry=382
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, Priest Trainer' WHERE `word_id` = 127339; -- locales_points_of_interest - icon_name : entry=383
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, Rogue Trainer' WHERE `word_id` = 127340; -- locales_points_of_interest - icon_name : entry=384
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, Skinning' WHERE `word_id` = 127353; -- locales_points_of_interest - icon_name : entry=398
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, Stable Master' WHERE `word_id` = 127332; -- locales_points_of_interest - icon_name : entry=376
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, Tailoring' WHERE `word_id` = 127354; -- locales_points_of_interest - icon_name : entry=399
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, Warlock Trainers' WHERE `word_id` = 127341; -- locales_points_of_interest - icon_name : entry=385
UPDATE `trans_words` SET `content_loc5`='Silvermoon City, Weapon Master' WHERE `word_id` = 127333; -- locales_points_of_interest - icon_name : entry=377
UPDATE `trans_words` SET `content_loc5`='Stillpine Hold, Leatherworker' WHERE `word_id` = 127297; -- locales_points_of_interest - icon_name : entry=234
UPDATE `trans_words` SET `content_loc5`='Stillpine Hold, Skinner' WHERE `word_id` = 127299; -- locales_points_of_interest - icon_name : entry=236
UPDATE `trans_words` SET `content_loc5`='Stonefire Tavern' WHERE `word_id` = 127180; -- locales_points_of_interest - icon_name : entry=55
UPDATE `trans_words` SET `content_loc5`='Stormwind - Rogue House' WHERE `word_id` = 127176; -- locales_points_of_interest - icon_name : entry=36
UPDATE `trans_words` SET `content_loc5`='Stormwind Bank' WHERE `word_id` = 127169; -- locales_points_of_interest - icon_name : entry=19
UPDATE `trans_words` SET `content_loc5`='Stormwind Barracks' WHERE `word_id` = 127177; -- locales_points_of_interest - icon_name : entry=39
UPDATE `trans_words` SET `content_loc5`='Stormwind Gryphon Master' WHERE `word_id` = 127171; -- locales_points_of_interest - icon_name : entry=23
UPDATE `trans_words` SET `content_loc5`='Stormwind Locksmith' WHERE `word_id` = 127250; -- locales_points_of_interest - icon_name : entry=25
UPDATE `trans_words` SET `content_loc5`='The Deeprun Tram' WHERE `word_id` = 127170; -- locales_points_of_interest - icon_name : entry=21
UPDATE `trans_words` SET `content_loc5`='The Vault' WHERE `word_id` = 127178; -- locales_points_of_interest - icon_name : entry=51
UPDATE `trans_words` SET `content_loc5`='Thunder Bluff Auction house' WHERE `word_id` = 127241; -- locales_points_of_interest - icon_name : entry=320
UPDATE `trans_words` SET `content_loc5`='Thunder Bluff Inn' WHERE `word_id` = 127243; -- locales_points_of_interest - icon_name : entry=322
UPDATE `trans_words` SET `content_loc5`='Thunder Bluff Mailbox' WHERE `word_id` = 127242; -- locales_points_of_interest - icon_name : entry=321
UPDATE `trans_words` SET `content_loc5`='Undercity Bank' WHERE `word_id` = 127236; -- locales_points_of_interest - icon_name : entry=283
UPDATE `trans_words` SET `content_loc5`='Undercity Bat Handler' WHERE `word_id` = 127235; -- locales_points_of_interest - icon_name : entry=281
UPDATE `trans_words` SET `content_loc5`='Undercity Blacksmithing Trainer' WHERE `word_id` = 127224; -- locales_points_of_interest - icon_name : entry=265
UPDATE `trans_words` SET `content_loc5`='Undercity Cooking Trainer' WHERE `word_id` = 127223; -- locales_points_of_interest - icon_name : entry=264
UPDATE `trans_words` SET `content_loc5`='Undercity Enchanting Trainer' WHERE `word_id` = 127222; -- locales_points_of_interest - icon_name : entry=263
UPDATE `trans_words` SET `content_loc5`='Undercity Engineering Trainer' WHERE `word_id` = 127221; -- locales_points_of_interest - icon_name : entry=262
UPDATE `trans_words` SET `content_loc5`='Undercity First Aid Trainer' WHERE `word_id` = 127220; -- locales_points_of_interest - icon_name : entry=261
UPDATE `trans_words` SET `content_loc5`='Undercity Fishing Trainer' WHERE `word_id` = 127219; -- locales_points_of_interest - icon_name : entry=260
UPDATE `trans_words` SET `content_loc5`='Undercity Guild Master' WHERE `word_id` = 127233; -- locales_points_of_interest - icon_name : entry=279
UPDATE `trans_words` SET `content_loc5`='Undercity Herbalism Trainer' WHERE `word_id` = 127218; -- locales_points_of_interest - icon_name : entry=259
UPDATE `trans_words` SET `content_loc5`='Undercity Inn' WHERE `word_id` = 127232; -- locales_points_of_interest - icon_name : entry=278
UPDATE `trans_words` SET `content_loc5`='Undercity Leatherworking Trainer' WHERE `word_id` = 127217; -- locales_points_of_interest - icon_name : entry=257
UPDATE `trans_words` SET `content_loc5`='Undercity Locksmith' WHERE `word_id` = 127301; -- locales_points_of_interest - icon_name : entry=277
UPDATE `trans_words` SET `content_loc5`='Undercity Mage Trainers' WHERE `word_id` = 127229; -- locales_points_of_interest - icon_name : entry=272
UPDATE `trans_words` SET `content_loc5`='Undercity Mailbox' WHERE `word_id` = 127231; -- locales_points_of_interest - icon_name : entry=276
UPDATE `trans_words` SET `content_loc5`='Undercity Mining Trainer' WHERE `word_id` = 127216; -- locales_points_of_interest - icon_name : entry=256
UPDATE `trans_words` SET `content_loc5`='Undercity Priest Trainers' WHERE `word_id` = 127228; -- locales_points_of_interest - icon_name : entry=270
UPDATE `trans_words` SET `content_loc5`='Undercity Rogue Trainers' WHERE `word_id` = 127227; -- locales_points_of_interest - icon_name : entry=269
UPDATE `trans_words` SET `content_loc5`='Undercity Skinning Trainer' WHERE `word_id` = 127215; -- locales_points_of_interest - icon_name : entry=255
UPDATE `trans_words` SET `content_loc5`='Undercity Tailoring Trainer' WHERE `word_id` = 127214; -- locales_points_of_interest - icon_name : entry=254
UPDATE `trans_words` SET `content_loc5`='Undercity Warlock Trainers' WHERE `word_id` = 127226; -- locales_points_of_interest - icon_name : entry=268
UPDATE `trans_words` SET `content_loc5`='Undercity Warrior Trainers' WHERE `word_id` = 127225; -- locales_points_of_interest - icon_name : entry=267
UPDATE `trans_words` SET `content_loc5`='Undercity Zeppelin' WHERE `word_id` = 127230; -- locales_points_of_interest - icon_name : entry=273
UPDATE `trans_words` SET `content_loc5`='Wind Rider Roost' WHERE `word_id` = 127244; -- locales_points_of_interest - icon_name : entry=324

SET NAMES 'latin1';
