-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc5`='68 TEST Green Cloth Belt' WHERE `word_id` = 27939; -- locales_item - name : entry=26128
UPDATE `trans_words` SET `content_loc5`='68 TEST Green Cloth Boot' WHERE `word_id` = 27940; -- locales_item - name : entry=26129
UPDATE `trans_words` SET `content_loc5`='68 TEST Green Cloth Chest' WHERE `word_id` = 27941; -- locales_item - name : entry=26130
UPDATE `trans_words` SET `content_loc5`='68 TEST Green Cloth Cloak' WHERE `word_id` = 27947; -- locales_item - name : entry=26513
UPDATE `trans_words` SET `content_loc5`='68 TEST Green Cloth Hand' WHERE `word_id` = 27942; -- locales_item - name : entry=26131
UPDATE `trans_words` SET `content_loc5`='68 TEST Green Cloth Head' WHERE `word_id` = 27943; -- locales_item - name : entry=26132
UPDATE `trans_words` SET `content_loc5`='68 TEST Green Cloth Legs' WHERE `word_id` = 27944; -- locales_item - name : entry=26133
UPDATE `trans_words` SET `content_loc5`='68 TEST Green Cloth Necklace' WHERE `word_id` = 27949; -- locales_item - name : entry=26541
UPDATE `trans_words` SET `content_loc5`='68 TEST Green Cloth Ring' WHERE `word_id` = 27948; -- locales_item - name : entry=26527
UPDATE `trans_words` SET `content_loc5`='68 TEST Green Cloth Shoulder' WHERE `word_id` = 27945; -- locales_item - name : entry=26134
UPDATE `trans_words` SET `content_loc5`='68 TEST Green Cloth Wrist' WHERE `word_id` = 27946; -- locales_item - name : entry=26135
UPDATE `trans_words` SET `content_loc5`='68 TEST Green Off Hand' WHERE `word_id` = 27950; -- locales_item - name : entry=26569
UPDATE `trans_words` SET `content_loc5`='68 TEST Green Spell Dagger' WHERE `word_id` = 27952; -- locales_item - name : entry=26779
UPDATE `trans_words` SET `content_loc5`='68 TEST Green Wand' WHERE `word_id` = 27951; -- locales_item - name : entry=26765
UPDATE `trans_words` SET `content_loc5`='A crystalline key that is seemingly held together by beams of light.' WHERE `word_id` = 31763; -- locales_item - description : entry=31704
UPDATE `trans_words` SET `content_loc5`='A reagent for mage spells.' WHERE `word_id` = 12315; -- locales_item - description : entry=5517
UPDATE `trans_words` SET `content_loc5`='Agmond\'s Belt Pouch' WHERE `word_id` = 24228; -- locales_item - name : entry=4981
UPDATE `trans_words` SET `content_loc5`='Alex\'s Ring of Audacity' WHERE `word_id` = 16991; -- locales_item - name : entry=12947
UPDATE `trans_words` SET `content_loc5`='Alex\'s Test Beatdown Staff' WHERE `word_id` = 21820; -- locales_item - name : entry=19879
UPDATE `trans_words` SET `content_loc5`='Ammen Vale Gift Voucher' WHERE `word_id` = 25024; -- locales_item - name : entry=22888
UPDATE `trans_words` SET `content_loc5`='And from the ashes it was reborn...' WHERE `word_id` = 32444; -- locales_item - description : entry=32458
UPDATE `trans_words` SET `content_loc5`='Archaedic Shard' WHERE `word_id` = 24322; -- locales_item - name : entry=9417
UPDATE `trans_words` SET `content_loc5`='Auchenai Key' WHERE `word_id` = 30711; -- locales_item - name : entry=30633
UPDATE `trans_words` SET `content_loc5`='Bears the mark of the Shattered Hand.' WHERE `word_id` = 25781; -- locales_item - description : entry=23881
UPDATE `trans_words` SET `content_loc5`='Bears the seal of Arazzius.' WHERE `word_id` = 28474; -- locales_item - description : entry=28046
UPDATE `trans_words` SET `content_loc5`='Bind On Acquire Test Item' WHERE `word_id` = 24319; -- locales_item - name : entry=8688
UPDATE `trans_words` SET `content_loc5`='Blessed Relic' WHERE `word_id` = 24187; -- locales_item - name : entry=2921
UPDATE `trans_words` SET `content_loc5`='Blue Bryanite of Agility' WHERE `word_id` = 25230; -- locales_item - name : entry=23234
UPDATE `trans_words` SET `content_loc5`='Cache of the Legion Key' WHERE `word_id` = 30546; -- locales_item - name : entry=30438
UPDATE `trans_words` SET `content_loc5`='Conjured Manna Biscuit' WHERE `word_id` = 33592; -- locales_item - name : entry=34062
UPDATE `trans_words` SET `content_loc5`='Conquerer\'s Band' WHERE `word_id` = 27691; -- locales_item - name : entry=25811
UPDATE `trans_words` SET `content_loc5`='Counts as an Air, Earth, Fire, and Water totem.' WHERE `word_id` = 23479; -- locales_item - description : entry=22345
UPDATE `trans_words` SET `content_loc5`='Cut cleanly off at the shoulders.' WHERE `word_id` = 31766; -- locales_item - description : entry=31706
UPDATE `trans_words` SET `content_loc5`='Demon Hunter Blindfold' WHERE `word_id` = 24215; -- locales_item - name : entry=3536
UPDATE `trans_words` SET `content_loc5`='Deprecated Feathered Helm' WHERE `word_id` = 24225; -- locales_item - name : entry=4193
UPDATE `trans_words` SET `content_loc5`='Deprecated Rogue\'s Vest' WHERE `word_id` = 24128; -- locales_item - name : entry=119
UPDATE `trans_words` SET `content_loc5`='Deprecated Silver Totem of Aquementas' WHERE `word_id` = 24337; -- locales_item - name : entry=11170
UPDATE `trans_words` SET `content_loc5`='Deprecated Silver-thread Cowl' WHERE `word_id` = 24198; -- locales_item - name : entry=3068
UPDATE `trans_words` SET `content_loc5`='Deprecated Stormrage Boots' WHERE `word_id` = 24383; -- locales_item - name : entry=13242
UPDATE `trans_words` SET `content_loc5`='Deprecated Tauren Trapper\'s Pants' WHERE `word_id` = 24129; -- locales_item - name : entry=128
UPDATE `trans_words` SET `content_loc5`='Diet McWeaksauce' WHERE `word_id` = 24081; -- locales_item - name : entry=23578
UPDATE `trans_words` SET `content_loc5`='Dragonstalker Tunic' WHERE `word_id` = 24377; -- locales_item - name : entry=13092
UPDATE `trans_words` SET `content_loc5`='Dreadmaster\'s Shroud' WHERE `word_id` = 24407; -- locales_item - name : entry=13936
UPDATE `trans_words` SET `content_loc5`='Eldr\'naan Boot' WHERE `word_id` = 26557; -- locales_item - name : entry=24670
UPDATE `trans_words` SET `content_loc5`='Elven Protector' WHERE `word_id` = 24326; -- locales_item - name : entry=9888
UPDATE `trans_words` SET `content_loc5`='Engraved with the words \'For years of service: -EVC.\'' WHERE `word_id` = 9700; -- locales_item - description : entry=2239
UPDATE `trans_words` SET `content_loc5`='Essence of the Firelord DEPRECATED' WHERE `word_id` = 24442; -- locales_item - name : entry=18566
UPDATE `trans_words` SET `content_loc5`='Etched on the side: Wazat will not be held accountable for any accidents that occur as a result of using the Jump-a-tron 4000.' WHERE `word_id` = 28303; -- locales_item - description : entry=27808
UPDATE `trans_words` SET `content_loc5`='Explosive Shell' WHERE `word_id` = 11998; -- locales_item - name : entry=5105
UPDATE `trans_words` SET `content_loc5`='First Sergeant\'s Cloak' WHERE `word_id` = 24428; -- locales_item - name : entry=16340
UPDATE `trans_words` SET `content_loc5`='Flamewrought Key' WHERE `word_id` = 30699; -- locales_item - name : entry=30622
UPDATE `trans_words` SET `content_loc5`='Food for the Mind' WHERE `word_id` = 24082; -- locales_item - description : entry=23578
UPDATE `trans_words` SET `content_loc5`='Formula: Enchant Boots - Minor Stamina' WHERE `word_id` = 24293; -- locales_item - name : entry=6376
UPDATE `trans_words` SET `content_loc5`='Formula: Enchant Gloves - Spell Strike' WHERE `word_id` = 28647; -- locales_item - name : entry=28271
UPDATE `trans_words` SET `content_loc5`='Formula: Imbue Cloak - Protection' WHERE `word_id` = 24290; -- locales_item - name : entry=6345
UPDATE `trans_words` SET `content_loc5`='Foror\'s Crate of Endless Resist Gear Storage' WHERE `word_id` = 25208; -- locales_item - name : entry=23162
UPDATE `trans_words` SET `content_loc5`='G.N.E.R.D.S.' WHERE `word_id` = 37233; -- locales_item - name : entry=37583
UPDATE `trans_words` SET `content_loc5`='Glaive of the Defender' WHERE `word_id` = 23918; -- locales_item - name : entry=23051
UPDATE `trans_words` SET `content_loc5`='Glyph of Arcane Warding' WHERE `word_id` = 29533; -- locales_item - name : entry=29195
UPDATE `trans_words` SET `content_loc5`='Glyph of Chromatic Warding' WHERE `word_id` = 30936; -- locales_item - name : entry=30845
UPDATE `trans_words` SET `content_loc5`='Glyph of Ferocity' WHERE `word_id` = 29530; -- locales_item - name : entry=29192
UPDATE `trans_words` SET `content_loc5`='Glyph of Fire Warding' WHERE `word_id` = 29534; -- locales_item - name : entry=29196
UPDATE `trans_words` SET `content_loc5`='Glyph of Frost Warding' WHERE `word_id` = 29535; -- locales_item - name : entry=29198
UPDATE `trans_words` SET `content_loc5`='Glyph of Nature Warding' WHERE `word_id` = 29532; -- locales_item - name : entry=29194
UPDATE `trans_words` SET `content_loc5`='Glyph of Power' WHERE `word_id` = 29529; -- locales_item - name : entry=29191
UPDATE `trans_words` SET `content_loc5`='Glyph of Renewal' WHERE `word_id` = 29528; -- locales_item - name : entry=29189
UPDATE `trans_words` SET `content_loc5`='Glyph of Shadow Warding' WHERE `word_id` = 29536; -- locales_item - name : entry=29199
UPDATE `trans_words` SET `content_loc5`='Glyph of the Defender' WHERE `word_id` = 29526; -- locales_item - name : entry=29186
UPDATE `trans_words` SET `content_loc5`='Glyph of the Gladiator' WHERE `word_id` = 29531; -- locales_item - name : entry=29193
UPDATE `trans_words` SET `content_loc5`='Glyph of the Outcast' WHERE `word_id` = 30937; -- locales_item - name : entry=30846
UPDATE `trans_words` SET `content_loc5`='Glyphic Rune' WHERE `word_id` = 14757; -- locales_item - name : entry=9572
UPDATE `trans_words` SET `content_loc5`='Goblin Gumbeaux' WHERE `word_id` = 33049; -- locales_item - name : entry=33218
UPDATE `trans_words` SET `content_loc5`='Gor\'tesh\'s severed head, propped up on a pike.' WHERE `word_id` = 15848; -- locales_item - description : entry=11079
UPDATE `trans_words` SET `content_loc5`='Gordok Inner Door Key' WHERE `word_id` = 20591; -- locales_item - name : entry=18268
UPDATE `trans_words` SET `content_loc5`='Harness: Black Ram' WHERE `word_id` = 24280; -- locales_item - name : entry=5874
UPDATE `trans_words` SET `content_loc5`='Harness: Blue Ram' WHERE `word_id` = 24281; -- locales_item - name : entry=5875
UPDATE `trans_words` SET `content_loc5`='His eyes are full of hatred.' WHERE `word_id` = 25802; -- locales_item - description : entry=23901
UPDATE `trans_words` SET `content_loc5`='Horn of the Skeletal Mount' WHERE `word_id` = 24313; -- locales_item - name : entry=8583
UPDATE `trans_words` SET `content_loc5`='It smells of death and fear.' WHERE `word_id` = 25787; -- locales_item - description : entry=23886
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:10611' WHERE `word_id` = 24328; -- locales_item - name : entry=10611
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:10612' WHERE `word_id` = 24329; -- locales_item - name : entry=10612
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:10615' WHERE `word_id` = 24330; -- locales_item - name : entry=10615
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:10616' WHERE `word_id` = 24331; -- locales_item - name : entry=10616
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:10617' WHERE `word_id` = 24332; -- locales_item - name : entry=10617
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:10619' WHERE `word_id` = 24333; -- locales_item - name : entry=10619
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:10756' WHERE `word_id` = 24334; -- locales_item - name : entry=10756
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:11021' WHERE `word_id` = 24335; -- locales_item - name : entry=11021
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:11041' WHERE `word_id` = 24336; -- locales_item - name : entry=11041
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:1117' WHERE `word_id` = 24132; -- locales_item - name : entry=1117
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:11586' WHERE `word_id` = 24339; -- locales_item - name : entry=11586
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:12183' WHERE `word_id` = 24343; -- locales_item - name : entry=12183
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:12290' WHERE `word_id` = 24344; -- locales_item - name : entry=12290
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:12294' WHERE `word_id` = 24345; -- locales_item - name : entry=12294
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:12297' WHERE `word_id` = 24346; -- locales_item - name : entry=12297
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:12452' WHERE `word_id` = 24347; -- locales_item - name : entry=12452
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:12453' WHERE `word_id` = 24348; -- locales_item - name : entry=12453
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:12454' WHERE `word_id` = 24349; -- locales_item - name : entry=12454
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:12456' WHERE `word_id` = 24350; -- locales_item - name : entry=12456
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:12523' WHERE `word_id` = 24351; -- locales_item - name : entry=12523
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:12593' WHERE `word_id` = 24352; -- locales_item - name : entry=12593
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:12629' WHERE `word_id` = 24353; -- locales_item - name : entry=12629
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:12745' WHERE `word_id` = 24355; -- locales_item - name : entry=12745
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:12786' WHERE `word_id` = 24356; -- locales_item - name : entry=12786
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:12787' WHERE `word_id` = 24357; -- locales_item - name : entry=12787
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:12851' WHERE `word_id` = 24358; -- locales_item - name : entry=12851
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:12853' WHERE `word_id` = 24359; -- locales_item - name : entry=12853
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:12856' WHERE `word_id` = 24360; -- locales_item - name : entry=12856
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:12857' WHERE `word_id` = 24361; -- locales_item - name : entry=12857
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:12859' WHERE `word_id` = 24362; -- locales_item - name : entry=12859
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:12861' WHERE `word_id` = 24363; -- locales_item - name : entry=12861
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:12863' WHERE `word_id` = 24364; -- locales_item - name : entry=12863
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:12865' WHERE `word_id` = 24365; -- locales_item - name : entry=12865
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:12867' WHERE `word_id` = 24366; -- locales_item - name : entry=12867
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:12868' WHERE `word_id` = 24367; -- locales_item - name : entry=12868
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:12893' WHERE `word_id` = 24368; -- locales_item - name : entry=12893
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:12937' WHERE `word_id` = 24369; -- locales_item - name : entry=12937
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:12941' WHERE `word_id` = 24370; -- locales_item - name : entry=12941
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:12944' WHERE `word_id` = 24371; -- locales_item - name : entry=12944
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:12951' WHERE `word_id` = 24372; -- locales_item - name : entry=12951
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:13061' WHERE `word_id` = 24374; -- locales_item - name : entry=13061
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:13147' WHERE `word_id` = 24378; -- locales_item - name : entry=13147
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:13165' WHERE `word_id` = 24379; -- locales_item - name : entry=13165
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:13219' WHERE `word_id` = 24381; -- locales_item - name : entry=13219
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:13222' WHERE `word_id` = 24382; -- locales_item - name : entry=13222
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:13312' WHERE `word_id` = 24386; -- locales_item - name : entry=13312
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:13319' WHERE `word_id` = 24387; -- locales_item - name : entry=13319
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:13341' WHERE `word_id` = 24388; -- locales_item - name : entry=13341
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:13406' WHERE `word_id` = 24389; -- locales_item - name : entry=13406
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:13407' WHERE `word_id` = 24390; -- locales_item - name : entry=13407
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:13604' WHERE `word_id` = 24394; -- locales_item - name : entry=13604
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:13605' WHERE `word_id` = 24395; -- locales_item - name : entry=13605
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:13606' WHERE `word_id` = 24396; -- locales_item - name : entry=13606
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:13607' WHERE `word_id` = 24397; -- locales_item - name : entry=13607
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:13609' WHERE `word_id` = 24398; -- locales_item - name : entry=13609
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:13610' WHERE `word_id` = 24399; -- locales_item - name : entry=13610
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:13707' WHERE `word_id` = 24402; -- locales_item - name : entry=13707
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:13721' WHERE `word_id` = 24403; -- locales_item - name : entry=13721
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:13855' WHERE `word_id` = 24405; -- locales_item - name : entry=13855
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:13924' WHERE `word_id` = 24406; -- locales_item - name : entry=13924
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:14105' WHERE `word_id` = 24409; -- locales_item - name : entry=14105
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:14118' WHERE `word_id` = 24410; -- locales_item - name : entry=14118
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:143' WHERE `word_id` = 24130; -- locales_item - name : entry=143
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:14475' WHERE `word_id` = 24411; -- locales_item - name : entry=14475
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:14642' WHERE `word_id` = 24413; -- locales_item - name : entry=14642
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:14643' WHERE `word_id` = 24414; -- locales_item - name : entry=14643
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:14706' WHERE `word_id` = 24415; -- locales_item - name : entry=14706
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:14870' WHERE `word_id` = 24417; -- locales_item - name : entry=14870
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:14875' WHERE `word_id` = 24418; -- locales_item - name : entry=14875
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:14880' WHERE `word_id` = 24419; -- locales_item - name : entry=14880
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:14882' WHERE `word_id` = 24420; -- locales_item - name : entry=14882
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:15460' WHERE `word_id` = 24423; -- locales_item - name : entry=15460
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:16582' WHERE `word_id` = 24429; -- locales_item - name : entry=16582
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:17123' WHERE `word_id` = 24433; -- locales_item - name : entry=17123
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:17282' WHERE `word_id` = 24435; -- locales_item - name : entry=17282
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:17283' WHERE `word_id` = 24436; -- locales_item - name : entry=17283
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:18596' WHERE `word_id` = 24443; -- locales_item - name : entry=18596
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:1896' WHERE `word_id` = 24135; -- locales_item - name : entry=1896
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:1897' WHERE `word_id` = 24136; -- locales_item - name : entry=1897
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:1899' WHERE `word_id` = 24137; -- locales_item - name : entry=1899
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:1900' WHERE `word_id` = 24138; -- locales_item - name : entry=1900
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:19015' WHERE `word_id` = 24445; -- locales_item - name : entry=19015
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:1902' WHERE `word_id` = 24139; -- locales_item - name : entry=1902
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:1903' WHERE `word_id` = 24140; -- locales_item - name : entry=1903
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:1904' WHERE `word_id` = 24141; -- locales_item - name : entry=1904
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:1905' WHERE `word_id` = 24142; -- locales_item - name : entry=1905
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:1906' WHERE `word_id` = 24143; -- locales_item - name : entry=1906
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:1907' WHERE `word_id` = 24144; -- locales_item - name : entry=1907
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:1908' WHERE `word_id` = 24145; -- locales_item - name : entry=1908
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:1909' WHERE `word_id` = 24146; -- locales_item - name : entry=1909
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:1910' WHERE `word_id` = 24147; -- locales_item - name : entry=1910
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:1911' WHERE `word_id` = 24148; -- locales_item - name : entry=1911
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:19485' WHERE `word_id` = 24447; -- locales_item - name : entry=19485
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:1957' WHERE `word_id` = 24149; -- locales_item - name : entry=1957
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:1961' WHERE `word_id` = 24150; -- locales_item - name : entry=1961
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:1984' WHERE `word_id` = 24151; -- locales_item - name : entry=1984
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:1985' WHERE `word_id` = 24152; -- locales_item - name : entry=1985
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:20417' WHERE `word_id` = 24454; -- locales_item - name : entry=20417
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:2051' WHERE `word_id` = 24153; -- locales_item - name : entry=2051
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:2052' WHERE `word_id` = 24154; -- locales_item - name : entry=2052
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:2053' WHERE `word_id` = 24155; -- locales_item - name : entry=2053
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:2081' WHERE `word_id` = 24156; -- locales_item - name : entry=2081
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:2147' WHERE `word_id` = 24157; -- locales_item - name : entry=2147
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:2178' WHERE `word_id` = 24160; -- locales_item - name : entry=2178
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:2179' WHERE `word_id` = 24161; -- locales_item - name : entry=2179
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:2180' WHERE `word_id` = 24162; -- locales_item - name : entry=2180
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:2183' WHERE `word_id` = 24163; -- locales_item - name : entry=2183
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:2184' WHERE `word_id` = 24164; -- locales_item - name : entry=2184
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:2197' WHERE `word_id` = 24165; -- locales_item - name : entry=2197
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:2198' WHERE `word_id` = 24166; -- locales_item - name : entry=2198
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:2202' WHERE `word_id` = 24167; -- locales_item - name : entry=2202
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:23052' WHERE `word_id` = 25122; -- locales_item - name : entry=23052
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:23174' WHERE `word_id` = 25216; -- locales_item - name : entry=23174
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:23889' WHERE `word_id` = 25792; -- locales_item - name : entry=23889
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:2550' WHERE `word_id` = 24172; -- locales_item - name : entry=2550
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:2551' WHERE `word_id` = 24173; -- locales_item - name : entry=2551
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:2552' WHERE `word_id` = 24174; -- locales_item - name : entry=2552
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:2557' WHERE `word_id` = 24175; -- locales_item - name : entry=2557
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:2559' WHERE `word_id` = 24176; -- locales_item - name : entry=2559
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:2705' WHERE `word_id` = 24178; -- locales_item - name : entry=2705
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:2711' WHERE `word_id` = 24179; -- locales_item - name : entry=2711
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:2714' WHERE `word_id` = 24180; -- locales_item - name : entry=2714
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:28023' WHERE `word_id` = 28451; -- locales_item - name : entry=28023
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:2809' WHERE `word_id` = 24181; -- locales_item - name : entry=2809
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:2810' WHERE `word_id` = 24182; -- locales_item - name : entry=2810
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:2812' WHERE `word_id` = 24183; -- locales_item - name : entry=2812
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:2813' WHERE `word_id` = 24184; -- locales_item - name : entry=2813
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:2827' WHERE `word_id` = 24185; -- locales_item - name : entry=2827
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:32826' WHERE `word_id` = 32772; -- locales_item - name : entry=32826
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:3326' WHERE `word_id` = 24206; -- locales_item - name : entry=3326
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:3346' WHERE `word_id` = 24207; -- locales_item - name : entry=3346
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:3361' WHERE `word_id` = 24208; -- locales_item - name : entry=3361
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:3364' WHERE `word_id` = 24209; -- locales_item - name : entry=3364
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:3432' WHERE `word_id` = 24213; -- locales_item - name : entry=3432
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:3694' WHERE `word_id` = 24217; -- locales_item - name : entry=3694
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:3695' WHERE `word_id` = 24218; -- locales_item - name : entry=3695
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:3697' WHERE `word_id` = 24219; -- locales_item - name : entry=3697
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:3757' WHERE `word_id` = 24222; -- locales_item - name : entry=3757
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:4991' WHERE `word_id` = 24232; -- locales_item - name : entry=4991
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:4994' WHERE `word_id` = 24233; -- locales_item - name : entry=4994
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:5258' WHERE `word_id` = 24240; -- locales_item - name : entry=5258
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:5259' WHERE `word_id` = 24241; -- locales_item - name : entry=5259
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:5260' WHERE `word_id` = 24242; -- locales_item - name : entry=5260
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:5261' WHERE `word_id` = 24243; -- locales_item - name : entry=5261
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:5262' WHERE `word_id` = 24244; -- locales_item - name : entry=5262
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:5276' WHERE `word_id` = 24245; -- locales_item - name : entry=5276
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:5277' WHERE `word_id` = 24246; -- locales_item - name : entry=5277
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:5278' WHERE `word_id` = 24247; -- locales_item - name : entry=5278
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:5280' WHERE `word_id` = 24248; -- locales_item - name : entry=5280
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:5281' WHERE `word_id` = 24249; -- locales_item - name : entry=5281
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:5283' WHERE `word_id` = 24250; -- locales_item - name : entry=5283
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:5284' WHERE `word_id` = 24251; -- locales_item - name : entry=5284
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:5285' WHERE `word_id` = 24252; -- locales_item - name : entry=5285
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:5286' WHERE `word_id` = 24253; -- locales_item - name : entry=5286
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:5287' WHERE `word_id` = 24254; -- locales_item - name : entry=5287
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:5288' WHERE `word_id` = 24255; -- locales_item - name : entry=5288
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:5289' WHERE `word_id` = 24256; -- locales_item - name : entry=5289
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:5291' WHERE `word_id` = 24257; -- locales_item - name : entry=5291
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:5292' WHERE `word_id` = 24258; -- locales_item - name : entry=5292
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:5293' WHERE `word_id` = 24259; -- locales_item - name : entry=5293
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:5300' WHERE `word_id` = 24260; -- locales_item - name : entry=5300
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:5301' WHERE `word_id` = 24261; -- locales_item - name : entry=5301
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:5303' WHERE `word_id` = 24262; -- locales_item - name : entry=5303
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:5304' WHERE `word_id` = 24263; -- locales_item - name : entry=5304
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:5305' WHERE `word_id` = 24264; -- locales_item - name : entry=5305
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:5491' WHERE `word_id` = 24267; -- locales_item - name : entry=5491
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:5598' WHERE `word_id` = 24270; -- locales_item - name : entry=5598
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:5856' WHERE `word_id` = 24275; -- locales_item - name : entry=5856
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:6088' WHERE `word_id` = 24283; -- locales_item - name : entry=6088
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:6224' WHERE `word_id` = 24286; -- locales_item - name : entry=6224
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:6231' WHERE `word_id` = 24287; -- locales_item - name : entry=6231
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:6334' WHERE `word_id` = 24289; -- locales_item - name : entry=6334
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:6618' WHERE `word_id` = 24296; -- locales_item - name : entry=6618
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:6886' WHERE `word_id` = 24299; -- locales_item - name : entry=6886
UPDATE `trans_words` SET `content_loc5`='Item Text Missing:751' WHERE `word_id` = 24131; -- locales_item - name : entry=751
UPDATE `trans_words` SET `content_loc5`='James\' Key' WHERE `word_id` = 20248; -- locales_item - name : entry=17262
UPDATE `trans_words` SET `content_loc5`='Jump-a-tron 4000 Key' WHERE `word_id` = 28302; -- locales_item - name : entry=27808
UPDATE `trans_words` SET `content_loc5`='Key of Time' WHERE `word_id` = 30715; -- locales_item - name : entry=30635
UPDATE `trans_words` SET `content_loc5`='Key to Salem\'s Chest' WHERE `word_id` = 20246; -- locales_item - name : entry=17242
UPDATE `trans_words` SET `content_loc5`='Kodo Mount' WHERE `word_id` = 24408; -- locales_item - name : entry=14062
UPDATE `trans_words` SET `content_loc5`='Large Moneybag' WHERE `word_id` = 24298; -- locales_item - name : entry=6754
UPDATE `trans_words` SET `content_loc5`='Learn how to permanently enchant a Melee Weapon to increase the damage done by your arcane and fire spells by up to 50.' WHERE `word_id` = 24896; -- locales_item - description : entry=22560
UPDATE `trans_words` SET `content_loc5`='Learn how to permanently enchant a Melee Weapon to increase the damage done by your frost and shadow spells by up to 54.' WHERE `word_id` = 24898; -- locales_item - description : entry=22561
UPDATE `trans_words` SET `content_loc5`='Learn how to permanently enchant a Melee Weapon to occasionally ignore 840 of your enemy\'s armor. Requires a level 60 or higher item.' WHERE `word_id` = 33129; -- locales_item - description : entry=33307
UPDATE `trans_words` SET `content_loc5`='Learn how to permanently enchant a Melee Weapon to occasionally increase Agility by 120 and attack speed slightly.' WHERE `word_id` = 24894; -- locales_item - description : entry=22559
UPDATE `trans_words` SET `content_loc5`='Learn how to permanently enchant a weapon so your damaging spells and melee weapon hits occasionally inflict an additional 150 Frost damage and reduce the target\'s melee, ranged, and casting speed by 15%for 8 sec.' WHERE `word_id` = 34521; -- locales_item - description : entry=35498
UPDATE `trans_words` SET `content_loc5`='Librarian\'s Satchel' WHERE `word_id` = 24223; -- locales_item - name : entry=3762
UPDATE `trans_words` SET `content_loc5`='Lok\'delar, Stave of the Ancient Keepers DEP' WHERE `word_id` = 22194; -- locales_item - name : entry=20487
UPDATE `trans_words` SET `content_loc5`='Looks great. Less filling.' WHERE `word_id` = 16992; -- locales_item - description : entry=12947
UPDATE `trans_words` SET `content_loc5`='Manual: The Path of Defense' WHERE `word_id` = 24297; -- locales_item - name : entry=6619
UPDATE `trans_words` SET `content_loc5`='Master Key to the Depths, Courtesy of F.F.F.' WHERE `word_id` = 15831; -- locales_item - description : entry=11000
UPDATE `trans_words` SET `content_loc5`='Mistyreed Boot' WHERE `word_id` = 26525; -- locales_item - name : entry=24638
UPDATE `trans_words` SET `content_loc5`='Mistyreed Bracer' WHERE `word_id` = 26531; -- locales_item - name : entry=24644
UPDATE `trans_words` SET `content_loc5`='Mystical Powder' WHERE `word_id` = 24284; -- locales_item - name : entry=6216
UPDATE `trans_words` SET `content_loc5`='Naga Treasure Map - Questgiver (PH)' WHERE `word_id` = 30529; -- locales_item - name : entry=30427
UPDATE `trans_words` SET `content_loc5`='Nessingwary Longrifle' WHERE `word_id` = 27156; -- locales_item - name : entry=25278
UPDATE `trans_words` SET `content_loc5`='New Bent Staff' WHERE `word_id` = 24561; -- locales_item - name : entry=20978
UPDATE `trans_words` SET `content_loc5`='NYI - THIS ITEM WILL SPAWN A QUEST' WHERE `word_id` = 24221; -- locales_item - description : entry=3744
UPDATE `trans_words` SET `content_loc5`='Obsidian Golem Shard' WHERE `word_id` = 24306; -- locales_item - name : entry=7681
UPDATE `trans_words` SET `content_loc5`='Old Whistle of the Ivory Raptor' WHERE `word_id` = 24314; -- locales_item - name : entry=8589
UPDATE `trans_words` SET `content_loc5`='Old Whistle of the Obsidian Raptor' WHERE `word_id` = 24315; -- locales_item - name : entry=8590
UPDATE `trans_words` SET `content_loc5`='Only ONE May Rise... (and consequently, only ONE may loot this head)' WHERE `word_id` = 22115; -- locales_item - description : entry=20383
UPDATE `trans_words` SET `content_loc5`='Open for a prize!' WHERE `word_id` = 24277; -- locales_item - description : entry=5858
UPDATE `trans_words` SET `content_loc5`='Opens Dark Cleric Salem\'s Chest' WHERE `word_id` = 20247; -- locales_item - description : entry=17242
UPDATE `trans_words` SET `content_loc5`='Opens the stolen chest from the Cathedral of Light' WHERE `word_id` = 20249; -- locales_item - description : entry=17262
UPDATE `trans_words` SET `content_loc5`='Plans: Goblin Rocket Boots' WHERE `word_id` = 24303; -- locales_item - name : entry=7192
UPDATE `trans_words` SET `content_loc5`='QR 9863 Warrior Chest' WHERE `word_id` = 27451; -- locales_item - name : entry=25573
UPDATE `trans_words` SET `content_loc5`='QR 9867 Hunter Gloves' WHERE `word_id` = 27459; -- locales_item - name : entry=25581
UPDATE `trans_words` SET `content_loc5`='QR 9867 Warrior Legs' WHERE `word_id` = 27458; -- locales_item - name : entry=25580
UPDATE `trans_words` SET `content_loc5`='QR 9922 Shield' WHERE `word_id` = 27497; -- locales_item - name : entry=25627
UPDATE `trans_words` SET `content_loc5`='Red Bryanite of Strength stuff' WHERE `word_id` = 25229; -- locales_item - name : entry=23233
UPDATE `trans_words` SET `content_loc5`='Reins of the Spotted Nightsaber' WHERE `word_id` = 14355; -- locales_item - name : entry=8628
UPDATE `trans_words` SET `content_loc5`='Relic of the Dead' WHERE `word_id` = 24194; -- locales_item - name : entry=3004
UPDATE `trans_words` SET `content_loc5`='Relic of the Eye' WHERE `word_id` = 24193; -- locales_item - name : entry=3003
UPDATE `trans_words` SET `content_loc5`='Relic of Truth' WHERE `word_id` = 24195; -- locales_item - name : entry=3005
UPDATE `trans_words` SET `content_loc5`='Required by jewelcrafters to transmute mercurial adamantite.' WHERE `word_id` = 31170; -- locales_item - description : entry=31080
UPDATE `trans_words` SET `content_loc5`='Requires artisan riding skill or higher to use.' WHERE `word_id` = 33591; -- locales_item - description : entry=34061
UPDATE `trans_words` SET `content_loc5`='Requires expert riding skill or higher to use.' WHERE `word_id` = 33589; -- locales_item - description : entry=34060
UPDATE `trans_words` SET `content_loc5`='Reservoir Key' WHERE `word_id` = 30701; -- locales_item - name : entry=30623
UPDATE `trans_words` SET `content_loc5`='Rhok\'delar, Longbow of the Ancient Keepers DEP' WHERE `word_id` = 22195; -- locales_item - name : entry=20488
UPDATE `trans_words` SET `content_loc5`='Ring of Critical Testing 2' WHERE `word_id` = 21161; -- locales_item - name : entry=18970
UPDATE `trans_words` SET `content_loc5`='Sacred Relic' WHERE `word_id` = 24186; -- locales_item - name : entry=2920
UPDATE `trans_words` SET `content_loc5`='Sergeant Major\'s Cape' WHERE `word_id` = 24426; -- locales_item - name : entry=16315
UPDATE `trans_words` SET `content_loc5`='Sergeant\'s Insignia' WHERE `word_id` = 24427; -- locales_item - name : entry=16334
UPDATE `trans_words` SET `content_loc5`='Shadowforge Key' WHERE `word_id` = 15830; -- locales_item - name : entry=11000
UPDATE `trans_words` SET `content_loc5`='Silver Throwing Knifes' WHERE `word_id` = 28909; -- locales_item - name : entry=28532
UPDATE `trans_words` SET `content_loc5`='Skeleton Key' WHERE `word_id` = 17505; -- locales_item - name : entry=13704
UPDATE `trans_words` SET `content_loc5`='Softer than any material found on Azeroth.' WHERE `word_id` = 28864; -- locales_item - description : entry=28490
UPDATE `trans_words` SET `content_loc5`='Spirit Relic' WHERE `word_id` = 24188; -- locales_item - name : entry=2922
UPDATE `trans_words` SET `content_loc5`='Still flying...' WHERE `word_id` = 30090; -- locales_item - description : entry=29960
UPDATE `trans_words` SET `content_loc5`='Stormwind Seasoning Salts' WHERE `word_id` = 24177; -- locales_item - name : entry=2693
UPDATE `trans_words` SET `content_loc5`='Sunstrider Isle Gift Voucher' WHERE `word_id` = 24535; -- locales_item - name : entry=20938
UPDATE `trans_words` SET `content_loc5`='Suntrider\'s Gauntlets' WHERE `word_id` = 27365; -- locales_item - name : entry=25481
UPDATE `trans_words` SET `content_loc5`='Talisman of Binding Shard' WHERE `word_id` = 20467; -- locales_item - name : entry=17782
UPDATE `trans_words` SET `content_loc5`='TCHILTON TEST DAWNSTONE' WHERE `word_id` = 28769; -- locales_item - name : entry=28389
UPDATE `trans_words` SET `content_loc5`='TCHILTON TEST RUBY' WHERE `word_id` = 28768; -- locales_item - name : entry=28388
UPDATE `trans_words` SET `content_loc5`='Teaches how to permanently enchant a cloak to grant 12 defense rating. Requires a level 35 or higher item.' WHERE `word_id` = 34588; -- locales_item - description : entry=35756
UPDATE `trans_words` SET `content_loc5`='Teaches how to permanently enchant a piece of chest armor to grant 15 defense rating. Requires a level 35 or higher item.' WHERE `word_id` = 34523; -- locales_item - description : entry=35500
UPDATE `trans_words` SET `content_loc5`='Teaches you how to cook a Herb Baked Egg.' WHERE `word_id` = 24301; -- locales_item - description : entry=6891
UPDATE `trans_words` SET `content_loc5`='Teaches you how to cook a Sporeling Snack.' WHERE `word_id` = 28173; -- locales_item - description : entry=27689
UPDATE `trans_words` SET `content_loc5`='Teaches you how to cut a Infused Nightseye.' WHERE `word_id` = 31923; -- locales_item - description : entry=31877
UPDATE `trans_words` SET `content_loc5`='Teaches you how to cut a Infused Shadowsong Amethyst.' WHERE `word_id` = 32262; -- locales_item - description : entry=32300
UPDATE `trans_words` SET `content_loc5`='Teaches you how to make Goblin Rocket Boots.' WHERE `word_id` = 24304; -- locales_item - description : entry=7192
UPDATE `trans_words` SET `content_loc5`='Teaches you how to make Thorium Shells.' WHERE `word_id` = 19461; -- locales_item - description : entry=16051
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a bracer to give 12 defense rating.' WHERE `word_id` = 24838; -- locales_item - description : entry=22530
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a bracer to increase spell damage and healing by up to 15.' WHERE `word_id` = 24846; -- locales_item - description : entry=22534
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a bracer to increase Stamina by 12.' WHERE `word_id` = 24844; -- locales_item - description : entry=22533
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a bracer to increase the effect of healing spells by up to 30 and damage spells by up to 10.' WHERE `word_id` = 24840; -- locales_item - description : entry=22531
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a bracer to restore 6 mana every 5 seconds.' WHERE `word_id` = 24842; -- locales_item - description : entry=22532
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a chest item to give 15 resilience rating.' WHERE `word_id` = 28646; -- locales_item - description : entry=28270
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a cloak to give 10 additional armor.' WHERE `word_id` = 24291; -- locales_item - description : entry=6345
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a cloak to give 20 Spell Penetration.' WHERE `word_id` = 28654; -- locales_item - description : entry=28274
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a cloak to increase all resistances by 7.' WHERE `word_id` = 24872; -- locales_item - description : entry=22548
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a cloak to increase Arcane Resistance by 15.' WHERE `word_id` = 28657; -- locales_item - description : entry=28276
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a cloak to increase Shadow Resistance by 15.' WHERE `word_id` = 28659; -- locales_item - description : entry=28277
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a Melee Weapon to have a 3%chance on spellcast to restore 100 mana to all party members over 10 seconds.' WHERE `word_id` = 24892; -- locales_item - description : entry=22558
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a melee weapon to increase healing by 81 and spell damage by 27.' WHERE `word_id` = 28666; -- locales_item - description : entry=28281
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a melee weapon to increase spell damage and healing by up to 40.' WHERE `word_id` = 24886; -- locales_item - description : entry=22555
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a pair of boots to grant +1 Stamina.' WHERE `word_id` = 24294; -- locales_item - description : entry=6376
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a ring to add 2 damage to physical attacks.' WHERE `word_id` = 24848; -- locales_item - description : entry=22535
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a ring to increase all stats by 4.' WHERE `word_id` = 24854; -- locales_item - description : entry=22538
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a ring to increase healing spell effects by up to 20 and damage spell effects by up to 7.' WHERE `word_id` = 24852; -- locales_item - description : entry=22537
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a ring to increase spell damage and healing by up to 12.' WHERE `word_id` = 24850; -- locales_item - description : entry=22536
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a shield to give +15 block rating.' WHERE `word_id` = 24858; -- locales_item - description : entry=22540
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a shield to give 18 Stamina.' WHERE `word_id` = 28668; -- locales_item - description : entry=28282
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a shield to increase all spell resistances by 5.' WHERE `word_id` = 24860; -- locales_item - description : entry=22541
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a shield to increase Intellect by 12.' WHERE `word_id` = 24856; -- locales_item - description : entry=22539
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a two-handed weapon to increase Agility by 35.' WHERE `word_id` = 24888; -- locales_item - description : entry=22556
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a two-handed weapon to increase attack power by 70.' WHERE `word_id` = 24884; -- locales_item - description : entry=22554
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a weapon to give a chance on striking to heal your party of 180 to 300 damage.' WHERE `word_id` = 24890; -- locales_item - description : entry=22557
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a weapon to grant 20 Agility.' WHERE `word_id` = 33017; -- locales_item - description : entry=33165
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a weapon to increase damage by 7.' WHERE `word_id` = 24880; -- locales_item - description : entry=22552
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a weapon to increase Intellect by 30.' WHERE `word_id` = 24878; -- locales_item - description : entry=22551
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a weapon to increase Strength by 20.' WHERE `word_id` = 24882; -- locales_item - description : entry=22553
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant boots to give 5%snare and root resistance as well as 10 hit rating.' WHERE `word_id` = 24868; -- locales_item - description : entry=22545
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant boots to grant 12 Agility.' WHERE `word_id` = 24866; -- locales_item - description : entry=22544
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant boots to grant 12 Stamina.' WHERE `word_id` = 24864; -- locales_item - description : entry=22543
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant boots to increase move speed slightly and Agility by 6.' WHERE `word_id` = 28662; -- locales_item - description : entry=28279
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant boots to increase move speed slightly and Stamina by 9.' WHERE `word_id` = 28664; -- locales_item - description : entry=28280
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant boots to restore 4 mana and health every 5 seconds.' WHERE `word_id` = 24862; -- locales_item - description : entry=22542
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant chest armor to increase all stats by 6.' WHERE `word_id` = 24870; -- locales_item - description : entry=22547
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant gloves to grant 15 spell hit rating.' WHERE `word_id` = 28648; -- locales_item - description : entry=28271
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant gloves to increase Healing by 35 and Spell Damage by 12.' WHERE `word_id` = 28652; -- locales_item - description : entry=28273
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant gloves to increase spell damage and healing by up to 20.' WHERE `word_id` = 28650; -- locales_item - description : entry=28272
UPDATE `trans_words` SET `content_loc5`='Test Arcane Res Legs Mail' WHERE `word_id` = 19488; -- locales_item - name : entry=16165
UPDATE `trans_words` SET `content_loc5`='Test Stationery' WHERE `word_id` = 14090; -- locales_item - name : entry=8164
UPDATE `trans_words` SET `content_loc5`='The bottom of the crate is leaking. Leaking tears...' WHERE `word_id` = 25209; -- locales_item - description : entry=23162
UPDATE `trans_words` SET `content_loc5`='The completed amulet of Rakh\'likh.' WHERE `word_id` = 15727; -- locales_item - description : entry=10757
UPDATE `trans_words` SET `content_loc5`='The Fall of Ameth\'Aran' WHERE `word_id` = 24269; -- locales_item - name : entry=5563
UPDATE `trans_words` SET `content_loc5`='The Lay of Ameth\'Aran' WHERE `word_id` = 24268; -- locales_item - name : entry=5562
UPDATE `trans_words` SET `content_loc5`='The Master\'s Key' WHERE `word_id` = 26403; -- locales_item - name : entry=24490
UPDATE `trans_words` SET `content_loc5`='The McWeaksauce Classic' WHERE `word_id` = 24083; -- locales_item - name : entry=23579
UPDATE `trans_words` SET `content_loc5`='The Original.' WHERE `word_id` = 24084; -- locales_item - description : entry=23579
UPDATE `trans_words` SET `content_loc5`='The Tempest Key' WHERE `word_id` = 31762; -- locales_item - name : entry=31704
UPDATE `trans_words` SET `content_loc5`='The totem\'s inscription identifies the bearer as an ally of the water elemental Naias.' WHERE `word_id` = 25572; -- locales_item - description : entry=23680
UPDATE `trans_words` SET `content_loc5`='They look heavily worn, yet still remain razor sharp.' WHERE `word_id` = 25579; -- locales_item - description : entry=23687
UPDATE `trans_words` SET `content_loc5`='This blade is dimensional. It appears to be fading from this plane of existence.' WHERE `word_id` = 23739; -- locales_item - description : entry=22736
UPDATE `trans_words` SET `content_loc5`='Throwing Tomahawk' WHERE `word_id` = 24227; -- locales_item - name : entry=4959
UPDATE `trans_words` SET `content_loc5`='Tier 5 Druid Test Gear Box 2' WHERE `word_id` = 32519; -- locales_item - name : entry=32544
UPDATE `trans_words` SET `content_loc5`='Tomb Rot' WHERE `word_id` = 24189; -- locales_item - name : entry=2929
UPDATE `trans_words` SET `content_loc5`='Torment Vine' WHERE `word_id` = 24190; -- locales_item - name : entry=2932
UPDATE `trans_words` SET `content_loc5`='Unlocks access to  Heroic mode for Auchindoun dungeons.' WHERE `word_id` = 30712; -- locales_item - description : entry=30633
UPDATE `trans_words` SET `content_loc5`='Unlocks Heroic Difficulty for Caverns of Time dungeons.' WHERE `word_id` = 30716; -- locales_item - description : entry=30635
UPDATE `trans_words` SET `content_loc5`='Unlocks Heroic Difficulty for Coilfang Reservoir dungeons.' WHERE `word_id` = 30702; -- locales_item - description : entry=30623
UPDATE `trans_words` SET `content_loc5`='Unlocks Heroic Difficulty for Hellfire Citadel dungeons.' WHERE `word_id` = 30700; -- locales_item - description : entry=30622
UPDATE `trans_words` SET `content_loc5`='Unlocks Heroic Difficulty for Tempest Keep dungeons.' WHERE `word_id` = 30714; -- locales_item - description : entry=30634
UPDATE `trans_words` SET `content_loc5`='Used by Enchanters to enchant items.' WHERE `word_id` = 24285; -- locales_item - description : entry=6216
UPDATE `trans_words` SET `content_loc5`='Used Monster Sample' WHERE `word_id` = 24323; -- locales_item - name : entry=9443
UPDATE `trans_words` SET `content_loc5`='Viewing Room Key' WHERE `word_id` = 17548; -- locales_item - name : entry=13873
UPDATE `trans_words` SET `content_loc5`='Warpforged Key' WHERE `word_id` = 30713; -- locales_item - name : entry=30634
UPDATE `trans_words` SET `content_loc5`='Weapon of Mass Destruction (test)' WHERE `word_id` = 12211; -- locales_item - name : entry=5418
UPDATE `trans_words` SET `content_loc5`='Weapon of Massive Destruction (test)' WHERE `word_id` = 12210; -- locales_item - name : entry=5417
UPDATE `trans_words` SET `content_loc5`='Wearing this would be a bad idea, as it would severely hinder your vision.' WHERE `word_id` = 31592; -- locales_item - description : entry=31529
UPDATE `trans_words` SET `content_loc5`='Work Shirt' WHERE `word_id` = 10340; -- locales_item - name : entry=3148
UPDATE `trans_words` SET `content_loc5`='X marksss the ssspot.' WHERE `word_id` = 30530; -- locales_item - description : entry=30427
UPDATE `trans_words` SET `content_loc5`='Yellow Bryanite of Stamina' WHERE `word_id` = 25231; -- locales_item - name : entry=23235
UPDATE `trans_words` SET `content_loc5`='You may turn 20 of these items in to Chief Researcher Amereldine at Halaa if the Horde have control of the base.' WHERE `word_id` = 27927; -- locales_item - description : entry=26042
UPDATE `trans_words` SET `content_loc5`='You may turn 20 of these items in to Chief Researcher Kartos at Halaa if the Alliance have control of the base.' WHERE `word_id` = 27928; -- locales_item - description : entry=26043
UPDATE `trans_words` SET `content_loc5`='zzDEPRECATED Warsong Mark of Honor' WHERE `word_id` = 24446; -- locales_item - name : entry=19322
UPDATE `trans_words` SET `content_loc5`='zzDEPRECATEDHeart of the Sky' WHERE `word_id` = 25274; -- locales_item - name : entry=23364
UPDATE `trans_words` SET `content_loc5`='zzDEPRECATEDPerfect Diamond' WHERE `word_id` = 25275; -- locales_item - name : entry=23366
UPDATE `trans_words` SET `content_loc5`='ZZOLD Spellthread' WHERE `word_id` = 24681; -- locales_item - name : entry=21878
UPDATE `trans_words` SET `content_loc5`='zzOLDBold Ornate Ruby' WHERE `word_id` = 28515; -- locales_item - name : entry=28117
UPDATE `trans_words` SET `content_loc5`='zzOLDEnscribed Ornate Topaz' WHERE `word_id` = 28520; -- locales_item - name : entry=28122
UPDATE `trans_words` SET `content_loc5`='zzOLDMighty Blood Garnet' WHERE `word_id` = 28268; -- locales_item - name : entry=27774

SET NAMES 'latin1';
