-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc5`='%s calls for his worgs!' WHERE `word_id` = 6411; -- creature_ai_texts - content : entry=-187
UPDATE `trans_words` SET `content_loc5`='%s grabs the back of his neck and his eyes go wide.' WHERE `word_id` = 5609; -- creature_ai_texts - content : entry=-934
UPDATE `trans_words` SET `content_loc5`='%s is getting hungry!' WHERE `word_id` = 5697; -- creature_ai_texts - content : entry=-539
UPDATE `trans_words` SET `content_loc5`='%s is getting VERY hungry!' WHERE `word_id` = 5696; -- creature_ai_texts - content : entry=-540
UPDATE `trans_words` SET `content_loc5`='%s looks weak enough to capture.' WHERE `word_id` = 5797; -- creature_ai_texts - content : entry=-274
UPDATE `trans_words` SET `content_loc5`='%s seems to no longer be able to cast spells...' WHERE `word_id` = 5570; -- creature_ai_texts - content : entry=-1058
UPDATE `trans_words` SET `content_loc5`='%s shimmers and becomes intangible.' WHERE `word_id` = 6159; -- creature_ai_texts - content : entry=-830
UPDATE `trans_words` SET `content_loc5`='%s stares in silence at the graver marker before him.' WHERE `word_id` = 6127; -- creature_ai_texts - content : entry=-923
UPDATE `trans_words` SET `content_loc5`='%s strength fades!' WHERE `word_id` = 6423; -- creature_ai_texts - content : entry=-153
UPDATE `trans_words` SET `content_loc5`='%s whispers softley in reverent tones under her breath.' WHERE `word_id` = 6301; -- creature_ai_texts - content : entry=-339
UPDATE `trans_words` SET `content_loc5`='%s\'s death cry has stirred the nearby silithid hive.' WHERE `word_id` = 5892; -- creature_ai_texts - content : entry=-344
UPDATE `trans_words` SET `content_loc5`='[Dwarvish] Dum mos' WHERE `word_id` = 5767; -- creature_ai_texts - content : entry=-374
UPDATE `trans_words` SET `content_loc5`='[Orcish] Ogg kaz ko zugas kil mog Tov\'nokaz Kagg' WHERE `word_id` = 5765; -- creature_ai_texts - content : entry=-376
UPDATE `trans_words` SET `content_loc5`='[Orcish] Tago mog regas gi mog Tov\'nokaz Kagg' WHERE `word_id` = 5764; -- creature_ai_texts - content : entry=-377
UPDATE `trans_words` SET `content_loc5`='Aaaahhhhhh!' WHERE `word_id` = 5806; -- creature_ai_texts - content : entry=-212
UPDATE `trans_words` SET `content_loc5`='Ahh, another powerful traveler. The nether can be dangerous; you\'ll want the most potent spells at your disposal. I carry the finest reagents, common and exotic. Come and buy - you won\'t be sorry!' WHERE `word_id` = 6302; -- creature_ai_texts - content : entry=-338
UPDATE `trans_words` SET `content_loc5`='Aku\'mai is dead! At last, I can leave this wretched place!' WHERE `word_id` = 5683; -- creature_ai_texts - content : entry=-569
UPDATE `trans_words` SET `content_loc5`='All of your efforts have been in vain, for the draining of the World Tree has already begun! Soon, the heart of your world shall beat no more!' WHERE `word_id` = 6409; -- creature_ai_texts - content : entry=-216
UPDATE `trans_words` SET `content_loc5`='Alright! We Surrender... Just put your weapons down, I\'ll cooperate' WHERE `word_id` = 5638; -- creature_ai_texts - content : entry=-775
UPDATE `trans_words` SET `content_loc5`='Alright, quiet down. We have a lot of work to do and very little time to do it in, people.' WHERE `word_id` = 6289; -- creature_ai_texts - content : entry=-382
UPDATE `trans_words` SET `content_loc5`='Amaze at the wonders that the Darkmoon Faire has uncovered in this vast and mysterious world! We have spared no expense in bringing you excitement that children of all ages will delight in!' WHERE `word_id` = 5598; -- creature_ai_texts - content : entry=-1021
UPDATE `trans_words` SET `content_loc5`='And if that weren\'t crazy enough, that big demon gets killed by a bunch of floating light things... Oh, I was also a female elf in that one... Yep...' WHERE `word_id` = 6231; -- creature_ai_texts - content : entry=-604
UPDATE `trans_words` SET `content_loc5`='And the Kirin Tor? What have they to say of this necromancy?' WHERE `word_id` = 6209; -- creature_ai_texts - content : entry=-626
UPDATE `trans_words` SET `content_loc5`='And then gnomes are even worse! They are always saying stuff like...' WHERE `word_id` = 6061; -- creature_ai_texts - content : entry=-1072
UPDATE `trans_words` SET `content_loc5`='And, don\'t forget to turn in your Darkmoon Faire Prize Tickets! All it takes is five or more and you\'re on your way to the most wondrous prizes on all of Azeroth. Everybody is a winner!' WHERE `word_id` = 5596; -- creature_ai_texts - content : entry=-1023
UPDATE `trans_words` SET `content_loc5`='Are They all.... Dead?' WHERE `word_id` = 5607; -- creature_ai_texts - content : entry=-981
UPDATE `trans_words` SET `content_loc5`='Arrrhhh...Guards!' WHERE `word_id` = 5692; -- creature_ai_texts - content : entry=-548
UPDATE `trans_words` SET `content_loc5`='ARRRRRRR!' WHERE `word_id` = 5775; -- creature_ai_texts - content : entry=-366
UPDATE `trans_words` SET `content_loc5`='Ashes to ashes, dust to dust.' WHERE `word_id` = 6439; -- creature_ai_texts - content : entry=-129
UPDATE `trans_words` SET `content_loc5`='At last, it ends...' WHERE `word_id` = 5542; -- creature_ai_texts - content : entry=-1298
UPDATE `trans_words` SET `content_loc5`='At last: one among you is worthy of my knowledge. Worry not: I have probed your thoughts, no harm will come to you.' WHERE `word_id` = 5906; -- creature_ai_texts - content : entry=-641
UPDATE `trans_words` SET `content_loc5`='Avuun dares to oppose me? I will crush him! When I am done with the draenei, they\'ll wish that they were Lost Ones!' WHERE `word_id` = 6095; -- creature_ai_texts - content : entry=-979
UPDATE `trans_words` SET `content_loc5`='Azeroth has cowered too long under our shadow! Now, feel the power of the Burning Crusade, and despair!' WHERE `word_id` = 5998; -- creature_ai_texts - content : entry=-1206
UPDATE `trans_words` SET `content_loc5`='Big red bastards! Bigger than any orc I\'d ever seen. Muscles out to here, tusks out to here...' WHERE `word_id` = 6343; -- creature_ai_texts - content : entry=-291
UPDATE `trans_words` SET `content_loc5`='Bladespire clan not fight fair. Have Gronn to help dem. You go to Blade\'s Edge Mountains. Talk to Mog\'dorg the Wizened. Kill Gromm.' WHERE `word_id` = 6372; -- creature_ai_texts - content : entry=-261
UPDATE `trans_words` SET `content_loc5`='Bron! \'Ey Bron! \'Ey Bron! Hit me!' WHERE `word_id` = 6308; -- creature_ai_texts - content : entry=-332
UPDATE `trans_words` SET `content_loc5`='By the Light, you will leave this tomb!' WHERE `word_id` = 5677; -- creature_ai_texts - content : entry=-581
UPDATE `trans_words` SET `content_loc5`='C\'mere, $R. Ya don\'t want to be riskin\' yerself in a dungeon, do ya? Filthy work, and for what? Some worthless trinket? Nah, what ya need be one of my amulets. Guarenteed to work!' WHERE `word_id` = 6381; -- creature_ai_texts - content : entry=-252
UPDATE `trans_words` SET `content_loc5`='Cabal Summoner summons a Cabal Acolyte to his aid!' WHERE `word_id` = 5968; -- creature_ai_texts - content : entry=-1248
UPDATE `trans_words` SET `content_loc5`='Cabal Summoner summons a Cabal Deathsworn to his aid!' WHERE `word_id` = 5969; -- creature_ai_texts - content : entry=-1247
UPDATE `trans_words` SET `content_loc5`='Can I get a buff? I\'m dying up here!' WHERE `word_id` = 6035; -- creature_ai_texts - content : entry=-1099
UPDATE `trans_words` SET `content_loc5`='Can\'t say I didn\'t warn you!' WHERE `word_id` = 6467; -- creature_ai_texts - content : entry=-92
UPDATE `trans_words` SET `content_loc5`='Cipher of Damnation belongs to us now!' WHERE `word_id` = 6528; -- creature_ai_texts - content : entry=-23
UPDATE `trans_words` SET `content_loc5`='Come, spirits, attend your master!' WHERE `word_id` = 5550; -- creature_ai_texts - content : entry=-1223
UPDATE `trans_words` SET `content_loc5`='Cower, little worms! Your heroes are nothing! Your saviors will be our first feast!' WHERE `word_id` = 5996; -- creature_ai_texts - content : entry=-1208
UPDATE `trans_words` SET `content_loc5`='Damm those ogres. Damn them to the Nether. Won\'t someone save us from these savages! This is the fifth kidnapping is as many days.' WHERE `word_id` = 6321; -- creature_ai_texts - content : entry=-314
UPDATE `trans_words` SET `content_loc5`='Dangerous out there, innit? Know what ya need? Protection. I can help ya defy death itself! Ya wear this madstone \'round yer neck, see, and then ya be able to come back if ya find yerself in the spirit world! Just a quick jaunt to yer corpse and up ya com' WHERE `word_id` = 6380; -- creature_ai_texts - content : entry=-253
UPDATE `trans_words` SET `content_loc5`='Darkness...consumes...all.' WHERE `word_id` = 6205; -- creature_ai_texts - content : entry=-636
UPDATE `trans_words` SET `content_loc5`='Die $R! These lands belong to the Stonesplinter Tribe!' WHERE `word_id` = 5770; -- creature_ai_texts - content : entry=-371
UPDATE `trans_words` SET `content_loc5`='Dim wha Siame cyaa fi so yudo' WHERE `word_id` = 5794; -- creature_ai_texts - content : entry=-322
UPDATE `trans_words` SET `content_loc5`='Do I detect a hint of cinnamon? Or is that nutmeg? Whatever it is, one thing is for sure - nobody cooks donkey like you, Cookie.' WHERE `word_id` = 6340; -- creature_ai_texts - content : entry=-294
UPDATE `trans_words` SET `content_loc5`='DO IT, YE PANSEY!' WHERE `word_id` = 6310; -- creature_ai_texts - content : entry=-330
UPDATE `trans_words` SET `content_loc5`='Do you think that demons will play fair? These beasts are more savage than the orcs, more cunning than the undead. Do not attempt to engage Legion by normal standards of war.' WHERE `word_id` = 6306; -- creature_ai_texts - content : entry=-334
UPDATE `trans_words` SET `content_loc5`='Does anyone need any supplies to down the trolls? Any troll will do.' WHERE `word_id` = 6123; -- creature_ai_texts - content : entry=-939
UPDATE `trans_words` SET `content_loc5`='Don\'t feel.....so good.....' WHERE `word_id` = 6245; -- creature_ai_texts - content : entry=-589
UPDATE `trans_words` SET `content_loc5`='DON\'T LET THIS STATUE BE MY ONLY COMPANY, COME OUT AND PLAY!' WHERE `word_id` = 5911; -- creature_ai_texts - content : entry=-750
UPDATE `trans_words` SET `content_loc5`='Dragonhawk incoming from the west! Shoot that druid down!' WHERE `word_id` = 6269; -- creature_ai_texts - content : entry=-403
UPDATE `trans_words` SET `content_loc5`='Enough! I will erase your very existence!' WHERE `word_id` = 5955; -- creature_ai_texts - content : entry=-1261
UPDATE `trans_words` SET `content_loc5`='Five seconds! I\'m not kidding!' WHERE `word_id` = 6497; -- creature_ai_texts - content : entry=-56
UPDATE `trans_words` SET `content_loc5`='Foolish mortal, you serve me now!' WHERE `word_id` = 5545; -- creature_ai_texts - content : entry=-1295
UPDATE `trans_words` SET `content_loc5`='For Victory! For Agamaggan!' WHERE `word_id` = 5876; -- creature_ai_texts - content : entry=-18
UPDATE `trans_words` SET `content_loc5`='Get it while it\'s hot!' WHERE `word_id` = 5895; -- creature_ai_texts - content : entry=-142
UPDATE `trans_words` SET `content_loc5`='Go ahead, gimme your best shot. I can take it!' WHERE `word_id` = 6469; -- creature_ai_texts - content : entry=-90
UPDATE `trans_words` SET `content_loc5`='Greetings citizen.' WHERE `word_id` = 5688; -- creature_ai_texts - content : entry=-552
UPDATE `trans_words` SET `content_loc5`='Grek get a drink.' WHERE `word_id` = 6386; -- creature_ai_texts - content : entry=-247
UPDATE `trans_words` SET `content_loc5`='Guards! Come and kill these intruders!' WHERE `word_id` = 6510; -- creature_ai_texts - content : entry=-39
UPDATE `trans_words` SET `content_loc5`='Guards! Urgh..Guards..!' WHERE `word_id` = 5963; -- creature_ai_texts - content : entry=-1253
UPDATE `trans_words` SET `content_loc5`='Ha! This place is not yet worthy of my infliction.' WHERE `word_id` = 5992; -- creature_ai_texts - content : entry=-1212
UPDATE `trans_words` SET `content_loc5`='HAVE YOU RUN OUT OF SHIPS TO SEND? WHERE IS YOUR COURAGE?' WHERE `word_id` = 5914; -- creature_ai_texts - content : entry=-753
UPDATE `trans_words` SET `content_loc5`='He asked if the imp could join in... can you believe it? Actually, it wasn\'t half bad...' WHERE `word_id` = 6495; -- creature_ai_texts - content : entry=-58
UPDATE `trans_words` SET `content_loc5`='Hearty Kill!' WHERE `word_id` = 5763; -- creature_ai_texts - content : entry=-388
UPDATE `trans_words` SET `content_loc5`='Here to visit the family? Die, fool!' WHERE `word_id` = 5588; -- creature_ai_texts - content : entry=-1033
UPDATE `trans_words` SET `content_loc5`='Hey Hey Hey! It\'s Raliq the drunk... His momma\'s so fat she didn\'t just make the front cover of Ogre Today...' WHERE `word_id` = 6057; -- creature_ai_texts - content : entry=-1077
UPDATE `trans_words` SET `content_loc5`='HEY YOU! DRINK OGRE BREWS! MAKE YOU BIG AND STRONG!' WHERE `word_id` = 6165; -- creature_ai_texts - content : entry=-718
UPDATE `trans_words` SET `content_loc5`='Hey! Hey, $R! I be havin\' just the thing for ya. Ya ever see a Tikbalang? Frightenin\' creatures. Prone to stealin\' ya away. What ya need is my tikbaland wards. Guaranteed to ward away all tikbalangs!' WHERE `word_id` = 6375; -- creature_ai_texts - content : entry=-258
UPDATE `trans_words` SET `content_loc5`='Hey, harbringer, how\'s that research coming along? There might be an Ultra-Kinetic Waffle Iron in it for you if you\'re prompt with the results!' WHERE `word_id` = 6158; -- creature_ai_texts - content : entry=-831
UPDATE `trans_words` SET `content_loc5`='Hey, hey sweet thing! Looking good!' WHERE `word_id` = 6078; -- creature_ai_texts - content : entry=-1007
UPDATE `trans_words` SET `content_loc5`='Hey, hey! Nice build you got there honey!' WHERE `word_id` = 6077; -- creature_ai_texts - content : entry=-1008
UPDATE `trans_words` SET `content_loc5`='Hey, it\'s Raliq the drunk... His momma\'s so fat, when she flies to Blade\'s Edge they charged her by the pound!' WHERE `word_id` = 6039; -- creature_ai_texts - content : entry=-1095
UPDATE `trans_words` SET `content_loc5`='Hold them back while I release the warhounds!' WHERE `word_id` = 6414; -- creature_ai_texts - content : entry=-179
UPDATE `trans_words` SET `content_loc5`='How dare you trifle with my playthings!' WHERE `word_id` = 6543; -- creature_ai_texts - content : entry=-2000
UPDATE `trans_words` SET `content_loc5`='I am slain! Summon Verog!' WHERE `word_id` = 5640; -- creature_ai_texts - content : entry=-769
UPDATE `trans_words` SET `content_loc5`='I am summoned! Intruders, come to my tent and face your death!' WHERE `word_id` = 5639; -- creature_ai_texts - content : entry=-770
UPDATE `trans_words` SET `content_loc5`='I am the serpent king! I can do anything.' WHERE `word_id` = 5857; -- creature_ai_texts - content : entry=-123
UPDATE `trans_words` SET `content_loc5`='I can\'t belive that Papa Wheeler thinks he\'s going to dupe anyone into going out to Manaforge B\'naar!' WHERE `word_id` = 6014; -- creature_ai_texts - content : entry=-1130
UPDATE `trans_words` SET `content_loc5`='I can\'t even believe this one... You know two loudmouthed ruffians, Foror and Tigule?' WHERE `word_id` = 6224; -- creature_ai_texts - content : entry=-611
UPDATE `trans_words` SET `content_loc5`='I cannot permit you to enter the temple! I must destroy you for your own good!' WHERE `word_id` = 5762; -- creature_ai_texts - content : entry=-404
UPDATE `trans_words` SET `content_loc5`='I could have sworn I had more apples. Grok!' WHERE `word_id` = 6378; -- creature_ai_texts - content : entry=-255
UPDATE `trans_words` SET `content_loc5`='I don\'t see why we ally with filthy stinking trolls? The only good troll is a dead troll.' WHERE `word_id` = 6122; -- creature_ai_texts - content : entry=-940
UPDATE `trans_words` SET `content_loc5`='I feel that war is fast approaching. The fruit vendor has enlisted to help an ogre. I shall have to enlist help as well.' WHERE `word_id` = 6369; -- creature_ai_texts - content : entry=-264
UPDATE `trans_words` SET `content_loc5`='I have a special message for $N. And it says you must die!' WHERE `word_id` = 5809; -- creature_ai_texts - content : entry=-209
UPDATE `trans_words` SET `content_loc5`='I have no equal.' WHERE `word_id` = 1720; -- creature_ai_texts - content : entry=-1269
UPDATE `trans_words` SET `content_loc5`='I HAVE YOUR LITTLE BELT TIED AROUND MY FINGER, SMOTTS. DON\'T YOU WANT IT BACK?' WHERE `word_id` = 5916; -- creature_ai_texts - content : entry=-755
UPDATE `trans_words` SET `content_loc5`='I have... failed.' WHERE `word_id` = 5654; -- creature_ai_texts - content : entry=-700
UPDATE `trans_words` SET `content_loc5`='I hope you die! Painfully!' WHERE `word_id` = 6517; -- creature_ai_texts - content : entry=-20
UPDATE `trans_words` SET `content_loc5`='I love blood elf women. Especially when they say stuff like this...' WHERE `word_id` = 6053; -- creature_ai_texts - content : entry=-1081
UPDATE `trans_words` SET `content_loc5`='I love night elf women. Especially when they say stuff like this...' WHERE `word_id` = 6021; -- creature_ai_texts - content : entry=-1113
UPDATE `trans_words` SET `content_loc5`='I miss my dog so much...' WHERE `word_id` = 6425; -- creature_ai_texts - content : entry=-151
UPDATE `trans_words` SET `content_loc5`='I will end this quickly...' WHERE `word_id` = 6261; -- creature_ai_texts - content : entry=-463
UPDATE `trans_words` SET `content_loc5`='I... Deserve this.' WHERE `word_id` = 6461; -- creature_ai_texts - content : entry=-98
UPDATE `trans_words` SET `content_loc5`='I\'m gonna cook ya, and then i\'m going to eat ya!' WHERE `word_id` = 6518; -- creature_ai_texts - content : entry=-19
UPDATE `trans_words` SET `content_loc5`='I\'m not gonna lie to you, soldiers. We\'re getting our butts out there! Now which one of you is orc enough to do something about it?' WHERE `word_id` = 6015; -- creature_ai_texts - content : entry=-1129
UPDATE `trans_words` SET `content_loc5`='If my division is correct you should be quite dead.' WHERE `word_id` = 6474; -- creature_ai_texts - content : entry=-85
UPDATE `trans_words` SET `content_loc5`='If no one help. Grok smash!' WHERE `word_id` = 6377; -- creature_ai_texts - content : entry=-256
UPDATE `trans_words` SET `content_loc5`='If none of you ladies have any questions, you can get further instruction and assignments from your squad leaders. That\'s it. Good luck!' WHERE `word_id` = 6284; -- creature_ai_texts - content : entry=-387
UPDATE `trans_words` SET `content_loc5`='If that weren\'t crazy enough, they decided to quit the ice-cream business and become adventurers... They travel all over the place and finally disappears into some portal. I woke up in a cold sweat after that one...' WHERE `word_id` = 6222; -- creature_ai_texts - content : entry=-613
UPDATE `trans_words` SET `content_loc5`='Illidan reigns!' WHERE `word_id` = 6422; -- creature_ai_texts - content : entry=-154
UPDATE `trans_words` SET `content_loc5`='Iman m t\'ief fu Fus\'obeah italaf' WHERE `word_id` = 5795; -- creature_ai_texts - content : entry=-321
UPDATE `trans_words` SET `content_loc5`='Impersonation time!! I call this, "The Silly Tauren."' WHERE `word_id` = 6068; -- creature_ai_texts - content : entry=-1065
UPDATE `trans_words` SET `content_loc5`='Impudent fools! I will kill you myself!' WHERE `word_id` = 5653; -- creature_ai_texts - content : entry=-701
UPDATE `trans_words` SET `content_loc5`='Insolence!' WHERE `word_id` = 6444; -- creature_ai_texts - content : entry=-124
UPDATE `trans_words` SET `content_loc5`='Intruder detected! Neutralizing threat immediately!' WHERE `word_id` = 6114; -- creature_ai_texts - content : entry=-959
UPDATE `trans_words` SET `content_loc5`='Is it true? Are there crocolisks in the canal?' WHERE `word_id` = 5741; -- creature_ai_texts - content : entry=-431
UPDATE `trans_words` SET `content_loc5`='It had to be done.' WHERE `word_id` = 6463; -- creature_ai_texts - content : entry=-96
UPDATE `trans_words` SET `content_loc5`='It\'s all... coming back to me.' WHERE `word_id` = 6490; -- creature_ai_texts - content : entry=-63
UPDATE `trans_words` SET `content_loc5`='It\'s too bad they don\'t stay cute. There must be some right of passage in the Barrens called, "Climb ugly tree and fall out."' WHERE `word_id` = 6043; -- creature_ai_texts - content : entry=-1091
UPDATE `trans_words` SET `content_loc5`='Just... Dust...' WHERE `word_id` = 5684; -- creature_ai_texts - content : entry=-568
UPDATE `trans_words` SET `content_loc5`='Last time someone went out to try and collect the bounty on Netherlock, all we got back was a compressed layer of foolhardy adventurer!' WHERE `word_id` = 6317; -- creature_ai_texts - content : entry=-318
UPDATE `trans_words` SET `content_loc5`='Lok\'tar Illidari!' WHERE `word_id` = 6417; -- creature_ai_texts - content : entry=-159
UPDATE `trans_words` SET `content_loc5`='Look over here, $C! I got somethin\' for ya. Just what ya need. It\'s soap, right... and it\'s on a rope! No offense, man, but yer a little ripe, you know what I\'m sayin\'?' WHERE `word_id` = 6376; -- creature_ai_texts - content : entry=-257
UPDATE `trans_words` SET `content_loc5`='Looks like today was the wrong day to quit mana tapping...' WHERE `word_id` = 6110; -- creature_ai_texts - content : entry=-963
UPDATE `trans_words` SET `content_loc5`='Low tech yet quite effective!' WHERE `word_id` = 5989; -- creature_ai_texts - content : entry=-1215
UPDATE `trans_words` SET `content_loc5`='Me hungry. Fruit look tasty.' WHERE `word_id` = 6367; -- creature_ai_texts - content : entry=-266
UPDATE `trans_words` SET `content_loc5`='Measure twice, cut once.' WHERE `word_id` = 6475; -- creature_ai_texts - content : entry=-84
UPDATE `trans_words` SET `content_loc5`='Mine! Mine! Mine! Gizlock is the ruler of this domain! You shall never reveal my presence!' WHERE `word_id` = 5833; -- creature_ai_texts - content : entry=-182
UPDATE `trans_words` SET `content_loc5`='Mission accomplished.' WHERE `word_id` = 6516; -- creature_ai_texts - content : entry=-21
UPDATE `trans_words` SET `content_loc5`='Mistress!! They seek to destroy your work!' WHERE `word_id` = 5603; -- creature_ai_texts - content : entry=-985
UPDATE `trans_words` SET `content_loc5`='More... More souls.' WHERE `word_id` = 5554; -- creature_ai_texts - content : entry=-1204
UPDATE `trans_words` SET `content_loc5`='Move along, $C.' WHERE `word_id` = 6125; -- creature_ai_texts - content : entry=-937
UPDATE `trans_words` SET `content_loc5`='My friends, please join me in humble supplication the the Light.' WHERE `word_id` = 6355; -- creature_ai_texts - content : entry=-279
UPDATE `trans_words` SET `content_loc5`='My pets are hungry and they will dine on your flesh!' WHERE `word_id` = 6413; -- creature_ai_texts - content : entry=-180
UPDATE `trans_words` SET `content_loc5`='Never underestimate the other ethereal\'s greed.' WHERE `word_id` = 6162; -- creature_ai_texts - content : entry=-816
UPDATE `trans_words` SET `content_loc5`='No more middling for you.' WHERE `word_id` = 5960; -- creature_ai_texts - content : entry=-1256
UPDATE `trans_words` SET `content_loc5`='No rest, for the angry dead.' WHERE `word_id` = 5555; -- creature_ai_texts - content : entry=-1203
UPDATE `trans_words` SET `content_loc5`='No! You must no do this!' WHERE `word_id` = 5679; -- creature_ai_texts - content : entry=-579
UPDATE `trans_words` SET `content_loc5`='No!...The master... will not... be pleased.' WHERE `word_id` = 5949; -- creature_ai_texts - content : entry=-1267
UPDATE `trans_words` SET `content_loc5`='No...more...life.' WHERE `word_id` = 6203; -- creature_ai_texts - content : entry=-638
UPDATE `trans_words` SET `content_loc5`='O\'ourse I\'m talking to myself. Only way to get a decent conversation in this city.' WHERE `word_id` = 5744; -- creature_ai_texts - content : entry=-428
UPDATE `trans_words` SET `content_loc5`='Off with you, $N.' WHERE `word_id` = 6126; -- creature_ai_texts - content : entry=-936
UPDATE `trans_words` SET `content_loc5`='Oh stop your whimpering.' WHERE `word_id` = 6514; -- creature_ai_texts - content : entry=-35
UPDATE `trans_words` SET `content_loc5`='Oh, would you please stop checking your nails and spanking yourself, for one moment? Really, no one cares!' WHERE `word_id` = 6098; -- creature_ai_texts - content : entry=-976
UPDATE `trans_words` SET `content_loc5`='Ooh what a dreadful job! All day, surrounded by the stench of bad feet.' WHERE `word_id` = 6119; -- creature_ai_texts - content : entry=-943
UPDATE `trans_words` SET `content_loc5`='Our job is to clear out as much of the fodder as we can, while supporting the specialists that the powers-that-be are having brought in.' WHERE `word_id` = 6274; -- creature_ai_texts - content : entry=-398
UPDATE `trans_words` SET `content_loc5`='Our new allies  will avenge us!' WHERE `word_id` = 5855; -- creature_ai_texts - content : entry=-134
UPDATE `trans_words` SET `content_loc5`='Perish, mortal.' WHERE `word_id` = 1721; -- creature_ai_texts - content : entry=-1270
UPDATE `trans_words` SET `content_loc5`='Scream for me!' WHERE `word_id` = 6406; -- creature_ai_texts - content : entry=-219
UPDATE `trans_words` SET `content_loc5`='Seems like a hundred times a day I walk all the way to get more water. No respect for their elders I tell ya.' WHERE `word_id` = 5747; -- creature_ai_texts - content : entry=-425
UPDATE `trans_words` SET `content_loc5`='Shattered Sun scum! Fire at will!' WHERE `word_id` = 6271; -- creature_ai_texts - content : entry=-401
UPDATE `trans_words` SET `content_loc5`='Shine yer armor for a copper?' WHERE `word_id` = 5812; -- creature_ai_texts - content : entry=-206
UPDATE `trans_words` SET `content_loc5`='Silithid Creeper Egg begins to crack and open...' WHERE `word_id` = 5528; -- creature_ai_texts - content : entry=-1318
UPDATE `trans_words` SET `content_loc5`='Silithid Creeper Egg splits open!' WHERE `word_id` = 5530; -- creature_ai_texts - content : entry=-1319
UPDATE `trans_words` SET `content_loc5`='Silithid Creeper lays an egg!' WHERE `word_id` = 5529; -- creature_ai_texts - content : entry=-1317
UPDATE `trans_words` SET `content_loc5`='Skywing! I will free you from your curse over my dead body!' WHERE `word_id` = 5984; -- creature_ai_texts - content : entry=-1220
UPDATE `trans_words` SET `content_loc5`='Sleep...' WHERE `word_id` = 5685; -- creature_ai_texts - content : entry=-567
UPDATE `trans_words` SET `content_loc5`='SMOTTS! HEY, SMOTTS! COME OUT AND PLAY!' WHERE `word_id` = 5910; -- creature_ai_texts - content : entry=-749
UPDATE `trans_words` SET `content_loc5`='SMOTTS, I HAVE YOUR LITTLE BELT....COME GET IT!' WHERE `word_id` = 5909; -- creature_ai_texts - content : entry=-748
UPDATE `trans_words` SET `content_loc5`='Snivvle is here! Snivvle claims the Coldtooth Mine!' WHERE `word_id` = 5668; -- creature_ai_texts - content : entry=-654
UPDATE `trans_words` SET `content_loc5`='So can you teach me this... this...' WHERE `word_id` = 6210; -- creature_ai_texts - content : entry=-625
UPDATE `trans_words` SET `content_loc5`='So ju weh siame is fus nehjo skam worl Uptfeel' WHERE `word_id` = 5793; -- creature_ai_texts - content : entry=-323
UPDATE `trans_words` SET `content_loc5`='So much to do, so much to do! Where does the time go?' WHERE `word_id` = 5798; -- creature_ai_texts - content : entry=-233
UPDATE `trans_words` SET `content_loc5`='So or\'manley fi siame Dim fus siame yudo' WHERE `word_id` = 5633; -- creature_ai_texts - content : entry=-817
UPDATE `trans_words` SET `content_loc5`='So this gnome tells a tauren he\'s been to Molten Core.' WHERE `word_id` = 6027; -- creature_ai_texts - content : entry=-1107
UPDATE `trans_words` SET `content_loc5`='So, the Blood Elves think they\'re one step away from ruling the world...' WHERE `word_id` = 6032; -- creature_ai_texts - content : entry=-1102
UPDATE `trans_words` SET `content_loc5`='Some coin?' WHERE `word_id` = 5810; -- creature_ai_texts - content : entry=-208
UPDATE `trans_words` SET `content_loc5`='Someone come read this wanted poster to Grek. Grek can\'t read.' WHERE `word_id` = 6389; -- creature_ai_texts - content : entry=-244
UPDATE `trans_words` SET `content_loc5`='Spare a copper, madame?' WHERE `word_id` = 6151; -- creature_ai_texts - content : entry=-838
UPDATE `trans_words` SET `content_loc5`='Spare some change for a poor blind man?...What do you mean I\'m not blind?...I\'M NOT BLIND! I CAN SEE! ITS A MIRACLE!' WHERE `word_id` = 5754; -- creature_ai_texts - content : entry=-412
UPDATE `trans_words` SET `content_loc5`='Speak, filthy refugee! What was your caravan doing in the Bone Wastes?' WHERE `word_id` = 6009; -- creature_ai_texts - content : entry=-1136
UPDATE `trans_words` SET `content_loc5`='Step forward! I will see that you are properly welcomed.' WHERE `word_id` = 6515; -- creature_ai_texts - content : entry=-34
UPDATE `trans_words` SET `content_loc5`='Step right up! Step right up! Greetings my friend. I\'m Silas Darkmoon and I want to welcome you to the greatest show on Azeroth! It\'s the Darkmoon Faire friend, and it\'s your lucky day! Sparing no expense, we\'ve gathered wonders and treats from around the world for your delight. Whether you\'re young or old, rich or poor, the Darkmoon Faire has it all!' WHERE `word_id` = 5599; -- creature_ai_texts - content : entry=-1020
UPDATE `trans_words` SET `content_loc5`='Struggle as much as you like!' WHERE `word_id` = 5950; -- creature_ai_texts - content : entry=-1266
UPDATE `trans_words` SET `content_loc5`='Succumb to the icy chill... of death!' WHERE `word_id` = 6442; -- creature_ai_texts - content : entry=-126
UPDATE `trans_words` SET `content_loc5`='Suffer you despicable insect!' WHERE `word_id` = 6410; -- creature_ai_texts - content : entry=-199
UPDATE `trans_words` SET `content_loc5`='Sure enough, scount came runnin\' back, talkin\' bout some orcs down the path. They hadn\'t seen us yet so we figured we\'d go get aquainted.' WHERE `word_id` = 6342; -- creature_ai_texts - content : entry=-292
UPDATE `trans_words` SET `content_loc5`='Sweet dreams...' WHERE `word_id` = 6400; -- creature_ai_texts - content : entry=-225
UPDATE `trans_words` SET `content_loc5`='Take heart! Your friends will not long mourn your passing!' WHERE `word_id` = 6457; -- creature_ai_texts - content : entry=-110
UPDATE `trans_words` SET `content_loc5`='Thank you everyone! And keep clapping, there is a fly in here and one of you are bound to get it! Good night!' WHERE `word_id` = 6036; -- creature_ai_texts - content : entry=-1098
UPDATE `trans_words` SET `content_loc5`='That one where thousands of people are all watching us up from the sky...' WHERE `word_id` = 6237; -- creature_ai_texts - content : entry=-598
UPDATE `trans_words` SET `content_loc5`='The %s doen\'t look like it minds the crystal\'s effect.' WHERE `word_id` = 6141; -- creature_ai_texts - content : entry=-909
UPDATE `trans_words` SET `content_loc5`='The Agamand Mills is held by the Scourge, $C. Join us!' WHERE `word_id` = 5587; -- creature_ai_texts - content : entry=-1034
UPDATE `trans_words` SET `content_loc5`='The blood is our power!' WHERE `word_id` = 6420; -- creature_ai_texts - content : entry=-156
UPDATE `trans_words` SET `content_loc5`='The coils of death... Will crush you.' WHERE `word_id` = 5851; -- creature_ai_texts - content : entry=-140
UPDATE `trans_words` SET `content_loc5`='The comedian impersonates a female dwarf.' WHERE `word_id` = 6028; -- creature_ai_texts - content : entry=-1106
UPDATE `trans_words` SET `content_loc5`='The comedian impersonates a female tauren.' WHERE `word_id` = 6042; -- creature_ai_texts - content : entry=-1092
UPDATE `trans_words` SET `content_loc5`='The comedian impersonates a night elf.' WHERE `word_id` = 6020; -- creature_ai_texts - content : entry=-1114
UPDATE `trans_words` SET `content_loc5`='The comedian impersonates an undead.' WHERE `word_id` = 6019; -- creature_ai_texts - content : entry=-1115
UPDATE `trans_words` SET `content_loc5`='The creatures of this place are strong, wayfarer. You\'ll need ample ammunition if you hope to survive. You\'re in luck - I am well-stocked with fine arrows, bullets, and throwing weapons. The price is reasonable, considering the circumstances.' WHERE `word_id` = 6303; -- creature_ai_texts - content : entry=-337
UPDATE `trans_words` SET `content_loc5`='The Loch belongs to the Stonesplinter Tribe now, $N! Now die!' WHERE `word_id` = 5769; -- creature_ai_texts - content : entry=-372
UPDATE `trans_words` SET `content_loc5`='The master... will be angry...' WHERE `word_id` = 6506; -- creature_ai_texts - content : entry=-45
UPDATE `trans_words` SET `content_loc5`='The processing will continue a schedule!' WHERE `word_id` = 5987; -- creature_ai_texts - content : entry=-1217
UPDATE `trans_words` SET `content_loc5`='The Scarlet Crusade shall not fail in it\'s mission!' WHERE `word_id` = 5591; -- creature_ai_texts - content : entry=-1030
UPDATE `trans_words` SET `content_loc5`='The swarm is eager to feed!' WHERE `word_id` = 6403; -- creature_ai_texts - content : entry=-222
UPDATE `trans_words` SET `content_loc5`='The Thandol Span fell to Ragnaros. So shall the Stonewrought Dam!' WHERE `word_id` = 5778; -- creature_ai_texts - content : entry=-363
UPDATE `trans_words` SET `content_loc5`='The time of the Raven is night, but yours will end here!' WHERE `word_id` = 6392; -- creature_ai_texts - content : entry=-239
UPDATE `trans_words` SET `content_loc5`='The void...beckons.' WHERE `word_id` = 6202; -- creature_ai_texts - content : entry=-639
UPDATE `trans_words` SET `content_loc5`='The work must continue.' WHERE `word_id` = 6466; -- creature_ai_texts - content : entry=-93
UPDATE `trans_words` SET `content_loc5`='They all go to the Spire but none never come back... just like Bijou.' WHERE `word_id` = 5673; -- creature_ai_texts - content : entry=-585
UPDATE `trans_words` SET `content_loc5`='They dont\'t know where to store the leftovers!' WHERE `word_id` = 6017; -- creature_ai_texts - content : entry=-1117
UPDATE `trans_words` SET `content_loc5`='Think you can hurt me, huh? Think I\'m afraid of you?!' WHERE `word_id` = 6468; -- creature_ai_texts - content : entry=-91
UPDATE `trans_words` SET `content_loc5`='This land belongs to the Dark Iron Dwarves. Prepare to see the afterlife, $C!' WHERE `word_id` = 5859; -- creature_ai_texts - content : entry=-104
UPDATE `trans_words` SET `content_loc5`='This one\'s real grim... So the king\'s kid Arthas...Well he goes out to battle evil, along with Uther *Nat pats his brow dry*' WHERE `word_id` = 6227; -- creature_ai_texts - content : entry=-608
UPDATE `trans_words` SET `content_loc5`='This vessel... is empty.' WHERE `word_id` = 6204; -- creature_ai_texts - content : entry=-637
UPDATE `trans_words` SET `content_loc5`='This war - and don\'t mistake this for anything but war - is not going to win itself. If we do not fight, scratch, claw, and kick for every speck of land on this shattered world, all will be lost.' WHERE `word_id` = 6304; -- creature_ai_texts - content : entry=-336
UPDATE `trans_words` SET `content_loc5`='This will teach you to lay off the herb, $R.' WHERE `word_id` = 5600; -- creature_ai_texts - content : entry=-1019
UPDATE `trans_words` SET `content_loc5`='Time to die, $C!' WHERE `word_id` = 5782; -- creature_ai_texts - content : entry=-358
UPDATE `trans_words` SET `content_loc5`='Time to move on...' WHERE `word_id` = 6487; -- creature_ai_texts - content : entry=-66
UPDATE `trans_words` SET `content_loc5`='Too...easy!' WHERE `word_id` = 5548; -- creature_ai_texts - content : entry=-1225
UPDATE `trans_words` SET `content_loc5`='Turn your back while you can!' WHERE `word_id` = 6482; -- creature_ai_texts - content : entry=-71
UPDATE `trans_words` SET `content_loc5`='Wait... No! No!' WHERE `word_id` = 6504; -- creature_ai_texts - content : entry=-49
UPDATE `trans_words` SET `content_loc5`='Warriors! Captains! Continue the fight!' WHERE `word_id` = 1061; -- creature_ai_texts - content : entry=-702
UPDATE `trans_words` SET `content_loc5`='Was... Was it all a dream? Azuremyst, Bloodymyst, Zangarmarsh, Shadowmoon... even Zul\'Aman... Jane! Jane where are you!' WHERE `word_id` = 6118; -- creature_ai_texts - content : entry=-944
UPDATE `trans_words` SET `content_loc5`='We have it all... delicious food, strong drink, exotic artifacts, fortunes read, amazing prizes and excitement without end!' WHERE `word_id` = 5597; -- creature_ai_texts - content : entry=-1022
UPDATE `trans_words` SET `content_loc5`='We need better representation from Stormwind. Our homes are falling to the undead.' WHERE `word_id` = 5726; -- creature_ai_texts - content : entry=-455
UPDATE `trans_words` SET `content_loc5`='We will find what the Master is looking for! Failure is not an option!' WHERE `word_id` = 6010; -- creature_ai_texts - content : entry=-1134
UPDATE `trans_words` SET `content_loc5`='We\'re here as support for the so-called \'adventurers\' that the brass called in. We\'ll help them hold the key points on the island, and keep the heat off so that they can do their jobs.' WHERE `word_id` = 6285; -- creature_ai_texts - content : entry=-386
UPDATE `trans_words` SET `content_loc5`='Well, he comes back to the king all pretendin\' to be nice, draws his sword, and runs the king through, elbow to... well you know... kills him on the spot...' WHERE `word_id` = 6225; -- creature_ai_texts - content : entry=-610
UPDATE `trans_words` SET `content_loc5`='What do you put in that pipe of yours Nat?' WHERE `word_id` = 6216; -- creature_ai_texts - content : entry=-619
UPDATE `trans_words` SET `content_loc5`='What is this?! Didn\'t mommy and daddy teach you anything?' WHERE `word_id` = 6174; -- creature_ai_texts - content : entry=-685
UPDATE `trans_words` SET `content_loc5`='What will become of...' WHERE `word_id` = 6508; -- creature_ai_texts - content : entry=-41
UPDATE `trans_words` SET `content_loc5`='What? No you can\'t beat me! Me will return!' WHERE `word_id` = 5601; -- creature_ai_texts - content : entry=-987
UPDATE `trans_words` SET `content_loc5`='What? Oh no. I don\'t care what you have to say. I just enjoy inflicting pain.' WHERE `word_id` = 5832; -- creature_ai_texts - content : entry=-183
UPDATE `trans_words` SET `content_loc5`='When do we eat again?' WHERE `word_id` = 6246; -- creature_ai_texts - content : entry=-588
UPDATE `trans_words` SET `content_loc5`='Where am I? What...' WHERE `word_id` = 6501; -- creature_ai_texts - content : entry=-52
UPDATE `trans_words` SET `content_loc5`='Where? Where are the Shards! You cannot hide them from us!' WHERE `word_id` = 5995; -- creature_ai_texts - content : entry=-1209
UPDATE `trans_words` SET `content_loc5`='Who dares disturb my meditation!' WHERE `word_id` = 5686; -- creature_ai_texts - content : entry=-566
UPDATE `trans_words` SET `content_loc5`='Whoah! Walk by again girl!' WHERE `word_id` = 6080; -- creature_ai_texts - content : entry=-1005
UPDATE `trans_words` SET `content_loc5`='Why couldn\'t mother have chosen something else to dedicate herself to? Cakes, pastries, even bread - anything but cheese!' WHERE `word_id` = 6120; -- creature_ai_texts - content : entry=-942
UPDATE `trans_words` SET `content_loc5`='Why, Luhanaa? Why?' WHERE `word_id` = 6133; -- creature_ai_texts - content : entry=-917
UPDATE `trans_words` SET `content_loc5`='Will you help me find my dog...?' WHERE `word_id` = 6426; -- creature_ai_texts - content : entry=-150
UPDATE `trans_words` SET `content_loc5`='Wow! The laughs dont\'t drop very often here, do they?' WHERE `word_id` = 6016; -- creature_ai_texts - content : entry=-1118
UPDATE `trans_words` SET `content_loc5`='Ya look lovesick. Special someone be gettin\' ya down, eh? No worries, no worries. Ya get this medallion from me, ya wear it when ya see \'em and they be all over ya, sweetheart!' WHERE `word_id` = 6368; -- creature_ai_texts - content : entry=-265
UPDATE `trans_words` SET `content_loc5`='Ya look tired, $C. I be havin\' somethin\' for ya. These amulets, they can help ya leap obstacles and swim through the rivers like ya be born to it. They energize the food ya be eatin\'. Makin\' yer wounds close before yer eyes!' WHERE `word_id` = 6371; -- creature_ai_texts - content : entry=-262
UPDATE `trans_words` SET `content_loc5`='Yea, that hit the spot. Muffins for sale! Get your fresh muffins right here!' WHERE `word_id` = 6363; -- creature_ai_texts - content : entry=-270
UPDATE `trans_words` SET `content_loc5`='Yes, YES! Ahahah!' WHERE `word_id` = 1722; -- creature_ai_texts - content : entry=-1271
UPDATE `trans_words` SET `content_loc5`='Yes... I think I remember now...' WHERE `word_id` = 6491; -- creature_ai_texts - content : entry=-62
UPDATE `trans_words` SET `content_loc5`='You are in the presence of a god!' WHERE `word_id` = 5575; -- creature_ai_texts - content : entry=-1048
UPDATE `trans_words` SET `content_loc5`='You are no longer dealing with some underling.' WHERE `word_id` = 6512; -- creature_ai_texts - content : entry=-37
UPDATE `trans_words` SET `content_loc5`='You are not worth my time, $N.' WHERE `word_id` = 5652; -- creature_ai_texts - content : entry=-703
UPDATE `trans_words` SET `content_loc5`='You are spotted by the eye of Grillok!' WHERE `word_id` = 6505; -- creature_ai_texts - content : entry=-48
UPDATE `trans_words` SET `content_loc5`='You are...irrelevant.' WHERE `word_id` = 5953; -- creature_ai_texts - content : entry=-1263
UPDATE `trans_words` SET `content_loc5`='You be too scared! Me find you!' WHERE `word_id` = 5602; -- creature_ai_texts - content : entry=-986
UPDATE `trans_words` SET `content_loc5`='You brought this on yourselves.' WHERE `word_id` = 6464; -- creature_ai_texts - content : entry=-95
UPDATE `trans_words` SET `content_loc5`='You just got MALOWNED!' WHERE `word_id` = 5562; -- creature_ai_texts - content : entry=-1196
UPDATE `trans_words` SET `content_loc5`='You know not what you do! We must destroy you for your own good.' WHERE `word_id` = 5631; -- creature_ai_texts - content : entry=-820
UPDATE `trans_words` SET `content_loc5`='You look tired...' WHERE `word_id` = 6401; -- creature_ai_texts - content : entry=-224
UPDATE `trans_words` SET `content_loc5`='You should not have come.' WHERE `word_id` = 6462; -- creature_ai_texts - content : entry=-97
UPDATE `trans_words` SET `content_loc5`='YOU WANT DRINK? WE GOT DRINK!' WHERE `word_id` = 6164; -- creature_ai_texts - content : entry=-719
UPDATE `trans_words` SET `content_loc5`='You will die for your hubris, druid!' WHERE `word_id` = 6390; -- creature_ai_texts - content : entry=-241
UPDATE `trans_words` SET `content_loc5`='You will talk eventually. You might as well spill it now.' WHERE `word_id` = 5831; -- creature_ai_texts - content : entry=-184
UPDATE `trans_words` SET `content_loc5`='You... are nothing!' WHERE `word_id` = 6249; -- creature_ai_texts - content : entry=-573
UPDATE `trans_words` SET `content_loc5`='You... will... pay...' WHERE `word_id` = 6499; -- creature_ai_texts - content : entry=-54
UPDATE `trans_words` SET `content_loc5`='You\'ll never leave this place... alive.' WHERE `word_id` = 5552; -- creature_ai_texts - content : entry=-1221
UPDATE `trans_words` SET `content_loc5`='You\'re a slave. That\'s all you\'ll ever be.' WHERE `word_id` = 5967; -- creature_ai_texts - content : entry=-1249
UPDATE `trans_words` SET `content_loc5`='You\'ve got money and we\'ve got food. What are you waiting for?' WHERE `word_id` = 5594; -- creature_ai_texts - content : entry=-1025
UPDATE `trans_words` SET `content_loc5`='Your fate is sealed, Azeroth! I will find the Aspect Shards, and then you will not stand against our might!' WHERE `word_id` = 5997; -- creature_ai_texts - content : entry=-1207
UPDATE `trans_words` SET `content_loc5`='Your own strength feeds me!' WHERE `word_id` = 5993; -- creature_ai_texts - content : entry=-1211
UPDATE `trans_words` SET `content_loc5`='Your pathetic attempt to escape will be short lived, Gorefiend. Let the boy go and submit! Even with your armour and weapons, you cannot defeat the ancients!' WHERE `word_id` = 6536; -- creature_ai_texts - content : entry=-1320
UPDATE `trans_words` SET `content_loc5`='Your world is ours now.' WHERE `word_id` = 6455; -- creature_ai_texts - content : entry=-112
UPDATE `trans_words` SET `content_loc5`='Your world will die, mortals! Your doom is now at hand!' WHERE `word_id` = 5994; -- creature_ai_texts - content : entry=-1210

SET NAMES 'latin1';
