-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc5`='[PH] SD2 unknown text' WHERE `word_id` = 269446; -- gossip_texts - content : entry=-3000000
UPDATE `trans_words` SET `content_loc5`='Control Conjured Water Elemental' WHERE `word_id` = 127718; -- gossip_texts - content : entry=-3532014
UPDATE `trans_words` SET `content_loc5`='Control Human Charger' WHERE `word_id` = 127717; -- gossip_texts - content : entry=-3532013
UPDATE `trans_words` SET `content_loc5`='Teleport me to the Guardian\'s Library' WHERE `word_id` = 127704; -- gossip_texts - content : entry=-3532000
UPDATE `trans_words` SET `content_loc5`='We\'ll get you out. Taretha. Don\'t worry. I doubt the wizard would wander too far away.' WHERE `word_id` = 127736; -- gossip_texts - content : entry=-3560006

SET NAMES 'latin1';
