-- ----------------------------------------------------------------
-- This is an attempt to create a full transactional MaNGOS update
-- Now compatible with newer MySql Databases (v1.5)
-- ----------------------------------------------------------------
DROP PROCEDURE IF EXISTS `update_mangos`; 

DELIMITER $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `update_mangos`()
BEGIN
    DECLARE bRollback BOOL  DEFAULT FALSE ;
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET `bRollback` = TRUE;

    -- Current Values (TODO - must be a better way to do this)
    SET @cCurVersion := (SELECT `version` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
    SET @cCurStructure := (SELECT `structure` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
    SET @cCurContent := (SELECT `content` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);

    -- Expected Values
    SET @cOldVersion = '21'; 
    SET @cOldStructure = '15'; 
    SET @cOldContent = '010';

    -- New Values
    SET @cNewVersion = '21';
    SET @cNewStructure = '15';
    SET @cNewContent = '011';
                            -- DESCRIPTION IS 30 Characters MAX    
    SET @cNewDescription = 'DB_Cleanup_pt7';

                        -- COMMENT is 150 Characters MAX
    SET @cNewComment = 'DB_Cleanup_pt7';

    -- Evaluate all settings
    SET @cCurResult := (SELECT `description` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
    SET @cOldResult := (SELECT `description` FROM `db_version` WHERE `version`=@cOldVersion AND `structure`=@cOldStructure AND `content`=@cOldContent);
    SET @cNewResult := (SELECT `description` FROM `db_version` WHERE `version`=@cNewVersion AND `structure`=@cNewStructure AND `content`=@cNewContent);

    IF (@cCurResult = @cOldResult) THEN    -- Does the current version match the expected version
        -- APPLY UPDATE
        START TRANSACTION;
        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
        -- -- PLACE UPDATE SQL BELOW -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -

UPDATE `quest_template` SET `offerrewardtext`='I had hoped, but despaired she was only a figment of my imagination. The child is amazing!$B$BIt\'s unheard of in this day and age that one of the draenei should exhibit such ability with the elements without any training. She must have inherited this power from an ancient ancestor.$B$BI will send a missive to the orphan matron in Shattrath City requesting that the child be allowed to come stay with us.$B$BPlease, keep her safe until then.' WHERE `entry`='10968';
UPDATE `quest_template` SET `offerrewardtext`='Word has gotten back of your heroics, $N. Haramad and I both agree that what you\'ve done deserves a great reward.$B$BThough... Nevermind, you\'ve done enough. I cannot in good conscience ask anything more from you.' WHERE `entry`='10977';
UPDATE `quest_template` SET `offerrewardtext`='You\'re from the Brewfest camp? Glory day! Brewfest may yet be saved.$B$B$N, Coren Direbrew must be stopped! We cannot let him sabotage our sacred holiday. Our brews must flow!' WHERE `entry`='12318';
UPDATE `quest_template` SET `offerrewardtext`='This is the Coren Direbrew\'s drink?  The brew he wanted more than anything to submit at Brewfest?  Well, officially we can\'t recognize this submission, but out of respect for a fallen brewer, perhaps I\'ll have a taste...' WHERE `entry`='12491';
UPDATE `quest_template` SET `RequestItemsText`='$N, your face has a grim set to it. Do you have dire news?' WHERE `entry`='12491';
UPDATE `quest_template` SET `offerrewardtext`='Ah, so Direbrew finally submitted his brew. What a pity he had to die to do it...$B$BOh, well. Bottoms up, eh?' WHERE `entry`='12492';
UPDATE `quest_template` SET `RequestItemsText`='Hey $N, your face is all smudged!  Have you been to Blackrock Depths?' WHERE `entry`='12492';
UPDATE `quest_template` SET `objectives`='Speak with Witch Doctor Unbagwa.' WHERE `entry`='349';
UPDATE `quest_template` SET `offerrewardtext`='The Malt is brewed, the Boars are dead$BAnd before all is done and anything said$BWe will have to fight for first dibs$BOn these savory Beer Basted Boar Ribs!' WHERE `entry`='384';
UPDATE `quest_template` SET `RequestItemsText`='I\'m going to need six crag boar ribs and a mug of Rhapsody Malt, $N.' WHERE `entry`='384';
UPDATE `quest_template` SET `offerrewardtext`='Another one of Eitrigg\'s recruits, hm?$B$BA sorry state of affairs we find ourselves in if this is the best the Horde can produce. No matter. By the time we think you\'re ready to leave the Valley, you\'ll be a proud warrior of the Horde.' WHERE `entry`='787';
UPDATE `quest_template` SET `offerrewardtext`='You have proven yourself as an ally of the Netherwing. My mother is free and my brothers and sisters are saved! $B$BPerhaps someday, we will call for you again. When that day comes, know that you will be welcomed with open arms - a brother to the Netherwing Dragonflight.' WHERE `entry`='10871';
UPDATE `quest_template` SET `offerrewardtext`='I am free! You have saved us, $N!' WHERE `entry`='10872';
UPDATE `quest_template` SET `offerrewardtext`='Bomb parts. So my suspicions were true. That\'s not something that I wanted to be right about.$B$BOkay, you and I have some grim business ahead of us then.' WHERE `entry`='10448';
UPDATE `quest_template` SET `offerrewardtext`='Are you sure this is the path you seek to take, $N? This is not a decision you ought to take lightly.$B$BThis ring is imbued with a droplet from the Well of Eternity. It will grow in power as you prove yourself to the Scale of the Sands.' WHERE `entry`='10461';
UPDATE `quest_template` SET `offerrewardtext`='You\'ve proven yourself, today, $N.$B$BWhile I have little else to give you, I do have this crown; a fitting gift for a conqueror. May it light your way.' WHERE `entry`='9339';
UPDATE `quest_template` SET `offerrewardtext`='You\'ve proven yourself, today, $N.$B$BWhile I have little else to give you, I do have this crown; a fitting gift for a conqueror. May it light your way.' WHERE `entry`='9365';
UPDATE `quest_template` SET `offerrewardtext`='Excellent. We were in need of these, $N. Good work.' WHERE `entry`='8540';
UPDATE `quest_template` SET `offerrewardtext`='Excellent. We were in need of these, $N. Good work.' WHERE `entry`='8541';
UPDATE `quest_template` SET `offerrewardtext`='I see that you\'re no ordinary mortal, $N. Your chances against the Old God, however infinitely small, are greater than ours at this point. After all, while he expects dragons at his doorstep, he is not prepared for someone like you.$B$BJust as Anachronos and Staghelm defeated the Qiraji a thousand years ago through the alliance of mortal and dragon races, we too shall form a pact. Gain the trust of the Bronze Dragonflight and you\'ll gain our trust. Only then we shall make a true champion out of you.' WHERE `entry`='8579';
UPDATE `quest_template` SET `RequestItemsText`='We sense the presence of our enslaved brethren deeper inside Ahn\'Qiraj; yet not even an army of dragons would be enough to rescue them, $R.$B$BThe same spell that imprisoned them would place us firmly under C\'Thun\'s control should we come any closer to him.$B$BThe Old God has foreseen our arrival. All hope is lost. What difference could a mere mortal like you possibly make?' WHERE `entry`='8579';
UPDATE `quest_template` SET `offerrewardtext`='Just in time. These supplies will save lives, $N. Your work is appreciated. Here\'s your next assignment.' WHERE `entry`='8496';
UPDATE `quest_template` SET `offerrewardtext`='Excellent!  We were in need of these, $N. Thanks.' WHERE `entry`='8497';
UPDATE `quest_template` SET `objectives`='Bring 20 Arthas\' Tears to Sergeant Major Germaine at the airfield in Dun Morogh.' WHERE `entry`='8510';
UPDATE `quest_template` SET `RequestItemsText`='What! You again? Well I\'ll be a monkey\'s uncle... except that I\'m a gnome. Slicky Gastronome to be precise! So you\'re back to help out again, eh? Well, I can\'t say as I blame you. Don\'t you just love the smell of all of that food? <drool>$B$BEnough loitering! Get out there and bring me back more rainbow fin albacore!' WHERE `entry`='8525';
UPDATE `quest_template` SET `offerrewardtext`='I can read most of this, enough to get a general idea. Whoever wrote this is praising the \'progress\' made by Luanga and encouraging him to continue interrogating his \'guests.\'$B$BMeanwhile, it says, \'the preparations in Skettis are proceeding as planned\' and that they will \'soon be ready to reclaim their ancestral lands.\'$B$BI\'m not familiar with this \'Skettis\' mentioned by the writer, but wherever it is, it sounds like the arakkoa are assembling an army there! Thander must be told about this immediately.' WHERE `entry`='9984';
UPDATE `quest_template` SET `offerrewardtext`='I can read most of this, enough to get a general idea. Whoever wrote this is praising the \'progress\' made by Luanga and encouraging him to continue interrogating his \'guests.\'$B$BMeanwhile, it says, \'the preparations in Skettis are proceeding as planned\' and that they will \'soon be ready to reclaim their ancestral lands.\'$B$BI\'m not familiar with this \'Skettis\' mentioned by the writer, but wherever it is, it sounds like the arakkoa are assembling an army there! Rokag must be told about this immediately.' WHERE `entry`='9985';
UPDATE `quest_template` SET `offerrewardtext`='Your deeds will be known to all, champion. They will sing your praises from Orgrimmar to the far reaches of the South Seas. All will know of the champion of the Bronze Flight, $N.' WHERE `entry`='8741';
UPDATE `quest_template` SET `RequestItemsText`='Have you brought the materials?' WHERE `entry`='9238';
UPDATE `quest_template` SET `offerrewardtext`='Simply by answering the call, we are in your debt, $N. The Argent Dawn is certain that through your shining example, others that are here to aid us will gain great insight into how best to throw back this Scourge Invasion!' WHERE `entry`='9247';
UPDATE `quest_template` SET `offerrewardtext`='<Lorax laughs.>' WHERE `entry`='5126';
UPDATE `quest_template` SET `offerrewardtext`='You gather the paladin\'s remains as carefully as you can, recalling that at least his spirit has been released from any pain or suffering that might have been forced upon him.' WHERE `entry`='5204';
UPDATE `quest_template` SET `offerrewardtext`='The key taken from Cauldron Lord Bilemaw is a perfect fit in unlocking the access panel, though it disappears after you use it. Still, you think you can open the panel now without a key. A foul stench emanates from the opened panel as an unknown mix of concentrated substances swirl inside the cauldron.$B$BThere is a small spigot that the bottle fits well enough under, allowing you to draw a sample for Shadow Priestess Vandis back at the Bulwark.' WHERE `entry`='5229';
UPDATE `quest_template` SET `offerrewardtext`='The cauldron lord\'s key unlocks the access panel to this cauldron and then disappears, much like the other keys have for the previous ones you\'ve dealt of. A putrid smelling substance churns violently beneath the platform of the cauldron.$B$BThere is a small spigot that the bottle fits well enough under, allowing you to draw a sample for Shadow Priestess Vandis back at the Bulwark.' WHERE `entry`='5233';
UPDATE `quest_template` SET `offerrewardtext`='Congratulations, $N - I am pleased to award you with an Argent Dawn valor token!$B$BThe tokens serve two purposes. One - they can be used to further your standing within the Argent Dawn; to do so may avail you options and rewards that are reserved for our honored and revered allies. Two - they can be given to our quartermasters, along with coin, as payment for some of the Dawn\'s more prized items.$B$BWhatever you decide, know that you are earning your commission. Well done!' WHERE `entry`='5402';
UPDATE `quest_template` SET `offerrewardtext`='Congratulations, $N - I am pleased to award you with an Argent Dawn valor token!$B$BTo acquire a valor token in such a manner indicates that you are a true hero in the cause of good. We value all effort brought to bear against the Scourge, but to take down one of their leaders is to truly deliver onto them a crushing defeat!$B$BFor the Dawn, my g$sister:brother;!' WHERE `entry`='5404';
UPDATE `quest_template` SET `offerrewardtext`='Congratulations, $N - I am pleased to award you with an Argent Dawn valor token!$B$BTo acquire a valor token in such a manner indicates that you are a true hero in the cause of good. We value all effort brought to bear against the Scourge, but to take down one of their leaders is to truly deliver onto them a crushing defeat!$B$BFor the Dawn, my g$sister:brother;!' WHERE `entry`='5406';
UPDATE `quest_template` SET `offerrewardtext`='Congratulations, $N - I am pleased to award you with an Argent Dawn valor token!$B$BThe tokens serve two purposes. One - they can be used to further your standing within the Argent Dawn; to do so may avail you options and rewards that are reserved for our honored and revered allies. Two - they can be given to our quartermasters, along with coin, as payment for some of the Dawn\'s more prized items.$B$BWhatever you decide, know that you are earning your commission. Well done!' WHERE `entry`='5408';
UPDATE `quest_template` SET `offerrewardtext`='Good, good. Maybe they\'ll think twice before slacking next time!  Thanks for the help!' WHERE `entry`='5441';
UPDATE `quest_template` SET `ObjectiveText3`='Legion Antenna: Oblivion Destroyed' WHERE `entry`='10144';
UPDATE `quest_template` SET `offerrewardtext`='Ah. good, another has arrived. Time may not matter to me, but to you it is of the essence. There is much for you to learn and there is much I wish to teach you. You simply must prove your worth. Do that, and you shall be greatly rewarded.' WHERE `entry`='10379';
UPDATE `quest_template` SET `RequestItemsText`='Have you found your way through the dark?' WHERE `entry`='9386';
UPDATE `quest_template` SET `RequestItemsText`='You appear to have uncovered the wreckage of... a robotic chicken? The voice from within the egg crackles to life again:$B$B"Yes, excellent work! This is indeed my homing robot, though my sensors indicate that it needs a jump start before it can fly back to Booty Bay for repairs. Go ahead and place the beacon inside the rover - the beacon will take care of the rest!"' WHERE `entry`='351';
UPDATE `quest_template` SET `offerrewardtext`='Countless times I urged the Warchief not to trust the humans, but personal pride is not what is at stake here.$B$BYou have served the Horde honorably, young $C.$B$BNow excuse me, I must counsel Thrall on these matters at once...' WHERE `entry`='831';
UPDATE `quest_template` SET `RequestItemsText`='Can you not see that I am busy? This had better be pressing...' WHERE `entry`='831';
UPDATE `quest_template` SET `RequestItemsText`='You wouldn\'t think it from a guy like my boss Gazlowe, but he always seemed to know the score. "Don\'t be afraid to take that big step," he said.$B$BHarpies won\'t stop bothering us and the caravans won\'t stop being attacked unless we do something about it, eh?' WHERE `entry`='835';
UPDATE `quest_template` SET `offerrewardtext`='Alright, $N. You want to earn your keep with the Horde? Well there\'s plenty to do here, so listen close and do what you\'re told.$B$B$GI see that look in your eyes, do not think I will tolerate any insolence. Thrall himself has declared the Hordes females to be on equal footing with you men. Disrespect me in the slightest, and you will know true pain.:I\'m happy to have met you. Thrall will be glad to know that more females like you and I are taking the initiative to push forward in the Barrens.' WHERE `entry`='842';
UPDATE `quest_template` SET `offerrewardtext`='Skorn Whitecloud is a wise tauren. He has hunted for years and years, and although his body is old, his spirit burns fiercely. We are honored to have him with us.$B$BIf Skorn sent you to me, then you too must have the hunter\'s spirit. And to have gathered these claws shows your burgeoning skills.$B$BPerhaps you are ready to walk the path.' WHERE `entry`='861';
UPDATE `quest_template` SET `offerrewardtext`='Shan\'do Stormrage never returned, and the druids were in disarray, and to this day we still do not know what became of him. With Malfurion missing, Arch Druid Fandral Staghelm took over the leadership of the druids, convincing the Circle of Ancients in Darkshore that it was time for our people to rebuild, and that it was time for our people to regain their immortality.$B$BWith the approval of the Circle, Staghelm and the most powerful druids grew Teldrassil, the new World Tree.' WHERE `entry`='933';
UPDATE `quest_template` SET `offerrewardtext`='To be in the presence of the Oracle Tree... it is almost to feel wisdom take form. Let me continue the telling...$B$BWith Teldrassil grown, the Arch Druid approached the dragons for their blessings, as the dragons had placed upon Nordrassil in ancient times. But Nozdormu, Lord of Time, refused to give his blessing, chiding the $C for his arrogance. In agreement with Nozdormu, Alexstrasza also refused Staghelm, and without her blessing, Teldrassil\'s growth has been flawed and unpredictable...' WHERE `entry`='934';
UPDATE `quest_template` SET `RequestItemsText`='Did you find the Syndicate Shadow Mages, and collect from them the blood?' WHERE `entry`='1066';
UPDATE `quest_template` SET `RequestItemsText`='Do you have the heirlooms, $N?' WHERE `entry`='1821';
UPDATE `quest_template` SET `offerrewardtext`='$N, I have a mission for you, here in the Mage district. Listen closely, for there is no time to waste.' WHERE `entry`='1919';
UPDATE `quest_template` SET `offerrewardtext`='Here is your nether-lace, $N. It is both comfortable and durable, and holds the magic of the laughing sisters\' hair.$B$BEnjoy, and if you find it amenable, please mention so to Deino. She is a mage on whose good side I wish to stay...' WHERE `entry`='1946';
UPDATE `quest_template` SET `offerrewardtext`='You did it?  Well done!$B$BI was chatting with some of my colleagues and when your name came up they said, "You know that $N sure works well under stress!"$B$BBut when I told them I sent you to Uldaman against the obsidian sentinel, they said I was crazy!  They said, "Tabetha, you\'re crazy!  There\'s no way $N could take on that sentinel!"$B$BAnd I said, "We\'ll see," and then they said "Yeah, we\'ll see..."$B$BWell we sure showed them, didn\'t we!' WHERE `entry`='1956';
UPDATE `quest_template` SET `offerrewardtext`='Ah, well done! These should last me for a little while at least. Here is your pay as promised.$B$BIf you\'re interested, I have some more reagents I could use. These, however, are only found in the depths of the Uldaman excavation. They will not be easy to get, but I will make it worth your while if you are interested in helping me again.$B$BPerhaps something more than some shiny coins, yes?' WHERE `entry`='2258';
UPDATE `quest_template` SET `offerrewardtext`='You seem to have found the remains of the paladin that Dran had mentioned from before. Searching the remains uncovers what would appear to be his journal. The book is in poor condition, as dried blood has stained most of the text in the book. What you can read, however, is gibberish; it is written in the native tongue of the humans, to the best of your knowledge.$B$BYou will need the book translated if you are to glean any knowledge from it.' WHERE `entry`='2284';
UPDATE `quest_template` SET `offerrewardtext`='To deny Ravenholdt the artifact, would be to deny one\'s own existence. Well done, $C. You may yet walk among the assassins of Ravenholdt.$B$BAs a young $C adventuring in Darkshore, I discovered a tea that replenishes energy in combat. It has served me well throughout the years and now I pass on a taste of the thistle tea to you. Drink of it when you tire, $N, and fight with vigor once more!' WHERE `entry`='2358';
UPDATE `quest_template` SET `objectives`='Journey to Orgrimmar and speak with Shenthul at the Cleft of Shadow.' WHERE `entry`='2378';
UPDATE `quest_template` SET `objectives`='Bring the Southsea Treasure back to Wrenix the Wretched in Ratchet. Do not forget to get an E.C.A.C. and Thieves\' Tools from Wrenix\'s Gizmotronic Apparatus. You will need both of these items to complete your mission.$B$BShould you be attacked by any unusually hostile parrots, use your E.C.A.C.!' WHERE `entry`='2381';
UPDATE `quest_template` SET `offerrewardtext`='Ah, that\'s my parchment. I heard you\'d be coming to the Valley, $N. I\'m glad to see you made it--let\'s hope you survive the trials ahead. Like I said, as you gain in power, come to me--I will do what I can to train you in the ways of the warrior.$B$BGood luck, $N, and return to me whenever you feel ready.' WHERE `entry`='2383';
UPDATE `quest_template` SET `objectives`='Travel to Tarren Mill in Hillsbrad Foothills and deliver the Sample of Zanzil\'s Mixture to Serge Hinott.$B$BTo get to Tarren Mill, take the Zeppelin to the Undercity and follow the road south through Silverpine and towards Hillsbrad. Follow the signs!' WHERE `entry`='2479';
UPDATE `quest_template` SET `offerrewardtext`='Ah, well done! These should last me for a little while at least. Here is your pay as promised.$B$BIf you\'re interested, I have some more reagents I could use. These, however, are only found in the depths of the Uldaman excavation. They will not be easy to get, but I will make it worth your while if you are interested in helping me again.$B$BPerhaps something more than some shiny coins, yes?' WHERE `entry`='2500';
UPDATE `quest_template` SET `offerrewardtext`='What the...?! Don\'t sneak up on me like that! And keep your voice down! What in the name of the Shadow are you doing sneakin\' up on me for? Can\'t you see I\'m busy, you daft fool?$B$BWhat do you mean, what am I doing? I\'m waiting for the next Dark Portal to open, what the heck do you think I\'m doing? Speak your peace and be off with you... \'fore the guards notice the two of us hiding in the bushes together. I have a reputation to maintain.' WHERE `entry`='2745';
UPDATE `quest_template` SET `offerrewardtext`='The wind approaches you quickly from the horizon; the earth is steady beneath your feet; and your spirit is already warmed by fire--I would say it is time for you to learn about the purity of water.$B$BYour path has led you this far, and your spirit will give you the strength to carry on even further. But the first step is yours to take.' WHERE `entry`='2986';
UPDATE `quest_template` SET `offerrewardtext`='You\'ll find this place fitting as you continue to train in the warrior ways. If you have any questions, feel free to ask anyone around, and when you feel you\'re ready, come back to me for training. I\'ve mastered as much as any warrior here in the Valley and can pass that knowledge on to you... for a price.' WHERE `entry`='3065';
UPDATE `quest_template` SET `offerrewardtext`='Now we teach them those things, and they teach us others. We become one race... almost. We be allies for long time now. So you remember to help them. And Jen\'shan remember to help you.$B$BJen\'shan teach you da ways of the hunter--teach you good. You never forget, $C\'s be respected greatly by da tribe. You be havin\' a large role to play in da future... you never forget that.$B$BWhen you feel da need, come to Jen\'shan. She teach you as much as she can when she feel you ready.' WHERE `entry`='3082';
UPDATE `quest_template` SET `RequestItemsText`='Jen\'shan see a mighty $C before her and da spirits approve.$B$BDa path of da $C is one of our oldest walks of life. Da Horde turned to us when they be just strugglin\' to survive on Azeroth, and they ask us to teach them, to show them the secrets of many tings. They were strong already: strong in shaman ways; strong in warrior ways. But the hunter path not be their path... then.' WHERE `entry`='3082';
UPDATE `quest_template` SET `offerrewardtext`='And it is my job to make sure you are prepared by teaching you the basics of our profession--how to tame your pet, how to fire your rifle, and many other skills that will become necessary.$B$BHunters are a strong part of our tradition and history, $N. You would do well to remember how important you are to the tribe. You will be respected and revered if you serve our people well.' WHERE `entry`='3092';
UPDATE `quest_template` SET `offerrewardtext`='You\'re gonna find a number of outfits that covet our skills, $N. Adventurers, SI:7... heck, even the Defias Brotherhood wouldn\'t mind a spy or two inside Stormwind. But you remember this, you\'re your own $Gman:woman;. Don\'t let nobody bully you into doing something you don\'t wanna do! Besides, we hold all the cards... at least, we do before the game\'s done. Know what I mean?$B$BAnyway, just wanted to introduce myself and let you know that I\'m here if you need any training. Come by anytime.' WHERE `entry`='3102';
UPDATE `quest_template` SET `offerrewardtext`='But none of that matters. What matters is that you\'ve seen your own Holy Light! You know where power truly comes from. You realize that having our own allies is much more... prudent. Special allies. Allies that, no matter the task, will obey till their last breath.$B$BAnd that\'s where I come in, $N. I can train you in the beginnings of those special powers. Seek me out often and I will do what I can to teach you more spells.' WHERE `entry`='3115';
UPDATE `quest_template` SET `RequestItemsText`='Wonderful! You got my memorandum obviously.$B$BIgnore the fools around you, $N. The Holy Light?! The sword and shield?! These aren\'t paths for ones as open minded as us. Look at what "normal" magic did to our home. Coupled with those damned tinkerers, our race almost became extinct. And now we have to rely on the dwarves-- they\'d rather spend time allying with humans than help us rebuild our own home. We\'re like second-class citizens. Have you seen the way they look at us?' WHERE `entry`='3115';
UPDATE `quest_template` SET `offerrewardtext`='What have you got there? A fake obviously!$B$BI\'ve been face to face with Margol and I know for a fact that her horn is at least eight times larger than the one you\'ve got in your hands, $N. You probably got that off of a stormsnout in the Barrens. No ma\'am, you can\'t fool Pebblebitty!' WHERE `entry`='3181';
UPDATE `quest_template` SET `offerrewardtext`='Thanks for the done work!' WHERE `entry`='3366';
UPDATE `quest_template` SET `offerrewardtext`='You truly disgust me, $R. A grown man drooling over a pile of junk? Pitiful! Take your reward and get out of my sight.' WHERE `entry`='3501';
UPDATE `quest_template` SET `RequestItemsText`='Ah, Belgrom wizened up and finally sent someone not in his ranks to aid us, did he?$B$BThis camp used to be a dozen warriors strong, $N, but now they\'re all dead. That mage, Rimtori, has slain them all. She played Belgrom like a lute... seduced him even. It\'s none of my business, but between you and I, she is quite the temptress. That\'s probably why I\'m still out here helping Belgrom--I probably would have done the same thing.' WHERE `entry`='3504';
UPDATE `quest_template` SET `offerrewardtext`='HAHA! Look at you now, pathetic woman! I spit on your remains!$B$BThank you, $N. Thank you from the bottom of my heart! This is indeed a great day!$B$BI would give you a kingdom if it were in my power! But perhaps you will settle for this.$B$B<Belgrom looks down at the head of the mage who had betrayed him.>$B$BHaha! Stupid blood elf, look at you now... in a burlap sack and missing your body! You should never have betrayed Belgrom!' WHERE `entry`='3507';
UPDATE `quest_template` SET `offerrewardtext`='Well done $N, I will be sure to give these to the Arch Druid himself when he has need of them. Meanwhile, please accept this as a token of the Cenarion Circle\'s appreciation.$B$BOur need for morrowgrain, for now, is constant; if you wish to continue aiding us, then please return when you have cultivated more of it.' WHERE `entry`='3785';
UPDATE `quest_template` SET `RequestItemsText`='Yes $N, have you grown some morrowgrain for the Arch Druid\'s important research? The mysterious properties of Un\'Goro Crater become clearer with each passing day, thanks to the help you are giving us.' WHERE `entry`='3785';
UPDATE `quest_template` SET `RequestItemsText`='You have found a sickly, corrupted version of what appears to be a Night Dragon plant. The fruits that hang from the plant appear rotten and poisonous. It desperately needs some sort of attention if it is to be turned back to normal.' WHERE `entry`='4119';
UPDATE `quest_template` SET `RequestItemsText`='You have found a sickly, corrupted version of what appears to be a Night Dragon plant. The fruits that hang from the plant appear rotten and poisonous. It desperately needs some sort of attention if it is to be turned back to normal.' WHERE `entry`='4447';
UPDATE `quest_template` SET `objectives`='Speak with Gornek. You recall Kaltunk marking your map with his location and mentioning that Gornek resided in the Den, a building to the west.' WHERE `entry`='4641';
UPDATE `quest_template` SET `objectives`='Destroy 8 Diseased Wolves, and then return to Mulgris Deepriver at the Writhing Haunt, Western Plaguelands.' WHERE `entry`='4984';
UPDATE `quest_template` SET `offerrewardtext`='This does not make sense. Why would Arikara be after Cairne Bloodhoof? Magatha could not be wrong, she is our most powerful shaman.$B$B<Motega shakes his head.>$B$BRegardless, your great deed to the Horde shall not go unnoticed - please, choose one of these as a reward for your aid.' WHERE `entry`='5088';
UPDATE `quest_template` SET `RequestItemsText`='Once the towers are marked, they\'ll become top priority targets for our attack on Andorhal. I suspect that once we neutralize the towers, the main threat of Andorhal will emerge. From that point on, we\'ll have a straight-up fight for control of the city!$B$BYou\'re back to report success, yes? Don\'t forget the beacon torch as well; we must maintain control of our materiel.' WHERE `entry`='5097';
UPDATE `quest_template` SET `objectives`='Kill 6 sheep for Benny and then run like hell!$B$BJust kidding... about the running part.' WHERE `entry`='5101';
UPDATE `quest_template` SET `offerrewardtext`='Ah, my doom weed. Excellent!$B$B<Junior Apothecary Holland rubs his hands together greedily.>$B$BThese will come in quite handy. You\'ve done me, uh, the Lady, a fine service today $N. As promised here is the reward that you deserve.' WHERE `entry`='5482';
UPDATE `quest_template` SET `offerrewardtext`='Congratulations, $N - I am pleased to award you with an Argent Dawn valor token!$B$BThe tokens serve two purposes. One - they can be used to further your standing within the Argent Dawn; to do so may avail you options and rewards that are reserved for our honored and revered allies. Two - they can be given to our quartermasters, along with coin, as payment for some of the Dawn\'s more prized items.$B$BWhatever you decide, know that you are earning your commission. Well done!' WHERE `entry`='5510';
UPDATE `quest_template` SET `offerrewardtext`='You are a shining example of decency, $R! It has been long since I have felt the blood of heroes pump through my veins. Your acts of bravery are uplifting!' WHERE `entry`='5543';
UPDATE `quest_template` SET `offerrewardtext`='Excellent, $N. With one more healthy guard out there to help the town, we\'ll be that much safer. I\'m glad to see you\'re already learning to use your abilities wisely. If you feel you are ready for more training at any time, please come back to me. But for now, take this robe. It will let others know that you are one of our order. If you don\'t want to wear it, that\'s fine. Later there will be more tests and this robe isn\'t necessary for those.' WHERE `entry`='5624';
UPDATE `quest_template` SET `offerrewardtext`='Excellent, $N. With one more healthy guard out there to help the town, we\'ll be that much safer. I\'m glad to see you\'re already learning to use your abilities wisely. If you feel you are ready for more training at any time, please come back to me. But for now, take this robe. It will let others know that you are one of our order. If you don\'t want to wear it, that\'s fine. Later there will be more tests and this robe isn\'t necessary for those.' WHERE `entry`='5625';
UPDATE `quest_template` SET `offerrewardtext`='You have finally taken your large step into a much larger world, $N. I sense the teaching of the Great Bear Spirit within you, and I sense that you have received the strength that Lunaclaw possessed.$B$BThere are no further obstacles in your way... let me now teach you what it means to be a Druid of the Claw!' WHERE `entry`='6001';
UPDATE `quest_template` SET `EndText`='Face Lunaclaw and earn the strength of body and heart it possesses.' WHERE `entry`='6001';
UPDATE `quest_template` SET `offerrewardtext`='You have finally taken your large step into a much larger world, $N. I sense the teaching of the Great Bear Spirit within you, and I sense that you have received the strength that Lunaclaw possessed.$B$BThere are no further obstacles in your way... let me now teach you what it means to be a Druid of the Claw!' WHERE `entry`='6002';
UPDATE `quest_template` SET `EndText`='Face Lunaclaw and earn the strength of body and heart it possesses.' WHERE `entry`='6002';
UPDATE `quest_template` SET `RequestItemsText`='Don\'t worry, $Glad:lass;! You\'ll get ta try a few before you\'ll need to decide on just one.' WHERE `entry`='6064';
UPDATE `quest_template` SET `offerrewardtext`='Yes, it is time, $C.' WHERE `entry`='6072';
UPDATE `quest_template` SET `offerrewardtext`='Greetings young $C, I\'m glad to see you ready and eager to learn about the curing of poisons.$B$BWhile most druids in the past were put through pre-planned trials, your work will involve no such thing. There has been a rash of animal poisonings in Auberdine, and the village there has been unable to cure it. To that end, a representative there has asked Moonglade for aid and we are sending you there to aid them. This is no exercise - the work you\'ll do is quite real. Bear this in mind.' WHERE `entry`='6121';
UPDATE `quest_template` SET `offerrewardtext`='Greetings young $C, I\'m glad to see you ready and eager to learn about the curing of poisons.$B$BWhile most druids in the past were put through pre-planned trials, your work will involve no such thing. There has been a rash of animal poisonings at the Crossroads in the Barrens, and they\'re unable to bring it under control. Someone there has requested Moonglade for aid, so we are sending you there to aid them. This is no exercise - the work you\'ll do is quite real. Bear this in mind.' WHERE `entry`='6126';
UPDATE `quest_template` SET `EndText`='Melizza Brimbuzzle escorted to safety' WHERE `entry`='6132';
UPDATE `quest_template` SET `offerrewardtext`='Excellent, $N. You\'ve saved me a lot of work!$B$BBut don\'t think that I\'m not grateful!' WHERE `entry`='6571';
UPDATE `quest_template` SET `RequestItemsText`='<Nipsy puts his index finger through one of the air holes in the carton.>$B$BAlive and kicking... and just in time!' WHERE `entry`='6662';
UPDATE `quest_template` SET `offerrewardtext`='A pleasure doin\' business with ya.$B$BAnd $N, wipe that look of disgust off yer face.' WHERE `entry`='7653';
UPDATE `quest_template` SET `offerrewardtext`='The legends and lore surrounding the Winter Veil are ones that have faded from the forefront of public thought over the years. Yes, I know that the goblins are helping to revive the season for their own ends, the fact that our people reflect upon it at least in some form does good to keep such lore alive.$B$BYour desire to go beyond the material and learn about our past is an admirable trait, young $C. I salute your wisdom.' WHERE `entry`='7061';
UPDATE `quest_template` SET `offerrewardtext`='The legends and lore surrounding the Winter Veil are ones that have faded from the forefront of public thought over the years. While I recognize that the goblins are helping to revive the season for their own ends, the fact that the citizenry thinks about it at least in some form does good to keep such lore alive.$B$BYour desire to go beyond the material and learn about our past is an admirable trait, young $C. I salute your erudite nature.' WHERE `entry`='7063';
UPDATE `quest_template` SET `details`='Tell Tammra Windfield, Kaya\'s aunt who\'s at Sun Rock Retreat, about the good news! Kaya is alive! We had thought she was lost after the brutal attack on our village. Follow the path to the west to get to Sun Rock Retreat.' WHERE `entry`='6401';
UPDATE `quest_template` SET `RequestItemsText`='Bhag\'thera can prove to be an elusive beast. How fares the hunt?' WHERE `entry`='193';
UPDATE `quest_template` SET `RequestItemsText`='Back so soon? In case I didn\'t make myself clear we need you to kill 10 Stonesplinter Shaman and 10 Stonesplinter Bonesnappers, $N. Now go get \'em, Trogg-Slayer!' WHERE `entry`='263';
UPDATE `quest_template` SET `RequestItemsText`='You wouldn\'t think it from a guy like my boss Gazlowe, but he always seemed to know the score. "Don\'t be afraid to take that big step", he said.$B$BHarpies won\'t stop bothering us and the caravans won\'t stop being attacked unless we do something about it, eh?' WHERE `entry`='835';
UPDATE `quest_template` SET `offerrewardtext`='Both strength and cunning were needed to find and defeat Frostmaw, $N. You have both.$B$BYour path has taken you to the valleys of Thousand Needles and to the high mountains of Alterac. It will one day lead you through all the Earthmother\'s lands, for such is the way of the hunter.' WHERE `entry`='1136';
UPDATE `quest_template` SET `offerrewardtext`='$N, noble $C. I am Keldran, student of magic... and other mystical arts.$B$BThe business Craven sent you here to speak to me about requires a touch more subtlety than you\'ve previously needed, but that does not mean you can not still aid our cause.$B$BPlease, make yourself comfortable, and I shall tell you why the Warchief has need of my aid... and yours.$B$BIt starts with appearances, $N. How the Horde sees itself. How our allies see us. And most importantly, how our enemies see us.' WHERE `entry`='1431';
UPDATE `quest_template` SET `offerrewardtext`='You have done well, $N.$B$BAlthough the Vile Familiars were merely pets of the darker powers within the Burning Blade, your success against them foretells greater deeds ahead.' WHERE `entry`='1499';
UPDATE `quest_template` SET `offerrewardtext`='Good day, $N. The Light is with you, I trust?$B$BWhat\'s that? You were sent by Duthorian!? My wife, how is she? I knew there was going to be trouble if I left.$B$BPlease tell me she\'s... oh, thank goodness. I\'m so glad that she\'s safe. The Defias were a threat long before these attacks, but now the King\'s advisors cannot deny it.$B$BWhat else did Duthorian have to say? You\'re the one that was sent to protect my wife? Then I thank you again, $N. I couldn\'t think of a better test of valor than that.' WHERE `entry`='1653';
UPDATE `quest_template` SET `RequestItemsText`='Have you been to Vejrek\'s hut, $N? Is that troll stink I smell on you?' WHERE `entry`='1678';
UPDATE `quest_template` SET `offerrewardtext`='I bid you greetings, $N. Your name rings loudly in Darnassus, for you show promise. But we shall soon see if you possess the strength of will to follow the path of the warrior.' WHERE `entry`='1684';
UPDATE `quest_template` SET `offerrewardtext`='Yes it\'s true. Techbot has gone rogue! Please, can you help me?' WHERE `entry`='2923';
UPDATE `quest_template` SET `offerrewardtext`='Congratulations, $N - I am pleased to award you with an Argent Dawn valor token!$B$BTo acquire a valor token in such a manner indicates that you are a true hero in the cause of good. We value all effort brought to bear against the Scourge, but to take down one of their leaders is to truly deliver onto them a crushing defeat!$B$BFor the Dawn, my $Gbrother:sister;!' WHERE `entry`='5404';
UPDATE `quest_template` SET `offerrewardtext`='Congratulations, $N - I am pleased to award you with an Argent Dawn valor token!$B$BTo acquire a valor token in such a manner indicates that you are a true hero in the cause of good. We value all effort brought to bear against the Scourge, but to take down one of their leaders is to truly deliver onto them a crushing defeat!$B$BFor the Dawn, my $Gbrother:sister;!' WHERE `entry`='5406';
UPDATE `quest_template` SET `objectives`='Bring 5 Gingerbread Cookies and an Ice Cold Milk to Great-father Winter in Orgrimmar.' WHERE `entry`='6962';
UPDATE `quest_template` SET `offerrewardtext`='You\'re quite the helper to ol\' Great-father Winter there, $N. Have a great Feast of Winter Veil.$B$BHere\'s a little something... you know, for the effort.' WHERE `entry`='6962';
UPDATE `quest_template` SET `objectives`='Deliver 2 Incendosaur Scales, 4 Kingsblood and one Coal to Master Smith Burninate.' WHERE `entry`='7736';
UPDATE `quest_template` SET `objectives`='Collect three Dim Necrotic Stones from the Scourge outside Ironforge and investigate the glowing runic circles near their encampment.' WHERE `entry`='9261';
UPDATE `quest_template` SET `objectives`='Collect three Dim Necrotic Stones from the Scourge outside Darnassus and investigate the glowing runic circles near their encampment.' WHERE `entry`='9262';
UPDATE `quest_template` SET `objectives`='Collect three Dim Necrotic Stones from the Scourge outside Orgrimmar and investigate the glowing runic circles near their encampment.' WHERE `entry`='9263';
UPDATE `quest_template` SET `objectives`='Collect three Dim Necrotic Stones from the Scourge outside Thunder Bluff and investigate the glowing runic circles near their encampment.' WHERE `entry`='9264';
UPDATE `quest_template` SET `objectives`='Collect three Dim Necrotic Stones from the Scourge outside the Undercity and investigate the glowing runic circles near their encampment.' WHERE `entry`='9265';
UPDATE `quest_template` SET `details`='If you bring me your white stallion, I\'ll trade you for one from the new herd. The new horse will be just as fast as your old one, but have a different look to it. You can look at the swift steeds here to see what it will look like.$B$BMUST PAY 500 Gold too....' WHERE `entry`='7677';
UPDATE `quest_template` SET `offerrewardtext`='Excellent, excellent!  These are going to work out incredibly well - I can already tell that they\'re going to be much harder when properly cured.$B$BThanks again for your help $N. Here - please take one of my latest creations.' WHERE `entry`='7734';
UPDATE `quest_template` SET `offerrewardtext`='$N, I have a pet boar named Huffer. He wants to help you to have some fun with one of the nearby sons of Gruul.$B$BGrulloc inhabits a place known as the Cursed Hollow. When you get there, let Huffer loose. The gronn will have a fine time chasing him around, and you will retrieve the bag that he guards and deliver it to Baron Sablemane.$B$BTo get to the Cursed Hollow, head down the northern ramp and east through Dragons\' End. The hollow is on the eastern edge.' WHERE `entry`='10721';
UPDATE `quest_template` SET `RequestItemsText`='You\'ve something for me, $Glad : lass;?' WHERE `entry`='11098';
UPDATE `quest_template` SET `details`='Lissen mon, there be sumthin\' else needs doin fer ol\' Prigmon.$B$BZungam, my good-fer-nuthin\' cousin, be stuck inside Zul\'Aman. He still be alive too - I seen his signal flare just last night!$B$BI should be lettin\' him rot fer gettin\' me tied up in this mess, but he be owin\' me big money.$B$BDo what ya can to help him out, then leave the collectin\' to me!' WHERE `entry`='11196';

        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
        -- -- PLACE UPDATE SQL ABOVE -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -

        -- If we get here ok, commit the changes
        IF bRollback = TRUE THEN
            ROLLBACK;
            SHOW ERRORS;
            SELECT '* UPDATE FAILED *' AS `===== Status =====`,@cCurResult AS `===== DB is on Version: =====`;
        ELSE
            COMMIT;
            -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
            -- UPDATE THE DB VERSION
            -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
            INSERT INTO `db_version` VALUES (@cNewVersion, @cNewStructure, @cNewContent, @cNewDescription, @cNewComment);
            SET @cNewResult := (SELECT `description` FROM `db_version` WHERE `version`=@cNewVersion AND `structure`=@cNewStructure AND `content`=@cNewContent);

            SELECT '* UPDATE COMPLETE *' AS `===== Status =====`,@cNewResult AS `===== DB is now on Version =====`;
        END IF;
    ELSE    -- Current version is not the expected version
        IF (@cCurResult = @cNewResult) THEN    -- Does the current version match the new version
            SELECT '* UPDATE SKIPPED *' AS `===== Status =====`,@cCurResult AS `===== DB is already on Version =====`;
        ELSE    -- Current version is not one related to this update
            IF(@cCurResult IS NULL) THEN    -- Something has gone wrong
                SELECT '* UPDATE FAILED *' AS `===== Status =====`,'Unable to locate DB Version Information' AS `============= Error Message =============`;
            ELSE
                IF(@cOldResult IS NULL) THEN    -- Something has gone wrong
                    SET @cCurVersion := (SELECT `version` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurStructure := (SELECT `STRUCTURE` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurContent := (SELECT `Content` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurOutput = CONCAT(@cCurVersion, '_', @cCurStructure, '_', @cCurContent, ' - ',@cCurResult);
                    SET @cOldResult = CONCAT('Rel',@cOldVersion, '_', @cOldStructure, '_', @cOldContent, ' - ','IS NOT APPLIED');
                    SELECT '* UPDATE SKIPPED *' AS `===== Status =====`,@cOldResult AS `=== Expected ===`,@cCurOutput AS `===== Found Version =====`;
                ELSE
                    SET @cCurVersion := (SELECT `version` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurStructure := (SELECT `STRUCTURE` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurContent := (SELECT `Content` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurOutput = CONCAT(@cCurVersion, '_', @cCurStructure, '_', @cCurContent, ' - ',@cCurResult);
                    SELECT '* UPDATE SKIPPED *' AS `===== Status =====`,@cOldResult AS `=== Expected ===`,@cCurOutput AS `===== Found Version =====`;
                END IF;
            END IF;
        END IF;
    END IF;
END $$

DELIMITER ;

-- Execute the procedure
CALL update_mangos();

-- Drop the procedure
DROP PROCEDURE IF EXISTS `update_mangos`;


