-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc2`='[PH] Learn Dimensional Ripper.' WHERE `word_id`=128975; -- locales_gossip_menu_option - option_text : menu_id=20003-id=0
UPDATE `trans_words` SET `content_loc2`='[PH] Learn Ultrasafe Transporter.' WHERE `word_id`=128976; -- locales_gossip_menu_option - option_text : menu_id=20004-id=0
UPDATE `trans_words` SET `content_loc2`='[ph]Learn recipe...' WHERE `word_id`=128221; -- locales_gossip_menu_option - option_text : menu_id=6443-id=0
UPDATE `trans_words` SET `content_loc2`='Gul\'dan' WHERE `word_id`=84267; -- locales_gossip_menu_option - option_text : menu_id=4764-id=0
UPDATE `trans_words` SET `content_loc2`='Impossible.' WHERE `word_id`=128124; -- locales_gossip_menu_option - option_text : menu_id=3371-id=0
UPDATE `trans_words` SET `content_loc2`='Mage' WHERE `word_id`=99887; -- locales_gossip_menu_option - option_text : menu_id=10768-id=0
UPDATE `trans_words` SET `content_loc2`='Ner\'zhul' WHERE `word_id`=128151; -- locales_gossip_menu_option - option_text : menu_id=4764-id=2
UPDATE `trans_words` SET `content_loc2`='Oh, its not my fault, I can assure you.' WHERE `word_id`=269449; -- locales_gossip_menu_option - option_text : menu_id=8435-id=0
UPDATE `trans_words` SET `content_loc2`='Paladin' WHERE `word_id`=99882; -- locales_gossip_menu_option - option_text : menu_id=10768-id=1
UPDATE `trans_words` SET `content_loc2`='What does the Dalson\'s Tears Cauldron need?' WHERE `word_id`=128546; -- locales_gossip_menu_option - option_text : menu_id=3223-id=3
UPDATE `trans_words` SET `content_loc2`='What does the Felstone Field Cauldron need?' WHERE `word_id`=128545; -- locales_gossip_menu_option - option_text : menu_id=3223-id=2
UPDATE `trans_words` SET `content_loc2`='What does the Gahrron\'s Withering Cauldron need?' WHERE `word_id`=128548; -- locales_gossip_menu_option - option_text : menu_id=3223-id=5
UPDATE `trans_words` SET `content_loc2`='What does the Writhing Haunt Cauldron need?' WHERE `word_id`=128547; -- locales_gossip_menu_option - option_text : menu_id=3223-id=4
UPDATE `trans_words` SET `content_loc2`='What Guardian? I don	 understand any of this.' WHERE `word_id`=128488; -- locales_gossip_menu_option - option_text : menu_id=86-id=0
UPDATE `trans_words` SET `content_loc2`='What if I don\'t like drinking... Is there another way I can help out?' WHERE `word_id`=128309; -- locales_gossip_menu_option - option_text : menu_id=9006-id=0
UPDATE `trans_words` SET `content_loc2`='Yes elder. Tell me more of the book.' WHERE `word_id`=128719; -- locales_gossip_menu_option - option_text : menu_id=8617-id=0
UPDATE `trans_words` SET `content_loc2`='Yes... yes, it\'s me.' WHERE `word_id`=128718; -- locales_gossip_menu_option - option_text : menu_id=8616-id=0
UPDATE `trans_words` SET `content_loc2`='You gave the crew disguises?' WHERE `word_id`=128740; -- locales_gossip_menu_option - option_text : menu_id=8775-id=0

SET NAMES 'latin1';
