-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc2`='[PH] Alliance Graveyard Mid Banner BIG' WHERE `word_id` = 115945; -- locales_gameobject - name : entry=179044
UPDATE `trans_words` SET `content_loc2`='[PH] Alliance Graveyard Mid Pre-Banner BIG' WHERE `word_id` = 115955; -- locales_gameobject - name : entry=179424
UPDATE `trans_words` SET `content_loc2`='[PH] Alliance H1 Tower Pre-Banner BIG' WHERE `word_id` = 115963; -- locales_gameobject - name : entry=179446
UPDATE `trans_words` SET `content_loc2`='[PH] Alliance H2 Tower Pre-Banner BIG' WHERE `word_id` = 115964; -- locales_gameobject - name : entry=179450
UPDATE `trans_words` SET `content_loc2`='[PH] Alliance H3 Tower Pre-Banner BIG' WHERE `word_id` = 115965; -- locales_gameobject - name : entry=179454
UPDATE `trans_words` SET `content_loc2`='[PH] Alliance H4 Tower Pre-Banner BIG' WHERE `word_id` = 115966; -- locales_gameobject - name : entry=179458
UPDATE `trans_words` SET `content_loc2`='[PH] Horde A1 Tower Pre-Banner BIG' WHERE `word_id` = 115957; -- locales_gameobject - name : entry=179436
UPDATE `trans_words` SET `content_loc2`='[PH] Horde A2 Tower Pre-Banner BIG' WHERE `word_id` = 115960; -- locales_gameobject - name : entry=179440
UPDATE `trans_words` SET `content_loc2`='[PH] Horde A3 Tower Pre-Banner BIG' WHERE `word_id` = 115961; -- locales_gameobject - name : entry=179442
UPDATE `trans_words` SET `content_loc2`='[PH] Horde A4 Tower Pre-Banner BIG' WHERE `word_id` = 115962; -- locales_gameobject - name : entry=179444
UPDATE `trans_words` SET `content_loc2`='Aeris' WHERE `word_id` = 117784; -- locales_gameobject - name : entry=183213
UPDATE `trans_words` SET `content_loc2`='Ahn\'Quiraj' WHERE `word_id` = 117099; -- locales_gameobject - name : entry=19086
UPDATE `trans_words` SET `content_loc2`='Aldrassil' WHERE `word_id` = 114525; -- locales_gameobject - name : entry=12354
UPDATE `trans_words` SET `content_loc2`='Altar of Elune (Trap) (DND)' WHERE `word_id` = 120863; -- locales_gameobject - name : entry=177529
UPDATE `trans_words` SET `content_loc2`='Ameth\'Aran' WHERE `word_id` = 114530; -- locales_gameobject - name : entry=12894
UPDATE `trans_words` SET `content_loc2`='Andorhal' WHERE `word_id` = 114332; -- locales_gameobject - name : entry=176982
UPDATE `trans_words` SET `content_loc2`='Ani' WHERE `word_id` = 115088; -- locales_gameobject - name : entry=149420
UPDATE `trans_words` SET `content_loc2`='AQROOT' WHERE `word_id` = 116385; -- locales_gameobject - name : entry=180899
UPDATE `trans_words` SET `content_loc2`='AQRUNE' WHERE `word_id` = 116384; -- locales_gameobject - name : entry=180898
UPDATE `trans_words` SET `content_loc2`='Arathi Basin BlastedLandsBonePile02' WHERE `word_id` = 116112; -- locales_gameobject - name : entry=180224
UPDATE `trans_words` SET `content_loc2`='Arathi Basin BlastedLandsBonePile03' WHERE `word_id` = 116113; -- locales_gameobject - name : entry=180225
UPDATE `trans_words` SET `content_loc2`='Arathi Basin BlastedLandsSkull01' WHERE `word_id` = 116111; -- locales_gameobject - name : entry=180223
UPDATE `trans_words` SET `content_loc2`='Arathi Basin Bone01' WHERE `word_id` = 116109; -- locales_gameobject - name : entry=180220
UPDATE `trans_words` SET `content_loc2`='Arathi Basin Bone02' WHERE `word_id` = 116110; -- locales_gameobject - name : entry=180222
UPDATE `trans_words` SET `content_loc2`='Arathi Basin Doomweed01' WHERE `word_id` = 116114; -- locales_gameobject - name : entry=180226
UPDATE `trans_words` SET `content_loc2`='Arathi Basin Gloomweed01' WHERE `word_id` = 116115; -- locales_gameobject - name : entry=180227
UPDATE `trans_words` SET `content_loc2`='ArenaGate01' WHERE `word_id` = 115146; -- locales_gameobject - name : entry=161525
UPDATE `trans_words` SET `content_loc2`='ArenaGate02' WHERE `word_id` = 115143; -- locales_gameobject - name : entry=161522
UPDATE `trans_words` SET `content_loc2`='ArenaGate03' WHERE `word_id` = 115145; -- locales_gameobject - name : entry=161524
UPDATE `trans_words` SET `content_loc2`='ArenaGate04' WHERE `word_id` = 115144; -- locales_gameobject - name : entry=161523
UPDATE `trans_words` SET `content_loc2`='Arklon' WHERE `word_id` = 117910; -- locales_gameobject - name : entry=184160
UPDATE `trans_words` SET `content_loc2`='Astranaar' WHERE `word_id` = 114535; -- locales_gameobject - name : entry=13349
UPDATE `trans_words` SET `content_loc2`='Auberdine' WHERE `word_id` = 114531; -- locales_gameobject - name : entry=12896
UPDATE `trans_words` SET `content_loc2`='Auchindoun' WHERE `word_id` = 117688; -- locales_gameobject - name : entry=182109
UPDATE `trans_words` SET `content_loc2`='AuctionNode' WHERE `word_id` = 115290; -- locales_gameobject - name : entry=152583
UPDATE `trans_words` SET `content_loc2`='Aura 1 - Linken' WHERE `word_id` = 115160; -- locales_gameobject - name : entry=164826
UPDATE `trans_words` SET `content_loc2`='Aura 2 - Linken' WHERE `word_id` = 115161; -- locales_gameobject - name : entry=164827
UPDATE `trans_words` SET `content_loc2`='Aura' WHERE `word_id` = 116675; -- locales_gameobject - name : entry=183516
UPDATE `trans_words` SET `content_loc2`='Azshara' WHERE `word_id` = 114538; -- locales_gameobject - name : entry=13358
UPDATE `trans_words` SET `content_loc2`='Baby_Ne' WHERE `word_id` = 118163; -- locales_gameobject - name : entry=185508
UPDATE `trans_words` SET `content_loc2`='Bashal\'Aran' WHERE `word_id` = 114532; -- locales_gameobject - name : entry=12900
UPDATE `trans_words` SET `content_loc2`='BigDoorDummyCollision02' WHERE `word_id` = 115142; -- locales_gameobject - name : entry=161516
UPDATE `trans_words` SET `content_loc2`='Brill' WHERE `word_id` = 114277; -- locales_gameobject - name : entry=146081
UPDATE `trans_words` SET `content_loc2`='Cage' WHERE `word_id` = 115579; -- locales_gameobject - name : entry=176306
UPDATE `trans_words` SET `content_loc2`='Camp Mojache' WHERE `word_id` = 115645; -- locales_gameobject - name : entry=176945
UPDATE `trans_words` SET `content_loc2`='Camp Narache' WHERE `word_id` = 114447; -- locales_gameobject - name : entry=2972
UPDATE `trans_words` SET `content_loc2`='CandleBlack01' WHERE `word_id` = 116184; -- locales_gameobject - name : entry=180415
UPDATE `trans_words` SET `content_loc2`='Coffin' WHERE `word_id` = 117392; -- locales_gameobject - name : entry=19425
UPDATE `trans_words` SET `content_loc2`='Couronne' WHERE `word_id` = 118254; -- locales_gameobject - name : entry=186315
UPDATE `trans_words` SET `content_loc2`='D.I.S.C.O.' WHERE `word_id` = 34669; -- locales_gameobject - name : entry=190351
UPDATE `trans_words` SET `content_loc2`='Darnassus' WHERE `word_id` = 114526; -- locales_gameobject - name : entry=12357
UPDATE `trans_words` SET `content_loc2`='Desolace' WHERE `word_id` = 114599; -- locales_gameobject - name : entry=152575
UPDATE `trans_words` SET `content_loc2`='Dolanaar' WHERE `word_id` = 114522; -- locales_gameobject - name : entry=12351
UPDATE `trans_words` SET `content_loc2`='Don de Mordant' WHERE `word_id` = 116852; -- locales_gameobject - name : entry=186418
UPDATE `trans_words` SET `content_loc2`='Doodad_Ahn_Qiraj_DoorRoots01' WHERE `word_id` = 115552; -- locales_gameobject - name : entry=176147
UPDATE `trans_words` SET `content_loc2`='Doodad_Ahn_Qiraj_DoorRunes01' WHERE `word_id` = 115553; -- locales_gameobject - name : entry=176148
UPDATE `trans_words` SET `content_loc2`='Draenei Hut 2' WHERE `word_id` = 117360; -- locales_gameobject - name : entry=19389
UPDATE `trans_words` SET `content_loc2`='Draenei Hut' WHERE `word_id` = 117358; -- locales_gameobject - name : entry=19387
UPDATE `trans_words` SET `content_loc2`='Draenei Tower' WHERE `word_id` = 117359; -- locales_gameobject - name : entry=19388
UPDATE `trans_words` SET `content_loc2`='Dragon Isles 2' WHERE `word_id` = 117128; -- locales_gameobject - name : entry=19117
UPDATE `trans_words` SET `content_loc2`='Dragon Isles 3' WHERE `word_id` = 117129; -- locales_gameobject - name : entry=19118
UPDATE `trans_words` SET `content_loc2`='Dragon Isles 4' WHERE `word_id` = 117130; -- locales_gameobject - name : entry=19119
UPDATE `trans_words` SET `content_loc2`='Dragon Isles' WHERE `word_id` = 117127; -- locales_gameobject - name : entry=19116
UPDATE `trans_words` SET `content_loc2`='Drizzlik\'s Emporium' WHERE `word_id` = 114487; -- locales_gameobject - name : entry=3767
UPDATE `trans_words` SET `content_loc2`='Druid Mesa 2' WHERE `word_id` = 117312; -- locales_gameobject - name : entry=19332
UPDATE `trans_words` SET `content_loc2`='Druid Mesa' WHERE `word_id` = 117311; -- locales_gameobject - name : entry=19331
UPDATE `trans_words` SET `content_loc2`='Druid Tent' WHERE `word_id` = 117287; -- locales_gameobject - name : entry=19294
UPDATE `trans_words` SET `content_loc2`='Druid Tower' WHERE `word_id` = 117261; -- locales_gameobject - name : entry=19255
UPDATE `trans_words` SET `content_loc2`='Dun Algaz' WHERE `word_id` = 114284; -- locales_gameobject - name : entry=1668
UPDATE `trans_words` SET `content_loc2`='Dun Garok' WHERE `word_id` = 114323; -- locales_gameobject - name : entry=1784
UPDATE `trans_words` SET `content_loc2`='Dun Modr' WHERE `word_id` = 114250; -- locales_gameobject - name : entry=376
UPDATE `trans_words` SET `content_loc2`='Dun Morogh' WHERE `word_id` = 114242; -- locales_gameobject - name : entry=302
UPDATE `trans_words` SET `content_loc2`='Durnholde Walls' WHERE `word_id` = 117352; -- locales_gameobject - name : entry=19380
UPDATE `trans_words` SET `content_loc2`='Durotar Rooted Rock' WHERE `word_id` = 117302; -- locales_gameobject - name : entry=19314
UPDATE `trans_words` SET `content_loc2`='Durotar' WHERE `word_id` = 114497; -- locales_gameobject - name : entry=4098
UPDATE `trans_words` SET `content_loc2`='Duskwood World Tree' WHERE `word_id` = 117065; -- locales_gameobject - name : entry=19051
UPDATE `trans_words` SET `content_loc2`='Dynamite' WHERE `word_id` = 117501; -- locales_gameobject - name : entry=19615
UPDATE `trans_words` SET `content_loc2`='Eclat apogide 01' WHERE `word_id` = 118225; -- locales_gameobject - name : entry=185933
UPDATE `trans_words` SET `content_loc2`='Eclat apogide 02' WHERE `word_id` = 118226; -- locales_gameobject - name : entry=185934
UPDATE `trans_words` SET `content_loc2`='Egg-O-Matic' WHERE `word_id` = 114997; -- locales_gameobject - name : entry=142071
UPDATE `trans_words` SET `content_loc2`='Eliza\'s Tombstone' WHERE `word_id` = 114195; -- locales_gameobject - name : entry=37
UPDATE `trans_words` SET `content_loc2`='Elwynn Fence' WHERE `word_id` = 116925; -- locales_gameobject - name : entry=211062
UPDATE `trans_words` SET `content_loc2`='Elwynn' WHERE `word_id` = 114223; -- locales_gameobject - name : entry=115
UPDATE `trans_words` SET `content_loc2`='Emerald Dream Catcher 2' WHERE `word_id` = 117445; -- locales_gameobject - name : entry=19489
UPDATE `trans_words` SET `content_loc2`='Emerald Dream Catcher 3' WHERE `word_id` = 117446; -- locales_gameobject - name : entry=19490
UPDATE `trans_words` SET `content_loc2`='Emerald Dream Catcher 4' WHERE `word_id` = 117447; -- locales_gameobject - name : entry=19491
UPDATE `trans_words` SET `content_loc2`='Emerald Dream Fountain Tree 2' WHERE `word_id` = 117451; -- locales_gameobject - name : entry=19495
UPDATE `trans_words` SET `content_loc2`='Emerald Dream Fountain Tree 3' WHERE `word_id` = 117452; -- locales_gameobject - name : entry=19496
UPDATE `trans_words` SET `content_loc2`='Emerald Dream Fountain Tree 4' WHERE `word_id` = 117453; -- locales_gameobject - name : entry=19497
UPDATE `trans_words` SET `content_loc2`='Emerald Dream Fountain Tree 5' WHERE `word_id` = 117454; -- locales_gameobject - name : entry=19498
UPDATE `trans_words` SET `content_loc2`='Emerald Dream Fountain Tree' WHERE `word_id` = 117450; -- locales_gameobject - name : entry=19494
UPDATE `trans_words` SET `content_loc2`='Emerald Dream Giant' WHERE `word_id` = 117448; -- locales_gameobject - name : entry=19492
UPDATE `trans_words` SET `content_loc2`='Emerald Dream Spinning Flower' WHERE `word_id` = 117449; -- locales_gameobject - name : entry=19493
UPDATE `trans_words` SET `content_loc2`='Enkaat' WHERE `word_id` = 117905; -- locales_gameobject - name : entry=184149
UPDATE `trans_words` SET `content_loc2`='Everlook Walls' WHERE `word_id` = 117307; -- locales_gameobject - name : entry=19325
UPDATE `trans_words` SET `content_loc2`='Excavation Plataform' WHERE `word_id` = 117345; -- locales_gameobject - name : entry=19372
UPDATE `trans_words` SET `content_loc2`='Excavation Tent Pavillion' WHERE `word_id` = 116900; -- locales_gameobject - name : entry=210286
UPDATE `trans_words` SET `content_loc2`='Eye of Asheron' WHERE `word_id` = 116917; -- locales_gameobject - name : entry=211021
UPDATE `trans_words` SET `content_loc2`='Farahlon' WHERE `word_id` = 117961; -- locales_gameobject - name : entry=184405
UPDATE `trans_words` SET `content_loc2`='Farmountain Maps' WHERE `word_id` = 114725; -- locales_gameobject - name : entry=26492
UPDATE `trans_words` SET `content_loc2`='Fel Cannonball Stack Trap' WHERE `word_id` = 120879; -- locales_gameobject - name : entry=185862
UPDATE `trans_words` SET `content_loc2`='Fel Orc Encampment Custom Area' WHERE `word_id` = 116892; -- locales_gameobject - name : entry=200000
UPDATE `trans_words` SET `content_loc2`='Fence Segment' WHERE `word_id` = 117399; -- locales_gameobject - name : entry=19434
UPDATE `trans_words` SET `content_loc2`='Feralas' WHERE `word_id` = 114618; -- locales_gameobject - name : entry=19842
UPDATE `trans_words` SET `content_loc2`='Ferren Marcus' WHERE `word_id` = 115501; -- locales_gameobject - name : entry=175775
UPDATE `trans_words` SET `content_loc2`='Fire of Elune (Trap)' WHERE `word_id` = 120862; -- locales_gameobject - name : entry=177493
UPDATE `trans_words` SET `content_loc2`='Fishing Hole' WHERE `word_id` = 117174; -- locales_gameobject - name : entry=19164
UPDATE `trans_words` SET `content_loc2`='Flickering Campfire' WHERE `word_id` = 114657; -- locales_gameobject - name : entry=20881
UPDATE `trans_words` SET `content_loc2`='Flinthammer\'s Armorer and Clothier' WHERE `word_id` = 114741; -- locales_gameobject - name : entry=143332
UPDATE `trans_words` SET `content_loc2`='Floating Purple Crystal Broken 01' WHERE `word_id` = 116912; -- locales_gameobject - name : entry=210348
UPDATE `trans_words` SET `content_loc2`='Floating Red Crystal Broken 01' WHERE `word_id` = 116910; -- locales_gameobject - name : entry=210346
UPDATE `trans_words` SET `content_loc2`='Floating Red Crystal Broken 03' WHERE `word_id` = 116909; -- locales_gameobject - name : entry=210345
UPDATE `trans_words` SET `content_loc2`='Forge Camp: Portal Glyph' WHERE `word_id` = 117765; -- locales_gameobject - name : entry=182935
UPDATE `trans_words` SET `content_loc2`='Forge' WHERE `word_id` = 114291; -- locales_gameobject - name : entry=113754
UPDATE `trans_words` SET `content_loc2`='Fortress (Swamp of Sorrows)' WHERE `word_id` = 117271; -- locales_gameobject - name : entry=19272
UPDATE `trans_words` SET `content_loc2`='Fortress' WHERE `word_id` = 117270; -- locales_gameobject - name : entry=19271
UPDATE `trans_words` SET `content_loc2`='Fountain' WHERE `word_id` = 117462; -- locales_gameobject - name : entry=19507
UPDATE `trans_words` SET `content_loc2`='Fragile - Do Not Drop' WHERE `word_id` = 114488; -- locales_gameobject - name : entry=3768
UPDATE `trans_words` SET `content_loc2`='Franger Statue' WHERE `word_id` = 117463; -- locales_gameobject - name : entry=19508
UPDATE `trans_words` SET `content_loc2`='Fumper Trap' WHERE `word_id` = 120878; -- locales_gameobject - name : entry=185305
UPDATE `trans_words` SET `content_loc2`='Furbolg Cave' WHERE `word_id` = 117246; -- locales_gameobject - name : entry=19236
UPDATE `trans_words` SET `content_loc2`='G_Cage 02' WHERE `word_id` = 116080; -- locales_gameobject - name : entry=180040
UPDATE `trans_words` SET `content_loc2`='G_Cage 03' WHERE `word_id` = 116081; -- locales_gameobject - name : entry=180041
UPDATE `trans_words` SET `content_loc2`='G_CandyBucket_01' WHERE `word_id` = 116183; -- locales_gameobject - name : entry=180412
UPDATE `trans_words` SET `content_loc2`='G_Ghost_01' WHERE `word_id` = 116182; -- locales_gameobject - name : entry=180411
UPDATE `trans_words` SET `content_loc2`='G_HangingSkeleton_01' WHERE `word_id` = 116181; -- locales_gameobject - name : entry=180410
UPDATE `trans_words` SET `content_loc2`='G_Pumpkin_01 scale 4.0' WHERE `word_id` = 116196; -- locales_gameobject - name : entry=180431
UPDATE `trans_words` SET `content_loc2`='G_Pumpkin_01' WHERE `word_id` = 116176; -- locales_gameobject - name : entry=180405
UPDATE `trans_words` SET `content_loc2`='G_Pumpkin_02' WHERE `word_id` = 116177; -- locales_gameobject - name : entry=180406
UPDATE `trans_words` SET `content_loc2`='G_Pumpkin_03' WHERE `word_id` = 116178; -- locales_gameobject - name : entry=180407
UPDATE `trans_words` SET `content_loc2`='G_RuneBlue01' WHERE `word_id` = 116638; -- locales_gameobject - name : entry=182591
UPDATE `trans_words` SET `content_loc2`='G_WitchBroom_01 scale 0.5' WHERE `word_id` = 116193; -- locales_gameobject - name : entry=180428
UPDATE `trans_words` SET `content_loc2`='G_WitchBroom_01' WHERE `word_id` = 116180; -- locales_gameobject - name : entry=180409
UPDATE `trans_words` SET `content_loc2`='G_WitchHat_01 scale 0.5' WHERE `word_id` = 116194; -- locales_gameobject - name : entry=180429
UPDATE `trans_words` SET `content_loc2`='G_WitchHat_01' WHERE `word_id` = 116179; -- locales_gameobject - name : entry=180408
UPDATE `trans_words` SET `content_loc2`='Gadgetzan Auction' WHERE `word_id` = 115524; -- locales_gameobject - name : entry=175904
UPDATE `trans_words` SET `content_loc2`='Gadgetzan' WHERE `word_id` = 115104; -- locales_gameobject - name : entry=151974
UPDATE `trans_words` SET `content_loc2`='Garadar' WHERE `word_id` = 117782; -- locales_gameobject - name : entry=183205
UPDATE `trans_words` SET `content_loc2`='Gastric Exit' WHERE `word_id` = 116913; -- locales_gameobject - name : entry=210349
UPDATE `trans_words` SET `content_loc2`='Gate 1' WHERE `word_id` = 117049; -- locales_gameobject - name : entry=19026
UPDATE `trans_words` SET `content_loc2`='Gate Segment' WHERE `word_id` = 117403; -- locales_gameobject - name : entry=19439
UPDATE `trans_words` SET `content_loc2`='Gates of Grim Batol' WHERE `word_id` = 117343; -- locales_gameobject - name : entry=19369
UPDATE `trans_words` SET `content_loc2`='Gates of Zul\'Gurub' WHERE `word_id` = 116128; -- locales_gameobject - name : entry=180323
UPDATE `trans_words` SET `content_loc2`='Gem Rock' WHERE `word_id` = 117487; -- locales_gameobject - name : entry=19537
UPDATE `trans_words` SET `content_loc2`='General Outpost 2' WHERE `word_id` = 117506; -- locales_gameobject - name : entry=19621
UPDATE `trans_words` SET `content_loc2`='General Outpost' WHERE `word_id` = 117505; -- locales_gameobject - name : entry=19620
UPDATE `trans_words` SET `content_loc2`='General Turalyon' WHERE `word_id` = 114709; -- locales_gameobject - name : entry=25330
UPDATE `trans_words` SET `content_loc2`='Giant Moonwell' WHERE `word_id` = 117262; -- locales_gameobject - name : entry=19259
UPDATE `trans_words` SET `content_loc2`='Giant Sea Turtle' WHERE `word_id` = 114653; -- locales_gameobject - name : entry=20820
UPDATE `trans_words` SET `content_loc2`='Giant Totem' WHERE `word_id` = 117313; -- locales_gameobject - name : entry=19333
UPDATE `trans_words` SET `content_loc2`='Giant Turtle' WHERE `word_id` = 114654; -- locales_gameobject - name : entry=20821
UPDATE `trans_words` SET `content_loc2`='Gilneas' WHERE `word_id` = 114294; -- locales_gameobject - name : entry=1698
UPDATE `trans_words` SET `content_loc2`='Glyphed Crystal' WHERE `word_id` = 116904; -- locales_gameobject - name : entry=210337
UPDATE `trans_words` SET `content_loc2`='Gnomeragan Door' WHERE `word_id` = 117478; -- locales_gameobject - name : entry=19524
UPDATE `trans_words` SET `content_loc2`='Gnomeragan Instance' WHERE `word_id` = 117122; -- locales_gameobject - name : entry=19111
UPDATE `trans_words` SET `content_loc2`='Gnomeragan' WHERE `word_id` = 117121; -- locales_gameobject - name : entry=19110
UPDATE `trans_words` SET `content_loc2`='Gnomeregan' WHERE `word_id` = 114285; -- locales_gameobject - name : entry=1674
UPDATE `trans_words` SET `content_loc2`='Gnomes' WHERE `word_id` = 114760; -- locales_gameobject - name : entry=32419
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:103773' WHERE `word_id` = 117548; -- locales_gameobject - name : entry=103773
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:126337' WHERE `word_id` = 117549; -- locales_gameobject - name : entry=126337
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:126338' WHERE `word_id` = 117550; -- locales_gameobject - name : entry=126338
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:126339' WHERE `word_id` = 117551; -- locales_gameobject - name : entry=126339
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:126340' WHERE `word_id` = 117552; -- locales_gameobject - name : entry=126340
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:126341' WHERE `word_id` = 117553; -- locales_gameobject - name : entry=126341
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:126342' WHERE `word_id` = 117554; -- locales_gameobject - name : entry=126342
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:126345' WHERE `word_id` = 117555; -- locales_gameobject - name : entry=126345
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:174849' WHERE `word_id` = 117556; -- locales_gameobject - name : entry=174849
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:175432' WHERE `word_id` = 117557; -- locales_gameobject - name : entry=175432
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:175786' WHERE `word_id` = 117558; -- locales_gameobject - name : entry=175786
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:176157' WHERE `word_id` = 117559; -- locales_gameobject - name : entry=176157
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:177271' WHERE `word_id` = 117561; -- locales_gameobject - name : entry=177271
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:179874' WHERE `word_id` = 117562; -- locales_gameobject - name : entry=179874
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:179875' WHERE `word_id` = 117563; -- locales_gameobject - name : entry=179875
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:179876' WHERE `word_id` = 117564; -- locales_gameobject - name : entry=179876
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:179877' WHERE `word_id` = 117565; -- locales_gameobject - name : entry=179877
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:179878' WHERE `word_id` = 117566; -- locales_gameobject - name : entry=179878
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:18047' WHERE `word_id` = 117021; -- locales_gameobject - name : entry=18047
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:18048' WHERE `word_id` = 117022; -- locales_gameobject - name : entry=18048
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:18049' WHERE `word_id` = 117023; -- locales_gameobject - name : entry=18049
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:18050' WHERE `word_id` = 117024; -- locales_gameobject - name : entry=18050
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:18051' WHERE `word_id` = 117025; -- locales_gameobject - name : entry=18051
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:18052' WHERE `word_id` = 117026; -- locales_gameobject - name : entry=18052
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:18053' WHERE `word_id` = 117027; -- locales_gameobject - name : entry=18053
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:18054' WHERE `word_id` = 117028; -- locales_gameobject - name : entry=18054
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:18055' WHERE `word_id` = 117029; -- locales_gameobject - name : entry=18055
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:18056' WHERE `word_id` = 117030; -- locales_gameobject - name : entry=18056
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:18057' WHERE `word_id` = 117031; -- locales_gameobject - name : entry=18057
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:18058' WHERE `word_id` = 117032; -- locales_gameobject - name : entry=18058
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:18059' WHERE `word_id` = 117033; -- locales_gameobject - name : entry=18059
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:18060' WHERE `word_id` = 117034; -- locales_gameobject - name : entry=18060
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:18061' WHERE `word_id` = 117035; -- locales_gameobject - name : entry=18061
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:18062' WHERE `word_id` = 117036; -- locales_gameobject - name : entry=18062
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:183163' WHERE `word_id` = 117772; -- locales_gameobject - name : entry=183163
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:183497' WHERE `word_id` = 117825; -- locales_gameobject - name : entry=183497
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:183498' WHERE `word_id` = 117826; -- locales_gameobject - name : entry=183498
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:183499' WHERE `word_id` = 117827; -- locales_gameobject - name : entry=183499
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:183500' WHERE `word_id` = 117828; -- locales_gameobject - name : entry=183500
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:183501' WHERE `word_id` = 117829; -- locales_gameobject - name : entry=183501
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:183502' WHERE `word_id` = 117830; -- locales_gameobject - name : entry=183502
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184093' WHERE `word_id` = 117880; -- locales_gameobject - name : entry=184093
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184094' WHERE `word_id` = 117881; -- locales_gameobject - name : entry=184094
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184095' WHERE `word_id` = 117882; -- locales_gameobject - name : entry=184095
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184096' WHERE `word_id` = 117883; -- locales_gameobject - name : entry=184096
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184097' WHERE `word_id` = 117884; -- locales_gameobject - name : entry=184097
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184098' WHERE `word_id` = 117885; -- locales_gameobject - name : entry=184098
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184099' WHERE `word_id` = 117886; -- locales_gameobject - name : entry=184099
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184100' WHERE `word_id` = 117887; -- locales_gameobject - name : entry=184100
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184101' WHERE `word_id` = 117888; -- locales_gameobject - name : entry=184101
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184102' WHERE `word_id` = 117889; -- locales_gameobject - name : entry=184102
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184103' WHERE `word_id` = 117890; -- locales_gameobject - name : entry=184103
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184104' WHERE `word_id` = 117891; -- locales_gameobject - name : entry=184104
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184105' WHERE `word_id` = 117892; -- locales_gameobject - name : entry=184105
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184114' WHERE `word_id` = 117894; -- locales_gameobject - name : entry=184114
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184416' WHERE `word_id` = 117965; -- locales_gameobject - name : entry=184416
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184461' WHERE `word_id` = 117972; -- locales_gameobject - name : entry=184461
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184507' WHERE `word_id` = 117978; -- locales_gameobject - name : entry=184507
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184508' WHERE `word_id` = 117979; -- locales_gameobject - name : entry=184508
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184509' WHERE `word_id` = 117980; -- locales_gameobject - name : entry=184509
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184511' WHERE `word_id` = 117982; -- locales_gameobject - name : entry=184511
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184512' WHERE `word_id` = 117983; -- locales_gameobject - name : entry=184512
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184513' WHERE `word_id` = 117984; -- locales_gameobject - name : entry=184513
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184514' WHERE `word_id` = 117985; -- locales_gameobject - name : entry=184514
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184515' WHERE `word_id` = 117986; -- locales_gameobject - name : entry=184515
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184563' WHERE `word_id` = 117994; -- locales_gameobject - name : entry=184563
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184564' WHERE `word_id` = 117995; -- locales_gameobject - name : entry=184564
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184565' WHERE `word_id` = 117996; -- locales_gameobject - name : entry=184565
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184579' WHERE `word_id` = 118006; -- locales_gameobject - name : entry=184579
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184580' WHERE `word_id` = 118007; -- locales_gameobject - name : entry=184580
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184581' WHERE `word_id` = 118008; -- locales_gameobject - name : entry=184581
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184582' WHERE `word_id` = 118009; -- locales_gameobject - name : entry=184582
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184583' WHERE `word_id` = 118010; -- locales_gameobject - name : entry=184583
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184584' WHERE `word_id` = 118011; -- locales_gameobject - name : entry=184584
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:184585' WHERE `word_id` = 118012; -- locales_gameobject - name : entry=184585
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:185571' WHERE `word_id` = 118178; -- locales_gameobject - name : entry=185571
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:185572' WHERE `word_id` = 118179; -- locales_gameobject - name : entry=185572
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:185573' WHERE `word_id` = 118180; -- locales_gameobject - name : entry=185573
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:3265' WHERE `word_id` = 117018; -- locales_gameobject - name : entry=3265
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:56809' WHERE `word_id` = 117546; -- locales_gameobject - name : entry=56809
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:56810' WHERE `word_id` = 117547; -- locales_gameobject - name : entry=56810
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:6286' WHERE `word_id` = 117019; -- locales_gameobject - name : entry=6286
UPDATE `trans_words` SET `content_loc2`='GO Text Missing:6287' WHERE `word_id` = 117020; -- locales_gameobject - name : entry=6287
UPDATE `trans_words` SET `content_loc2`='Goblin Melting Pot' WHERE `word_id` = 117380; -- locales_gameobject - name : entry=19412
UPDATE `trans_words` SET `content_loc2`='Goblin Shredder Suit' WHERE `word_id` = 114603; -- locales_gameobject - name : entry=19582
UPDATE `trans_words` SET `content_loc2`='Goblin Statue' WHERE `word_id` = 117366; -- locales_gameobject - name : entry=19397
UPDATE `trans_words` SET `content_loc2`='Goldmine 2' WHERE `word_id` = 117177; -- locales_gameobject - name : entry=19167
UPDATE `trans_words` SET `content_loc2`='Goldmine 3' WHERE `word_id` = 117178; -- locales_gameobject - name : entry=19168
UPDATE `trans_words` SET `content_loc2`='Goldmine 4' WHERE `word_id` = 117179; -- locales_gameobject - name : entry=19169
UPDATE `trans_words` SET `content_loc2`='Goldmine 5' WHERE `word_id` = 117180; -- locales_gameobject - name : entry=19170
UPDATE `trans_words` SET `content_loc2`='Goldmine 6' WHERE `word_id` = 117181; -- locales_gameobject - name : entry=19171
UPDATE `trans_words` SET `content_loc2`='Goldmine 7' WHERE `word_id` = 117182; -- locales_gameobject - name : entry=19172
UPDATE `trans_words` SET `content_loc2`='Goldmine Small' WHERE `word_id` = 117176; -- locales_gameobject - name : entry=19166
UPDATE `trans_words` SET `content_loc2`='Gong of Bethekk' WHERE `word_id` = 116216; -- locales_gameobject - name : entry=180526
UPDATE `trans_words` SET `content_loc2`='Gong' WHERE `word_id` = 115075; -- locales_gameobject - name : entry=148917
UPDATE `trans_words` SET `content_loc2`='Gor	eshs Lopped Off Head' WHERE `word_id` = 268308; -- locales_gameobject - name : entry=160842
UPDATE `trans_words` SET `content_loc2`='Grand Widow Faerlina Door' WHERE `word_id` = 116442; -- locales_gameobject - name : entry=181167
UPDATE `trans_words` SET `content_loc2`='Grave Frame' WHERE `word_id` = 117401; -- locales_gameobject - name : entry=19437
UPDATE `trans_words` SET `content_loc2`='Grave' WHERE `word_id` = 116927; -- locales_gameobject - name : entry=211065
UPDATE `trans_words` SET `content_loc2`='Graveyard Banner' WHERE `word_id` = 114539; -- locales_gameobject - name : entry=13756
UPDATE `trans_words` SET `content_loc2`='Great Hall (Swamp of Sorrows)' WHERE `word_id` = 117274; -- locales_gameobject - name : entry=19275
UPDATE `trans_words` SET `content_loc2`='Great Hall' WHERE `word_id` = 117273; -- locales_gameobject - name : entry=19274
UPDATE `trans_words` SET `content_loc2`='Great Wall Portcullis' WHERE `word_id` = 117522; -- locales_gameobject - name : entry=19638
UPDATE `trans_words` SET `content_loc2`='Griffon Aviary' WHERE `word_id` = 117336; -- locales_gameobject - name : entry=19359
UPDATE `trans_words` SET `content_loc2`='Grim Batol' WHERE `word_id` = 114252; -- locales_gameobject - name : entry=381
UPDATE `trans_words` SET `content_loc2`='Grishnath' WHERE `word_id` = 117817; -- locales_gameobject - name : entry=183487
UPDATE `trans_words` SET `content_loc2`='Grom\'gol' WHERE `word_id` = 114451; -- locales_gameobject - name : entry=3202
UPDATE `trans_words` SET `content_loc2`='Guard Tower 2' WHERE `word_id` = 117411; -- locales_gameobject - name : entry=19449
UPDATE `trans_words` SET `content_loc2`='Guard Tower' WHERE `word_id` = 114649; -- locales_gameobject - name : entry=19256
UPDATE `trans_words` SET `content_loc2`='Halaa' WHERE `word_id` = 117777; -- locales_gameobject - name : entry=183199
UPDATE `trans_words` SET `content_loc2`='Hammer 2' WHERE `word_id` = 117531; -- locales_gameobject - name : entry=19648
UPDATE `trans_words` SET `content_loc2`='Hanging Body 2' WHERE `word_id` = 117383; -- locales_gameobject - name : entry=19415
UPDATE `trans_words` SET `content_loc2`='Hanging Body' WHERE `word_id` = 117382; -- locales_gameobject - name : entry=19414
UPDATE `trans_words` SET `content_loc2`='HangingSkullLight01' WHERE `word_id` = 116209; -- locales_gameobject - name : entry=180471
UPDATE `trans_words` SET `content_loc2`='HangingSkullLight02' WHERE `word_id` = 116210; -- locales_gameobject - name : entry=180472
UPDATE `trans_words` SET `content_loc2`='Hay Stack' WHERE `word_id` = 117394; -- locales_gameobject - name : entry=19429
UPDATE `trans_words` SET `content_loc2`='Hay Wagon' WHERE `word_id` = 117395; -- locales_gameobject - name : entry=19430
UPDATE `trans_words` SET `content_loc2`='Hearse' WHERE `word_id` = 117396; -- locales_gameobject - name : entry=19431
UPDATE `trans_words` SET `content_loc2`='Hive Arch' WHERE `word_id` = 117183; -- locales_gameobject - name : entry=19173
UPDATE `trans_words` SET `content_loc2`='Hive Fireflies 01' WHERE `word_id` = 116906; -- locales_gameobject - name : entry=210341
UPDATE `trans_words` SET `content_loc2`='Hive Piece (exterior)' WHERE `word_id` = 117184; -- locales_gameobject - name : entry=19174
UPDATE `trans_words` SET `content_loc2`='Hive Piece 2 (exterior)' WHERE `word_id` = 117185; -- locales_gameobject - name : entry=19175
UPDATE `trans_words` SET `content_loc2`='Hive Piece 3 (exterior)' WHERE `word_id` = 117186; -- locales_gameobject - name : entry=19176
UPDATE `trans_words` SET `content_loc2`='Hive Piece 4 (exterior)' WHERE `word_id` = 117187; -- locales_gameobject - name : entry=19177
UPDATE `trans_words` SET `content_loc2`='Hive Piece 5 (exterior)' WHERE `word_id` = 117188; -- locales_gameobject - name : entry=19178
UPDATE `trans_words` SET `content_loc2`='Holy Spring Well' WHERE `word_id` = 117441; -- locales_gameobject - name : entry=19483
UPDATE `trans_words` SET `content_loc2`='Hoofprints' WHERE `word_id` = 114667; -- locales_gameobject - name : entry=21015
UPDATE `trans_words` SET `content_loc2`='Horde Mine 2' WHERE `word_id` = 117200; -- locales_gameobject - name : entry=19190
UPDATE `trans_words` SET `content_loc2`='Horde Mine' WHERE `word_id` = 117199; -- locales_gameobject - name : entry=19189
UPDATE `trans_words` SET `content_loc2`='Horde Shrine' WHERE `word_id` = 117075; -- locales_gameobject - name : entry=19061
UPDATE `trans_words` SET `content_loc2`='HornCover' WHERE `word_id` = 114980; -- locales_gameobject - name : entry=138496
UPDATE `trans_words` SET `content_loc2`='House (Swamp of Sorrows)' WHERE `word_id` = 117281; -- locales_gameobject - name : entry=19287
UPDATE `trans_words` SET `content_loc2`='House Tower Small' WHERE `word_id` = 117285; -- locales_gameobject - name : entry=19292
UPDATE `trans_words` SET `content_loc2`='House' WHERE `word_id` = 117041; -- locales_gameobject - name : entry=19006
UPDATE `trans_words` SET `content_loc2`='Human Arrow' WHERE `word_id` = 117525; -- locales_gameobject - name : entry=19641
UPDATE `trans_words` SET `content_loc2`='Human Arrows' WHERE `word_id` = 117526; -- locales_gameobject - name : entry=19642
UPDATE `trans_words` SET `content_loc2`='Human Ballista' WHERE `word_id` = 117414; -- locales_gameobject - name : entry=19452
UPDATE `trans_words` SET `content_loc2`='Human Fountain' WHERE `word_id` = 117497; -- locales_gameobject - name : entry=19609
UPDATE `trans_words` SET `content_loc2`='Human PvP Barracks City' WHERE `word_id` = 117064; -- locales_gameobject - name : entry=19048
UPDATE `trans_words` SET `content_loc2`='Human Sign Post' WHERE `word_id` = 117511; -- locales_gameobject - name : entry=19626
UPDATE `trans_words` SET `content_loc2`='Human Statue' WHERE `word_id` = 117474; -- locales_gameobject - name : entry=19519
UPDATE `trans_words` SET `content_loc2`='Human Vendor Tent' WHERE `word_id` = 117521; -- locales_gameobject - name : entry=19637
UPDATE `trans_words` SET `content_loc2`='Hunter Tent' WHERE `word_id` = 117288; -- locales_gameobject - name : entry=19295
UPDATE `trans_words` SET `content_loc2`='Hut 2' WHERE `word_id` = 117048; -- locales_gameobject - name : entry=19014
UPDATE `trans_words` SET `content_loc2`='Hut Big' WHERE `word_id` = 117289; -- locales_gameobject - name : entry=19296
UPDATE `trans_words` SET `content_loc2`='Hut' WHERE `word_id` = 117047; -- locales_gameobject - name : entry=19013
UPDATE `trans_words` SET `content_loc2`='Ice Cave 2' WHERE `word_id` = 117203; -- locales_gameobject - name : entry=19193
UPDATE `trans_words` SET `content_loc2`='Ice Cave 3' WHERE `word_id` = 117204; -- locales_gameobject - name : entry=19194
UPDATE `trans_words` SET `content_loc2`='Ice Cave 4' WHERE `word_id` = 117205; -- locales_gameobject - name : entry=19195
UPDATE `trans_words` SET `content_loc2`='Ice Cave Medium' WHERE `word_id` = 117202; -- locales_gameobject - name : entry=19192
UPDATE `trans_words` SET `content_loc2`='Ice Cave' WHERE `word_id` = 117201; -- locales_gameobject - name : entry=19191
UPDATE `trans_words` SET `content_loc2`='Ice Den' WHERE `word_id` = 117149; -- locales_gameobject - name : entry=19139
UPDATE `trans_words` SET `content_loc2`='Igloo 2' WHERE `word_id` = 117252; -- locales_gameobject - name : entry=19244
UPDATE `trans_words` SET `content_loc2`='Igloo 3' WHERE `word_id` = 117253; -- locales_gameobject - name : entry=19245
UPDATE `trans_words` SET `content_loc2`='Igloo 4' WHERE `word_id` = 117254; -- locales_gameobject - name : entry=19246
UPDATE `trans_words` SET `content_loc2`='Igloo' WHERE `word_id` = 117251; -- locales_gameobject - name : entry=19243
UPDATE `trans_words` SET `content_loc2`='Incantion of Celebras Trap' WHERE `word_id` = 120868; -- locales_gameobject - name : entry=178963
UPDATE `trans_words` SET `content_loc2`='Industrial District' WHERE `word_id` = 114713; -- locales_gameobject - name : entry=25334
UPDATE `trans_words` SET `content_loc2`='Infernal' WHERE `word_id` = 72332; -- locales_gameobject - name : entry=184834
UPDATE `trans_words` SET `content_loc2`='Inferno' WHERE `word_id` = 115769; -- locales_gameobject - name : entry=177764
UPDATE `trans_words` SET `content_loc2`='Inn (snow)' WHERE `word_id` = 117337; -- locales_gameobject - name : entry=19361
UPDATE `trans_words` SET `content_loc2`='Instance Portal Green' WHERE `word_id` = 117482; -- locales_gameobject - name : entry=19528
UPDATE `trans_words` SET `content_loc2`='Instance Portal Red' WHERE `word_id` = 117483; -- locales_gameobject - name : entry=19529
UPDATE `trans_words` SET `content_loc2`='Instance Portal' WHERE `word_id` = 117481; -- locales_gameobject - name : entry=19527
UPDATE `trans_words` SET `content_loc2`='Instance Portal White' WHERE `word_id` = 117484; -- locales_gameobject - name : entry=19530
UPDATE `trans_words` SET `content_loc2`='Instance_Portal_Difficulty_0' WHERE `word_id` = 117920; -- locales_gameobject - name : entry=184190
UPDATE `trans_words` SET `content_loc2`='Instance_Portal_Difficulty_1' WHERE `word_id` = 117919; -- locales_gameobject - name : entry=184189
UPDATE `trans_words` SET `content_loc2`='InstancePortal_01_Difficulty_0' WHERE `word_id` = 117918; -- locales_gameobject - name : entry=184188
UPDATE `trans_words` SET `content_loc2`='InstancePortal_01_Difficulty_1' WHERE `word_id` = 117917; -- locales_gameobject - name : entry=184187
UPDATE `trans_words` SET `content_loc2`='InstancePortal_02_Difficulty_0' WHERE `word_id` = 117915; -- locales_gameobject - name : entry=184185
UPDATE `trans_words` SET `content_loc2`='InstancePortal_02_Difficulty_1' WHERE `word_id` = 117916; -- locales_gameobject - name : entry=184186
UPDATE `trans_words` SET `content_loc2`='InstancePortal_03_Difficulty_0' WHERE `word_id` = 117911; -- locales_gameobject - name : entry=184181
UPDATE `trans_words` SET `content_loc2`='InstancePortal_03_Difficulty_1' WHERE `word_id` = 117912; -- locales_gameobject - name : entry=184182
UPDATE `trans_words` SET `content_loc2`='InstancePortal_04_Difficulty_0' WHERE `word_id` = 117913; -- locales_gameobject - name : entry=184183
UPDATE `trans_words` SET `content_loc2`='InstancePortal_04_Difficulty_1' WHERE `word_id` = 117914; -- locales_gameobject - name : entry=184184
UPDATE `trans_words` SET `content_loc2`='Iron Maiden' WHERE `word_id` = 117518; -- locales_gameobject - name : entry=19634
UPDATE `trans_words` SET `content_loc2`='Ironfoot Bridge' WHERE `word_id` = 117076; -- locales_gameobject - name : entry=19062
UPDATE `trans_words` SET `content_loc2`='IronForge Elevator' WHERE `word_id` = 114740; -- locales_gameobject - name : entry=32056
UPDATE `trans_words` SET `content_loc2`='Jaedenar' WHERE `word_id` = 115671; -- locales_gameobject - name : entry=177105
UPDATE `trans_words` SET `content_loc2`='Jungle Cave 2' WHERE `word_id` = 117209; -- locales_gameobject - name : entry=19199
UPDATE `trans_words` SET `content_loc2`='Jungle Cave Crystal' WHERE `word_id` = 117207; -- locales_gameobject - name : entry=19197
UPDATE `trans_words` SET `content_loc2`='Jungle Cave Medium' WHERE `word_id` = 117208; -- locales_gameobject - name : entry=19198
UPDATE `trans_words` SET `content_loc2`='Jungle Cave' WHERE `word_id` = 117206; -- locales_gameobject - name : entry=19196
UPDATE `trans_words` SET `content_loc2`='Jungle Den' WHERE `word_id` = 117150; -- locales_gameobject - name : entry=19140
UPDATE `trans_words` SET `content_loc2`='Kaldorei Tome of Summoning' WHERE `word_id` = 115100; -- locales_gameobject - name : entry=151286
UPDATE `trans_words` SET `content_loc2`='Karazahn Chandelier' WHERE `word_id` = 117424; -- locales_gameobject - name : entry=19466
UPDATE `trans_words` SET `content_loc2`='Karazahn Pedestal 2' WHERE `word_id` = 117426; -- locales_gameobject - name : entry=19468
UPDATE `trans_words` SET `content_loc2`='Karazahn Pedestal' WHERE `word_id` = 117425; -- locales_gameobject - name : entry=19467
UPDATE `trans_words` SET `content_loc2`='Karazahn Portcullis' WHERE `word_id` = 117423; -- locales_gameobject - name : entry=19465
UPDATE `trans_words` SET `content_loc2`='Karazahn Sconce 2' WHERE `word_id` = 117428; -- locales_gameobject - name : entry=19470
UPDATE `trans_words` SET `content_loc2`='Karazahn Sconce 3' WHERE `word_id` = 117429; -- locales_gameobject - name : entry=19471
UPDATE `trans_words` SET `content_loc2`='Karazahn Sconce 4' WHERE `word_id` = 117430; -- locales_gameobject - name : entry=19472
UPDATE `trans_words` SET `content_loc2`='Karazahn Sconce 5' WHERE `word_id` = 117431; -- locales_gameobject - name : entry=19473
UPDATE `trans_words` SET `content_loc2`='Karazahn Sconce 6' WHERE `word_id` = 117432; -- locales_gameobject - name : entry=19474
UPDATE `trans_words` SET `content_loc2`='Karazahn Sconce 7' WHERE `word_id` = 117433; -- locales_gameobject - name : entry=19475
UPDATE `trans_words` SET `content_loc2`='Karazahn Sconce' WHERE `word_id` = 117427; -- locales_gameobject - name : entry=19469
UPDATE `trans_words` SET `content_loc2`='Karazahn Starlab' WHERE `word_id` = 117434; -- locales_gameobject - name : entry=19476
UPDATE `trans_words` SET `content_loc2`='Karazahn Table' WHERE `word_id` = 117435; -- locales_gameobject - name : entry=19477
UPDATE `trans_words` SET `content_loc2`='Karazahn Throne' WHERE `word_id` = 117436; -- locales_gameobject - name : entry=19478
UPDATE `trans_words` SET `content_loc2`='Karazhan Future Tower Instance' WHERE `word_id` = 117089; -- locales_gameobject - name : entry=19076
UPDATE `trans_words` SET `content_loc2`='Kel\'Theril' WHERE `word_id` = 115678; -- locales_gameobject - name : entry=177131
UPDATE `trans_words` SET `content_loc2`='Kennel (Swamp of Sorrows)' WHERE `word_id` = 117278; -- locales_gameobject - name : entry=19281
UPDATE `trans_words` SET `content_loc2`='Kennel' WHERE `word_id` = 117277; -- locales_gameobject - name : entry=19280
UPDATE `trans_words` SET `content_loc2`='Khadgar Statue' WHERE `word_id` = 117514; -- locales_gameobject - name : entry=19629
UPDATE `trans_words` SET `content_loc2`='Kharanos' WHERE `word_id` = 114246; -- locales_gameobject - name : entry=1566
UPDATE `trans_words` SET `content_loc2`='Kharazan Actual Tower (no instance)' WHERE `word_id` = 117090; -- locales_gameobject - name : entry=19077
UPDATE `trans_words` SET `content_loc2`='Kodo Bones Trap' WHERE `word_id` = 120861; -- locales_gameobject - name : entry=176750
UPDATE `trans_words` SET `content_loc2`='Kre\'tal\'s Wagon' WHERE `word_id` = 116914; -- locales_gameobject - name : entry=211017
UPDATE `trans_words` SET `content_loc2`='Kurdran Statue' WHERE `word_id` = 117515; -- locales_gameobject - name : entry=19630
UPDATE `trans_words` SET `content_loc2`='L70ETC Music Doodad' WHERE `word_id` = 116846; -- locales_gameobject - name : entry=186312
UPDATE `trans_words` SET `content_loc2`='Laboratory' WHERE `word_id` = 117259; -- locales_gameobject - name : entry=19251
UPDATE `trans_words` SET `content_loc2`='Lair Exit' WHERE `word_id` = 116921; -- locales_gameobject - name : entry=211035
UPDATE `trans_words` SET `content_loc2`='Large Tunnel' WHERE `word_id` = 117169; -- locales_gameobject - name : entry=19159
UPDATE `trans_words` SET `content_loc2`='Lava Altar' WHERE `word_id` = 117374; -- locales_gameobject - name : entry=19405
UPDATE `trans_words` SET `content_loc2`='Lava Bridge' WHERE `word_id` = 117375; -- locales_gameobject - name : entry=19406
UPDATE `trans_words` SET `content_loc2`='Lava Plug 2' WHERE `word_id` = 117377; -- locales_gameobject - name : entry=19408
UPDATE `trans_words` SET `content_loc2`='Lava Plug' WHERE `word_id` = 117376; -- locales_gameobject - name : entry=19407
UPDATE `trans_words` SET `content_loc2`='Lava Shrine' WHERE `word_id` = 117378; -- locales_gameobject - name : entry=19409
UPDATE `trans_words` SET `content_loc2`='Lianthes Strongbox' WHERE `word_id` = 268310; -- locales_gameobject - name : entry=185297
UPDATE `trans_words` SET `content_loc2`='Lion Statue' WHERE `word_id` = 117420; -- locales_gameobject - name : entry=19460
UPDATE `trans_words` SET `content_loc2`='Loch Modan' WHERE `word_id` = 114245; -- locales_gameobject - name : entry=1565
UPDATE `trans_words` SET `content_loc2`='Longhouse' WHERE `word_id` = 117291; -- locales_gameobject - name : entry=19301
UPDATE `trans_words` SET `content_loc2`='Lordaeron Walls' WHERE `word_id` = 117355; -- locales_gameobject - name : entry=19384
UPDATE `trans_words` SET `content_loc2`='Lothar Statue' WHERE `word_id` = 117379; -- locales_gameobject - name : entry=19410
UPDATE `trans_words` SET `content_loc2`='Lower Mesa 2' WHERE `word_id` = 117315; -- locales_gameobject - name : entry=19335
UPDATE `trans_words` SET `content_loc2`='Lower Mesa 3' WHERE `word_id` = 117316; -- locales_gameobject - name : entry=19336
UPDATE `trans_words` SET `content_loc2`='Lower Mesa 4' WHERE `word_id` = 117317; -- locales_gameobject - name : entry=19337
UPDATE `trans_words` SET `content_loc2`='Lower Mesa 5' WHERE `word_id` = 117318; -- locales_gameobject - name : entry=19338
UPDATE `trans_words` SET `content_loc2`='Lower Mesa 6' WHERE `word_id` = 117319; -- locales_gameobject - name : entry=19339
UPDATE `trans_words` SET `content_loc2`='Lower Mesa' WHERE `word_id` = 117314; -- locales_gameobject - name : entry=19334
UPDATE `trans_words` SET `content_loc2`='Mace 2' WHERE `word_id` = 117532; -- locales_gameobject - name : entry=19650
UPDATE `trans_words` SET `content_loc2`='Mage Portal' WHERE `word_id` = 117485; -- locales_gameobject - name : entry=19531
UPDATE `trans_words` SET `content_loc2`='Mage Quarters' WHERE `word_id` = 114373; -- locales_gameobject - name : entry=2188
UPDATE `trans_words` SET `content_loc2`='Mage Statue' WHERE `word_id` = 117464; -- locales_gameobject - name : entry=19509
UPDATE `trans_words` SET `content_loc2`='Magus Rimtori\'s Journal' WHERE `word_id` = 115110; -- locales_gameobject - name : entry=152098
UPDATE `trans_words` SET `content_loc2`='Manaforge Ara' WHERE `word_id` = 117942; -- locales_gameobject - name : entry=184292
UPDATE `trans_words` SET `content_loc2`='Manaforge B\'naar' WHERE `word_id` = 117907; -- locales_gameobject - name : entry=184154
UPDATE `trans_words` SET `content_loc2`='Manaforge Coruu' WHERE `word_id` = 117928; -- locales_gameobject - name : entry=184258
UPDATE `trans_words` SET `content_loc2`='Manaforge Duro' WHERE `word_id` = 117990; -- locales_gameobject - name : entry=184542
UPDATE `trans_words` SET `content_loc2`='Manaforge Ultris' WHERE `word_id` = 117960; -- locales_gameobject - name : entry=184403
UPDATE `trans_words` SET `content_loc2`='Maraudon Intance' WHERE `word_id` = 117110; -- locales_gameobject - name : entry=19098
UPDATE `trans_words` SET `content_loc2`='Maraudon' WHERE `word_id` = 117109; -- locales_gameobject - name : entry=19097
UPDATE `trans_words` SET `content_loc2`='Mathystra' WHERE `word_id` = 114533; -- locales_gameobject - name : entry=12903
UPDATE `trans_words` SET `content_loc2`='Mausoleum' WHERE `word_id` = 117404; -- locales_gameobject - name : entry=19440
UPDATE `trans_words` SET `content_loc2`='Medium Tunnel (Snow)' WHERE `word_id` = 117171; -- locales_gameobject - name : entry=19161
UPDATE `trans_words` SET `content_loc2`='Medium Tunnel' WHERE `word_id` = 117170; -- locales_gameobject - name : entry=19160
UPDATE `trans_words` SET `content_loc2`='Meeting Stone 2' WHERE `word_id` = 117486; -- locales_gameobject - name : entry=19533
UPDATE `trans_words` SET `content_loc2`='Meetingstone01' WHERE `word_id` = 115997; -- locales_gameobject - name : entry=179597
UPDATE `trans_words` SET `content_loc2`='Menethil' WHERE `word_id` = 114251; -- locales_gameobject - name : entry=377
UPDATE `trans_words` SET `content_loc2`='Mephistroph\'s HellFire' WHERE `word_id` = 116929; -- locales_gameobject - name : entry=211084
UPDATE `trans_words` SET `content_loc2`='Mid Mesa 2' WHERE `word_id` = 117321; -- locales_gameobject - name : entry=19341
UPDATE `trans_words` SET `content_loc2`='Mid Mesa 3' WHERE `word_id` = 117322; -- locales_gameobject - name : entry=19342
UPDATE `trans_words` SET `content_loc2`='Mid Mesa 4' WHERE `word_id` = 117323; -- locales_gameobject - name : entry=19343
UPDATE `trans_words` SET `content_loc2`='Mid Mesa' WHERE `word_id` = 117320; -- locales_gameobject - name : entry=19340
UPDATE `trans_words` SET `content_loc2`='Midsummer Bonfire Spawn Trap' WHERE `word_id` = 120872; -- locales_gameobject - name : entry=181290
UPDATE `trans_words` SET `content_loc2`='Mini-Hive 1' WHERE `word_id` = 117189; -- locales_gameobject - name : entry=19179
UPDATE `trans_words` SET `content_loc2`='Mini-Hive 2' WHERE `word_id` = 117190; -- locales_gameobject - name : entry=19180
UPDATE `trans_words` SET `content_loc2`='Mini-Hive 3 Albino' WHERE `word_id` = 117192; -- locales_gameobject - name : entry=19182
UPDATE `trans_words` SET `content_loc2`='Mini-Hive 3' WHERE `word_id` = 117191; -- locales_gameobject - name : entry=19181
UPDATE `trans_words` SET `content_loc2`='Mini-Hive 4 Albino' WHERE `word_id` = 117194; -- locales_gameobject - name : entry=19184
UPDATE `trans_words` SET `content_loc2`='Mini-Hive 4' WHERE `word_id` = 117193; -- locales_gameobject - name : entry=19183
UPDATE `trans_words` SET `content_loc2`='Mini-Hive 5 Albino' WHERE `word_id` = 117196; -- locales_gameobject - name : entry=19186
UPDATE `trans_words` SET `content_loc2`='Mini-Hive 5' WHERE `word_id` = 117195; -- locales_gameobject - name : entry=19185
UPDATE `trans_words` SET `content_loc2`='Mini-Hive 6 Albino' WHERE `word_id` = 117198; -- locales_gameobject - name : entry=19188
UPDATE `trans_words` SET `content_loc2`='Mini-Hive 6' WHERE `word_id` = 117197; -- locales_gameobject - name : entry=19187
UPDATE `trans_words` SET `content_loc2`='Monestary Cathedral' WHERE `word_id` = 117131; -- locales_gameobject - name : entry=19120
UPDATE `trans_words` SET `content_loc2`='Monestary Cementery' WHERE `word_id` = 117132; -- locales_gameobject - name : entry=19121
UPDATE `trans_words` SET `content_loc2`='Monestary Library' WHERE `word_id` = 117133; -- locales_gameobject - name : entry=19122
UPDATE `trans_words` SET `content_loc2`='Monestary Secret Door' WHERE `word_id` = 117489; -- locales_gameobject - name : entry=19588
UPDATE `trans_words` SET `content_loc2`='Monestary War' WHERE `word_id` = 117134; -- locales_gameobject - name : entry=19123
UPDATE `trans_words` SET `content_loc2`='Monster Machine' WHERE `word_id` = 117305; -- locales_gameobject - name : entry=19322
UPDATE `trans_words` SET `content_loc2`='Moon Well 2' WHERE `word_id` = 114652; -- locales_gameobject - name : entry=20819
UPDATE `trans_words` SET `content_loc2`='Mortar Shell' WHERE `word_id` = 117502; -- locales_gameobject - name : entry=19616
UPDATE `trans_words` SET `content_loc2`='Mound of loose dirt' WHERE `word_id` = 114200; -- locales_gameobject - name : entry=59
UPDATE `trans_words` SET `content_loc2`='Mountain Cave Medium 2' WHERE `word_id` = 117211; -- locales_gameobject - name : entry=19201
UPDATE `trans_words` SET `content_loc2`='Mountain Cave Medium 3' WHERE `word_id` = 117212; -- locales_gameobject - name : entry=19202
UPDATE `trans_words` SET `content_loc2`='Mountain Cave Medium 4' WHERE `word_id` = 117213; -- locales_gameobject - name : entry=19203
UPDATE `trans_words` SET `content_loc2`='Mountain Cave Medium 5' WHERE `word_id` = 117214; -- locales_gameobject - name : entry=19204
UPDATE `trans_words` SET `content_loc2`='Mountain Cave Medium 6' WHERE `word_id` = 117215; -- locales_gameobject - name : entry=19205
UPDATE `trans_words` SET `content_loc2`='Mountain Cave Medium 7' WHERE `word_id` = 117216; -- locales_gameobject - name : entry=19206
UPDATE `trans_words` SET `content_loc2`='Mountain Cave Medium 8' WHERE `word_id` = 117217; -- locales_gameobject - name : entry=19207
UPDATE `trans_words` SET `content_loc2`='Mountain Cave Medium' WHERE `word_id` = 117210; -- locales_gameobject - name : entry=19200
UPDATE `trans_words` SET `content_loc2`='Mountain King Statue' WHERE `word_id` = 117461; -- locales_gameobject - name : entry=19506
UPDATE `trans_words` SET `content_loc2`='Mulgore' WHERE `word_id` = 114498; -- locales_gameobject - name : entry=18033
UPDATE `trans_words` SET `content_loc2`='Mushroom Cave 10' WHERE `word_id` = 117227; -- locales_gameobject - name : entry=19217
UPDATE `trans_words` SET `content_loc2`='Mushroom Cave 2' WHERE `word_id` = 117219; -- locales_gameobject - name : entry=19209
UPDATE `trans_words` SET `content_loc2`='Mushroom Cave 3' WHERE `word_id` = 117220; -- locales_gameobject - name : entry=19210
UPDATE `trans_words` SET `content_loc2`='Mushroom Cave 4' WHERE `word_id` = 117221; -- locales_gameobject - name : entry=19211
UPDATE `trans_words` SET `content_loc2`='Mushroom Cave 5' WHERE `word_id` = 117222; -- locales_gameobject - name : entry=19212
UPDATE `trans_words` SET `content_loc2`='Mushroom Cave 6' WHERE `word_id` = 117223; -- locales_gameobject - name : entry=19213
UPDATE `trans_words` SET `content_loc2`='Mushroom Cave 7' WHERE `word_id` = 117224; -- locales_gameobject - name : entry=19214
UPDATE `trans_words` SET `content_loc2`='Mushroom Cave 8' WHERE `word_id` = 117225; -- locales_gameobject - name : entry=19215
UPDATE `trans_words` SET `content_loc2`='Mushroom Cave 9' WHERE `word_id` = 117226; -- locales_gameobject - name : entry=19216
UPDATE `trans_words` SET `content_loc2`='Mushroom Cave' WHERE `word_id` = 117218; -- locales_gameobject - name : entry=19208
UPDATE `trans_words` SET `content_loc2`='Mushroom Den' WHERE `word_id` = 117151; -- locales_gameobject - name : entry=19141
UPDATE `trans_words` SET `content_loc2`='Mysterious Monument' WHERE `word_id` = 116924; -- locales_gameobject - name : entry=211053
UPDATE `trans_words` SET `content_loc2`='Naga Brazier (trap) (DND)' WHERE `word_id` = 120865; -- locales_gameobject - name : entry=178248
UPDATE `trans_words` SET `content_loc2`='Naga Pagoda' WHERE `word_id` = 117260; -- locales_gameobject - name : entry=19252
UPDATE `trans_words` SET `content_loc2`='Nagrand' WHERE `word_id` = 117709; -- locales_gameobject - name : entry=182283
UPDATE `trans_words` SET `content_loc2`='Naxx Teleporter trap' WHERE `word_id` = 268306; -- locales_gameobject - name : entry=129
UPDATE `trans_words` SET `content_loc2`='Naxxramas' WHERE `word_id` = 116405; -- locales_gameobject - name : entry=181056
UPDATE `trans_words` SET `content_loc2`='Necropolis critter spawner' WHERE `word_id` = 120871; -- locales_gameobject - name : entry=181214
UPDATE `trans_words` SET `content_loc2`='Nefarian\'s Balcony' WHERE `word_id` = 117084; -- locales_gameobject - name : entry=19071
UPDATE `trans_words` SET `content_loc2`='Netherguard Walls' WHERE `word_id` = 117346; -- locales_gameobject - name : entry=19374
UPDATE `trans_words` SET `content_loc2`='New Year Alliance Hanging Banner 02' WHERE `word_id` = 116895; -- locales_gameobject - name : entry=210211
UPDATE `trans_words` SET `content_loc2`='New Year Alliance Hanging Banner' WHERE `word_id` = 116894; -- locales_gameobject - name : entry=210210
UPDATE `trans_words` SET `content_loc2`='New Year Alliance Standing Banner' WHERE `word_id` = 116898; -- locales_gameobject - name : entry=210214
UPDATE `trans_words` SET `content_loc2`='New Year Horde Hanging Banner 02' WHERE `word_id` = 116897; -- locales_gameobject - name : entry=210213
UPDATE `trans_words` SET `content_loc2`='New Year Horde Hanging Banner' WHERE `word_id` = 116896; -- locales_gameobject - name : entry=210212
UPDATE `trans_words` SET `content_loc2`='New Year Horde Standing Banner' WHERE `word_id` = 116899; -- locales_gameobject - name : entry=210215
UPDATE `trans_words` SET `content_loc2`='Night Elf Moon Well' WHERE `word_id` = 114651; -- locales_gameobject - name : entry=20818
UPDATE `trans_words` SET `content_loc2`='Night Elf Owl Banner' WHERE `word_id` = 117544; -- locales_gameobject - name : entry=19664
UPDATE `trans_words` SET `content_loc2`='Night Elf Tree Banner' WHERE `word_id` = 117545; -- locales_gameobject - name : entry=19665
UPDATE `trans_words` SET `content_loc2`='Observatory (snow)' WHERE `word_id` = 117250; -- locales_gameobject - name : entry=19242
UPDATE `trans_words` SET `content_loc2`='Oeuf d\'Aile-furie' WHERE `word_id` = 118228; -- locales_gameobject - name : entry=185937
UPDATE `trans_words` SET `content_loc2`='Oeuf d\'Insidion' WHERE `word_id` = 118229; -- locales_gameobject - name : entry=185938
UPDATE `trans_words` SET `content_loc2`='Ogremound 2' WHERE `word_id` = 117232; -- locales_gameobject - name : entry=19222
UPDATE `trans_words` SET `content_loc2`='Ogremound 3' WHERE `word_id` = 117233; -- locales_gameobject - name : entry=19223
UPDATE `trans_words` SET `content_loc2`='Ogremound 4' WHERE `word_id` = 117234; -- locales_gameobject - name : entry=19224
UPDATE `trans_words` SET `content_loc2`='Ogremound 5' WHERE `word_id` = 117235; -- locales_gameobject - name : entry=19225
UPDATE `trans_words` SET `content_loc2`='Ogremound 6' WHERE `word_id` = 117237; -- locales_gameobject - name : entry=19227
UPDATE `trans_words` SET `content_loc2`='Ogremound 7' WHERE `word_id` = 117238; -- locales_gameobject - name : entry=19228
UPDATE `trans_words` SET `content_loc2`='Ogremound 8' WHERE `word_id` = 117239; -- locales_gameobject - name : entry=19229
UPDATE `trans_words` SET `content_loc2`='Ogremound 9' WHERE `word_id` = 117388; -- locales_gameobject - name : entry=19420
UPDATE `trans_words` SET `content_loc2`='Ogremound Medium' WHERE `word_id` = 117236; -- locales_gameobject - name : entry=19226
UPDATE `trans_words` SET `content_loc2`='Ogremound' WHERE `word_id` = 117231; -- locales_gameobject - name : entry=19221
UPDATE `trans_words` SET `content_loc2`='Oil Plataform' WHERE `word_id` = 117056; -- locales_gameobject - name : entry=19040
UPDATE `trans_words` SET `content_loc2`='Old Blackfathom Facade' WHERE `word_id` = 117106; -- locales_gameobject - name : entry=19093
UPDATE `trans_words` SET `content_loc2`='Onyxia\'s Lair Piece' WHERE `word_id` = 117112; -- locales_gameobject - name : entry=19100
UPDATE `trans_words` SET `content_loc2`='Orc Catapult' WHERE `word_id` = 117415; -- locales_gameobject - name : entry=19453
UPDATE `trans_words` SET `content_loc2`='Orc Pvp Barracks City' WHERE `word_id` = 117308; -- locales_gameobject - name : entry=19327
UPDATE `trans_words` SET `content_loc2`='Orc Tower' WHERE `word_id` = 114648; -- locales_gameobject - name : entry=20812
UPDATE `trans_words` SET `content_loc2`='Orgrimmar City' WHERE `word_id` = 117309; -- locales_gameobject - name : entry=19328
UPDATE `trans_words` SET `content_loc2`='Orgrimmar' WHERE `word_id` = 114455; -- locales_gameobject - name : entry=3226
UPDATE `trans_words` SET `content_loc2`='OUT OF ORDER! Use Postman instead - your GM\'s' WHERE `word_id` = 116053; -- locales_gameobject - name : entry=179963
UPDATE `trans_words` SET `content_loc2`='Outpost' WHERE `word_id` = 117263; -- locales_gameobject - name : entry=19261
UPDATE `trans_words` SET `content_loc2`='Paladin Statue' WHERE `word_id` = 117475; -- locales_gameobject - name : entry=19520
UPDATE `trans_words` SET `content_loc2`='Pick Axe' WHERE `word_id` = 117523; -- locales_gameobject - name : entry=19639
UPDATE `trans_words` SET `content_loc2`='Pillar of Amethyst' WHERE `word_id` = 114427; -- locales_gameobject - name : entry=2858
UPDATE `trans_words` SET `content_loc2`='Pillar of Diamond' WHERE `word_id` = 114423; -- locales_gameobject - name : entry=2842
UPDATE `trans_words` SET `content_loc2`='Pillar of Opal' WHERE `word_id` = 114425; -- locales_gameobject - name : entry=2848
UPDATE `trans_words` SET `content_loc2`='Pirate Ship 2' WHERE `word_id` = 117241; -- locales_gameobject - name : entry=19231
UPDATE `trans_words` SET `content_loc2`='Pirate Ship' WHERE `word_id` = 117240; -- locales_gameobject - name : entry=19230
UPDATE `trans_words` SET `content_loc2`='Pithwick\'s Bags and Supplies' WHERE `word_id` = 114724; -- locales_gameobject - name : entry=26491
UPDATE `trans_words` SET `content_loc2`='Plagued Fountain' WHERE `word_id` = 117495; -- locales_gameobject - name : entry=19607
UPDATE `trans_words` SET `content_loc2`='Player Housing' WHERE `word_id` = 114656; -- locales_gameobject - name : entry=20823
UPDATE `trans_words` SET `content_loc2`='Portal Gate' WHERE `word_id` = 117409; -- locales_gameobject - name : entry=19446
UPDATE `trans_words` SET `content_loc2`='Portcullis Active' WHERE `word_id` = 117490; -- locales_gameobject - name : entry=19589
UPDATE `trans_words` SET `content_loc2`='Postbox' WHERE `word_id` = 115449; -- locales_gameobject - name : entry=175668
UPDATE `trans_words` SET `content_loc2`='Priest Statue' WHERE `word_id` = 117476; -- locales_gameobject - name : entry=19521
UPDATE `trans_words` SET `content_loc2`='Prison Cage 1' WHERE `word_id` = 117059; -- locales_gameobject - name : entry=19043
UPDATE `trans_words` SET `content_loc2`='Prison Cage 2 (with tunnel)' WHERE `word_id` = 117060; -- locales_gameobject - name : entry=19044
UPDATE `trans_words` SET `content_loc2`='Prison Cage 3 (with tunnel)' WHERE `word_id` = 117061; -- locales_gameobject - name : entry=19045
UPDATE `trans_words` SET `content_loc2`='Prison Cage 4 (with tunnel)' WHERE `word_id` = 117062; -- locales_gameobject - name : entry=19046
UPDATE `trans_words` SET `content_loc2`='Prison Cell' WHERE `word_id` = 117542; -- locales_gameobject - name : entry=19662
UPDATE `trans_words` SET `content_loc2`='Prison Headquarters' WHERE `word_id` = 117057; -- locales_gameobject - name : entry=19041
UPDATE `trans_words` SET `content_loc2`='Prison House' WHERE `word_id` = 117058; -- locales_gameobject - name : entry=19042
UPDATE `trans_words` SET `content_loc2`='PVP HOLIDAY GENERIC SIGNPOST' WHERE `word_id` = 116168; -- locales_gameobject - name : entry=180397
UPDATE `trans_words` SET `content_loc2`='PvP Wall 2' WHERE `word_id` = 117362; -- locales_gameobject - name : entry=19393
UPDATE `trans_words` SET `content_loc2`='PvP Wall 3' WHERE `word_id` = 117363; -- locales_gameobject - name : entry=19394
UPDATE `trans_words` SET `content_loc2`='PvP Wall' WHERE `word_id` = 117310; -- locales_gameobject - name : entry=19329
UPDATE `trans_words` SET `content_loc2`='Quel\'Thalas' WHERE `word_id` = 115658; -- locales_gameobject - name : entry=176969
UPDATE `trans_words` SET `content_loc2`='Rack' WHERE `word_id` = 117519; -- locales_gameobject - name : entry=19635
UPDATE `trans_words` SET `content_loc2`='Rail' WHERE `word_id` = 114872; -- locales_gameobject - name : entry=80024
UPDATE `trans_words` SET `content_loc2`='Razorfen Downs Intance' WHERE `word_id` = 117115; -- locales_gameobject - name : entry=19104
UPDATE `trans_words` SET `content_loc2`='Razorfen Kraul Intance' WHERE `word_id` = 117117; -- locales_gameobject - name : entry=19106
UPDATE `trans_words` SET `content_loc2`='Red Raptor Nest' WHERE `word_id` = 114516; -- locales_gameobject - name : entry=6906
UPDATE `trans_words` SET `content_loc2`='Resonite Crystal (Trap)' WHERE `word_id` = 120864; -- locales_gameobject - name : entry=178124
UPDATE `trans_words` SET `content_loc2`='Rifle 2' WHERE `word_id` = 117503; -- locales_gameobject - name : entry=19617
UPDATE `trans_words` SET `content_loc2`='Rifle' WHERE `word_id` = 117500; -- locales_gameobject - name : entry=19613
UPDATE `trans_words` SET `content_loc2`='Rin\'ji\'s Cage' WHERE `word_id` = 114996; -- locales_gameobject - name : entry=142036
UPDATE `trans_words` SET `content_loc2`='Robe' WHERE `word_id` = 114890; -- locales_gameobject - name : entry=92531
UPDATE `trans_words` SET `content_loc2`='Rock Arch 2' WHERE `word_id` = 117385; -- locales_gameobject - name : entry=19417
UPDATE `trans_words` SET `content_loc2`='Rock Arch 3' WHERE `word_id` = 117386; -- locales_gameobject - name : entry=19418
UPDATE `trans_words` SET `content_loc2`='Rock Arch' WHERE `word_id` = 117384; -- locales_gameobject - name : entry=19416
UPDATE `trans_words` SET `content_loc2`='Rock Bridge' WHERE `word_id` = 117381; -- locales_gameobject - name : entry=19413
UPDATE `trans_words` SET `content_loc2`='Rock Monument' WHERE `word_id` = 117418; -- locales_gameobject - name : entry=19458
UPDATE `trans_words` SET `content_loc2`='Rock Wall' WHERE `word_id` = 117407; -- locales_gameobject - name : entry=19444
UPDATE `trans_words` SET `content_loc2`='Rockwall Fence' WHERE `word_id` = 116926; -- locales_gameobject - name : entry=211064
UPDATE `trans_words` SET `content_loc2`='Ruined Fortress' WHERE `word_id` = 117242; -- locales_gameobject - name : entry=19232
UPDATE `trans_words` SET `content_loc2`='Ruined Fountain' WHERE `word_id` = 117419; -- locales_gameobject - name : entry=19459
UPDATE `trans_words` SET `content_loc2`='Ruined Keep' WHERE `word_id` = 117243; -- locales_gameobject - name : entry=19233
UPDATE `trans_words` SET `content_loc2`='Rune of Beth\'Amara' WHERE `word_id` = 115093; -- locales_gameobject - name : entry=149481
UPDATE `trans_words` SET `content_loc2`='Rune of Jin\'yael' WHERE `word_id` = 115092; -- locales_gameobject - name : entry=149480
UPDATE `trans_words` SET `content_loc2`='Rune of Markri' WHERE `word_id` = 115094; -- locales_gameobject - name : entry=149482
UPDATE `trans_words` SET `content_loc2`='Rune of Sael\'hai' WHERE `word_id` = 115095; -- locales_gameobject - name : entry=149483
UPDATE `trans_words` SET `content_loc2`='Rune' WHERE `word_id` = 116549; -- locales_gameobject - name : entry=181599
UPDATE `trans_words` SET `content_loc2`='Samophlange' WHERE `word_id` = 11947; -- locales_gameobject - name : entry=162024
UPDATE `trans_words` SET `content_loc2`='Sand Worm Rock Base' WHERE `word_id` = 116907; -- locales_gameobject - name : entry=210343
UPDATE `trans_words` SET `content_loc2`='Sarcophag' WHERE `word_id` = 116928; -- locales_gameobject - name : entry=211067
UPDATE `trans_words` SET `content_loc2`='Sarcophagus' WHERE `word_id` = 117507; -- locales_gameobject - name : entry=19622
UPDATE `trans_words` SET `content_loc2`='Scarecrow' WHERE `word_id` = 117397; -- locales_gameobject - name : entry=19432
UPDATE `trans_words` SET `content_loc2`='Scarley Monastery' WHERE `word_id` = 117247; -- locales_gameobject - name : entry=19238
UPDATE `trans_words` SET `content_loc2`='Sergeant\'s Quarters' WHERE `word_id` = 117574; -- locales_gameobject - name : entry=181032
UPDATE `trans_words` SET `content_loc2`='Shack' WHERE `word_id` = 117508; -- locales_gameobject - name : entry=19623
UPDATE `trans_words` SET `content_loc2`='Shadowfang Instance' WHERE `word_id` = 117135; -- locales_gameobject - name : entry=19125
UPDATE `trans_words` SET `content_loc2`='Shaman Mesa' WHERE `word_id` = 117324; -- locales_gameobject - name : entry=19344
UPDATE `trans_words` SET `content_loc2`='Shaman Tent' WHERE `word_id` = 117292; -- locales_gameobject - name : entry=19302
UPDATE `trans_words` SET `content_loc2`='Shattrath' WHERE `word_id` = 117683; -- locales_gameobject - name : entry=182100
UPDATE `trans_words` SET `content_loc2`='Shop Counter 2' WHERE `word_id` = 117510; -- locales_gameobject - name : entry=19625
UPDATE `trans_words` SET `content_loc2`='Shop Counter' WHERE `word_id` = 117509; -- locales_gameobject - name : entry=19624
UPDATE `trans_words` SET `content_loc2`='Shopping Centre' WHERE `word_id` = 116893; -- locales_gameobject - name : entry=200001
UPDATE `trans_words` SET `content_loc2`='Silithus Crystal Formation 03' WHERE `word_id` = 116908; -- locales_gameobject - name : entry=210344
UPDATE `trans_words` SET `content_loc2`='Silvermoon City Bench' WHERE `word_id` = 118347; -- locales_gameobject - name : entry=190000
UPDATE `trans_words` SET `content_loc2`='Silvermoon Hunter\'s Lodge' WHERE `word_id` = 118354; -- locales_gameobject - name : entry=190010
UPDATE `trans_words` SET `content_loc2`='SkullCandle01' WHERE `word_id` = 116190; -- locales_gameobject - name : entry=180425
UPDATE `trans_words` SET `content_loc2`='Slaughter House' WHERE `word_id` = 117348; -- locales_gameobject - name : entry=19376
UPDATE `trans_words` SET `content_loc2`='Small Boat' WHERE `word_id` = 117439; -- locales_gameobject - name : entry=19481
UPDATE `trans_words` SET `content_loc2`='Small House' WHERE `word_id` = 117264; -- locales_gameobject - name : entry=19262
UPDATE `trans_words` SET `content_loc2`='Small Tunnel (Snow)' WHERE `word_id` = 117173; -- locales_gameobject - name : entry=19163
UPDATE `trans_words` SET `content_loc2`='Small Tunnel' WHERE `word_id` = 117172; -- locales_gameobject - name : entry=19162
UPDATE `trans_words` SET `content_loc2`='Smoke Emitter, Large AOI, scale 2' WHERE `word_id` = 115947; -- locales_gameobject - name : entry=179066
UPDATE `trans_words` SET `content_loc2`='Smoldering Coals' WHERE `word_id` = 114984; -- locales_gameobject - name : entry=140358
UPDATE `trans_words` SET `content_loc2`='Smoldering Fire' WHERE `word_id` = 114328; -- locales_gameobject - name : entry=2004
UPDATE `trans_words` SET `content_loc2`='Snake Statue' WHERE `word_id` = 117442; -- locales_gameobject - name : entry=19485
UPDATE `trans_words` SET `content_loc2`='Snow Fountain' WHERE `word_id` = 117496; -- locales_gameobject - name : entry=19608
UPDATE `trans_words` SET `content_loc2`='Spear 2' WHERE `word_id` = 117534; -- locales_gameobject - name : entry=19652
UPDATE `trans_words` SET `content_loc2`='Spearman Statue' WHERE `word_id` = 117465; -- locales_gameobject - name : entry=19510
UPDATE `trans_words` SET `content_loc2`='Spectral Rift (temp)' WHERE `word_id` = 118291; -- locales_gameobject - name : entry=187055
UPDATE `trans_words` SET `content_loc2`='Spidermane' WHERE `word_id` = 117245; -- locales_gameobject - name : entry=19235
UPDATE `trans_words` SET `content_loc2`='Spike Wall' WHERE `word_id` = 117364; -- locales_gameobject - name : entry=19395
UPDATE `trans_words` SET `content_loc2`='Stable (snow)' WHERE `word_id` = 117338; -- locales_gameobject - name : entry=19363
UPDATE `trans_words` SET `content_loc2`='Staff 2' WHERE `word_id` = 117535; -- locales_gameobject - name : entry=19654
UPDATE `trans_words` SET `content_loc2`='Stanley\'s Dish' WHERE `word_id` = 114297; -- locales_gameobject - name : entry=1720
UPDATE `trans_words` SET `content_loc2`='Stocks' WHERE `word_id` = 117520; -- locales_gameobject - name : entry=19636
UPDATE `trans_words` SET `content_loc2`='Stolen Books' WHERE `word_id` = 114873; -- locales_gameobject - name : entry=83763
UPDATE `trans_words` SET `content_loc2`='Stone Fence' WHERE `word_id` = 117416; -- locales_gameobject - name : entry=19455
UPDATE `trans_words` SET `content_loc2`='Stone Pyre' WHERE `word_id` = 117421; -- locales_gameobject - name : entry=19461
UPDATE `trans_words` SET `content_loc2`='Stonebranch Herbalist' WHERE `word_id` = 114726; -- locales_gameobject - name : entry=26493
UPDATE `trans_words` SET `content_loc2`='Stormwind Gate Old' WHERE `word_id` = 117413; -- locales_gameobject - name : entry=19451
UPDATE `trans_words` SET `content_loc2`='Stormwind Valley of Heroes Bridge' WHERE `word_id` = 117073; -- locales_gameobject - name : entry=19059
UPDATE `trans_words` SET `content_loc2`='Stormwind Valley of Heroes Gate' WHERE `word_id` = 117074; -- locales_gameobject - name : entry=19060
UPDATE `trans_words` SET `content_loc2`='Stranglethorn Arena' WHERE `word_id` = 117078; -- locales_gameobject - name : entry=19065
UPDATE `trans_words` SET `content_loc2`='Stratholme Part 2' WHERE `word_id` = 117137; -- locales_gameobject - name : entry=19127
UPDATE `trans_words` SET `content_loc2`='Stratholme Part 3' WHERE `word_id` = 117138; -- locales_gameobject - name : entry=19128
UPDATE `trans_words` SET `content_loc2`='Stratholme Part 4' WHERE `word_id` = 117139; -- locales_gameobject - name : entry=19129
UPDATE `trans_words` SET `content_loc2`='Stratholme Part' WHERE `word_id` = 117136; -- locales_gameobject - name : entry=19126
UPDATE `trans_words` SET `content_loc2`='Stratholme' WHERE `word_id` = 115656; -- locales_gameobject - name : entry=176967
UPDATE `trans_words` SET `content_loc2`='Stromgarde' WHERE `word_id` = 114394; -- locales_gameobject - name : entry=2672
UPDATE `trans_words` SET `content_loc2`='Stromguard Walls' WHERE `word_id` = 117353; -- locales_gameobject - name : entry=19381
UPDATE `trans_words` SET `content_loc2`='Sunken Temple Instance' WHERE `word_id` = 117249; -- locales_gameobject - name : entry=19240
UPDATE `trans_words` SET `content_loc2`='Sunken Temple Portcullis' WHERE `word_id` = 117479; -- locales_gameobject - name : entry=19525
UPDATE `trans_words` SET `content_loc2`='Sunshield Statue 2' WHERE `word_id` = 117467; -- locales_gameobject - name : entry=19512
UPDATE `trans_words` SET `content_loc2`='Sunshield Statue' WHERE `word_id` = 117466; -- locales_gameobject - name : entry=19511
UPDATE `trans_words` SET `content_loc2`='Sword 2' WHERE `word_id` = 117537; -- locales_gameobject - name : entry=19656
UPDATE `trans_words` SET `content_loc2`='Sylvanaar' WHERE `word_id` = 117813; -- locales_gameobject - name : entry=183471
UPDATE `trans_words` SET `content_loc2`='Tabards' WHERE `word_id` = 114833; -- locales_gameobject - name : entry=58607
UPDATE `trans_words` SET `content_loc2`='Table' WHERE `word_id` = 116414; -- locales_gameobject - name : entry=181075
UPDATE `trans_words` SET `content_loc2`='Tanaris' WHERE `word_id` = 114621; -- locales_gameobject - name : entry=19850
UPDATE `trans_words` SET `content_loc2`='Target' WHERE `word_id` = 114541; -- locales_gameobject - name : entry=13952
UPDATE `trans_words` SET `content_loc2`='Tavern (snow)' WHERE `word_id` = 117340; -- locales_gameobject - name : entry=19366
UPDATE `trans_words` SET `content_loc2`='Tavern' WHERE `word_id` = 117341; -- locales_gameobject - name : entry=19367
UPDATE `trans_words` SET `content_loc2`='Telaar' WHERE `word_id` = 117779; -- locales_gameobject - name : entry=183201
UPDATE `trans_words` SET `content_loc2`='Teleport-Stone to Hyjal' WHERE `word_id` = 116922; -- locales_gameobject - name : entry=211050
UPDATE `trans_words` SET `content_loc2`='Telredor' WHERE `word_id` = 117712; -- locales_gameobject - name : entry=182287
UPDATE `trans_words` SET `content_loc2`='TEMP Rysons All Seeing Eye Trap' WHERE `word_id` = 268309; -- locales_gameobject - name : entry=178644
UPDATE `trans_words` SET `content_loc2`='Tepee' WHERE `word_id` = 117290; -- locales_gameobject - name : entry=19299
UPDATE `trans_words` SET `content_loc2`='Terocone' WHERE `word_id` = 24982; -- locales_gameobject - name : entry=181277
UPDATE `trans_words` SET `content_loc2`='Terokkar Forest - Derelict Caravan - Quest - Chest Opened' WHERE `word_id` = 116794; -- locales_gameobject - name : entry=185221
UPDATE `trans_words` SET `content_loc2`='TEST Ribbon Pole TRAP' WHERE `word_id` = 120873; -- locales_gameobject - name : entry=181604
UPDATE `trans_words` SET `content_loc2`='Test' WHERE `word_id` = 49952; -- locales_gameobject - name : entry=2558
UPDATE `trans_words` SET `content_loc2`='Thalanaar' WHERE `word_id` = 114620; -- locales_gameobject - name : entry=19847
UPDATE `trans_words` SET `content_loc2`='Thane\'s Boots and Shoulderpads' WHERE `word_id` = 114355; -- locales_gameobject - name : entry=2151
UPDATE `trans_words` SET `content_loc2`='The Cheese Cutters' WHERE `word_id` = 114352; -- locales_gameobject - name : entry=2148
UPDATE `trans_words` SET `content_loc2`='The Forlorn Caverns' WHERE `word_id` = 114756; -- locales_gameobject - name : entry=32381
UPDATE `trans_words` SET `content_loc2`='The Lay of Ameth\'Aran' WHERE `word_id` = 24268; -- locales_gameobject - name : entry=17188
UPDATE `trans_words` SET `content_loc2`='The Mystic Mage & Priest Council' WHERE `word_id` = 118350; -- locales_gameobject - name : entry=190003
UPDATE `trans_words` SET `content_loc2`='The Mystic Mage' WHERE `word_id` = 118348; -- locales_gameobject - name : entry=190001
UPDATE `trans_words` SET `content_loc2`='The Paladian Blood Knights Order' WHERE `word_id` = 118353; -- locales_gameobject - name : entry=190009
UPDATE `trans_words` SET `content_loc2`='The Priest Council' WHERE `word_id` = 118349; -- locales_gameobject - name : entry=190002
UPDATE `trans_words` SET `content_loc2`='The Royal Exchange Auction House' WHERE `word_id` = 118351; -- locales_gameobject - name : entry=190007
UPDATE `trans_words` SET `content_loc2`='The Seven Deadly Venoms' WHERE `word_id` = 114353; -- locales_gameobject - name : entry=2149
UPDATE `trans_words` SET `content_loc2`='The Stockades' WHERE `word_id` = 117091; -- locales_gameobject - name : entry=19078
UPDATE `trans_words` SET `content_loc2`='The Wine Cask' WHERE `word_id` = 114347; -- locales_gameobject - name : entry=2130
UPDATE `trans_words` SET `content_loc2`='Thelsamar' WHERE `word_id` = 114239; -- locales_gameobject - name : entry=298
UPDATE `trans_words` SET `content_loc2`='Theramore Docks' WHERE `word_id` = 117303; -- locales_gameobject - name : entry=19316
UPDATE `trans_words` SET `content_loc2`='Thundershot Guns \'n Ammo' WHERE `word_id` = 114718; -- locales_gameobject - name : entry=26485
UPDATE `trans_words` SET `content_loc2`='Tirisfal' WHERE `word_id` = 114288; -- locales_gameobject - name : entry=1677
UPDATE `trans_words` SET `content_loc2`='Tomb Monument' WHERE `word_id` = 117406; -- locales_gameobject - name : entry=19443
UPDATE `trans_words` SET `content_loc2`='Tomb Stone 1' WHERE `word_id` = 117405; -- locales_gameobject - name : entry=19442
UPDATE `trans_words` SET `content_loc2`='Tonk Control Console Trap' WHERE `word_id` = 120870; -- locales_gameobject - name : entry=180525
UPDATE `trans_words` SET `content_loc2`='Torche en sorbier' WHERE `word_id` = 116853; -- locales_gameobject - name : entry=186425
UPDATE `trans_words` SET `content_loc2`='Tower (snow)' WHERE `word_id` = 117339; -- locales_gameobject - name : entry=19364
UPDATE `trans_words` SET `content_loc2`='Tower (Swamp of Sorrows)' WHERE `word_id` = 117283; -- locales_gameobject - name : entry=19290
UPDATE `trans_words` SET `content_loc2`='Tower Zeppelin' WHERE `word_id` = 117350; -- locales_gameobject - name : entry=19378
UPDATE `trans_words` SET `content_loc2`='Townhall 3' WHERE `word_id` = 117063; -- locales_gameobject - name : entry=19047
UPDATE `trans_words` SET `content_loc2`='Townhall without Wall' WHERE `word_id` = 117046; -- locales_gameobject - name : entry=19012
UPDATE `trans_words` SET `content_loc2`='Trade & Training Organization for Jewelers' WHERE `word_id` = 118352; -- locales_gameobject - name : entry=190008
UPDATE `trans_words` SET `content_loc2`='Tranquillien' WHERE `word_id` = 117651; -- locales_gameobject - name : entry=181935
UPDATE `trans_words` SET `content_loc2`='Tree Stump' WHERE `word_id` = 116923; -- locales_gameobject - name : entry=211052
UPDATE `trans_words` SET `content_loc2`='Troll Burrow (Swamp of Sorrows)' WHERE `word_id` = 117294; -- locales_gameobject - name : entry=19304
UPDATE `trans_words` SET `content_loc2`='Troll Burrow' WHERE `word_id` = 117295; -- locales_gameobject - name : entry=19305
UPDATE `trans_words` SET `content_loc2`='Troll City Arena' WHERE `word_id` = 117354; -- locales_gameobject - name : entry=19382
UPDATE `trans_words` SET `content_loc2`='Troll Den 2' WHERE `word_id` = 117153; -- locales_gameobject - name : entry=19143
UPDATE `trans_words` SET `content_loc2`='Troll Den' WHERE `word_id` = 117152; -- locales_gameobject - name : entry=19142
UPDATE `trans_words` SET `content_loc2`='Troll Hotel' WHERE `word_id` = 117296; -- locales_gameobject - name : entry=19306
UPDATE `trans_words` SET `content_loc2`='Troll Hut Desert Small' WHERE `word_id` = 118361; -- locales_gameobject - name : entry=193010
UPDATE `trans_words` SET `content_loc2`='Troll Hut Desert' WHERE `word_id` = 117299; -- locales_gameobject - name : entry=19309
UPDATE `trans_words` SET `content_loc2`='Troll Hut Small' WHERE `word_id` = 117301; -- locales_gameobject - name : entry=19312
UPDATE `trans_words` SET `content_loc2`='Troll Hut' WHERE `word_id` = 117300; -- locales_gameobject - name : entry=19311
UPDATE `trans_words` SET `content_loc2`='Troll Shop House' WHERE `word_id` = 117297; -- locales_gameobject - name : entry=19307
UPDATE `trans_words` SET `content_loc2`='Troll Shopping Mall' WHERE `word_id` = 117298; -- locales_gameobject - name : entry=19308
UPDATE `trans_words` SET `content_loc2`='Troll Watch Tower' WHERE `word_id` = 117440; -- locales_gameobject - name : entry=19482
UPDATE `trans_words` SET `content_loc2`='Troll Ziggurat' WHERE `word_id` = 117066; -- locales_gameobject - name : entry=19052
UPDATE `trans_words` SET `content_loc2`='Tunnel Cave to Cave (Ice)' WHERE `word_id` = 117157; -- locales_gameobject - name : entry=19147
UPDATE `trans_words` SET `content_loc2`='Tunnel Cave to Cave (Warm)' WHERE `word_id` = 117159; -- locales_gameobject - name : entry=19149
UPDATE `trans_words` SET `content_loc2`='Tunnel Cave to Cave Large' WHERE `word_id` = 117158; -- locales_gameobject - name : entry=19148
UPDATE `trans_words` SET `content_loc2`='Tunnel Cave to Cave' WHERE `word_id` = 117156; -- locales_gameobject - name : entry=19146
UPDATE `trans_words` SET `content_loc2`='Turalyon Statue' WHERE `word_id` = 117516; -- locales_gameobject - name : entry=19632
UPDATE `trans_words` SET `content_loc2`='Tuurem' WHERE `word_id` = 117691; -- locales_gameobject - name : entry=182172
UPDATE `trans_words` SET `content_loc2`='Twilight Tablet' WHERE `word_id` = 116903; -- locales_gameobject - name : entry=210335
UPDATE `trans_words` SET `content_loc2`='Twinblades Statue' WHERE `word_id` = 117468; -- locales_gameobject - name : entry=19513
UPDATE `trans_words` SET `content_loc2`='Uldaman Door' WHERE `word_id` = 117480; -- locales_gameobject - name : entry=19526
UPDATE `trans_words` SET `content_loc2`='Uldaman Piece 2' WHERE `word_id` = 117124; -- locales_gameobject - name : entry=19113
UPDATE `trans_words` SET `content_loc2`='Uldaman Piece 3' WHERE `word_id` = 117125; -- locales_gameobject - name : entry=19114
UPDATE `trans_words` SET `content_loc2`='Uldaman Piece 4' WHERE `word_id` = 117126; -- locales_gameobject - name : entry=19115
UPDATE `trans_words` SET `content_loc2`='Uldaman Piece' WHERE `word_id` = 117123; -- locales_gameobject - name : entry=19112
UPDATE `trans_words` SET `content_loc2`='Undead Campfire' WHERE `word_id` = 117492; -- locales_gameobject - name : entry=19604
UPDATE `trans_words` SET `content_loc2`='Undead Cave' WHERE `word_id` = 117325; -- locales_gameobject - name : entry=19345
UPDATE `trans_words` SET `content_loc2`='Undead Fire Large' WHERE `word_id` = 117493; -- locales_gameobject - name : entry=19605
UPDATE `trans_words` SET `content_loc2`='Undead Fire Small' WHERE `word_id` = 117494; -- locales_gameobject - name : entry=19606
UPDATE `trans_words` SET `content_loc2`='Undead Fountain' WHERE `word_id` = 117498; -- locales_gameobject - name : entry=19610
UPDATE `trans_words` SET `content_loc2`='Underwater Cave Medium' WHERE `word_id` = 117228; -- locales_gameobject - name : entry=19218
UPDATE `trans_words` SET `content_loc2`='unk' WHERE `word_id` = 114688; -- locales_gameobject - name : entry=21653
UPDATE `trans_words` SET `content_loc2`='Upper Mesa 2' WHERE `word_id` = 117327; -- locales_gameobject - name : entry=19347
UPDATE `trans_words` SET `content_loc2`='Upper Mesa 3' WHERE `word_id` = 117328; -- locales_gameobject - name : entry=19348
UPDATE `trans_words` SET `content_loc2`='Upper Mesa 4' WHERE `word_id` = 117329; -- locales_gameobject - name : entry=19349
UPDATE `trans_words` SET `content_loc2`='Upper Mesa 5' WHERE `word_id` = 117330; -- locales_gameobject - name : entry=19350
UPDATE `trans_words` SET `content_loc2`='Upper Mesa' WHERE `word_id` = 117326; -- locales_gameobject - name : entry=19346
UPDATE `trans_words` SET `content_loc2`='Uther Shrine' WHERE `word_id` = 117351; -- locales_gameobject - name : entry=19379
UPDATE `trans_words` SET `content_loc2`='Uther Statue' WHERE `word_id` = 117517; -- locales_gameobject - name : entry=19633
UPDATE `trans_words` SET `content_loc2`='Vault Door' WHERE `word_id` = 115704; -- locales_gameobject - name : entry=177237
UPDATE `trans_words` SET `content_loc2`='Volcanic den' WHERE `word_id` = 117154; -- locales_gameobject - name : entry=19144
UPDATE `trans_words` SET `content_loc2`='Wagon' WHERE `word_id` = 117387; -- locales_gameobject - name : entry=19419
UPDATE `trans_words` SET `content_loc2`='Wailing Caverns Intance' WHERE `word_id` = 117119; -- locales_gameobject - name : entry=19108
UPDATE `trans_words` SET `content_loc2`='Wailing Caverns Teeth' WHERE `word_id` = 117120; -- locales_gameobject - name : entry=19109
UPDATE `trans_words` SET `content_loc2`='Wall Piece 2' WHERE `word_id` = 117051; -- locales_gameobject - name : entry=19031
UPDATE `trans_words` SET `content_loc2`='Wall Piece 3' WHERE `word_id` = 117052; -- locales_gameobject - name : entry=19032
UPDATE `trans_words` SET `content_loc2`='Wall Piece' WHERE `word_id` = 117050; -- locales_gameobject - name : entry=19029
UPDATE `trans_words` SET `content_loc2`='Wall Piece with Stairs' WHERE `word_id` = 117053; -- locales_gameobject - name : entry=19034
UPDATE `trans_words` SET `content_loc2`='Wall Sword' WHERE `word_id` = 117539; -- locales_gameobject - name : entry=19659
UPDATE `trans_words` SET `content_loc2`='WallPost' WHERE `word_id` = 117054; -- locales_gameobject - name : entry=19035
UPDATE `trans_words` SET `content_loc2`='War Catapult' WHERE `word_id` = 117773; -- locales_gameobject - name : entry=183164
UPDATE `trans_words` SET `content_loc2`='Warcraft 2 Dark Portal' WHERE `word_id` = 117357; -- locales_gameobject - name : entry=19386
UPDATE `trans_words` SET `content_loc2`='Warm Cave Medium' WHERE `word_id` = 117230; -- locales_gameobject - name : entry=19220
UPDATE `trans_words` SET `content_loc2`='Warm Cave' WHERE `word_id` = 117229; -- locales_gameobject - name : entry=19219
UPDATE `trans_words` SET `content_loc2`='Warm Den' WHERE `word_id` = 117155; -- locales_gameobject - name : entry=19145
UPDATE `trans_words` SET `content_loc2`='Warning Tree' WHERE `word_id` = 117408; -- locales_gameobject - name : entry=19445
UPDATE `trans_words` SET `content_loc2`='Warrior Mesa 1' WHERE `word_id` = 117332; -- locales_gameobject - name : entry=19352
UPDATE `trans_words` SET `content_loc2`='Warrior Mesa' WHERE `word_id` = 117331; -- locales_gameobject - name : entry=19351
UPDATE `trans_words` SET `content_loc2`='Warsong Clan Banner 07' WHERE `word_id` = 118362; -- locales_gameobject - name : entry=210068
UPDATE `trans_words` SET `content_loc2`='Watch Tower' WHERE `word_id` = 117412; -- locales_gameobject - name : entry=19450
UPDATE `trans_words` SET `content_loc2`='Water Basin' WHERE `word_id` = 117422; -- locales_gameobject - name : entry=19462
UPDATE `trans_words` SET `content_loc2`='Waterfall 3' WHERE `word_id` = 117460; -- locales_gameobject - name : entry=19505
UPDATE `trans_words` SET `content_loc2`='Wheat' WHERE `word_id` = 117398; -- locales_gameobject - name : entry=19433
UPDATE `trans_words` SET `content_loc2`='Wheel Plataform' WHERE `word_id` = 117306; -- locales_gameobject - name : entry=19323
UPDATE `trans_words` SET `content_loc2`='Winterspring Cave' WHERE `word_id` = 117333; -- locales_gameobject - name : entry=19353
UPDATE `trans_words` SET `content_loc2`='Wooden Stairs 2' WHERE `word_id` = 117541; -- locales_gameobject - name : entry=19661
UPDATE `trans_words` SET `content_loc2`='Wooden Stairs' WHERE `word_id` = 117540; -- locales_gameobject - name : entry=19660
UPDATE `trans_words` SET `content_loc2`='Wrought Iron Door' WHERE `word_id` = 117491; -- locales_gameobject - name : entry=19593
UPDATE `trans_words` SET `content_loc2`='Yellow Raptor Nest' WHERE `word_id` = 114518; -- locales_gameobject - name : entry=6908
UPDATE `trans_words` SET `content_loc2`='Zabra\'jin' WHERE `word_id` = 117713; -- locales_gameobject - name : entry=182288
UPDATE `trans_words` SET `content_loc2`='Zephyrium Capacitorium' WHERE `word_id` = 118028; -- locales_gameobject - name : entry=184628
UPDATE `trans_words` SET `content_loc2`='Zeppelin House' WHERE `word_id` = 117286; -- locales_gameobject - name : entry=19293
UPDATE `trans_words` SET `content_loc2`='Zeppelin Landing Tower' WHERE `word_id` = 115195; -- locales_gameobject - name : entry=165557
UPDATE `trans_words` SET `content_loc2`='Ziggurat' WHERE `word_id` = 117349; -- locales_gameobject - name : entry=19377
UPDATE `trans_words` SET `content_loc2`='Zul\'Gurub Piece' WHERE `word_id` = 117067; -- locales_gameobject - name : entry=19053

SET NAMES 'latin1';
