-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc2`='All right, let\'s go.' WHERE `word_id` = 7586; -- db_script_string - content : entry=2000000012
UPDATE `trans_words` SET `content_loc2`='An Avatar of Terokk! To arms!' WHERE `word_id` = 7599; -- db_script_string - content : entry=2000000025
UPDATE `trans_words` SET `content_loc2`='Anaya\'s soft voice trails away into the mists. "Know that I love you always..."' WHERE `word_id` = 7428; -- db_script_string - content : entry=2000005344
UPDATE `trans_words` SET `content_loc2`='And even more!' WHERE `word_id` = 7598; -- db_script_string - content : entry=2000000024
UPDATE `trans_words` SET `content_loc2`='And who do we have here?  No doubt th... crzzzk ...ade this communication possible?  I give you greetings fro... psshzzzk... Azure Watch.' WHERE `word_id` = 268219; -- db_script_string - content : entry=2000005549
UPDATE `trans_words` SET `content_loc2`='At least we would not be around to have to clean it up.' WHERE `word_id` = 7523; -- db_script_string - content : entry=2000005149
UPDATE `trans_words` SET `content_loc2`='begins a spell of summoning...' WHERE `word_id` = 7591; -- db_script_string - content : entry=2000000043
UPDATE `trans_words` SET `content_loc2`='But wouldn`t that mean crossing the streams? Isn`t that really bad?' WHERE `word_id` = 7526; -- db_script_string - content : entry=2000005160
UPDATE `trans_words` SET `content_loc2`='BY THE LIGHT OF ELUNE! Eredar! Cursed demons, what have you to me? I have not come alone, we will fight you as we have in the past! I...' WHERE `word_id` = 7636; -- db_script_string - content : entry=2000000660
UPDATE `trans_words` SET `content_loc2`='Derived from cutting edge Shattered Hand Offensive military technology, it blasts away stubborn stains with ease!' WHERE `word_id` = 7532; -- db_script_string - content : entry=2000005207
UPDATE `trans_words` SET `content_loc2`='Fear not! All fortunes can be discerned for those who know the way.' WHERE `word_id` = 7535; -- db_script_string - content : entry=2000005213
UPDATE `trans_words` SET `content_loc2`='Get it while its hot' WHERE `word_id` = 7516; -- db_script_string - content : entry=2000005100
UPDATE `trans_words` SET `content_loc2`='Glad to see you\'re doing so well, Harlan. And I hope to see you again soon' WHERE `word_id` = 7563; -- db_script_string - content : entry=2000000149
UPDATE `trans_words` SET `content_loc2`='Hey, you there. Want some candy?' WHERE `word_id` = 7492; -- db_script_string - content : entry=2000005052
UPDATE `trans_words` SET `content_loc2`='I FEEL DEATH ALONGSIDE' WHERE `word_id` = 7546; -- db_script_string - content : entry=2000005231
UPDATE `trans_words` SET `content_loc2`='I think, I\'ll be able to get to Brackenwall. The cargo they carried to the top of the towers. Be careful!' WHERE `word_id` = 8726; -- db_script_string - content : entry=2000000486
UPDATE `trans_words` SET `content_loc2`='I WICKED OGR' WHERE `word_id` = 7545; -- db_script_string - content : entry=2000005230
UPDATE `trans_words` SET `content_loc2`='I WILL DESTROY ALL' WHERE `word_id` = 7483; -- db_script_string - content : entry=2000005043
UPDATE `trans_words` SET `content_loc2`='I will do my best to take care of the children, Grandmother.' WHERE `word_id` = 7481; -- db_script_string - content : entry=2000005041
UPDATE `trans_words` SET `content_loc2`='It is time to force your final challenge young warriors! Prepare for your hardest fight yet.' WHERE `word_id` = 7559; -- db_script_string - content : entry=2000005075
UPDATE `trans_words` SET `content_loc2`='It\'s all here... how the raven\'s followers captured and subdued the sprints of rivals, trapping them forever within stone statues! The tablet even mentions the raven god\'s name -- Anzu. I\'d thought it was lost to history!' WHERE `word_id` = 7581; -- db_script_string - content : entry=2000000072
UPDATE `trans_words` SET `content_loc2`='Jeffrey Kaplan! Tom Chilton! Rob Pardo!' WHERE `word_id` = 268222; -- db_script_string - content : entry=2000000490
UPDATE `trans_words` SET `content_loc2`='Justin Thavirat! Roman Kenney! Our entire awesome art and animation team!' WHERE `word_id` = 268223; -- db_script_string - content : entry=2000000491
UPDATE `trans_words` SET `content_loc2`='Keep moving!' WHERE `word_id` = 7608; -- db_script_string - content : entry=2000000033
UPDATE `trans_words` SET `content_loc2`='Kevin Jordan and Jonathan LeCraft!' WHERE `word_id` = 268224; -- db_script_string - content : entry=2000000492
UPDATE `trans_words` SET `content_loc2`='Look out! More are coming!' WHERE `word_id` = 7597; -- db_script_string - content : entry=2000000023
UPDATE `trans_words` SET `content_loc2`='Look! Minions of Terokk are approaching!' WHERE `word_id` = 7596; -- db_script_string - content : entry=2000000022
UPDATE `trans_words` SET `content_loc2`='New posting up! Adventurers and heroes, gather round the bulletin board!' WHERE `word_id` = 7482; -- db_script_string - content : entry=2000005042
UPDATE `trans_words` SET `content_loc2`='NOBODY WILL GET THROUGH ME' WHERE `word_id` = 7548; -- db_script_string - content : entry=2000005235
UPDATE `trans_words` SET `content_loc2`='Not a challenge at all it seems. Let us see how hou handle your second test. Lysta, bring forth the minions of the Lich King.' WHERE `word_id` = 7561; -- db_script_string - content : entry=2000005073
UPDATE `trans_words` SET `content_loc2`='Now get out of my way, it\'s time to send the Burning Legion back to the nether!' WHERE `word_id` = 7504; -- db_script_string - content : entry=2000005413
UPDATE `trans_words` SET `content_loc2`='Of Course Im talking to myself. Only way to get a decent conversation in this city.' WHERE `word_id` = 7519; -- db_script_string - content : entry=2000005105
UPDATE `trans_words` SET `content_loc2`='Oh no! They a here!' WHERE `word_id` = 7587; -- db_script_string - content : entry=2000000013
UPDATE `trans_words` SET `content_loc2`='Oh sweet, delicious, spotted eggs - you will be mine...' WHERE `word_id` = 7573; -- db_script_string - content : entry=2000005093
UPDATE `trans_words` SET `content_loc2`='Oh, hello Grimclaw.' WHERE `word_id` = 7588; -- db_script_string - content : entry=2000000014
UPDATE `trans_words` SET `content_loc2`='Ok, $N. Now i can go the the Auberdine alone. Go to Terenthis. He waits for you. Thanks for the help.' WHERE `word_id` = 7589; -- db_script_string - content : entry=2000000015
UPDATE `trans_words` SET `content_loc2`='Ok, good luck friend. Thanks for the help.' WHERE `word_id` = 7590; -- db_script_string - content : entry=2000000016
UPDATE `trans_words` SET `content_loc2`='Ok, let\'s get started!' WHERE `word_id` = 7422; -- db_script_string - content : entry=2000000096
UPDATE `trans_words` SET `content_loc2`='Only if we did not follow the proper initialization procedures.' WHERE `word_id` = 7524; -- db_script_string - content : entry=2000005150
UPDATE `trans_words` SET `content_loc2`='Perry Gatner! What an act! The cantina is open all night long, so please, stay and enjoy yourselves!' WHERE `word_id` = 7550; -- db_script_string - content : entry=2000005301
UPDATE `trans_words` SET `content_loc2`='Please! I must feed on something soon... A mana crystal... a shard... anything! The pain is unbearable!' WHERE `word_id` = 7476; -- db_script_string - content : entry=2000005036
UPDATE `trans_words` SET `content_loc2`='Prizes! Get your prizes right here! Get over here and turn in your Darkmoon Faire Prize Tickets for valuable prizes!' WHERE `word_id` = 7471; -- db_script_string - content : entry=2000005025
UPDATE `trans_words` SET `content_loc2`='Right. We just busted our tails to haul all of this stuff up here, and you want us to work more?' WHERE `word_id` = 7494; -- db_script_string - content : entry=2000005056
UPDATE `trans_words` SET `content_loc2`='Sarath fades into the mist...' WHERE `word_id` = 7427; -- db_script_string - content : entry=2000000080
UPDATE `trans_words` SET `content_loc2`='Shane Dabiri, Lee, Alex T., Rob F., J. A. B., A. Mayberry!' WHERE `word_id` = 268221; -- db_script_string - content : entry=2000000489
UPDATE `trans_words` SET `content_loc2`='Sniff... That\'s the spirit soldier... I only wish we had more soldiers like you in this army. Now go out there and give \'em hell!' WHERE `word_id` = 7503; -- db_script_string - content : entry=2000005414
UPDATE `trans_words` SET `content_loc2`='Spirits of Water, I give you praise, and I beg of you a favour. You have heard $N\'s pleas, and I trust his inent is noble. Please, will you aid us?' WHERE `word_id` = 7572; -- db_script_string - content : entry=2000000057
UPDATE `trans_words` SET `content_loc2`='Tell us! Where does you leader hide?' WHERE `word_id` = 7478; -- db_script_string - content : entry=2000005038
UPDATE `trans_words` SET `content_loc2`='Thank you. I thought I was going to die.' WHERE `word_id` = 7625; -- db_script_string - content : entry=2000005545
UPDATE `trans_words` SET `content_loc2`='The Darkmoon Faire is the greatest event in all of Outland' WHERE `word_id` = 7540; -- db_script_string - content : entry=2000005221
UPDATE `trans_words` SET `content_loc2`='The Portal will shift slightly. At this point if you cast a binding cantrip you will solidify it in place.' WHERE `word_id` = 7528; -- db_script_string - content : entry=2000005173
UPDATE `trans_words` SET `content_loc2`='There\'s something else here, too. After a discription of a bloody battle and the downfall of the raven, there\'s a prophecy. Anzu will haunt the dreams of his enemies, twisting them to affect a return to this world...' WHERE `word_id` = 7582; -- db_script_string - content : entry=2000000073
UPDATE `trans_words` SET `content_loc2`='This data will be quite usefull for Project Blue Book. Er, I mean this will be great for my new look. See if you can gather any more data.' WHERE `word_id` = 7541; -- db_script_string - content : entry=2000005222
UPDATE `trans_words` SET `content_loc2`='This is great news! Your efforts have indeed saved us, $N!' WHERE `word_id` = 8633; -- db_script_string - content : entry=2000005551
UPDATE `trans_words` SET `content_loc2`='This is the last time that I buy second-hand equipment from ethereal' WHERE `word_id` = 7466; -- db_script_string - content : entry=2000005067
UPDATE `trans_words` SET `content_loc2`='Tickets! Redeem your Darkmoon Faire Prize Tickets here! Wondrous and exotic prizes are waiting for you!' WHERE `word_id` = 7534; -- db_script_string - content : entry=2000005212
UPDATE `trans_words` SET `content_loc2`='Turning to face Tuluun, the Draenei Artificer sneers contemptuously.' WHERE `word_id` = 7642; -- db_script_string - content : entry=2000000662
UPDATE `trans_words` SET `content_loc2`='US ALREADY ALL ANYMORE AND ANYMORE' WHERE `word_id` = 7484; -- db_script_string - content : entry=2000005044
UPDATE `trans_words` SET `content_loc2`='Welcome one and all to the Darkmoon Faire, the greatest event in all the worlds! We have it all... delicious food, strong drinks, exotic artifacts, fortunes read, amazing prizes and excitement without end! Don\'t forget to turn in your Darkmoon Faire Prize Tickets to Gelvas Grimegate! All it takes is five or more and you\'re on your way to the most wondrous prizes in all of Outland. Everybody is a winner' WHERE `word_id` = 7475; -- db_script_string - content : entry=2000005034
UPDATE `trans_words` SET `content_loc2`='Well hand it overand let\'s see what you got!' WHERE `word_id` = 7490; -- db_script_string - content : entry=2000005050
UPDATE `trans_words` SET `content_loc2`='Where do you think you are going soldier? Those are fatal wounds you\'ve got there. Now, get back in tent and let the nurse treat you!' WHERE `word_id` = 7505; -- db_script_string - content : entry=2000005412
UPDATE `trans_words` SET `content_loc2`='Who? The Tauren Chieftains! What? A live performance. Where? The World\'s End Tavern! When? The top of the hour! BE THERE!' WHERE `word_id` = 7439; -- db_script_string - content : entry=2000005305
UPDATE `trans_words` SET `content_loc2`='Wouldn\'t you like to bring those days back? I have some friends who know just the way to do that.' WHERE `word_id` = 7469; -- db_script_string - content : entry=2000005022
UPDATE `trans_words` SET `content_loc2`='Wow, all this for a love potion. Hope he is worth it.' WHERE `word_id` = 7527; -- db_script_string - content : entry=2000005171
UPDATE `trans_words` SET `content_loc2`='Yer wearin down, princess, I can sense it!' WHERE `word_id` = 7530; -- db_script_string - content : entry=2000005203
UPDATE `trans_words` SET `content_loc2`='Yes you may, $N. But do not stray too far from home.' WHERE `word_id` = 7506; -- db_script_string - content : entry=2000005321
UPDATE `trans_words` SET `content_loc2`='YOU PRAY SERVANTS MY' WHERE `word_id` = 7539; -- db_script_string - content : entry=2000005220
UPDATE `trans_words` SET `content_loc2`='You want to go do the bounty off of this wanted poster after this shift is over?' WHERE `word_id` = 7487; -- db_script_string - content : entry=2000005047
UPDATE `trans_words` SET `content_loc2`='Your body is mine! Our fates are forever intertwined!' WHERE `word_id` = 7595; -- db_script_string - content : entry=2000000031

SET NAMES 'latin1';
