-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc8`='[PH] Learn Dimensional Ripper.' WHERE `word_id`=128975; -- locales_gossip_menu_option - option_text : menu_id=20003-id=0
UPDATE `trans_words` SET `content_loc8`='[PH] Learn Ultrasafe Transporter.' WHERE `word_id`=128976; -- locales_gossip_menu_option - option_text : menu_id=20004-id=0
UPDATE `trans_words` SET `content_loc8`='[ph]Learn recipe...' WHERE `word_id`=128221; -- locales_gossip_menu_option - option_text : menu_id=6443-id=0
UPDATE `trans_words` SET `content_loc8`='Can you tell me about this shard?' WHERE `word_id`=127827; -- locales_gossip_menu_option - option_text : menu_id=21-id=1
UPDATE `trans_words` SET `content_loc8`='Do you know where I can find Half Pendant of Aquatic Agility?' WHERE `word_id`=127921; -- locales_gossip_menu_option - option_text : menu_id=4041-id=1
UPDATE `trans_words` SET `content_loc8`='Do you know where I can find Half Pendant of Aquatic Endurance?' WHERE `word_id`=128016; -- locales_gossip_menu_option - option_text : menu_id=4042-id=1
UPDATE `trans_words` SET `content_loc8`='Emblem Gear' WHERE `word_id`=128942; -- locales_gossip_menu_option - option_text : menu_id=10173-id=2
UPDATE `trans_words` SET `content_loc8`='Garrosh is beyond redemption, Greatmother. I fear that in helping the Maghar, I have convinced Garrosh that he is unfit to lead.' WHERE `word_id`=269448; -- locales_gossip_menu_option - option_text : menu_id=7768-id=1
UPDATE `trans_words` SET `content_loc8`='Guide me to the Broken Ring Graveyard.' WHERE `word_id`=128935; -- locales_gossip_menu_option - option_text : menu_id=10128-id=2
UPDATE `trans_words` SET `content_loc8`='Hmm, I listen. Also that you offer?' WHERE `word_id`=128551; -- locales_gossip_menu_option - option_text : menu_id=4781-id=1
UPDATE `trans_words` SET `content_loc8`='I have pald your price, Gloom\'rel. Now teach me your secrets!' WHERE `word_id`=128541; -- locales_gossip_menu_option - option_text : menu_id=1945-id=1
UPDATE `trans_words` SET `content_loc8`='I need to find Dajik, do you have his worn chalk?' WHERE `word_id`=128851; -- locales_gossip_menu_option - option_text : menu_id=9741-id=3
UPDATE `trans_words` SET `content_loc8`='I wish to to visit the Rise of the Defiler.' WHERE `word_id`=128540; -- locales_gossip_menu_option - option_text : menu_id=1541-id=0
UPDATE `trans_words` SET `content_loc8`='I wish to train my pet.' WHERE `word_id`=128552; -- locales_gossip_menu_option - option_text : menu_id=4783-id=3
UPDATE `trans_words` SET `content_loc8`='I\'m ready to fly! Take me to the dragon!' WHERE `word_id`=128676; -- locales_gossip_menu_option - option_text : menu_id=8229-id=0
UPDATE `trans_words` SET `content_loc8`='Im fine, thank you. You asked for me?' WHERE `word_id`=269450; -- locales_gossip_menu_option - option_text : menu_id=8436-id=0
UPDATE `trans_words` SET `content_loc8`='Is there anything you would have of me?' WHERE `word_id`=128367; -- locales_gossip_menu_option - option_text : menu_id=20007-id=1
UPDATE `trans_words` SET `content_loc8`='Ner\'zhul' WHERE `word_id`=128151; -- locales_gossip_menu_option - option_text : menu_id=4764-id=2
UPDATE `trans_words` SET `content_loc8`='Oh, its not my fault, I can assure you.' WHERE `word_id`=269449; -- locales_gossip_menu_option - option_text : menu_id=8435-id=0
UPDATE `trans_words` SET `content_loc8`='Perhaps I can be of some assistance. I will make a deal with you, Satyr. I shall recover this unforged breastplate and slay the beast. In exchange for this task, you will teach me how to create the breastplate.' WHERE `word_id`=128373; -- locales_gossip_menu_option - option_text : menu_id=20019-id=0
UPDATE `trans_words` SET `content_loc8`='Than I can help?' WHERE `word_id`=128526; -- locales_gossip_menu_option - option_text : menu_id=21-id=0
UPDATE `trans_words` SET `content_loc8`='This Dimensional Imploder sounds dangerous! How can I make one?' WHERE `word_id`=128186; -- locales_gossip_menu_option - option_text : menu_id=6092-id=0
UPDATE `trans_words` SET `content_loc8`='Um, no... no, I don	 want that at all.' WHERE `word_id`=269451; -- locales_gossip_menu_option - option_text : menu_id=8437-id=0
UPDATE `trans_words` SET `content_loc8`='What does the Dalson\'s Tears Cauldron need?' WHERE `word_id`=128546; -- locales_gossip_menu_option - option_text : menu_id=3223-id=3
UPDATE `trans_words` SET `content_loc8`='What does the Felstone Field Cauldron need?' WHERE `word_id`=128545; -- locales_gossip_menu_option - option_text : menu_id=3223-id=2
UPDATE `trans_words` SET `content_loc8`='What does the Gahrron\'s Withering Cauldron need?' WHERE `word_id`=128548; -- locales_gossip_menu_option - option_text : menu_id=3223-id=5
UPDATE `trans_words` SET `content_loc8`='What does the Writhing Haunt Cauldron need?' WHERE `word_id`=128547; -- locales_gossip_menu_option - option_text : menu_id=3223-id=4
UPDATE `trans_words` SET `content_loc8`='What Guardian? I don	 understand any of this.' WHERE `word_id`=128488; -- locales_gossip_menu_option - option_text : menu_id=86-id=0
UPDATE `trans_words` SET `content_loc8`='Yes elder. Tell me more of the book.' WHERE `word_id`=128719; -- locales_gossip_menu_option - option_text : menu_id=8617-id=0
UPDATE `trans_words` SET `content_loc8`='Yes... yes, it\'s me.' WHERE `word_id`=128718; -- locales_gossip_menu_option - option_text : menu_id=8616-id=0
UPDATE `trans_words` SET `content_loc8`='You gave the crew disguises?' WHERE `word_id`=128740; -- locales_gossip_menu_option - option_text : menu_id=8775-id=0

SET NAMES 'latin1';
