-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc8`='%s reads from the book of the dead.' WHERE `word_id` = 268248; -- db_script_string - content : entry=2000000488
UPDATE `trans_words` SET `content_loc8`='All right, I shall find people to help him.' WHERE `word_id` = 6944; -- db_script_string - content : entry=2000000011
UPDATE `trans_words` SET `content_loc8`='All right, let\'s go.' WHERE `word_id` = 7586; -- db_script_string - content : entry=2000000012
UPDATE `trans_words` SET `content_loc8`='Anaya\'s soft voice trails away into the mists. "Know that I love you always..."' WHERE `word_id` = 7428; -- db_script_string - content : entry=2000005344
UPDATE `trans_words` SET `content_loc8`='And who do we have here?  No doubt th... crzzzk ...ade this communication possible?  I give you greetings fro... psshzzzk... Azure Watch.' WHERE `word_id` = 268219; -- db_script_string - content : entry=2000005549
UPDATE `trans_words` SET `content_loc8`='begins a spell of summoning...' WHERE `word_id` = 7591; -- db_script_string - content : entry=2000000043
UPDATE `trans_words` SET `content_loc8`='BY THE LIGHT OF ELUNE! Eredar! Cursed demons, what have you to me? I have not come alone, we will fight you as we have in the past! I...' WHERE `word_id` = 7636; -- db_script_string - content : entry=2000000660
UPDATE `trans_words` SET `content_loc8`='Children if you would please follow me, we will now be going to see the keep where King Anduin Wrynn himself sits on this throne.' WHERE `word_id` = 7113; -- db_script_string - content : entry=2000005136
UPDATE `trans_words` SET `content_loc8`='Fizzles used to be a great wizard. But got turned into a rabbit when one of his spells went bad.' WHERE `word_id` = 7144; -- db_script_string - content : entry=2000005184
UPDATE `trans_words` SET `content_loc8`='Fresh bread for sale' WHERE `word_id` = 7515; -- db_script_string - content : entry=2000005099
UPDATE `trans_words` SET `content_loc8`='Get it while its hot' WHERE `word_id` = 7516; -- db_script_string - content : entry=2000005100
UPDATE `trans_words` SET `content_loc8`='Glowing Soulgem bursts open!' WHERE `word_id` = 6967; -- db_script_string - content : entry=2000000078
UPDATE `trans_words` SET `content_loc8`='Hey, you there. Want some candy?' WHERE `word_id` = 7492; -- db_script_string - content : entry=2000005052
UPDATE `trans_words` SET `content_loc8`='Just sit right back and you\'ll hear a ta... *hic* a tai... *hic* a taiii *hic* Damnit!' WHERE `word_id` = 7156; -- db_script_string - content : entry=2000005233
UPDATE `trans_words` SET `content_loc8`='New posting up! Adventurers and heroes, gather round the bulletin board!' WHERE `word_id` = 7482; -- db_script_string - content : entry=2000005042
UPDATE `trans_words` SET `content_loc8`='Of Course Im talking to myself. Only way to get a decent conversation in this city.' WHERE `word_id` = 7519; -- db_script_string - content : entry=2000005105
UPDATE `trans_words` SET `content_loc8`='Oh no! They a here!' WHERE `word_id` = 7587; -- db_script_string - content : entry=2000000013
UPDATE `trans_words` SET `content_loc8`='Oh, hello Grimclaw.' WHERE `word_id` = 7588; -- db_script_string - content : entry=2000000014
UPDATE `trans_words` SET `content_loc8`='Ok, $N. Now i can go the the Auberdine alone. Go to Terenthis. He waits for you. Thanks for the help.' WHERE `word_id` = 7589; -- db_script_string - content : entry=2000000015
UPDATE `trans_words` SET `content_loc8`='Ok, good luck friend. Thanks for the help.' WHERE `word_id` = 7590; -- db_script_string - content : entry=2000000016
UPDATE `trans_words` SET `content_loc8`='Ok, let\'s get started!' WHERE `word_id` = 7422; -- db_script_string - content : entry=2000000096
UPDATE `trans_words` SET `content_loc8`='Our oldest clutch of dragons are still far from maturity, but with patience and study, we are confident the dragons will soon be ready.' WHERE `word_id` = 7078; -- db_script_string - content : entry=2000005029
UPDATE `trans_words` SET `content_loc8`='Sure Paige. Just be gentle.' WHERE `word_id` = 7141; -- db_script_string - content : entry=2000005181
UPDATE `trans_words` SET `content_loc8`='The boss wants all hands on high alert. The rusty anchor sinks tonight.' WHERE `word_id` = 7225; -- db_script_string - content : entry=2000005408
UPDATE `trans_words` SET `content_loc8`='The Darkmoon Faire is the greatest event in all of Outland' WHERE `word_id` = 7540; -- db_script_string - content : entry=2000005221
UPDATE `trans_words` SET `content_loc8`='This is the last time that I buy second-hand equipment from ethereal' WHERE `word_id` = 7466; -- db_script_string - content : entry=2000005067
UPDATE `trans_words` SET `content_loc8`='This makes sense!' WHERE `word_id` = 6955; -- db_script_string - content : entry=2000000030
UPDATE `trans_words` SET `content_loc8`='Volcor need help ?' WHERE `word_id` = 6943; -- db_script_string - content : entry=2000000010
UPDATE `trans_words` SET `content_loc8`='Who? The Tauren Chieftains! What? A live performance. Where? The World\'s End Tavern! When? The top of the hour! BE THERE!' WHERE `word_id` = 7439; -- db_script_string - content : entry=2000005305
UPDATE `trans_words` SET `content_loc8`='Yes you may, $N. But do not stray too far from home.' WHERE `word_id` = 7506; -- db_script_string - content : entry=2000005321

SET NAMES 'latin1';
