-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc3`='"Lowly"? I don\'t care who you are friend, no one refers to the mighty Millhouse Manastorm as "Lowly"! I have no idea what goes on here, but I will gladly join your fight against this impudent imbecile! Prepare to defend yourself, cretin!' WHERE `word_id` = 1819; -- script_texts - content : entry=-1552011
UPDATE `trans_words` SET `content_loc3`='$N, I sentance you to death!' WHERE `word_id` = 2412; -- script_texts - content : entry=-1999906
UPDATE `trans_words` SET `content_loc3`='%s acquires a new target!' WHERE `word_id` = 2041; -- script_texts - content : entry=-1564010
UPDATE `trans_words` SET `content_loc3`='%s begins to channel arcane energy...' WHERE `word_id` = 1942; -- script_texts - content : entry=-1556015
UPDATE `trans_words` SET `content_loc3`='%s begins to channel from the nearby Fel Crystal...' WHERE `word_id` = 2383; -- script_texts - content : entry=-1585006
UPDATE `trans_words` SET `content_loc3`='%s begins to rust.' WHERE `word_id` = 1449; -- script_texts - content : entry=-1532038
UPDATE `trans_words` SET `content_loc3`='%s casts Condemation on everyone!' WHERE `word_id` = 1275; -- script_texts - content : entry=-1533157
UPDATE `trans_words` SET `content_loc3`='%s cheats!' WHERE `word_id` = 1543; -- script_texts - content : entry=-1532132
UPDATE `trans_words` SET `content_loc3`='%s cries out in withdrawal, opening gates to the warp.' WHERE `word_id` = 1500; -- script_texts - content : entry=-1532089
UPDATE `trans_words` SET `content_loc3`='%s descends from the sky.' WHERE `word_id` = 1667; -- script_texts - content : entry=-1543025
UPDATE `trans_words` SET `content_loc3`='%s discharges pure energy!' WHERE `word_id` = 2388; -- script_texts - content : entry=-1585011
UPDATE `trans_words` SET `content_loc3`='%s draws energy from the air.' WHERE `word_id` = 1927; -- script_texts - content : entry=-1555036
UPDATE `trans_words` SET `content_loc3`='%s enrages!' WHERE `word_id` = 1616; -- script_texts - content : entry=-1540041
UPDATE `trans_words` SET `content_loc3`='%s hisses' WHERE `word_id` = 706; -- script_texts - content : entry=-1000872
UPDATE `trans_words` SET `content_loc3`='%s punches the ground in anger!' WHERE `word_id` = 2042; -- script_texts - content : entry=-1564011
UPDATE `trans_words` SET `content_loc3`='%s reaches into his pack and pulls out the encoded tablets...' WHERE `word_id` = 692; -- script_texts - content : entry=-1000858
UPDATE `trans_words` SET `content_loc3`='%s reads from the tablets. Unknown, unheard sounds flow through your consciousness' WHERE `word_id` = 695; -- script_texts - content : entry=-1000861
UPDATE `trans_words` SET `content_loc3`='%s salutes $N.' WHERE `word_id` = 1356; -- script_texts - content : entry=-1000904
UPDATE `trans_words` SET `content_loc3`='%s sets his gaze on $N!' WHERE `word_id` = 1800; -- script_texts - content : entry=-1550037
UPDATE `trans_words` SET `content_loc3`='%s startles the horse with a fierce yell!' WHERE `word_id` = 1981; -- script_texts - content : entry=-1560006
UPDATE `trans_words` SET `content_loc3`='%s surveys the ground for the buried raven stones.' WHERE `word_id` = 2454; -- script_texts - content : entry=-1000964
UPDATE `trans_words` SET `content_loc3`='%s tries to calm the horse down.' WHERE `word_id` = 1984; -- script_texts - content : entry=-1560009
UPDATE `trans_words` SET `content_loc3`='...no...how could you let me die $N' WHERE `word_id` = 2423; -- script_texts - content : entry=-1999917
UPDATE `trans_words` SET `content_loc3`='<babbling>' WHERE `word_id` = 2065; -- script_texts - content : entry=-1564034
UPDATE `trans_words` SET `content_loc3`='<laugh> Now, you\'ll stay for eternity!' WHERE `word_id` = 1973; -- script_texts - content : entry=-1558008
UPDATE `trans_words` SET `content_loc3`='<maniacal cackle>' WHERE `word_id` = 2094; -- script_texts - content : entry=-1564064
UPDATE `trans_words` SET `content_loc3`='<squawk>' WHERE `word_id` = 1940; -- script_texts - content : entry=-1556012
UPDATE `trans_words` SET `content_loc3`='<squawk>..Trinkets yes pretty Trinkets..<squawk>..power, great power.<squawk>..power in Trinkets..<squawk>' WHERE `word_id` = 1935; -- script_texts - content : entry=-1556007
UPDATE `trans_words` SET `content_loc3`='A $C! Slaying him would please the master. Attack!' WHERE `word_id` = 613; -- script_texts - content : entry=-1000775
UPDATE `trans_words` SET `content_loc3`='A rider approaches!' WHERE `word_id` = 1998; -- script_texts - content : entry=-1560025
UPDATE `trans_words` SET `content_loc3`='Aaaahrg...' WHERE `word_id` = 2067; -- script_texts - content : entry=-1564036
UPDATE `trans_words` SET `content_loc3`='Aaahhh! Help me, before I lose my mind!' WHERE `word_id` = 2277; -- script_texts - content : entry=-1580007
UPDATE `trans_words` SET `content_loc3`='Achor-she-ki! Feast my pet! Eat your fill!' WHERE `word_id` = 1655; -- script_texts - content : entry=-1543012
UPDATE `trans_words` SET `content_loc3`='Aggh! No longer will I be a slave to Malygos! Challenge me and you will be destroyed!' WHERE `word_id` = 2270; -- script_texts - content : entry=-1580000
UPDATE `trans_words` SET `content_loc3`='Ah ah ah...' WHERE `word_id` = 1430; -- script_texts - content : entry=-1532019
UPDATE `trans_words` SET `content_loc3`='Ah ha ha ha ha ha ha!' WHERE `word_id` = 1705; -- script_texts - content : entry=-1545022
UPDATE `trans_words` SET `content_loc3`='Ah, lambs to the slaughter!' WHERE `word_id` = 1104; -- script_texts - content : entry=-1531026
UPDATE `trans_words` SET `content_loc3`='Ah, there you are. I had hoped to accomplish this with a bit of subtlety, but I suppose direct confrontation was inevitable. Your future, Thrall, must not come to pass and so...you and your troublesome friends must die!' WHERE `word_id` = 1990; -- script_texts - content : entry=-1560015
UPDATE `trans_words` SET `content_loc3`='Ah, you\'re just in time. The rituals are about to begin.' WHERE `word_id` = 1479; -- script_texts - content : entry=-1532068
UPDATE `trans_words` SET `content_loc3`='Aha-ha ha ha!' WHERE `word_id` = 2171; -- script_texts - content : entry=-1565007
UPDATE `trans_words` SET `content_loc3`='Ahh! More lambs to the slaughter!' WHERE `word_id` = 2292; -- script_texts - content : entry=-1580022
UPDATE `trans_words` SET `content_loc3`='Ahh, what a waste... Next!' WHERE `word_id` = 1581; -- script_texts - content : entry=-1540006
UPDATE `trans_words` SET `content_loc3`='Ahh... That is much better.' WHERE `word_id` = 1840; -- script_texts - content : entry=-1552032
UPDATE `trans_words` SET `content_loc3`='A-kreesh!' WHERE `word_id` = 1566; -- script_texts - content : entry=-1534022
UPDATE `trans_words` SET `content_loc3`='Alana be\'lendor!' WHERE `word_id` = 1735; -- script_texts - content : entry=-1548027
UPDATE `trans_words` SET `content_loc3`='Alert, you are marked for extermination!' WHERE `word_id` = 1764; -- script_texts - content : entry=-1550000
UPDATE `trans_words` SET `content_loc3`='All creation must be unmade!' WHERE `word_id` = 1902; -- script_texts - content : entry=-1555009
UPDATE `trans_words` SET `content_loc3`='All creation will be devoured!' WHERE `word_id` = 1568; -- script_texts - content : entry=-1534024
UPDATE `trans_words` SET `content_loc3`='All flesh must burn.' WHERE `word_id` = 1901; -- script_texts - content : entry=-1555008
UPDATE `trans_words` SET `content_loc3`='All of your efforts have been in vain, for the draining of the World Tree has already begun. Soon the heart of your world will beat no more.' WHERE `word_id` = 1562; -- script_texts - content : entry=-1534018
UPDATE `trans_words` SET `content_loc3`='All the better to own you with!' WHERE `word_id` = 1454; -- script_texts - content : entry=-1532043
UPDATE `trans_words` SET `content_loc3`='All you be doing is wasting my time!' WHERE `word_id` = 2213; -- script_texts - content : entry=-1568029
UPDATE `trans_words` SET `content_loc3`='Alright, pylon two down. Now for the heat mainfold.' WHERE `word_id` = 2552; -- script_texts - content : entry=-1000973
UPDATE `trans_words` SET `content_loc3`='Amateurs! Do not think you can best me! I kill for a living.' WHERE `word_id` = 1421; -- script_texts - content : entry=-1532010
UPDATE `trans_words` SET `content_loc3`='An epic battle. How exciting!' WHERE `word_id` = 1952; -- script_texts - content : entry=-1557002
UPDATE `trans_words` SET `content_loc3`='Anar\'alah belore!' WHERE `word_id` = 1805; -- script_texts - content : entry=-1550042
UPDATE `trans_words` SET `content_loc3`='Anar\'endal dracon!' WHERE `word_id` = 1880; -- script_texts - content : entry=-1554016
UPDATE `trans_words` SET `content_loc3`='And of course i\'ll need some mana. You guys are gonna love this, just wait.' WHERE `word_id` = 1822; -- script_texts - content : entry=-1552014
UPDATE `trans_words` SET `content_loc3`='Anger... Hate... These are tools I can use.' WHERE `word_id` = 1637; -- script_texts - content : entry=-1542011
UPDATE `trans_words` SET `content_loc3`='Annihilate them!' WHERE `word_id` = 2389; -- script_texts - content : entry=-1585012
UPDATE `trans_words` SET `content_loc3`='Another step towards destruction!' WHERE `word_id` = 2340; -- script_texts - content : entry=-1580070
UPDATE `trans_words` SET `content_loc3`='Anu... bala belore...alon.' WHERE `word_id` = 1883; -- script_texts - content : entry=-1554019
UPDATE `trans_words` SET `content_loc3`='Anukh-Kyrie!' WHERE `word_id` = 2341; -- script_texts - content : entry=-1580071
UPDATE `trans_words` SET `content_loc3`='Anveena, I love you! Focus on my voice, come back for me now! Only you can cleanse the Sunwell!' WHERE `word_id` = 2355; -- script_texts - content : entry=-1580085
UPDATE `trans_words` SET `content_loc3`='Anveena, you must awaken, this world needs you!' WHERE `word_id` = 2351; -- script_texts - content : entry=-1580081
UPDATE `trans_words` SET `content_loc3`='Arrgh, aah...ahhh' WHERE `word_id` = 1918; -- script_texts - content : entry=-1555027
UPDATE `trans_words` SET `content_loc3`='As it should be!' WHERE `word_id` = 2120; -- script_texts - content : entry=-1564091
UPDATE `trans_words` SET `content_loc3`='As you see, I have many weapons in my arsenal...' WHERE `word_id` = 1785; -- script_texts - content : entry=-1550021
UPDATE `trans_words` SET `content_loc3`='At last it is here. Mourn and lament the passing of all you have ever known and all that would have been! Akmin-kurai!' WHERE `word_id` = 1571; -- script_texts - content : entry=-1534027
UPDATE `trans_words` SET `content_loc3`='At last... The nightmare is.. over...' WHERE `word_id` = 1498; -- script_texts - content : entry=-1532087
UPDATE `trans_words` SET `content_loc3`='Away vermin!' WHERE `word_id` = 1567; -- script_texts - content : entry=-1534023
UPDATE `trans_words` SET `content_loc3`='Away, you mindless parasites. My blood is my own!' WHERE `word_id` = 1671; -- script_texts - content : entry=-1544003
UPDATE `trans_words` SET `content_loc3`='Azzaga choogo zinn!' WHERE `word_id` = 2232; -- script_texts - content : entry=-1568048
UPDATE `trans_words` SET `content_loc3`='Ba\'ahntha sol\'dorei!' WHERE `word_id` = 1703; -- script_texts - content : entry=-1545020
UPDATE `trans_words` SET `content_loc3`='Back to being an old rustbucket.' WHERE `word_id` = 1447; -- script_texts - content : entry=-1532036
UPDATE `trans_words` SET `content_loc3`='Bal\'amer ch\'itah!' WHERE `word_id` = 2038; -- script_texts - content : entry=-1564007
UPDATE `trans_words` SET `content_loc3`='Be careful what you wish for...' WHERE `word_id` = 2089; -- script_texts - content : entry=-1564059
UPDATE `trans_words` SET `content_loc3`='Be ready for Dark One\'s return.' WHERE `word_id` = 1911; -- script_texts - content : entry=-1555018
UPDATE `trans_words` SET `content_loc3`='Be wary friends, The Betrayer meditates in the court just beyond.' WHERE `word_id` = 2149; -- script_texts - content : entry=-1564120
UPDATE `trans_words` SET `content_loc3`='Be\'lamere an\'delay' WHERE `word_id` = 1761; -- script_texts - content : entry=-1548054
UPDATE `trans_words` SET `content_loc3`='Beg for your pittyfull life!' WHERE `word_id` = 1584; -- script_texts - content : entry=-1540009
UPDATE `trans_words` SET `content_loc3`='Beg... for life' WHERE `word_id` = 2178; -- script_texts - content : entry=-1565014
UPDATE `trans_words` SET `content_loc3`='Behold another terrifying creature of incomprehensible power!' WHERE `word_id` = 1834; -- script_texts - content : entry=-1552026
UPDATE `trans_words` SET `content_loc3`='Bel\'anen dal\'lorei!' WHERE `word_id` = 2036; -- script_texts - content : entry=-1564005
UPDATE `trans_words` SET `content_loc3`='Belesa menoor!' WHERE `word_id` = 2121; -- script_texts - content : entry=-1564092
UPDATE `trans_words` SET `content_loc3`='Beware! We are attacked!' WHERE `word_id` = 1363; -- script_texts - content : entry=-1000913
UPDATE `trans_words` SET `content_loc3`='Beware, coward.' WHERE `word_id` = 2097; -- script_texts - content : entry=-1564067
UPDATE `trans_words` SET `content_loc3`='Bleed as I have bled!' WHERE `word_id` = 2146; -- script_texts - content : entry=-1564117
UPDATE `trans_words` SET `content_loc3`='Blood will flow!' WHERE `word_id` = 2037; -- script_texts - content : entry=-1564006
UPDATE `trans_words` SET `content_loc3`='Boldly said. But I remain unconvinced.' WHERE `word_id` = 2128; -- script_texts - content : entry=-1564099
UPDATE `trans_words` SET `content_loc3`='Burn you hellish fiends!' WHERE `word_id` = 1488; -- script_texts - content : entry=-1532077
UPDATE `trans_words` SET `content_loc3`='But beware, for not all love stories end happily, as you may find out. Sometimes, love pricks like a thorn.' WHERE `word_id` = 1524; -- script_texts - content : entry=-1532113
UPDATE `trans_words` SET `content_loc3`='But don\'t let me pull the wool over your eyes. See for yourself what lies beneath those covers! And now... on with the show!' WHERE `word_id` = 1521; -- script_texts - content : entry=-1532110
UPDATE `trans_words` SET `content_loc3`='But don\'t take it from me, see for yourself what tragedy lies ahead when the paths of star-crossed lovers meet. And now...on with the show!' WHERE `word_id` = 1525; -- script_texts - content : entry=-1532114
UPDATE `trans_words` SET `content_loc3`='But she is pursued... by a wicked malevolent crone!' WHERE `word_id` = 1516; -- script_texts - content : entry=-1532105
UPDATE `trans_words` SET `content_loc3`='By the Tides, kill them at once!' WHERE `word_id` = 1739; -- script_texts - content : entry=-1548031
UPDATE `trans_words` SET `content_loc3`='Bye Bye!' WHERE `word_id` = 2421; -- script_texts - content : entry=-1999915
UPDATE `trans_words` SET `content_loc3`='Can it be ?' WHERE `word_id` = 2371; -- script_texts - content : entry=-1580101
UPDATE `trans_words` SET `content_loc3`='Chaga... choka\'jinn.' WHERE `word_id` = 2226; -- script_texts - content : entry=-1568042
UPDATE `trans_words` SET `content_loc3`='Champions, my shield grows weak!' WHERE `word_id` = 1404; -- script_texts - content : entry=-1269022
UPDATE `trans_words` SET `content_loc3`='Chaos!' WHERE `word_id` = 2344; -- script_texts - content : entry=-1580074
UPDATE `trans_words` SET `content_loc3`='Chaos...' WHERE `word_id` = 2319; -- script_texts - content : entry=-1580049
UPDATE `trans_words` SET `content_loc3`='Closer... Come closer.. and burn!' WHERE `word_id` = 1632; -- script_texts - content : entry=-1542006
UPDATE `trans_words` SET `content_loc3`='Come on! ... Show me a real fight.' WHERE `word_id` = 1588; -- script_texts - content : entry=-1540013
UPDATE `trans_words` SET `content_loc3`='Come to my aid, heed your master now!' WHERE `word_id` = 1923; -- script_texts - content : entry=-1555032
UPDATE `trans_words` SET `content_loc3`='Come, and join me bruddahs!' WHERE `word_id` = 2212; -- script_texts - content : entry=-1568028
UPDATE `trans_words` SET `content_loc3`='Come, fools. Fill ma empty cages...' WHERE `word_id` = 2227; -- script_texts - content : entry=-1568043
UPDATE `trans_words` SET `content_loc3`='Come, friends. Your bodies gonna feed ma hatchlings, and your souls are going to feed me with power!' WHERE `word_id` = 2193; -- script_texts - content : entry=-1568009
UPDATE `trans_words` SET `content_loc3`='Come, strangers. The spirit of the dragonhawk hot be hungry for worthy souls.' WHERE `word_id` = 2192; -- script_texts - content : entry=-1568008
UPDATE `trans_words` SET `content_loc3`='Come, try your luck!' WHERE `word_id` = 2291; -- script_texts - content : entry=-1580021
UPDATE `trans_words` SET `content_loc3`='Come, you dwellers in the dark. Rally to my call!' WHERE `word_id` = 1482; -- script_texts - content : entry=-1532071
UPDATE `trans_words` SET `content_loc3`='Come... and die.' WHERE `word_id` = 2174; -- script_texts - content : entry=-1565010
UPDATE `trans_words` SET `content_loc3`='Completely ineffective. Just like someone else I know.' WHERE `word_id` = 1842; -- script_texts - content : entry=-1552034
UPDATE `trans_words` SET `content_loc3`='Cowards! You\'ll never pull me into the shadows!' WHERE `word_id` = 1623; -- script_texts - content : entry=-1540048
UPDATE `trans_words` SET `content_loc3`='Da Amani de chuka!' WHERE `word_id` = 2248; -- script_texts - content : entry=-1568064
UPDATE `trans_words` SET `content_loc3`='Da eagles gonna bear your spirits to me. Your sacrifice is not gonna be in vein!' WHERE `word_id` = 2208; -- script_texts - content : entry=-1568024
UPDATE `trans_words` SET `content_loc3`='Da shadow gonna fall on you...' WHERE `word_id` = 2229; -- script_texts - content : entry=-1568045
UPDATE `trans_words` SET `content_loc3`='Dark one promise!' WHERE `word_id` = 1913; -- script_texts - content : entry=-1555020
UPDATE `trans_words` SET `content_loc3`='Darkness comin\' for you...' WHERE `word_id` = 2234; -- script_texts - content : entry=-1568050
UPDATE `trans_words` SET `content_loc3`='Death is close...' WHERE `word_id` = 1111; -- script_texts - content : entry=-1531033
UPDATE `trans_words` SET `content_loc3`='Death.. meeting life is.. <squawking>' WHERE `word_id` = 1932; -- script_texts - content : entry=-1556004
UPDATE `trans_words` SET `content_loc3`='Death... really isn\'t so bad.' WHERE `word_id` = 2073; -- script_texts - content : entry=-1564042
UPDATE `trans_words` SET `content_loc3`='De-ek Anur!' WHERE `word_id` = 2332; -- script_texts - content : entry=-1580062
UPDATE `trans_words` SET `content_loc3`='Defend yourself, for all the good it will do...' WHERE `word_id` = 1853; -- script_texts - content : entry=-1552045
UPDATE `trans_words` SET `content_loc3`='Destroy them my subjects!' WHERE `word_id` = 1740; -- script_texts - content : entry=-1548032
UPDATE `trans_words` SET `content_loc3`='Did you think me weak? Soft? Who is the weak one now?!' WHERE `word_id` = 1678; -- script_texts - content : entry=-1544010
UPDATE `trans_words` SET `content_loc3`='Die scum!' WHERE `word_id` = 2417; -- script_texts - content : entry=-1999911
UPDATE `trans_words` SET `content_loc3`='Die' WHERE `word_id` = 2181; -- script_texts - content : entry=-1565017
UPDATE `trans_words` SET `content_loc3`='Diel ma\'ahn... oreindel\'o' WHERE `word_id` = 2125; -- script_texts - content : entry=-1564096
UPDATE `trans_words` SET `content_loc3`='DING!' WHERE `word_id` = 952; -- script_texts - content : entry=-1309016
UPDATE `trans_words` SET `content_loc3`='Dis not... da end of me...' WHERE `word_id` = 2239; -- script_texts - content : entry=-1568055
UPDATE `trans_words` SET `content_loc3`='Do not harbor false hope. You cannot win!' WHERE `word_id` = 2348; -- script_texts - content : entry=-1580078
UPDATE `trans_words` SET `content_loc3`='Do not proceed. You will be eliminated!' WHERE `word_id` = 1329; -- script_texts - content : entry=-1000159
UPDATE `trans_words` SET `content_loc3`='Do not... get too comfortable.' WHERE `word_id` = 2405; -- script_texts - content : entry=-1585028
UPDATE `trans_words` SET `content_loc3`='Do not...grow...overconfident, mortal.' WHERE `word_id` = 1900; -- script_texts - content : entry=-1555007
UPDATE `trans_words` SET `content_loc3`='Do you smell that? Fresh meat has somehow breached our citadel. Be wary of any intruders.' WHERE `word_id` = 1643; -- script_texts - content : entry=-1543000
UPDATE `trans_words` SET `content_loc3`='Don\'t be delayin\' your fate. Come to me now. I make your sacrifice quick.' WHERE `word_id` = 2199; -- script_texts - content : entry=-1568015
UPDATE `trans_words` SET `content_loc3`='Don\'t cross those beams!' WHERE `word_id` = 967; -- script_texts - content : entry=-1329003
UPDATE `trans_words` SET `content_loc3`='Don\'t let them make a mattress... out of me.' WHERE `word_id` = 1444; -- script_texts - content : entry=-1532033
UPDATE `trans_words` SET `content_loc3`='Don\'t waste your time on that one. He\'s weak!' WHERE `word_id` = 1578; -- script_texts - content : entry=-1540003
UPDATE `trans_words` SET `content_loc3`='Drink your blood! Eat your flesh!' WHERE `word_id` = 2063; -- script_texts - content : entry=-1564032
UPDATE `trans_words` SET `content_loc3`='Ed-ir Halach!' WHERE `word_id` = 2331; -- script_texts - content : entry=-1580061
UPDATE `trans_words` SET `content_loc3`='Ee-nok Kryul!' WHERE `word_id` = 2325; -- script_texts - content : entry=-1580055
UPDATE `trans_words` SET `content_loc3`='En\'dala finel el\'dal' WHERE `word_id` = 1882; -- script_texts - content : entry=-1554018
UPDATE `trans_words` SET `content_loc3`='Endorel aluminor!' WHERE `word_id` = 1867; -- script_texts - content : entry=-1553003
UPDATE `trans_words` SET `content_loc3`='Energy. Power. My people are addicted to it... a dependence made manifest after the Sunwell was destroyed. Welcome... to the future. A pity you are too late to stop it. No one can stop me now! Selama ashal\'anore!' WHERE `word_id` = 1780; -- script_texts - content : entry=-1550016
UPDATE `trans_words` SET `content_loc3`='Enjoy the storm, warm bloods!' WHERE `word_id` = 1707; -- script_texts - content : entry=-1545024
UPDATE `trans_words` SET `content_loc3`='Enjoy your final moments!' WHERE `word_id` = 2107; -- script_texts - content : entry=-1564077
UPDATE `trans_words` SET `content_loc3`='Enough of this! Now I call upon the fury of the cosmos itself.' WHERE `word_id` = 1778; -- script_texts - content : entry=-1550014
UPDATE `trans_words` SET `content_loc3`='Enough. No more.' WHERE `word_id` = 2095; -- script_texts - content : entry=-1564065
UPDATE `trans_words` SET `content_loc3`='Everybody always wanna take from us. Now we gonna start takin\' back. Anybody who get in our way...gonna drown in dey own blood! Da Amani empire be back now...seekin\' vengeance. And we gonna start wit\' you.' WHERE `word_id` = 2240; -- script_texts - content : entry=-1568056
UPDATE `trans_words` SET `content_loc3`='Extermination, successful.' WHERE `word_id` = 1765; -- script_texts - content : entry=-1550001
UPDATE `trans_words` SET `content_loc3`='Facing difficulties, Dalliah? How nice.' WHERE `word_id` = 1849; -- script_texts - content : entry=-1552041
UPDATE `trans_words` SET `content_loc3`='Fantastic! Next, some protective spells. Yes! Now we\'re cookin\'' WHERE `word_id` = 1821; -- script_texts - content : entry=-1552013
UPDATE `trans_words` SET `content_loc3`='Felomin ashal!' WHERE `word_id` = 2402; -- script_texts - content : entry=-1585025
UPDATE `trans_words` SET `content_loc3`='Finally! Something to relieve the tedium!' WHERE `word_id` = 1896; -- script_texts - content : entry=-1555003
UPDATE `trans_words` SET `content_loc3`='Finally! Well done!' WHERE `word_id` = 1851; -- script_texts - content : entry=-1552043
UPDATE `trans_words` SET `content_loc3`='Fire, consume!' WHERE `word_id` = 2330; -- script_texts - content : entry=-1580060
UPDATE `trans_words` SET `content_loc3`='Fixed you, didn\'t I? <cackles>' WHERE `word_id` = 1453; -- script_texts - content : entry=-1532042
UPDATE `trans_words` SET `content_loc3`='Flee in terror!' WHERE `word_id` = 1814; -- script_texts - content : entry=-1552006
UPDATE `trans_words` SET `content_loc3`='Foolsss...Kill the one in the dress!' WHERE `word_id` = 881; -- script_texts - content : entry=-1229006
UPDATE `trans_words` SET `content_loc3`='Fulfilment is at hand!' WHERE `word_id` = 2086; -- script_texts - content : entry=-1564056
UPDATE `trans_words` SET `content_loc3`='Gah! Well done... Now... this gets... interesting...' WHERE `word_id` = 2300; -- script_texts - content : entry=-1580030
UPDATE `trans_words` SET `content_loc3`='Gather, my pets. There is plenty for all.' WHERE `word_id` = 1483; -- script_texts - content : entry=-1532072
UPDATE `trans_words` SET `content_loc3`='Gaz now, mortals - upon the HEART OF M\'URU! Umblemished. Bathed by the light of Creation - just as it was at the Dawn.' WHERE `word_id` = 2372; -- script_texts - content : entry=-1580102
UPDATE `trans_words` SET `content_loc3`='Give in to your fear!' WHERE `word_id` = 2142; -- script_texts - content : entry=-1564113
UPDATE `trans_words` SET `content_loc3`='Give in!' WHERE `word_id` = 2074; -- script_texts - content : entry=-1564043
UPDATE `trans_words` SET `content_loc3`='Good evening, Ladies and Gentlemen! Welcome to this evening\'s presentation!' WHERE `word_id` = 1518; -- script_texts - content : entry=-1532107
UPDATE `trans_words` SET `content_loc3`='Good luck... you\'ll need it..' WHERE `word_id` = 1633; -- script_texts - content : entry=-1542007
UPDATE `trans_words` SET `content_loc3`='Good, a worthy sacrifice.' WHERE `word_id` = 1922; -- script_texts - content : entry=-1555031
UPDATE `trans_words` SET `content_loc3`='Goodbye, Anveena, my love. Few will remember your name, yet this day you change the course of destiny. What was once corrupt is now pure. Heroes, do not let her sacrifice be in vain.' WHERE `word_id` = 2359; -- script_texts - content : entry=-1580089
UPDATE `trans_words` SET `content_loc3`='Grah! Your magic is weak!' WHERE `word_id` = 2288; -- script_texts - content : entry=-1580018
UPDATE `trans_words` SET `content_loc3`='Grark Lorkrub, you have been charged and found guilty of treason against Horde. How you plead is unimportant. High Executioner Nuzrak, step forward.' WHERE `word_id` = 717; -- script_texts - content : entry=-1000884
UPDATE `trans_words` SET `content_loc3`='Great... currents of... Ageon.' WHERE `word_id` = 1746; -- script_texts - content : entry=-1548038
UPDATE `trans_words` SET `content_loc3`='Gronn are the real power in outland.' WHERE `word_id` = 2164; -- script_texts - content : entry=-1565000
UPDATE `trans_words` SET `content_loc3`='Gruul... will crush you...' WHERE `word_id` = 2173; -- script_texts - content : entry=-1565009
UPDATE `trans_words` SET `content_loc3`='Guards, attention! We have visitors...' WHERE `word_id` = 1729; -- script_texts - content : entry=-1548021
UPDATE `trans_words` SET `content_loc3`='Gul\'dan speaks the truth! We should return at once to tell our brothers of the news! Retreat back trought the portal!' WHERE `word_id` = 1410; -- script_texts - content : entry=-1269028
UPDATE `trans_words` SET `content_loc3`='Ha ha ha! You are hopelessly outmatched!' WHERE `word_id` = 1772; -- script_texts - content : entry=-1550008
UPDATE `trans_words` SET `content_loc3`='Ha ha ha.' WHERE `word_id` = 1607; -- script_texts - content : entry=-1540032
UPDATE `trans_words` SET `content_loc3`='Hahah.. <cough> ..argh!' WHERE `word_id` = 1651; -- script_texts - content : entry=-1543008
UPDATE `trans_words` SET `content_loc3`='Hail our leader! Hail Akama!' WHERE `word_id` = 2047; -- script_texts - content : entry=-1564016
UPDATE `trans_words` SET `content_loc3`='Harken, cur! Tis you I spurn! Now, $N, feel the burn!' WHERE `word_id` = 1374; -- script_texts - content : entry=-1189026
UPDATE `trans_words` SET `content_loc3`='Have you come to kill Dalliah? Can I watch?' WHERE `word_id` = 1847; -- script_texts - content : entry=-1552039
UPDATE `trans_words` SET `content_loc3`='Heal me! Oh, for the love of all that is holy, HEAL me! I\'m dying!' WHERE `word_id` = 1828; -- script_texts - content : entry=-1552020
UPDATE `trans_words` SET `content_loc3`='Heal me! QUICKLY!' WHERE `word_id` = 1644; -- script_texts - content : entry=-1543001
UPDATE `trans_words` SET `content_loc3`='Heh... this may hurt a little.' WHERE `word_id` = 1647; -- script_texts - content : entry=-1543004
UPDATE `trans_words` SET `content_loc3`='Help $N! I\'m under attack!' WHERE `word_id` = 2416; -- script_texts - content : entry=-1999910
UPDATE `trans_words` SET `content_loc3`='Help us, hurry!' WHERE `word_id` = 1909; -- script_texts - content : entry=-1555016
UPDATE `trans_words` SET `content_loc3`='Her ... excellency ... awaits!' WHERE `word_id` = 1737; -- script_texts - content : entry=-1548029
UPDATE `trans_words` SET `content_loc3`='Hey you numbskull!' WHERE `word_id` = 1606; -- script_texts - content : entry=-1540031
UPDATE `trans_words` SET `content_loc3`='Hmm a nice day for a walk alright' WHERE `word_id` = 2418; -- script_texts - content : entry=-1999912
UPDATE `trans_words` SET `content_loc3`='Hmm, I think I could use a buff.' WHERE `word_id` = 2427; -- script_texts - content : entry=-1999921
UPDATE `trans_words` SET `content_loc3`='Hmm, now where is the next collector?' WHERE `word_id` = 2436; -- script_texts - content : entry=-1557019
UPDATE `trans_words` SET `content_loc3`='Hmm, unannounced visitors? Preparations must be made.' WHERE `word_id` = 1422; -- script_texts - content : entry=-1532011
UPDATE `trans_words` SET `content_loc3`='Hold them back as long as possible.' WHERE `word_id` = 1548; -- script_texts - content : entry=-1534004
UPDATE `trans_words` SET `content_loc3`='How can you hope to withstand against such overwhelming power?' WHERE `word_id` = 1507; -- script_texts - content : entry=-1532096
UPDATE `trans_words` SET `content_loc3`='How could you? What a cruel, cruel world!' WHERE `word_id` = 1452; -- script_texts - content : entry=-1532041
UPDATE `trans_words` SET `content_loc3`='How dare you leave me like that! I hate you! =*(' WHERE `word_id` = 2422; -- script_texts - content : entry=-1999916
UPDATE `trans_words` SET `content_loc3`='How long do you beleive your pathetic sorcery can hold me?' WHERE `word_id` = 1642; -- script_texts - content : entry=-1542016
UPDATE `trans_words` SET `content_loc3`='How terribly clumsy of me...' WHERE `word_id` = 1428; -- script_texts - content : entry=-1532017
UPDATE `trans_words` SET `content_loc3`='Hrrmm.. Time to.. hrrm.. make my move.' WHERE `word_id` = 1929; -- script_texts - content : entry=-1556001
UPDATE `trans_words` SET `content_loc3`='I always knew... someday I would become... the hunted.' WHERE `word_id` = 1419; -- script_texts - content : entry=-1532008
UPDATE `trans_words` SET `content_loc3`='I always thought I was a good dancer.' WHERE `word_id` = 2414; -- script_texts - content : entry=-1999908
UPDATE `trans_words` SET `content_loc3`='I am called Bladefist for a reason, as you will see!' WHERE `word_id` = 1619; -- script_texts - content : entry=-1540044
UPDATE `trans_words` SET `content_loc3`='I am gathering a bogbean. It takes some time.' WHERE `word_id` = 744; -- script_texts - content : entry=-1000961
UPDATE `trans_words` SET `content_loc3`='I am grateful for your aid, champions. Now, Gul\'dan\'s Horde will sweep across this world, like a locust swarm, and all my designs, all my carefully laid plans will at last fall into place.' WHERE `word_id` = 1408; -- script_texts - content : entry=-1269026
UPDATE `trans_words` SET `content_loc3`='I am... released...' WHERE `word_id` = 1712; -- script_texts - content : entry=-1548004
UPDATE `trans_words` SET `content_loc3`='I bet Quae\'ll think this is important. She\'s pretty knowledgeable about these things--no expert, but knowledgable.' WHERE `word_id` = 739; -- script_texts - content : entry=-1000954
UPDATE `trans_words` SET `content_loc3`='I bet you\'re sorry now, aren\'t you?' WHERE `word_id` = 908; -- script_texts - content : entry=-1230012
UPDATE `trans_words` SET `content_loc3`='I can feel your hatred.' WHERE `word_id` = 2141; -- script_texts - content : entry=-1564112
UPDATE `trans_words` SET `content_loc3`='I can make it the rest of the way. $N. THANKS!' WHERE `word_id` = 732; -- script_texts - content : entry=-1000906
UPDATE `trans_words` SET `content_loc3`='I could have sworn there were more of you.' WHERE `word_id` = 2395; -- script_texts - content : entry=-1585018
UPDATE `trans_words` SET `content_loc3`='I did not wish to lower myself by engaging your kind, but you leave me little choice!' WHERE `word_id` = 1755; -- script_texts - content : entry=-1548047
UPDATE `trans_words` SET `content_loc3`='I didn\'t even break a sweat on that one.' WHERE `word_id` = 1824; -- script_texts - content : entry=-1552016
UPDATE `trans_words` SET `content_loc3`='I DRAW CLOSER TO YOUR WORLD!' WHERE `word_id` = 847; -- script_texts - content : entry=-1109008
UPDATE `trans_words` SET `content_loc3`='I guess I\'m not a failure after all.' WHERE `word_id` = 1445; -- script_texts - content : entry=-1532034
UPDATE `trans_words` SET `content_loc3`='I had more fun torturing the peons.' WHERE `word_id` = 1589; -- script_texts - content : entry=-1540014
UPDATE `trans_words` SET `content_loc3`='I have longed for a good adventure.' WHERE `word_id` = 1953; -- script_texts - content : entry=-1557003
UPDATE `trans_words` SET `content_loc3`='I have no choice.' WHERE `word_id` = 1711; -- script_texts - content : entry=-1548003
UPDATE `trans_words` SET `content_loc3`='I have no equal.' WHERE `word_id` = 1720; -- script_texts - content : entry=-1548012
UPDATE `trans_words` SET `content_loc3`='I have pets..<squawk>..of my own!' WHERE `word_id` = 1928; -- script_texts - content : entry=-1556000
UPDATE `trans_words` SET `content_loc3`='I have use for you!' WHERE `word_id` = 2070; -- script_texts - content : entry=-1564039
UPDATE `trans_words` SET `content_loc3`='I just need to get some things ready first. You guys go ahead and get started. I need to summon up some water...' WHERE `word_id` = 1820; -- script_texts - content : entry=-1552012
UPDATE `trans_words` SET `content_loc3`='I need... your help... Cannot... resist him... much longer...' WHERE `word_id` = 2276; -- script_texts - content : entry=-1580006
UPDATE `trans_words` SET `content_loc3`='I prefeer to be hands-on...' WHERE `word_id` = 1888; -- script_texts - content : entry=-1554024
UPDATE `trans_words` SET `content_loc3`='I refuse to concede defeat. I am a prince of the Eredar! I am...' WHERE `word_id` = 1513; -- script_texts - content : entry=-1532102
UPDATE `trans_words` SET `content_loc3`='I see dead people!' WHERE `word_id` = 1906; -- script_texts - content : entry=-1555013
UPDATE `trans_words` SET `content_loc3`='I see endless suffering. I see torment. I see rage. I see everything.' WHERE `word_id` = 2409; -- script_texts - content : entry=-1999901
UPDATE `trans_words` SET `content_loc3`='I see the subtlety of conception is beyond primitives such as you.' WHERE `word_id` = 1504; -- script_texts - content : entry=-1532093
UPDATE `trans_words` SET `content_loc3`='I suggest a new strategy, you draw the attackers while I gather reinforcements. Hahaha!' WHERE `word_id` = 1850; -- script_texts - content : entry=-1552042
UPDATE `trans_words` SET `content_loc3`='I think I\'m going to go take fourty winks.' WHERE `word_id` = 1442; -- script_texts - content : entry=-1532031
UPDATE `trans_words` SET `content_loc3`='I was the first, you know. For me, the wheel of death has spun many times. <laughs> So much time has passed. I have a lot of catching up to do...' WHERE `word_id` = 2068; -- script_texts - content : entry=-1564037
UPDATE `trans_words` SET `content_loc3`='I wasn\'t... finished.' WHERE `word_id` = 2059; -- script_texts - content : entry=-1564028
UPDATE `trans_words` SET `content_loc3`='I will channel my power into the orbs, be ready!' WHERE `word_id` = 2361; -- script_texts - content : entry=-1580091
UPDATE `trans_words` SET `content_loc3`='I will feed on your soul.' WHERE `word_id` = 1958; -- script_texts - content : entry=-1557008
UPDATE `trans_words` SET `content_loc3`='I will fight to the last!' WHERE `word_id` = 2007; -- script_texts - content : entry=-1560035
UPDATE `trans_words` SET `content_loc3`='I will lie down for no one!' WHERE `word_id` = 1553; -- script_texts - content : entry=-1534009
UPDATE `trans_words` SET `content_loc3`='I will not be taken so easily. Let the walls of this prison tremble...and FALL!!!' WHERE `word_id` = 1677; -- script_texts - content : entry=-1544009
UPDATE `trans_words` SET `content_loc3`='I will not last much longer...' WHERE `word_id` = 2045; -- script_texts - content : entry=-1564014
UPDATE `trans_words` SET `content_loc3`='I will purge you from this place.' WHERE `word_id` = 1714; -- script_texts - content : entry=-1548006
UPDATE `trans_words` SET `content_loc3`='I will show you horrors undreamed of!' WHERE `word_id` = 1815; -- script_texts - content : entry=-1552007
UPDATE `trans_words` SET `content_loc3`='I won\'t be far...' WHERE `word_id` = 2091; -- script_texts - content : entry=-1564061
UPDATE `trans_words` SET `content_loc3`='I won\'t... be... ignored.' WHERE `word_id` = 2098; -- script_texts - content : entry=-1564068
UPDATE `trans_words` SET `content_loc3`='I\'ll be waiting...' WHERE `word_id` = 2090; -- script_texts - content : entry=-1564060
UPDATE `trans_words` SET `content_loc3`='I\'ll deal with these mongrels. Strike now, friends! Strike at the betrayer!' WHERE `word_id` = 2151; -- script_texts - content : entry=-1564122
UPDATE `trans_words` SET `content_loc3`='I\'ll deal with you later!' WHERE `word_id` = 2033; -- script_texts - content : entry=-1564002
UPDATE `trans_words` SET `content_loc3`='I\'ll show you this beaten dog still has some teeth!' WHERE `word_id` = 1487; -- script_texts - content : entry=-1532076
UPDATE `trans_words` SET `content_loc3`='I\'ll turn your world... upside... down...' WHERE `word_id` = 2403; -- script_texts - content : entry=-1585026
UPDATE `trans_words` SET `content_loc3`='I\'m already bored.' WHERE `word_id` = 1587; -- script_texts - content : entry=-1540012
UPDATE `trans_words` SET `content_loc3`='I\'m gonna enjoy this.' WHERE `word_id` = 1648; -- script_texts - content : entry=-1543005
UPDATE `trans_words` SET `content_loc3`='I\'m in jeopardy, help me if you can!' WHERE `word_id` = 1544; -- script_texts - content : entry=-1534000
UPDATE `trans_words` SET `content_loc3`='I\'m not afraid of you.' WHERE `word_id` = 2168; -- script_texts - content : entry=-1565004
UPDATE `trans_words` SET `content_loc3`='I\'m not finished yet! No, I have a few more tricks up me sleeve.' WHERE `word_id` = 1494; -- script_texts - content : entry=-1532083
UPDATE `trans_words` SET `content_loc3`='I\'m... never on... the losing... side...' WHERE `word_id` = 2281; -- script_texts - content : entry=-1580011
UPDATE `trans_words` SET `content_loc3`='I\'ve gone and made a mess.' WHERE `word_id` = 1427; -- script_texts - content : entry=-1532016
UPDATE `trans_words` SET `content_loc3`='I\'ve researched this site extensively and I won\'t allow any dim-witted treasure hunters to swoop in and steal what belongs to in a museum. I\'ll lead this charge.' WHERE `word_id` = 2265; -- script_texts - content : entry=-1568081
UPDATE `trans_words` SET `content_loc3`='Ice, ice, baby!' WHERE `word_id` = 1827; -- script_texts - content : entry=-1552019
UPDATE `trans_words` SET `content_loc3`='Ikiss cut you pretty..<squawk>..slice you. Yes!' WHERE `word_id` = 1937; -- script_texts - content : entry=-1556009
UPDATE `trans_words` SET `content_loc3`='Ikiss will not..<squawk>..die' WHERE `word_id` = 1941; -- script_texts - content : entry=-1556013
UPDATE `trans_words` SET `content_loc3`='Illidan is an arrogant fool. I will crush him and reclaim Outland as my own.' WHERE `word_id` = 1670; -- script_texts - content : entry=-1544002
UPDATE `trans_words` SET `content_loc3`='Imbecile life form, no longer functional.' WHERE `word_id` = 1766; -- script_texts - content : entry=-1550002
UPDATE `trans_words` SET `content_loc3`='Infidels have invaded the sanctuary! Sniveling pests...You have yet to learn the true meaning of agony!' WHERE `word_id` = 1893; -- script_texts - content : entry=-1555000
UPDATE `trans_words` SET `content_loc3`='Intruders are destroying our eggs! Stop!!' WHERE `word_id` = 895; -- script_texts - content : entry=-1229020
UPDATE `trans_words` SET `content_loc3`='Is there no one left to test me?' WHERE `word_id` = 1663; -- script_texts - content : entry=-1543021
UPDATE `trans_words` SET `content_loc3`='It gets worse...' WHERE `word_id` = 2071; -- script_texts - content : entry=-1564040
UPDATE `trans_words` SET `content_loc3`='It is a small matter to control the mind of the weak... for I bear allegiance to powers untouched by time, unmoved by fate. No force on this world or beyond harbors the strength to bend our knee... not even the mighty Legion!' WHERE `word_id` = 1808; -- script_texts - content : entry=-1552000
UPDATE `trans_words` SET `content_loc3`='It is only a matter...of time.' WHERE `word_id` = 1400; -- script_texts - content : entry=-1269017
UPDATE `trans_words` SET `content_loc3`='It is over, your search is done! Let fate choose now, the righteous one.' WHERE `word_id` = 1370; -- script_texts - content : entry=-1189022
UPDATE `trans_words` SET `content_loc3`='It is over. Finished!' WHERE `word_id` = 1664; -- script_texts - content : entry=-1543022
UPDATE `trans_words` SET `content_loc3`='It is over. Withdraw! We have failed.' WHERE `word_id` = 1559; -- script_texts - content : entry=-1534015
UPDATE `trans_words` SET `content_loc3`='It is unwise to anger me.' WHERE `word_id` = 1839; -- script_texts - content : entry=-1552031
UPDATE `trans_words` SET `content_loc3`='It looks like we have a ranking officer among our captives...how amusing. Execute the green-skinned dog at once!' WHERE `word_id` = 1625; -- script_texts - content : entry=-1540050
UPDATE `trans_words` SET `content_loc3`='It must be the purity of the Mark of the Lightbringer that is drawing forth the Scourge to us. We must proceed with caution lest we overwhelmed!' WHERE `word_id` = 1364; -- script_texts - content : entry=-1000914
UPDATE `trans_words` SET `content_loc3`='It will all be over soon! <cackles>' WHERE `word_id` = 1451; -- script_texts - content : entry=-1532040
UPDATE `trans_words` SET `content_loc3`='It\'s too late to turn away.' WHERE `word_id` = 1097; -- script_texts - content : entry=-1531019
UPDATE `trans_words` SET `content_loc3`='Join me brother, there is blood to be shed!' WHERE `word_id` = 1106; -- script_texts - content : entry=-1531028
UPDATE `trans_words` SET `content_loc3`='Kalec... Kalec?' WHERE `word_id` = 2356; -- script_texts - content : entry=-1580086
UPDATE `trans_words` SET `content_loc3`='Keep your minds focused for the days of reckoning are close at hand. Soon, the destroyer of worlds will return to make good on his promise. Soon the destruction of all that is will begin!' WHERE `word_id` = 1919; -- script_texts - content : entry=-1555028
UPDATE `trans_words` SET `content_loc3`='Kil\'jaeden... will... prevail...' WHERE `word_id` = 2312; -- script_texts - content : entry=-1580042
UPDATE `trans_words` SET `content_loc3`='Kill two monsters, who stay near Bogbean plant and then I gather a bogbean.' WHERE `word_id` = 743; -- script_texts - content : entry=-1000960
UPDATE `trans_words` SET `content_loc3`='Kill! KILL!' WHERE `word_id` = 1723; -- script_texts - content : entry=-1548015
UPDATE `trans_words` SET `content_loc3`='Kirel Narak!' WHERE `word_id` = 58; -- script_texts - content : entry=-1000152
UPDATE `trans_words` SET `content_loc3`='Kneel, Grark' WHERE `word_id` = 716; -- script_texts - content : entry=-1000883
UPDATE `trans_words` SET `content_loc3`='Knew this was... the only way out' WHERE `word_id` = 1854; -- script_texts - content : entry=-1552046
UPDATE `trans_words` SET `content_loc3`='Lackies be damned! I\'ll finish you myself!' WHERE `word_id` = 2393; -- script_texts - content : entry=-1585016
UPDATE `trans_words` SET `content_loc3`='Let none survive!' WHERE `word_id` = 1105; -- script_texts - content : entry=-1531027
UPDATE `trans_words` SET `content_loc3`='Let the games begin.' WHERE `word_id` = 2408; -- script_texts - content : entry=-1999900
UPDATE `trans_words` SET `content_loc3`='Let the sacrifice serve his testament to my fealty.' WHERE `word_id` = 1481; -- script_texts - content : entry=-1532070
UPDATE `trans_words` SET `content_loc3`='Let us see how your nerves hold up against the Darkener, Thaladred.' WHERE `word_id` = 1783; -- script_texts - content : entry=-1550019
UPDATE `trans_words` SET `content_loc3`='Let us see what fate lays in store...' WHERE `word_id` = 1396; -- script_texts - content : entry=-1269013
UPDATE `trans_words` SET `content_loc3`='Let\'s go $N!' WHERE `word_id` = 609; -- script_texts - content : entry=-1000771
UPDATE `trans_words` SET `content_loc3`='Let\'s see what I can make of you.' WHERE `word_id` = 1638; -- script_texts - content : entry=-1542012
UPDATE `trans_words` SET `content_loc3`='Like a fly in a web.' WHERE `word_id` = 1099; -- script_texts - content : entry=-1531021
UPDATE `trans_words` SET `content_loc3`='Look at what you make me do!' WHERE `word_id` = 2080; -- script_texts - content : entry=-1564049
UPDATE `trans_words` SET `content_loc3`='Look brother, fresh blood!' WHERE `word_id` = 1107; -- script_texts - content : entry=-1531029
UPDATE `trans_words` SET `content_loc3`='Looks like my work here is done. Report to the holo-image of Ameer over at the transporter.' WHERE `word_id` = 1352; -- script_texts - content : entry=-1000900
UPDATE `trans_words` SET `content_loc3`='Lord Illidan will... crush you.' WHERE `word_id` = 2040; -- script_texts - content : entry=-1564009
UPDATE `trans_words` SET `content_loc3`='Lord Illidan... I...' WHERE `word_id` = 2122; -- script_texts - content : entry=-1564093
UPDATE `trans_words` SET `content_loc3`='Lot more gonna fall like you!' WHERE `word_id` = 2249; -- script_texts - content : entry=-1568065
UPDATE `trans_words` SET `content_loc3`='Madrigosa deserved a far better fate. You did what had to be done, but this battle is far from over.' WHERE `word_id` = 2313; -- script_texts - content : entry=-1580043
UPDATE `trans_words` SET `content_loc3`='Maiev... How is this even possible?' WHERE `word_id` = 2133; -- script_texts - content : entry=-1564104
UPDATE `trans_words` SET `content_loc3`='Make ready for another wave! LOK-TAR OGAR!' WHERE `word_id` = 1555; -- script_texts - content : entry=-1534011
UPDATE `trans_words` SET `content_loc3`='Make way for Nalorakk!' WHERE `word_id` = 2203; -- script_texts - content : entry=-1568019
UPDATE `trans_words` SET `content_loc3`='Malygos, my lord! I did my best!' WHERE `word_id` = 2305; -- script_texts - content : entry=-1580035
UPDATE `trans_words` SET `content_loc3`='Manach sheek-thrish!' WHERE `word_id` = 1565; -- script_texts - content : entry=-1534021
UPDATE `trans_words` SET `content_loc3`='Master... grant me strength.' WHERE `word_id` = 2404; -- script_texts - content : entry=-1585027
UPDATE `trans_words` SET `content_loc3`='Maybe this is not--No, we fight! Come to my aid.' WHERE `word_id` = 1875; -- script_texts - content : entry=-1553011
UPDATE `trans_words` SET `content_loc3`='Me get bored...' WHERE `word_id` = 1604; -- script_texts - content : entry=-1540029
UPDATE `trans_words` SET `content_loc3`='Me kill someone else...' WHERE `word_id` = 1601; -- script_texts - content : entry=-1540026
UPDATE `trans_words` SET `content_loc3`='Mebbe me fall...but da Amani empire...never gonna die...' WHERE `word_id` = 2250; -- script_texts - content : entry=-1568066
UPDATE `trans_words` SET `content_loc3`='Meet your end, demon!' WHERE `word_id` = 2148; -- script_texts - content : entry=-1564119
UPDATE `trans_words` SET `content_loc3`='More perils... await' WHERE `word_id` = 1806; -- script_texts - content : entry=-1550043
UPDATE `trans_words` SET `content_loc3`='More... I must have more!' WHERE `word_id` = 1962; -- script_texts - content : entry=-1557012
UPDATE `trans_words` SET `content_loc3`='Move out Soldier!' WHERE `word_id` = 2415; -- script_texts - content : entry=-1999909
UPDATE `trans_words` SET `content_loc3`='Mua-ha-ha! Now whatchoo got to say?' WHERE `word_id` = 2205; -- script_texts - content : entry=-1568021
UPDATE `trans_words` SET `content_loc3`='Muahahahaha' WHERE `word_id` = 2410; -- script_texts - content : entry=-1999902
UPDATE `trans_words` SET `content_loc3`='Much too easy...' WHERE `word_id` = 1650; -- script_texts - content : entry=-1543007
UPDATE `trans_words` SET `content_loc3`='Mulgar is king!' WHERE `word_id` = 2172; -- script_texts - content : entry=-1565008
UPDATE `trans_words` SET `content_loc3`='My brother...NO!' WHERE `word_id` = 1102; -- script_texts - content : entry=-1531024
UPDATE `trans_words` SET `content_loc3`='My death means ... little.' WHERE `word_id` = 1388; -- script_texts - content : entry=-1269005
UPDATE `trans_words` SET `content_loc3`='My demise accomplishes nothing! The Master will have you! You will drown in your own blood! This world shall burn! Aaaghh!' WHERE `word_id` = 2406; -- script_texts - content : entry=-1585029
UPDATE `trans_words` SET `content_loc3`='My life, is yours. Oh great one.' WHERE `word_id` = 1478; -- script_texts - content : entry=-1532067
UPDATE `trans_words` SET `content_loc3`='My lord will be the end you all...' WHERE `word_id` = 1666; -- script_texts - content : entry=-1543024
UPDATE `trans_words` SET `content_loc3`='My patience has ran out! Die, DIE!' WHERE `word_id` = 2039; -- script_texts - content : entry=-1564008
UPDATE `trans_words` SET `content_loc3`='My work must not be interrupted.' WHERE `word_id` = 1635; -- script_texts - content : entry=-1542009
UPDATE `trans_words` SET `content_loc3`='Nature bends to my will!' WHERE `word_id` = 1868; -- script_texts - content : entry=-1553004
UPDATE `trans_words` SET `content_loc3`='Nice pets have.. weapons. No so..<squawk>..nice.' WHERE `word_id` = 1931; -- script_texts - content : entry=-1556003
UPDATE `trans_words` SET `content_loc3`='Nice pets..hrm.. Yes! <squawking>' WHERE `word_id` = 1930; -- script_texts - content : entry=-1556002
UPDATE `trans_words` SET `content_loc3`='Nice try!' WHERE `word_id` = 1908; -- script_texts - content : entry=-1555015
UPDATE `trans_words` SET `content_loc3`='No comin\' back for you!' WHERE `word_id` = 1907; -- script_texts - content : entry=-1555014
UPDATE `trans_words` SET `content_loc3`='No escape for..<squawk>..for you' WHERE `word_id` = 1938; -- script_texts - content : entry=-1556010
UPDATE `trans_words` SET `content_loc3`='No more life..hrm. No more pain. <squawks weakly>' WHERE `word_id` = 1934; -- script_texts - content : entry=-1556006
UPDATE `trans_words` SET `content_loc3`='No more' WHERE `word_id` = 2179; -- script_texts - content : entry=-1565015
UPDATE `trans_words` SET `content_loc3`='No one can stop us! No one!' WHERE `word_id` = 1399; -- script_texts - content : entry=-1269016
UPDATE `trans_words` SET `content_loc3`='NO! I ...will... not...' WHERE `word_id` = 1802; -- script_texts - content : entry=-1550039
UPDATE `trans_words` SET `content_loc3`='No! More... I must have more!' WHERE `word_id` = 2382; -- script_texts - content : entry=-1585005
UPDATE `trans_words` SET `content_loc3`='No! Not yet...' WHERE `word_id` = 2044; -- script_texts - content : entry=-1564013
UPDATE `trans_words` SET `content_loc3`='No, we will NOT let you live!' WHERE `word_id` = 1597; -- script_texts - content : entry=-1540022
UPDATE `trans_words` SET `content_loc3`='No... damn this feeble mortal coil...' WHERE `word_id` = 1407; -- script_texts - content : entry=-1269025
UPDATE `trans_words` SET `content_loc3`='No... no! What have you done? I am the master! Do you hear me? I am... aaggh! Can\'t... contain him...' WHERE `word_id` = 1726; -- script_texts - content : entry=-1548018
UPDATE `trans_words` SET `content_loc3`='Nobody badduh dan me!' WHERE `word_id` = 2241; -- script_texts - content : entry=-1568057
UPDATE `trans_words` SET `content_loc3`='Normal select, guess you\'re not interested.' WHERE `word_id` = 2428; -- script_texts - content : entry=-1999922
UPDATE `trans_words` SET `content_loc3`='Not again...NOT AGAIN!' WHERE `word_id` = 1676; -- script_texts - content : entry=-1544008
UPDATE `trans_words` SET `content_loc3`='Not really much of a group, anymore, is it?' WHERE `word_id` = 2396; -- script_texts - content : entry=-1585019
UPDATE `trans_words` SET `content_loc3`='Not what I had... planned...' WHERE `word_id` = 2399; -- script_texts - content : entry=-1585022
UPDATE `trans_words` SET `content_loc3`='Now I\'m really... angry...' WHERE `word_id` = 1846; -- script_texts - content : entry=-1552038
UPDATE `trans_words` SET `content_loc3`='Now you gone for good.' WHERE `word_id` = 1916; -- script_texts - content : entry=-1555024
UPDATE `trans_words` SET `content_loc3`='Now, where was I? Oh yes...' WHERE `word_id` = 1423; -- script_texts - content : entry=-1532012
UPDATE `trans_words` SET `content_loc3`='Obey me.' WHERE `word_id` = 1792; -- script_texts - content : entry=-1550028
UPDATE `trans_words` SET `content_loc3`='Oh at last, at last. I can go home.' WHERE `word_id` = 1436; -- script_texts - content : entry=-1532025
UPDATE `trans_words` SET `content_loc3`='Oh dear, we simply must find a way home! The old wizard could be our only hope! Strawman, Roar, Tinhead, will you... wait! Oh golly, look! We have visitors!' WHERE `word_id` = 1439; -- script_texts - content : entry=-1532028
UPDATE `trans_words` SET `content_loc3`='Oh no, he was merely an instrument, a stepping stone to a much larger plan! It has all led to this, and this time, you will not interfere!' WHERE `word_id` = 2407; -- script_texts - content : entry=-1585030
UPDATE `trans_words` SET `content_loc3`='Oh, the horror.' WHERE `word_id` = 2390; -- script_texts - content : entry=-1585013
UPDATE `trans_words` SET `content_loc3`='Ohh! Just die.' WHERE `word_id` = 1591; -- script_texts - content : entry=-1540016
UPDATE `trans_words` SET `content_loc3`='Ok, let\'s go!!' WHERE `word_id` = 731; -- script_texts - content : entry=-1000905
UPDATE `trans_words` SET `content_loc3`='One final cell remains. Yes, O\'great one, right away!' WHERE `word_id` = 1837; -- script_texts - content : entry=-1552029
UPDATE `trans_words` SET `content_loc3`='One pitiful wretch down. Go on, take another one.' WHERE `word_id` = 1580; -- script_texts - content : entry=-1540005
UPDATE `trans_words` SET `content_loc3`='Only the strong survive.' WHERE `word_id` = 1745; -- script_texts - content : entry=-1548037
UPDATE `trans_words` SET `content_loc3`='Orb of Domination loses power and shuts off!' WHERE `word_id` = 1045; -- script_texts - content : entry=-1469035
UPDATE `trans_words` SET `content_loc3`='Orcs of the Horde! This portalis the gateway to your new destiny! Azeroth lies before you, ripe for the taking!' WHERE `word_id` = 1409; -- script_texts - content : entry=-1269027
UPDATE `trans_words` SET `content_loc3`='Our matron will be.. the end of.. you..' WHERE `word_id` = 1690; -- script_texts - content : entry=-1545006
UPDATE `trans_words` SET `content_loc3`='Over here, you idiot!' WHERE `word_id` = 1373; -- script_texts - content : entry=-1189025
UPDATE `trans_words` SET `content_loc3`='Overlord Wyrmthalak calls for help!' WHERE `word_id` = 1327; -- script_texts - content : entry=-1999926
UPDATE `trans_words` SET `content_loc3`='Pathetic mortals! You will pay dearly!' WHERE `word_id` = 1894; -- script_texts - content : entry=-1555001
UPDATE `trans_words` SET `content_loc3`='Perhaps I can find a use for you.' WHERE `word_id` = 1636; -- script_texts - content : entry=-1542010
UPDATE `trans_words` SET `content_loc3`='Perish, mortal.' WHERE `word_id` = 1721; -- script_texts - content : entry=-1548013
UPDATE `trans_words` SET `content_loc3`='Pitious mortal!' WHERE `word_id` = 2284; -- script_texts - content : entry=-1580014
UPDATE `trans_words` SET `content_loc3`='Please, accept this humble offering, oh great one.' WHERE `word_id` = 1480; -- script_texts - content : entry=-1532069
UPDATE `trans_words` SET `content_loc3`='Please, no more. My son... he\'s gone mad!' WHERE `word_id` = 1484; -- script_texts - content : entry=-1532073
UPDATE `trans_words` SET `content_loc3`='Please, rise my friend. Keep the Blessing as a symbol of the strength of the Light and how heroes long gone might once again rise in each of us to inspire.' WHERE `word_id` = 1369; -- script_texts - content : entry=-1000919
UPDATE `trans_words` SET `content_loc3`='Power will be yours!' WHERE `word_id` = 1903; -- script_texts - content : entry=-1555010
UPDATE `trans_words` SET `content_loc3`='Prepare to embrace oblivion!' WHERE `word_id` = 1098; -- script_texts - content : entry=-1531020
UPDATE `trans_words` SET `content_loc3`='Rise my fallen brothers. Take form and fight!' WHERE `word_id` = 1966; -- script_texts - content : entry=-1558001
UPDATE `trans_words` SET `content_loc3`='Run covad, ruun!' WHERE `word_id` = 1585; -- script_texts - content : entry=-1540010
UPDATE `trans_words` SET `content_loc3`='Run! They are coming.' WHERE `word_id` = 1044; -- script_texts - content : entry=-1469034
UPDATE `trans_words` SET `content_loc3`='Sacrolash!' WHERE `word_id` = 2329; -- script_texts - content : entry=-1580059
UPDATE `trans_words` SET `content_loc3`='Scram, surface filth!' WHERE `word_id` = 1704; -- script_texts - content : entry=-1545021
UPDATE `trans_words` SET `content_loc3`='Scurry' WHERE `word_id` = 2175; -- script_texts - content : entry=-1565011
UPDATE `trans_words` SET `content_loc3`='Seek sanctuary in Hearthglen! It is our only hope!' WHERE `word_id` = 655; -- script_texts - content : entry=-1000821
UPDATE `trans_words` SET `content_loc3`='Selama am\'oronor!' WHERE `word_id` = 2114; -- script_texts - content : entry=-1564085
UPDATE `trans_words` SET `content_loc3`='Sha\'amoor ara mashal?' WHERE `word_id` = 2113; -- script_texts - content : entry=-1564084
UPDATE `trans_words` SET `content_loc3`='Sha\'amoor sine menoor!' WHERE `word_id` = 2106; -- script_texts - content : entry=-1564076
UPDATE `trans_words` SET `content_loc3`='Shadow Lord Xiraxis yells: Bravo! Bravo! Good show... I couldn\'t convince you to work for me, could I? No, I suppose the needless slaughter of my employees might negatively impact your employment application.' WHERE `word_id` = 2443; -- script_texts - content : entry=-1557026
UPDATE `trans_words` SET `content_loc3`='Shadows, engulf!' WHERE `word_id` = 2324; -- script_texts - content : entry=-1580054
UPDATE `trans_words` SET `content_loc3`='Shall be your undoing!' WHERE `word_id` = 1110; -- script_texts - content : entry=-1531032
UPDATE `trans_words` SET `content_loc3`='Shorel\'aran.' WHERE `word_id` = 2117; -- script_texts - content : entry=-1564088
UPDATE `trans_words` SET `content_loc3`='So be it ... you have been warned.' WHERE `word_id` = 1384; -- script_texts - content : entry=-1269001
UPDATE `trans_words` SET `content_loc3`='So eager you are for my blood to spill, yet to vanquish me this my head you must kill!' WHERE `word_id` = 1372; -- script_texts - content : entry=-1189024
UPDATE `trans_words` SET `content_loc3`='So much for a real challenge... Die!' WHERE `word_id` = 2299; -- script_texts - content : entry=-1580029
UPDATE `trans_words` SET `content_loc3`='So we have place in new universe.' WHERE `word_id` = 1912; -- script_texts - content : entry=-1555019
UPDATE `trans_words` SET `content_loc3`='So... confused. Do not... belong here!' WHERE `word_id` = 1876; -- script_texts - content : entry=-1553012
UPDATE `trans_words` SET `content_loc3`='So... full of life!' WHERE `word_id` = 1959; -- script_texts - content : entry=-1557009
UPDATE `trans_words` SET `content_loc3`='Speak, I grow weary of asking!' WHERE `word_id` = 2304; -- script_texts - content : entry=-1580034
UPDATE `trans_words` SET `content_loc3`='Splendid, I\'m going to get the audience ready. Break a leg!' WHERE `word_id` = 1526; -- script_texts - content : entry=-1532115
UPDATE `trans_words` SET `content_loc3`='Stay alert! Another wave approaches.' WHERE `word_id` = 1546; -- script_texts - content : entry=-1534002
UPDATE `trans_words` SET `content_loc3`='Stay away from... me.' WHERE `word_id` = 1640; -- script_texts - content : entry=-1542014
UPDATE `trans_words` SET `content_loc3`='Stay on task! Do not waste time!' WHERE `word_id` = 2335; -- script_texts - content : entry=-1580065
UPDATE `trans_words` SET `content_loc3`='Stop! Do not go further, mortals. You are ill-prepared to face the forces of the Infinite Dragonflight. Come, let me help you.' WHERE `word_id` = 1401; -- script_texts - content : entry=-1269019
UPDATE `trans_words` SET `content_loc3`='Strike now, heroes, while he is weakened! Vanquish the Deceiver!' WHERE `word_id` = 2360; -- script_texts - content : entry=-1580090
UPDATE `trans_words` SET `content_loc3`='Strugging only makes it worse.' WHERE `word_id` = 1744; -- script_texts - content : entry=-1548036
UPDATE `trans_words` SET `content_loc3`='Such easy sport.' WHERE `word_id` = 1420; -- script_texts - content : entry=-1532009
UPDATE `trans_words` SET `content_loc3`='Such... arrogance!' WHERE `word_id` = 2144; -- script_texts - content : entry=-1564115
UPDATE `trans_words` SET `content_loc3`='Suit yourself. At least five of you must assist me if we\'re to get inside. Follow me.' WHERE `word_id` = 2263; -- script_texts - content : entry=-1568079
UPDATE `trans_words` SET `content_loc3`='Surely you would not deny an old man a replenishing drink? No, no I thought not.' WHERE `word_id` = 1493; -- script_texts - content : entry=-1532082
UPDATE `trans_words` SET `content_loc3`='Surge forth my pets!' WHERE `word_id` = 1684; -- script_texts - content : entry=-1545000
UPDATE `trans_words` SET `content_loc3`='Systems... shutting... down...' WHERE `word_id` = 1768; -- script_texts - content : entry=-1550004
UPDATE `trans_words` SET `content_loc3`='Take for instance, this quiet, elderly woman, waiting for a visit from her granddaughter. Surely there is nothing to fear from this sweet, grey-haired, old lady.' WHERE `word_id` = 1520; -- script_texts - content : entry=-1532109
UPDATE `trans_words` SET `content_loc3`='Tal anu\'men no Sin\'dorei!' WHERE `word_id` = 1771; -- script_texts - content : entry=-1550007
UPDATE `trans_words` SET `content_loc3`='Taste death!' WHERE `word_id` = 2425; -- script_texts - content : entry=-1999919
UPDATE `trans_words` SET `content_loc3`='Tazaga-choo!' WHERE `word_id` = 2190; -- script_texts - content : entry=-1568006
UPDATE `trans_words` SET `content_loc3`='Than fortunate it is, that I have reclaimed the noble naaru\'s spark from where it fell! Where faith dwells, hope is never lost, young blood elf.' WHERE `word_id` = 2370; -- script_texts - content : entry=-1580100
UPDATE `trans_words` SET `content_loc3`='Thank you for coming in remembrance of me. Your efforts in recovering that symbol, while unnecessary, are certainly touching to an old man\'s heart.' WHERE `word_id` = 1368; -- script_texts - content : entry=-1000918
UPDATE `trans_words` SET `content_loc3`='Thank you for releasing me. Now...die!' WHERE `word_id` = 1675; -- script_texts - content : entry=-1544007
UPDATE `trans_words` SET `content_loc3`='Thank you for saving me the trouble! Now it\'s my turn to have some fun...' WHERE `word_id` = 1583; -- script_texts - content : entry=-1540008
UPDATE `trans_words` SET `content_loc3`='Thank you! I will run for safety immediately!' WHERE `word_id` = 928; -- script_texts - content : entry=-1230032
UPDATE `trans_words` SET `content_loc3`='Thanks you for help.' WHERE `word_id` = 1280; -- script_texts - content : entry=-1000962
UPDATE `trans_words` SET `content_loc3`='That should do it. The teleporter should blow any second now!' WHERE `word_id` = 2553; -- script_texts - content : entry=-1000974
UPDATE `trans_words` SET `content_loc3`='That\'s right! Yes!' WHERE `word_id` = 1724; -- script_texts - content : entry=-1548016
UPDATE `trans_words` SET `content_loc3`='The cerestial forces are mine to manipulate.' WHERE `word_id` = 1506; -- script_texts - content : entry=-1532095
UPDATE `trans_words` SET `content_loc3`='The chaos I have sown here is but a taste...' WHERE `word_id` = 1811; -- script_texts - content : entry=-1552003
UPDATE `trans_words` SET `content_loc3`='The enemy is among you.' WHERE `word_id` = 2343; -- script_texts - content : entry=-1580073
UPDATE `trans_words` SET `content_loc3`='The expendible have perished... So be it! Now I shall succeed where Sargeras could not! I will bleed this wretched world and secure my place as the true master of the Burning Legion. The end has come! Let the unraveling of this world commence!' WHERE `word_id` = 2339; -- script_texts - content : entry=-1580069
UPDATE `trans_words` SET `content_loc3`='The feast of souls begin now...' WHERE `word_id` = 1096; -- script_texts - content : entry=-1531018
UPDATE `trans_words` SET `content_loc3`='The halls of Karazhan shake, as the curse binding the doors of the Gamemaster\'s Hall is lifted.' WHERE `word_id` = 1542; -- script_texts - content : entry=-1532131
UPDATE `trans_words` SET `content_loc3`='The land truly needs to be cleansed by the Light! Let us continue on the tomb. It isn\'t far now.' WHERE `word_id` = 1366; -- script_texts - content : entry=-1000916
UPDATE `trans_words` SET `content_loc3`='The Legion...will consume you...all...' WHERE `word_id` = 1679; -- script_texts - content : entry=-1544011
UPDATE `trans_words` SET `content_loc3`='The Light will fill these dismal halls once again. I swear it.' WHERE `word_id` = 2140; -- script_texts - content : entry=-1564111
UPDATE `trans_words` SET `content_loc3`='The naaru kept some of the most dangerous beings in existence here in these cells. Let me introduce you to another...' WHERE `word_id` = 1832; -- script_texts - content : entry=-1552024
UPDATE `trans_words` SET `content_loc3`='The nightmare is over, the spell is broken! Goodbye, Kalec, my love!' WHERE `word_id` = 2358; -- script_texts - content : entry=-1580088
UPDATE `trans_words` SET `content_loc3`='The pain is only beginning!' WHERE `word_id` = 2082; -- script_texts - content : entry=-1564051
UPDATE `trans_words` SET `content_loc3`='The sin\'dore reign supreme!' WHERE `word_id` = 1803; -- script_texts - content : entry=-1550040
UPDATE `trans_words` SET `content_loc3`='The specimens...must be preserved.' WHERE `word_id` = 1869; -- script_texts - content : entry=-1553005
UPDATE `trans_words` SET `content_loc3`='The suffering has just begun!' WHERE `word_id` = 2413; -- script_texts - content : entry=-1999907
UPDATE `trans_words` SET `content_loc3`='The time has come to shatter this clockwork universe forever! Let us no longer be slaves of the hourglass! I warn you: those who do not embrace the greater path shall become victims of its passing!' WHERE `word_id` = 1395; -- script_texts - content : entry=-1269012
UPDATE `trans_words` SET `content_loc3`='The time is now! Leave none standing!' WHERE `word_id` = 1756; -- script_texts - content : entry=-1548048
UPDATE `trans_words` SET `content_loc3`='The true Horde... will.. prevail...' WHERE `word_id` = 1622; -- script_texts - content : entry=-1540047
UPDATE `trans_words` SET `content_loc3`='The wheel...spins...again....' WHERE `word_id` = 2077; -- script_texts - content : entry=-1564046
UPDATE `trans_words` SET `content_loc3`='There will be no reprieve. My work here is nearly finished.' WHERE `word_id` = 2280; -- script_texts - content : entry=-1580010
UPDATE `trans_words` SET `content_loc3`='There\'s no turning back now!' WHERE `word_id` = 1968; -- script_texts - content : entry=-1558003
UPDATE `trans_words` SET `content_loc3`='These are the hallmarks...' WHERE `word_id` = 2320; -- script_texts - content : entry=-1580050
UPDATE `trans_words` SET `content_loc3`='These are the pillars...' WHERE `word_id` = 2321; -- script_texts - content : entry=-1580051
UPDATE `trans_words` SET `content_loc3`='These mortal infedels my lord, they have invaded your sanctum and seek to steal your secrets.' WHERE `word_id` = 2411; -- script_texts - content : entry=-1999903
UPDATE `trans_words` SET `content_loc3`='These walls will be your doom.' WHERE `word_id` = 1972; -- script_texts - content : entry=-1558007
UPDATE `trans_words` SET `content_loc3`='They have forced me to this...' WHERE `word_id` = 1710; -- script_texts - content : entry=-1548002
UPDATE `trans_words` SET `content_loc3`='Things are looking grim...' WHERE `word_id` = 2006; -- script_texts - content : entry=-1560034
UPDATE `trans_words` SET `content_loc3`='This all...your fault!' WHERE `word_id` = 1614; -- script_texts - content : entry=-1540039
UPDATE `trans_words` SET `content_loc3`='This area is known to be full of foul Scourge. You may want to take a moment to prepare any defenses at your disposal.' WHERE `word_id` = 1361; -- script_texts - content : entry=-1000911
UPDATE `trans_words` SET `content_loc3`='This Curator is no longer op... er... ation... al.' WHERE `word_id` = 1475; -- script_texts - content : entry=-1532064
UPDATE `trans_words` SET `content_loc3`='This day is long overdue. Out of my way!' WHERE `word_id` = 2011; -- script_texts - content : entry=-1560039
UPDATE `trans_words` SET `content_loc3`='This day\'s black fate on more days doth depend. This but begins the woe. Others must end.' WHERE `word_id` = 1465; -- script_texts - content : entry=-1532054
UPDATE `trans_words` SET `content_loc3`='This door is all that stands between us and the Betrayer. Stand aside, friends.' WHERE `word_id` = 2160; -- script_texts - content : entry=-1564131
UPDATE `trans_words` SET `content_loc3`='This end have I reached before. What new adventure lies in store?' WHERE `word_id` = 1377; -- script_texts - content : entry=-1189029
UPDATE `trans_words` SET `content_loc3`='This is the part I enjoy most.' WHERE `word_id` = 1899; -- script_texts - content : entry=-1555006
UPDATE `trans_words` SET `content_loc3`='This is... where.. I belong...' WHERE `word_id` = 1974; -- script_texts - content : entry=-1558009
UPDATE `trans_words` SET `content_loc3`='This may be the end for you, Dalliah. What a shame that would be.' WHERE `word_id` = 1848; -- script_texts - content : entry=-1552040
UPDATE `trans_words` SET `content_loc3`='This part of forest are very danger for us. We must be a careful!' WHERE `word_id` = 742; -- script_texts - content : entry=-1000959
UPDATE `trans_words` SET `content_loc3`='Thrall! You didn\'t really think you would escape did you? You and your allies shall answer to Blackmoore - after I\'ve had my fun!' WHERE `word_id` = 1976; -- script_texts - content : entry=-1560000
UPDATE `trans_words` SET `content_loc3`='Time ... is on our side.' WHERE `word_id` = 1394; -- script_texts - content : entry=-1269011
UPDATE `trans_words` SET `content_loc3`='Time for me to go! See ya around $N!' WHERE `word_id` = 2420; -- script_texts - content : entry=-1999914
UPDATE `trans_words` SET `content_loc3`='Time for you to go!' WHERE `word_id` = 2035; -- script_texts - content : entry=-1564004
UPDATE `trans_words` SET `content_loc3`='Time to feast!' WHERE `word_id` = 2061; -- script_texts - content : entry=-1564030
UPDATE `trans_words` SET `content_loc3`='Time... sands of time is run out for you.' WHERE `word_id` = 1385; -- script_texts - content : entry=-1269002
UPDATE `trans_words` SET `content_loc3`='Tito, oh Tito, no!' WHERE `word_id` = 1438; -- script_texts - content : entry=-1532027
UPDATE `trans_words` SET `content_loc3`='To decorate our halls!' WHERE `word_id` = 1103; -- script_texts - content : entry=-1531025
UPDATE `trans_words` SET `content_loc3`='To the void... once... more..' WHERE `word_id` = 1963; -- script_texts - content : entry=-1557013
UPDATE `trans_words` SET `content_loc3`='Tonight we plumb the depths of the human soul as we join a lost, lonely girl trying desperately -- with the help of her loyal companions -- to find her way home!' WHERE `word_id` = 1515; -- script_texts - content : entry=-1532104
UPDATE `trans_words` SET `content_loc3`='Tonight, things are not what they seem. For tonight, your eyes may not be trusted' WHERE `word_id` = 1519; -- script_texts - content : entry=-1532108
UPDATE `trans_words` SET `content_loc3`='Tonight, we explore a tale of forbidden love!' WHERE `word_id` = 1523; -- script_texts - content : entry=-1532112
UPDATE `trans_words` SET `content_loc3`='Tou... che!' WHERE `word_id` = 1169; -- script_texts - content : entry=-1533050
UPDATE `trans_words` SET `content_loc3`='Uhn.. Be free..<squawk>' WHERE `word_id` = 1933; -- script_texts - content : entry=-1556005
UPDATE `trans_words` SET `content_loc3`='Valiant effort!' WHERE `word_id` = 2115; -- script_texts - content : entry=-1564086
UPDATE `trans_words` SET `content_loc3`='Very well. Before we head down there, take a moment to prepare yourself.' WHERE `word_id` = 2547; -- script_texts - content : entry=-1000968
UPDATE `trans_words` SET `content_loc3`='Victory to Lord Illidan!' WHERE `word_id` = 1752; -- script_texts - content : entry=-1548044
UPDATE `trans_words` SET `content_loc3`='Wanna fight? Huh? Do ya? C\'mon, I\'ll fight you with both claws behind my back!' WHERE `word_id` = 1440; -- script_texts - content : entry=-1532029
UPDATE `trans_words` SET `content_loc3`='Was this fabled, Windsor? If it was death that you came for then the prophecy has been fulfilled. May your consciousness rot in the Twisting Nether. Finish the rest of these meddlesome insects, children. Bolvar, you have been a pleasureable puppet.' WHERE `word_id` = 701; -- script_texts - content : entry=-1000867
UPDATE `trans_words` SET `content_loc3`='Water is life. It has become a rare commodity here in Outland. A commodity that we alone shall control. We are the Highborne, and the time has come at last for us to retake our rightful place in the world!' WHERE `word_id` = 1750; -- script_texts - content : entry=-1548042
UPDATE `trans_words` SET `content_loc3`='We all have our demons...' WHERE `word_id` = 1719; -- script_texts - content : entry=-1548011
UPDATE `trans_words` SET `content_loc3`='We are beset upon again! Defend yourself!' WHERE `word_id` = 1365; -- script_texts - content : entry=-1000915
UPDATE `trans_words` SET `content_loc3`='We are lost. Fall back!' WHERE `word_id` = 1550; -- script_texts - content : entry=-1534006
UPDATE `trans_words` SET `content_loc3`='We can overcome these foul creatures.' WHERE `word_id` = 626; -- script_texts - content : entry=-1000792
UPDATE `trans_words` SET `content_loc3`='We have not yet been properly introduced.' WHERE `word_id` = 1951; -- script_texts - content : entry=-1557001
UPDATE `trans_words` SET `content_loc3`='We have played our part and done well. It is up to the others now.' WHERE `word_id` = 1560; -- script_texts - content : entry=-1534016
UPDATE `trans_words` SET `content_loc3`='We have won valuable time. Now we must pull back!' WHERE `word_id` = 1551; -- script_texts - content : entry=-1534007
UPDATE `trans_words` SET `content_loc3`='We leave, Torlok. I have only one request...' WHERE `word_id` = 646; -- script_texts - content : entry=-1000812
UPDATE `trans_words` SET `content_loc3`='Welcome, O\'great one. I am your humble servant.' WHERE `word_id` = 1838; -- script_texts - content : entry=-1552030
UPDATE `trans_words` SET `content_loc3`='Well done Midnight!' WHERE `word_id` = 1411; -- script_texts - content : entry=-1532000
UPDATE `trans_words` SET `content_loc3`='Well then, let\'s get this started. The longer we\'re here, the more damage the undead could be doing back in Hilsbrad.' WHERE `word_id` = 733; -- script_texts - content : entry=-1000948
UPDATE `trans_words` SET `content_loc3`='Well, now or never I suppose. Remember, once we get to the road safety, return to Terenthis to let him know we escaped.' WHERE `word_id` = 624; -- script_texts - content : entry=-1000789
UPDATE `trans_words` SET `content_loc3`='What a ... a shame.' WHERE `word_id` = 1592; -- script_texts - content : entry=-1540017
UPDATE `trans_words` SET `content_loc3`='What are you doing!' WHERE `word_id` = 1600; -- script_texts - content : entry=-1540025
UPDATE `trans_words` SET `content_loc3`='What are you doing? These specimens are very delicate!' WHERE `word_id` = 1864; -- script_texts - content : entry=-1553000
UPDATE `trans_words` SET `content_loc3`='What do we have here? I thought you said the area was secure? This is now the third attack? If we make it out of here, I will definitely be deducting this from your reward. Now don\'t just stand here, destroy them so I can get to that collector.' WHERE `word_id` = 2439; -- script_texts - content : entry=-1557022
UPDATE `trans_words` SET `content_loc3`='What have we here...?' WHERE `word_id` = 1646; -- script_texts - content : entry=-1543003
UPDATE `trans_words` SET `content_loc3`='What is this? A lowly gnome? I will do better, O\'great one.' WHERE `word_id` = 1835; -- script_texts - content : entry=-1552027
UPDATE `trans_words` SET `content_loc3`='What is this? Champions, coming to my aid? I sense the hand of the dark one in this. Truly this sacred event bears his blessing?' WHERE `word_id` = 1403; -- script_texts - content : entry=-1269021
UPDATE `trans_words` SET `content_loc3`='What say the elements, Torlok? I only hear silence.' WHERE `word_id` = 640; -- script_texts - content : entry=-1000806
UPDATE `trans_words` SET `content_loc3`='Whatch you be doing? Pissin\' yourselves...' WHERE `word_id` = 2223; -- script_texts - content : entry=-1568039
UPDATE `trans_words` SET `content_loc3`='Where did you get that?! Did HE send you?!' WHERE `word_id` = 1499; -- script_texts - content : entry=-1532088
UPDATE `trans_words` SET `content_loc3`='Where is my Lord? Where is my Romulo? Ohh, happy dagger! This is thy sheath! There rust, and let me die!' WHERE `word_id` = 1460; -- script_texts - content : entry=-1532049
UPDATE `trans_words` SET `content_loc3`='Where is my lord? Where is my Romulo?' WHERE `word_id` = 1458; -- script_texts - content : entry=-1532047
UPDATE `trans_words` SET `content_loc3`='Whhy! He almost dead!' WHERE `word_id` = 1608; -- script_texts - content : entry=-1540033
UPDATE `trans_words` SET `content_loc3`='Who can you trust?' WHERE `word_id` = 2342; -- script_texts - content : entry=-1580072
UPDATE `trans_words` SET `content_loc3`='Who dares interrupt... What is this? What have you done? You ruin everything!' WHERE `word_id` = 1626; -- script_texts - content : entry=-1542000
UPDATE `trans_words` SET `content_loc3`='Who knows what secrets hide in the dark.' WHERE `word_id` = 1505; -- script_texts - content : entry=-1532094
UPDATE `trans_words` SET `content_loc3`='Who shall be next to taste my blades?!' WHERE `word_id` = 2152; -- script_texts - content : entry=-1564123
UPDATE `trans_words` SET `content_loc3`='Who you gonna call?' WHERE `word_id` = 966; -- script_texts - content : entry=-1329002
UPDATE `trans_words` SET `content_loc3`='Why do you aid the Magus? Just think of how many lives could be saved if the portal is never opened, if the resulting wars could be erased ...' WHERE `word_id` = 1389; -- script_texts - content : entry=-1269006
UPDATE `trans_words` SET `content_loc3`='Why do you persist? Surely you can see the futility of it all. It is not too late! You may still leave with your lives ...' WHERE `word_id` = 1383; -- script_texts - content : entry=-1269000
UPDATE `trans_words` SET `content_loc3`='Wild Felboar attack!' WHERE `word_id` = 2419; -- script_texts - content : entry=-1999913
UPDATE `trans_words` SET `content_loc3`='Will she survive? Will she prevail? Only time will tell. And now ... on with the show!' WHERE `word_id` = 1517; -- script_texts - content : entry=-1532106
UPDATE `trans_words` SET `content_loc3`='Woe to each and every one of you my pretties! <cackles>' WHERE `word_id` = 1450; -- script_texts - content : entry=-1532039
UPDATE `trans_words` SET `content_loc3`='Wretched, meddling insects. Release me and perhaps i will grant you a merciful death!' WHERE `word_id` = 1668; -- script_texts - content : entry=-1544000
UPDATE `trans_words` SET `content_loc3`='Ya don\'t kill me yet, ya don\'t get another chance!' WHERE `word_id` = 2230; -- script_texts - content : entry=-1568046
UPDATE `trans_words` SET `content_loc3`='Ya not do too bad. Ya efforts [...] for a small time. Come to me now. Ya prove yourself worthy offerings.' WHERE `word_id` = 2261; -- script_texts - content : entry=-1568077
UPDATE `trans_words` SET `content_loc3`='Yes! I am a god!' WHERE `word_id` = 2379; -- script_texts - content : entry=-1585002
UPDATE `trans_words` SET `content_loc3`='Yes! I am... empowered!' WHERE `word_id` = 1961; -- script_texts - content : entry=-1557011
UPDATE `trans_words` SET `content_loc3`='Yes, Anveena! Let fate embrace you now!' WHERE `word_id` = 2357; -- script_texts - content : entry=-1580087
UPDATE `trans_words` SET `content_loc3`='Yes, beat him mercilessly. His skull is a thick as an ogres.' WHERE `word_id` = 1577; -- script_texts - content : entry=-1540002
UPDATE `trans_words` SET `content_loc3`='Yes, that was quite satisfying' WHERE `word_id` = 1855; -- script_texts - content : entry=-1552047
UPDATE `trans_words` SET `content_loc3`='Yes, YES! Ahahah!' WHERE `word_id` = 1722; -- script_texts - content : entry=-1548014
UPDATE `trans_words` SET `content_loc3`='Yes, yes, my son is quite powerful... but I have powers of my own!' WHERE `word_id` = 1491; -- script_texts - content : entry=-1532080
UPDATE `trans_words` SET `content_loc3`='Yes... you\'ll stay with us now...' WHERE `word_id` = 2087; -- script_texts - content : entry=-1564057
UPDATE `trans_words` SET `content_loc3`='You always hungry. That why we so fat!' WHERE `word_id` = 1598; -- script_texts - content : entry=-1540023
UPDATE `trans_words` SET `content_loc3`='You are already dead.' WHERE `word_id` = 1112; -- script_texts - content : entry=-1531034
UPDATE `trans_words` SET `content_loc3`='You are not alone. The Blue Dragonflight shall help you vanquish the Deceiver.' WHERE `word_id` = 2350; -- script_texts - content : entry=-1580080
UPDATE `trans_words` SET `content_loc3`='You are nothing, I answer a higher call!' WHERE `word_id` = 1661; -- script_texts - content : entry=-1543019
UPDATE `trans_words` SET `content_loc3`='You are the disease, not I' WHERE `word_id` = 1716; -- script_texts - content : entry=-1548008
UPDATE `trans_words` SET `content_loc3`='You are weak.' WHERE `word_id` = 1117; -- script_texts - content : entry=-1531039
UPDATE `trans_words` SET `content_loc3`='You are, but a plaything, unfit even to amuse.' WHERE `word_id` = 1510; -- script_texts - content : entry=-1532099
UPDATE `trans_words` SET `content_loc3`='You be dead people!' WHERE `word_id` = 1915; -- script_texts - content : entry=-1555023
UPDATE `trans_words` SET `content_loc3`='You can have that one. I no longer need him.' WHERE `word_id` = 1576; -- script_texts - content : entry=-1540001
UPDATE `trans_words` SET `content_loc3`='You cannot kill me! Fools, I\'ll be back! I\'ll... aarghh...' WHERE `word_id` = 1728; -- script_texts - content : entry=-1548020
UPDATE `trans_words` SET `content_loc3`='You cant fight the power!' WHERE `word_id` = 2224; -- script_texts - content : entry=-1568040
UPDATE `trans_words` SET `content_loc3`='You dare challenge me at my own dwelling? Your arrogance is astounding, even for a dragon.' WHERE `word_id` = 1529; -- script_texts - content : entry=-1532118
UPDATE `trans_words` SET `content_loc3`='You dare stand against me?!' WHERE `word_id` = 1652; -- script_texts - content : entry=-1543009
UPDATE `trans_words` SET `content_loc3`='You didn\'t have to go and do that.' WHERE `word_id` = 1441; -- script_texts - content : entry=-1532030
UPDATE `trans_words` SET `content_loc3`='You die..<squawk>..stay away from Trinkets' WHERE `word_id` = 1939; -- script_texts - content : entry=-1556011
UPDATE `trans_words` SET `content_loc3`='You do not fight alone, %n! Together, we will banish this spawn of hellfire!' WHERE `word_id` = 637; -- script_texts - content : entry=-1000803
UPDATE `trans_words` SET `content_loc3`='You failed, haha haha' WHERE `word_id` = 1917; -- script_texts - content : entry=-1555025
UPDATE `trans_words` SET `content_loc3`='You gambled...and lost.' WHERE `word_id` = 1790; -- script_texts - content : entry=-1550026
UPDATE `trans_words` SET `content_loc3`='You gonna fail!' WHERE `word_id` = 2225; -- script_texts - content : entry=-1568041
UPDATE `trans_words` SET `content_loc3`='You got lucky!' WHERE `word_id` = 2123; -- script_texts - content : entry=-1564094
UPDATE `trans_words` SET `content_loc3`='You guys, feel free to jump in anytime.' WHERE `word_id` = 1825; -- script_texts - content : entry=-1552017
UPDATE `trans_words` SET `content_loc3`='You had your chance, now it be too late!' WHERE `word_id` = 2204; -- script_texts - content : entry=-1568020
UPDATE `trans_words` SET `content_loc3`='You have defiled the resting place of our ancestors. For this offense, there can be but one punishment. It is fitting that you have come to a place of the dead... for you will soon be joining them.' WHERE `word_id` = 1965; -- script_texts - content : entry=-1558000
UPDATE `trans_words` SET `content_loc3`='You have done a great thing. Alas, the young warchief\'s memory of these events must be as they originally were ... Andormu awaits you in the master\'s lair.' WHERE `word_id` = 2030; -- script_texts - content : entry=-1560058
UPDATE `trans_words` SET `content_loc3`='You have faced many challenges, pity they were all in vain. Soon your people will kneel to my lord!' WHERE `word_id` = 1659; -- script_texts - content : entry=-1543017
UPDATE `trans_words` SET `content_loc3`='You have my word that I shall find a use for your body after I\'ve killed you, Kinelory.' WHERE `word_id` = 736; -- script_texts - content : entry=-1000951
UPDATE `trans_words` SET `content_loc3`='You have outstayed your welcome, Timekeeper. Begone!' WHERE `word_id` = 1391; -- script_texts - content : entry=-1269008
UPDATE `trans_words` SET `content_loc3`='You leave me no alternative. I will stop you by force if you wont listen to reason.' WHERE `word_id` = 1532; -- script_texts - content : entry=-1532121
UPDATE `trans_words` SET `content_loc3`='You Loose.' WHERE `word_id` = 1590; -- script_texts - content : entry=-1540015
UPDATE `trans_words` SET `content_loc3`='You make war on Ikiss?..<squawk>' WHERE `word_id` = 1936; -- script_texts - content : entry=-1556008
UPDATE `trans_words` SET `content_loc3`='You may want to take cover.' WHERE `word_id` = 1757; -- script_texts - content : entry=-1548049
UPDATE `trans_words` SET `content_loc3`='You must die! But wait: this does not--No, no... you must die!' WHERE `word_id` = 1872; -- script_texts - content : entry=-1553008
UPDATE `trans_words` SET `content_loc3`='You must let go! You must become what you were always meant to be! The time is now, Anveena!' WHERE `word_id` = 2353; -- script_texts - content : entry=-1580083
UPDATE `trans_words` SET `content_loc3`='You must protect me from monsters, who are living in this forest!' WHERE `word_id` = 741; -- script_texts - content : entry=-1000958
UPDATE `trans_words` SET `content_loc3`='You not so tough afterall!' WHERE `word_id` = 2170; -- script_texts - content : entry=-1565006
UPDATE `trans_words` SET `content_loc3`='You seem a little tense.' WHERE `word_id` = 2053; -- script_texts - content : entry=-1564022
UPDATE `trans_words` SET `content_loc3`='You stay here. Me go kill someone else!' WHERE `word_id` = 1599; -- script_texts - content : entry=-1540024
UPDATE `trans_words` SET `content_loc3`='You too slow! Me too strong!' WHERE `word_id` = 2247; -- script_texts - content : entry=-1568063
UPDATE `trans_words` SET `content_loc3`='You will betray your friends.' WHERE `word_id` = 1115; -- script_texts - content : entry=-1531037
UPDATE `trans_words` SET `content_loc3`='You will die.' WHERE `word_id` = 1116; -- script_texts - content : entry=-1531038
UPDATE `trans_words` SET `content_loc3`='You will not prevail.' WHERE `word_id` = 1789; -- script_texts - content : entry=-1550025
UPDATE `trans_words` SET `content_loc3`='You wish to kill me? Hahaha, you first!' WHERE `word_id` = 2104; -- script_texts - content : entry=-1564074
UPDATE `trans_words` SET `content_loc3`='You won\'t kill next one so easy!' WHERE `word_id` = 2166; -- script_texts - content : entry=-1565002
UPDATE `trans_words` SET `content_loc3`='You\'ll be a fine example, for the others.' WHERE `word_id` = 1921; -- script_texts - content : entry=-1555030
UPDATE `trans_words` SET `content_loc3`='You\'ll be hearing from my lawyer...' WHERE `word_id` = 1829; -- script_texts - content : entry=-1552021
UPDATE `trans_words` SET `content_loc3`='You\'re in for a world of hurt!' WHERE `word_id` = 1692; -- script_texts - content : entry=-1545008
UPDATE `trans_words` SET `content_loc3`='You\'re not caught up for this!' WHERE `word_id` = 2108; -- script_texts - content : entry=-1564078
UPDATE `trans_words` SET `content_loc3`='You\'re right, you are allowed to see my inner secrets.' WHERE `word_id` = 2430; -- script_texts - content : entry=-1999924
UPDATE `trans_words` SET `content_loc3`='You\'ve wasted enough of my time. Let these games be finished!' WHERE `word_id` = 1497; -- script_texts - content : entry=-1532086
UPDATE `trans_words` SET `content_loc3`='You\'ve wasted too much time mortals, now you shall fall!' WHERE `word_id` = 2158; -- script_texts - content : entry=-1564129
UPDATE `trans_words` SET `content_loc3`='Your behavior will not be tolerated!' WHERE `word_id` = 1429; -- script_texts - content : entry=-1532018
UPDATE `trans_words` SET `content_loc3`='Your blood will anoint my circle.' WHERE `word_id` = 1476; -- script_texts - content : entry=-1532065
UPDATE `trans_words` SET `content_loc3`='Your body lies beaten, battered and broken. Let my curse be your own, fate has spoken.' WHERE `word_id` = 1376; -- script_texts - content : entry=-1189028
UPDATE `trans_words` SET `content_loc3`='Your brash arrogance!' WHERE `word_id` = 1100; -- script_texts - content : entry=-1531022
UPDATE `trans_words` SET `content_loc3`='Your courage will fail.' WHERE `word_id` = 1113; -- script_texts - content : entry=-1531035
UPDATE `trans_words` SET `content_loc3`='Your death gonna be quick, strangers. You shoulda never have come to this place...' WHERE `word_id` = 2209; -- script_texts - content : entry=-1568025
UPDATE `trans_words` SET `content_loc3`='Your death is for the greater cause!' WHERE `word_id` = 1925; -- script_texts - content : entry=-1555034
UPDATE `trans_words` SET `content_loc3`='Your fate is written!' WHERE `word_id` = 1810; -- script_texts - content : entry=-1552002
UPDATE `trans_words` SET `content_loc3`='Your friends will abandon you.' WHERE `word_id` = 1114; -- script_texts - content : entry=-1531036
UPDATE `trans_words` SET `content_loc3`='Your friends will soon be joining you.' WHERE `word_id` = 1631; -- script_texts - content : entry=-1542005
UPDATE `trans_words` SET `content_loc3`='Your heart will explode.' WHERE `word_id` = 1118; -- script_texts - content : entry=-1531040
UPDATE `trans_words` SET `content_loc3`='Your insolence will be your death.' WHERE `word_id` = 1654; -- script_texts - content : entry=-1543011
UPDATE `trans_words` SET `content_loc3`='Your life cycle is now concluded!' WHERE `word_id` = 1865; -- script_texts - content : entry=-1553001
UPDATE `trans_words` SET `content_loc3`='Your pain amuses me.' WHERE `word_id` = 1586; -- script_texts - content : entry=-1540011
UPDATE `trans_words` SET `content_loc3`='Your success was short lived!' WHERE `word_id` = 2034; -- script_texts - content : entry=-1564003
UPDATE `trans_words` SET `content_loc3`='Your time is night...' WHERE `word_id` = 1379; -- script_texts - content : entry=-1189032
UPDATE `trans_words` SET `content_loc3`='Your time is up, slave of the past!' WHERE `word_id` = 1397; -- script_texts - content : entry=-1269014
UPDATE `trans_words` SET `content_loc3`='Your victory shall be short lived. The days of both the Alliance and Horde are coming to an end. The next time we meet shall be the last.' WHERE `word_id` = 893; -- script_texts - content : entry=-1229018
UPDATE `trans_words` SET `content_loc3`='Zul\'jin got a surprise for ya...' WHERE `word_id` = 2251; -- script_texts - content : entry=-1568067
UPDATE `trans_words` SET `content_loc3`='Zul\'jin... got a surprise for you...' WHERE `word_id` = 2191; -- script_texts - content : entry=-1568007

SET NAMES 'latin1';
